# -*- coding: utf-8 -*-
# Lote 58 - Portugues, Literatura, Artes subtopicos
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- PORTUGUES: INTERPRETACAO ---
{"id":"6401","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Interpretacao de Texto","subtema":"Ideia principal","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Na leitura de um texto, a ideia principal e aquela que:","alternativa_a":"Sintetiza o tema central e e sustentada pelas demais informacoes do texto","alternativa_b":"Aparece apenas na introducao","alternativa_c":"E sempre explicita e nunca implicita","alternativa_d":"Nao pode ser inferida","alternativa_e":"Repete as palavras do titulo","resposta_correta":"a","explicacao":"A ideia principal condensa o sentido global do texto, podendo ser explicita ou inferida pelo leitor.","resposta":""},
{"id":"6402","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Interpretacao de Texto","subtema":"Inferencia","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A inferencia em leitura consiste em:","alternativa_a":"Deduzir informacoes implicitas a partir do contexto e conhecimento de mundo","alternativa_b":"Copiar literalmente o texto","alternativa_c":"Traduzir o texto para outra lingua","alternativa_d":"Identificar apenas palavras desconhecidas","alternativa_e":"Memorizar o texto integralmente","resposta_correta":"a","explicacao":"Inferir e ir alem do expresso: usar pistas do texto e o proprio repertorio para construir sentido.","resposta":""},
{"id":"6403","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Interpretacao de Texto","subtema":"Coesao referencial","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O pronome na frase Joao comprou um carro. Ele e muito caro. substitui:","alternativa_a":"O carro","alternativa_b":"Joao","alternativa_c":"A compra","alternativa_d":"O preco","alternativa_e":"Nenhum elemento anterior","resposta_correta":"a","explicacao":"Coesao referencial: o pronome ELE retoma o substantivo carro (anafora), garantindo coesao textual.","resposta":""},
# --- GENEROS TEXTUAIS ---
{"id":"6404","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Generos Textuais","subtema":"Cronica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A cronica e um genero textual que se caracteriza por:","alternativa_a":"Relato breve de situacoes do cotidiano com leveza e reflexao","alternativa_b":"Texto longo e argumentativo sobre politica","alternativa_c":"Descricao tecnica de fenomenos","alternativa_d":"Narrativa de ficcao longa","alternativa_e":"Texto normativo com linguagem juridica","resposta_correta":"a","explicacao":"Cronica: genero hibrido (narrativo/lirico), curto, sobre o cotidiano, publicado em jornais e revistas.","resposta":""},
{"id":"6405","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Generos Textuais","subtema":"Publicidade","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um texto publicitario tem como objetivo principal:","alternativa_a":"Persuadir o receptor a adquirir um produto ou adotar um comportamento","alternativa_b":"Informar objetivamente sobre fatos","alternativa_c":"Narrar historias de ficcao","alternativa_d":"Instruir procedimentos tecnicos","alternativa_e":"Questionar o receptor filosoficamente","resposta_correta":"a","explicacao":"A publicidade usa linguagem apelativa, imagens e argumentos para persuadir e vender.","resposta":""},
# --- FUNCOES DA LINGUAGEM ---
{"id":"6406","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Funcoes da Linguagem","subtema":"Funcao referencial","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A funcao referencial da linguagem centra-se no:","alternativa_a":"Contexto, transmitindo informacoes objetivas","alternativa_b":"Emissor, expressando sentimentos","alternativa_c":"Receptor, convencendo-o","alternativa_d":"Codigo, descrevendo-o","alternativa_e":"Canal, mantendo o contato","resposta_correta":"a","explicacao":"Funcao referencial (ou denotativa): predomina em textos informativos e cientificos, voltada ao contexto.","resposta":""},
{"id":"6407","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Funcoes da Linguagem","subtema":"Funcao poetica","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A funcao poetica da linguagem destaca:","alternativa_a":"A propria mensagem, explorando efeitos esteticos da linguagem","alternativa_b":"O emissor e suas emocoes","alternativa_c":"O receptor","alternativa_d":"O canal de comunicacao","alternativa_e":"O codigo linguistico","resposta_correta":"a","explicacao":"Funcao poetica: o foco e na forma da mensagem - escolha de palavras, ritmo, sonoridade, figuras.","resposta":""},
# --- FIGURAS DE LINGUAGEM ---
{"id":"6408","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Figuras de Linguagem","subtema":"Ironia","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Na frase Que servico excelente! Esperei 2 horas pelo atendimento., a figura de linguagem presente e:","alternativa_a":"Ironia","alternativa_b":"Eufemismo","alternativa_c":"Litotes","alternativa_d":"Hiperbole","alternativa_e":"Personificacao","resposta_correta":"a","explicacao":"Ironia: dizer o contrario do que se pensa para criticar. Elogio aparente que na verdade critica o mau servico.","resposta":""},
{"id":"6409","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Figuras de Linguagem","subtema":"Hiperbole","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A frase Ja te disse isso um milhao de vezes! exemplifica a figura de:","alternativa_a":"Hiperbole","alternativa_b":"Metafora","alternativa_c":"Antitese","alternativa_d":"Eufemismo","alternativa_e":"Paradoxo","resposta_correta":"a","explicacao":"Hiperbole: exagero intencional para dar enfase - ninguem diz literalmente um milhao de vezes.","resposta":""},
{"id":"6410","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Figuras de Linguagem","subtema":"Eufemismo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Usar a expressao ele nos deixou no lugar de ele morreu e um exemplo de:","alternativa_a":"Eufemismo","alternativa_b":"Ironia","alternativa_c":"Hiperbole","alternativa_d":"Onomatopeia","alternativa_e":"Paranomasia","resposta_correta":"a","explicacao":"Eufemismo: substituicao de expressao rude por outra mais suave para amenizar o impacto.","resposta":""},
# --- VARIACAO LINGUISTICA ---
{"id":"6411","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Variacao Linguistica","subtema":"Registro formal e informal","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A variacao linguistica que ocorre de acordo com a situacao de comunicacao (formal ou informal) e chamada de:","alternativa_a":"Diafasica (ou de registro)","alternativa_b":"Diatopica (regional)","alternativa_c":"Diacronica (historica)","alternativa_d":"Diastratica (social)","alternativa_e":"Diatecnica","resposta_correta":"a","explicacao":"Variacao diafasica: adaptar o uso da lingua ao contexto (trabalho=formal, amigos=informal).","resposta":""},
# --- COESAO E COERENCIA ---
{"id":"6412","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Coesao e Coerencia","subtema":"Conectivos","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O conectivo PORTANTO indica, entre os enunciados que liga, uma relacao de:","alternativa_a":"Conclusao","alternativa_b":"Oposicao","alternativa_c":"Condicao","alternativa_d":"Adicao","alternativa_e":"Causa","resposta_correta":"a","explicacao":"PORTANTO (logo, dessa forma) liga uma conclusao a premissas anteriores.","resposta":""},
{"id":"6413","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Coesao e Coerencia","subtema":"Coerencia textual","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A coerencia textual refere-se a:","alternativa_a":"Unidade de sentido e nao contradicao das ideias ao longo do texto","alternativa_b":"Uso correto da gramatica","alternativa_c":"Presenca de conectivos","alternativa_d":"Organizacao em paragrafos","alternativa_e":"Ausencia de metaforas","resposta_correta":"a","explicacao":"Coerencia: logica e harmonia de sentido entre as partes do texto. Difere de coesao (formal).","resposta":""},
# --- PONTUACAO E SENTIDO ---
{"id":"6414","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Pontuacao","subtema":"Virgula e sentido","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A virgula altera o sentido em: O professor disse o aluno errou vs O professor, disse o aluno, errou. No segundo, quem errou?","alternativa_a":"O professor (o aluno relata que o professor errou)","alternativa_b":"O aluno","alternativa_c":"Ambos erraram","alternativa_d":"Ninguem errou","alternativa_e":"O sentido e identico","resposta_correta":"a","explicacao":"A virgula isola o aluno disse como inciso, indicando que o aluno e o narrador e o professor e quem errou.","resposta":""},
# --- CONCORDANCIA E REGENCIA ---
{"id":"6415","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Concordancia","subtema":"Concordancia verbal","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Na frase Fazem dez anos que nao o vejo., o verbo fazer no sentido de tempo decorrido deve ser:","alternativa_a":"Impessoal - uso correto no singular: Faz dez anos","alternativa_b":"Plural para concordar com dez anos","alternativa_c":"No passado composto","alternativa_d":"Substituido pelo verbo ter","alternativa_e":"Acompanhado de sujeito","resposta_correta":"a","explicacao":"Fazer indicando tempo decorrido e verbo impessoal: Faz dez anos (singular), nao fazem.","resposta":""},
{"id":"6416","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Regencia","subtema":"Crase","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O uso correto do acento grave (crase) ocorre em:","alternativa_a":"Fui a cidade (a+a artigo = a cidade feminina: a cidade)","alternativa_b":"Fui a Pedro","alternativa_c":"Fui a praias","alternativa_d":"Refiro-me a isso","alternativa_e":"Entreguei a ela","resposta_correta":"a","explicacao":"Crase: fusao da preposicao a com o artigo a. Usa-se antes de substantivos femininos precedidos de artigo.","resposta":""},
# --- LITERATURA: ESCOLAS LITERARIAS ---
{"id":"6417","tipo":"multipla","disciplina":"Literatura","tema":"Escolas Literarias","subtema":"Barroco","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Barroco literario (sec. XVII) caracteriza-se pelo conflito entre:","alternativa_a":"Fe e razao, corpo e alma, mundo terreno e divino","alternativa_b":"Razao e sentimento apenas","alternativa_c":"Romantismo e classicismo","alternativa_d":"Campo e cidade","alternativa_e":"Passado e futuro","resposta_correta":"a","explicacao":"O Barroco reflete a crise espiritual do sec. XVII: tensao entre fe religiosa e o humanismo renascentista.","resposta":""},
{"id":"6418","tipo":"multipla","disciplina":"Literatura","tema":"Escolas Literarias","subtema":"Romantismo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O Romantismo brasileiro no seculo XIX valorizava principalmente:","alternativa_a":"O nacionalismo, a natureza, o indio e os sentimentos","alternativa_b":"A razao e a objetividade","alternativa_c":"O proletariado e a industria","alternativa_d":"A descricao cientifica","alternativa_e":"O universalismo classico","resposta_correta":"a","explicacao":"O Romantismo brasileiro (1836-1881) exaltou a patria, o indio como heroi, a natureza e o subjetivismo.","resposta":""},
{"id":"6419","tipo":"multipla","disciplina":"Literatura","tema":"Escolas Literarias","subtema":"Realismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Realismo/Naturalismo (fin do sec. XIX) na literatura brasileira tem como principal nome:","alternativa_a":"Machado de Assis (Realismo) e Eca de Queiros e Azevedo (Naturalismo)","alternativa_b":"Jose de Alencar","alternativa_c":"Castro Alves","alternativa_d":"Carlos Drummond de Andrade","alternativa_e":"Guimaraes Rosa","resposta_correta":"a","explicacao":"O Realismo (1880) critica a sociedade burguesa. Machado de Assis e o maior nome brasileiro; Azevedo no Naturalismo.","resposta":""},
{"id":"6420","tipo":"multipla","disciplina":"Literatura","tema":"Escolas Literarias","subtema":"Modernismo brasileiro","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A primeira fase do Modernismo brasileiro (1922-1930) tem como marco:","alternativa_a":"A Semana de Arte Moderna de 1922 em Sao Paulo","alternativa_b":"A publicacao de Memorias Postumas de Bras Cubas","alternativa_c":"A morte de Euclides da Cunha","alternativa_d":"A revolucao de 1930","alternativa_e":"A publicacao de Iracema","resposta_correta":"a","explicacao":"A Semana de 22 rompeu com o academicismo e inaugurou o Modernismo, buscando linguagem e temas brasileiros.","resposta":""},
# --- VANGUARDAS EUROPEIAS ---
{"id":"6421","tipo":"multipla","disciplina":"Literatura","tema":"Vanguardas Europeias","subtema":"Surrealismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Surrealismo europeu caracteriza-se por:","alternativa_a":"Explorar o inconsciente, sonhos e o irracional como fontes de criacao artistica","alternativa_b":"Celebrar a industria e a tecnologia","alternativa_c":"Usar versos metrificados classsicos","alternativa_d":"Negar qualquer forma de arte","alternativa_e":"Retratar o cotidiano operario","resposta_correta":"a","explicacao":"O Surrealismo (Andre Breton, 1924) valoriza o sonho, o inconsciente freudiano e a liberdade criativa total.","resposta":""},
{"id":"6422","tipo":"multipla","disciplina":"Literatura","tema":"Vanguardas Europeias","subtema":"Futurismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Futurismo, de Marinetti (1909), exaltava:","alternativa_a":"A velocidade, a tecnologia, as maquinas e a ruptura com o passado","alternativa_b":"A natureza e a arte pastoral","alternativa_c":"O retorno a antiguidade classica","alternativa_d":"A introspeccao e o inconsciente","alternativa_e":"A permanencia das tradicoes","resposta_correta":"a","explicacao":"O Futurismo celebrava o progresso, as maquinas, os carros e rompeu com as tradicoes artisticas.","resposta":""},
# --- ANALISE LITERARIA ---
{"id":"6423","tipo":"multipla","disciplina":"Literatura","tema":"Analise de Poemas","subtema":"Versificacao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A rima entre versos em ABAB e chamada de rima:","alternativa_a":"Alternada (ou cruzada)","alternativa_b":"Emparelhada (AABB)","alternativa_c":"Interpolada (ABBA)","alternativa_d":"Toante","alternativa_e":"Rica","resposta_correta":"a","explicacao":"ABAB = rima alternada/cruzada. AABB = emparelhada. ABBA = interpolada ou abraco.","resposta":""},
{"id":"6424","tipo":"multipla","disciplina":"Literatura","tema":"Analise de Narrativas","subtema":"Narrador","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O narrador-personagem (1a pessoa) na narrativa e aquele que:","alternativa_a":"Participa da historia e conta a propria experiencia","alternativa_b":"Sabe tudo sobre todos os personagens","alternativa_c":"Nao aparece na historia","alternativa_d":"Narra em terceira pessoa","alternativa_e":"E o proprio autor","resposta_correta":"a","explicacao":"Narrador em 1a pessoa: conta da sua perspectiva limitada. Narrador observador: 3a pessoa limitada.","resposta":""},
# --- ARTES ---
{"id":"6425","tipo":"multipla","disciplina":"Artes","tema":"Movimentos artisticos","subtema":"Impressionismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Impressionismo (fin do sec. XIX) revolucionou a pintura ao:","alternativa_a":"Capturar a luz e o instante fugaz, com pinceladas soltas e cores vibrantes","alternativa_b":"Retratar cenas religiosas com perfeicao anatomica","alternativa_c":"Usar linhas geometricas precisas","alternativa_d":"Pintar apenas retratos de nobres","alternativa_e":"Negar a representacao da natureza","resposta_correta":"a","explicacao":"Monet, Renoir: Impressionismo captura a luz natural e impressoes visuais, nao o realismo fotografico.","resposta":""},
{"id":"6426","tipo":"multipla","disciplina":"Artes","tema":"Movimentos artisticos","subtema":"Cubismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Cubismo, de Picasso e Braque, caracteriza-se por:","alternativa_a":"Representar objetos de multiplos angulos simultaneamente em formas geometricas","alternativa_b":"Usar apenas cores primarias em faixas horizontais","alternativa_c":"Retratar cenas rurais","alternativa_d":"Negar qualquer forma de figuracao","alternativa_e":"Imitar a fotografia","resposta_correta":"a","explicacao":"O Cubismo (1907) fragmentou a representacao, mostrando varios angulos ao mesmo tempo.","resposta":""},
{"id":"6427","tipo":"multipla","disciplina":"Artes","tema":"Arte e sociedade","subtema":"Arte engajada","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O muralismo mexicano de Diego Rivera utilizou a arte para:","alternativa_a":"Retratar lutas sociais e exaltar a historia e o povo mexicano","alternativa_b":"Decorar igrejas com temas religiosos","alternativa_c":"Promover a arte abstrata","alternativa_d":"Criticar exclusivamente a arte europeia","alternativa_e":"Criar quadros para mercado de arte privado","resposta_correta":"a","explicacao":"O muralismo mexicano (Rivera, Orozco, Siqueiros) usou paredes publicas para narrar historia e politica.","resposta":""},
{"id":"6428","tipo":"multipla","disciplina":"Artes","tema":"Patrimonio cultural","subtema":"Patrimonio imaterial","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O patrimonio cultural imaterial inclui:","alternativa_a":"Musicas, festas, saberes, rituais e modos de fazer transmitidos de geracao em geracao","alternativa_b":"Apenas monumentos e edificios historicos","alternativa_c":"Apenas obras de arte em museus","alternativa_d":"Apenas documentos escritos","alternativa_e":"Apenas artefatos arqueologicos","resposta_correta":"a","explicacao":"Patrimonio imaterial: samba, capoeira, festas, culinaria, artesanato - bens culturais vivos e dinamicos.","resposta":""},
{"id":"6429","tipo":"multipla","disciplina":"Artes","tema":"Arte moderna e contemporanea","subtema":"Arte conceitual","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A arte conceitual (sec. XX) prioriza:","alternativa_a":"A ideia e o conceito acima da execucao tecnica da obra","alternativa_b":"A perfeicao tecnica do desenho","alternativa_c":"O realismo fotografico","alternativa_d":"A pintura a oleo classica","alternativa_e":"O artesanato tradicional","resposta_correta":"a","explicacao":"A arte conceitual (anos 60-70) questiona o que e arte: a ideia e a obra, nao a habilidade manual.","resposta":""},
# --- INTERTEXTUALIDADE E DENOTACAO/CONOTACAO ---
{"id":"6430","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Intertextualidade","subtema":"Parodia","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A parodia e uma forma de intertextualidade que:","alternativa_a":"Imita e transforma um texto para criar efeito comico ou critico","alternativa_b":"Copia o texto original integralmente","alternativa_c":"Elogia o texto fonte","alternativa_d":"Traduz o texto para outra lingua","alternativa_e":"Resume o texto original","resposta_correta":"a","explicacao":"Parodia: imitacao transformada com intencao humoristica ou critica. Diferente de plagio (copia sem credito).","resposta":""},
{"id":"6431","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Denotacao e Conotacao","subtema":"Sentido conotativo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Na frase Ela tem um coracao de ouro., o uso de ouro e:","alternativa_a":"Conotativo (sentido figurado: pessoa bondosa)","alternativa_b":"Denotativo (sentido literal)","alternativa_c":"Tecnico","alternativa_d":"Juridico","alternativa_e":"Cientifico","resposta_correta":"a","explicacao":"Conotacao: sentido figurado. Ninguem tem ouro no coracao literalmente; indica bondade.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote58.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 58 criado: {len(rows)} questoes")
