# -*- coding: utf-8 -*-
# Lote 59 - Concursos Bancarios: Conhecimentos Bancarios completo (estilo Cesgranrio/BB/CEF)
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- SISTEMA FINANCEIRO NACIONAL ---
{"id":"6501","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Sistema Financeiro Nacional","subtema":"Estrutura do SFN","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O Sistema Financeiro Nacional (SFN) e composto por orgaos normativos, supervisores e operadores. O principal orgao normativo e:","alternativa_a":"Conselho Monetario Nacional (CMN)","alternativa_b":"Banco Central do Brasil (BACEN)","alternativa_c":"Comissao de Valores Mobiliarios (CVM)","alternativa_d":"Banco do Brasil","alternativa_e":"Caixa Economica Federal","resposta_correta":"a","explicacao":"O CMN e o orgao maximo normativo do SFN: define politicas de moeda, credito e cambio. O BACEN e supervisor (executa as politicas).","resposta":""},
{"id":"6502","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Sistema Financeiro Nacional","subtema":"Banco Central","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Entre as funcoes do Banco Central do Brasil (BACEN), esta a de:","alternativa_a":"Emitir moeda, controlar inflacao e fiscalizar as instituicoes financeiras","alternativa_b":"Financiar o Governo diretamente","alternativa_c":"Conceder emprestimos diretos ao publico","alternativa_d":"Regular o mercado de acoes","alternativa_e":"Fiscalizar o mercado de seguros","resposta_correta":"a","explicacao":"O BACEN emite papel-moeda, controla a politica monetaria (taxa Selic), fiscaliza bancos e administra reservas.","resposta":""},
{"id":"6503","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Sistema Financeiro Nacional","subtema":"CVM","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A Comissao de Valores Mobiliarios (CVM) tem como funcao principal:","alternativa_a":"Regular e fiscalizar o mercado de capitais (acoes, debentures, fundos)","alternativa_b":"Emitir moeda","alternativa_c":"Definir a taxa SELIC","alternativa_d":"Fiscalizar os bancos comerciais","alternativa_e":"Regular os seguros","resposta_correta":"a","explicacao":"CVM: autarquia que regula e fiscaliza o mercado de valores mobiliarios (bolsa, fundos). Criada pela Lei 6.385/1976.","resposta":""},
{"id":"6504","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Sistema Financeiro Nacional","subtema":"SUSEP","dificuldade":"Medio","fonte":"FCC-CEF","ano":"2023","enunciado":"A SUSEP e o orgao responsavel por fiscalizar:","alternativa_a":"O mercado de seguros, previdencia privada aberta e capitalizacao","alternativa_b":"Os bancos comerciais","alternativa_c":"O mercado de acoes","alternativa_d":"Os fundos de pensao de servidores","alternativa_e":"A emissao de moeda","resposta_correta":"a","explicacao":"SUSEP (Superintendencia de Seguros Privados) regula seguros, previdencia aberta (PGBL/VGBL) e capitalizacao.","resposta":""},
{"id":"6505","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Sistema Financeiro Nacional","subtema":"Taxa Selic","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A taxa SELIC, definida pelo COPOM (Comite de Politica Monetaria), e:","alternativa_a":"A taxa basica de juros da economia brasileira, usada como referencia","alternativa_b":"A taxa cobrada por bancos em emprestimos pessoais","alternativa_c":"A taxa de cambio oficial","alternativa_d":"A taxa de inflacao mensal","alternativa_e":"A taxa de redesconto do Tesouro","resposta_correta":"a","explicacao":"SELIC e a taxa dos titulos publicos federais, usada como referencia para todos os juros da economia.","resposta":""},
# --- PRODUTOS BANCARIOS ---
{"id":"6506","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"Conta poupanca","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A caderneta de poupanca e o investimento mais basico do sistema bancario e possui como caracteristica:","alternativa_a":"Garantia do FGC ate R$ 250.000 por CPF por instituicao, liquidez e rentabilidade moderada","alternativa_b":"Rentabilidade atrelada ao CDI sem garantia","alternativa_c":"Aplicacao minima de R$ 1.000,00","alternativa_d":"Prazo minimo de 12 meses","alternativa_e":"Tributacao de 25% sobre os rendimentos","resposta_correta":"a","explicacao":"Poupanca: liquidez diaria, isenta de IR para pessoas fisicas, garantida pelo FGC ate R$ 250 mil. Rendimento baseado em TR+juros ou 70% da Selic (quando Selic <= 8,5%).","resposta":""},
{"id":"6507","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"CDB","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O CDB (Certificado de Deposito Bancario) e um titulo emitido por bancos e possui as seguintes caracteristicas:","alternativa_a":"Rentabilidade em geral atrelada ao CDI, garantia do FGC e tributacao regressiva de IR","alternativa_b":"Isencao total de IR e sem garantia","alternativa_c":"Rendimento fixo igual a poupanca","alternativa_d":"Prazo unico de 2 anos","alternativa_e":"So disponivel para pessoas juridicas","resposta_correta":"a","explicacao":"CDB: produto bancario de renda fixa, geralmente pre ou pos-fixado (CDI). IR regressivo: 22,5% (ate 180 dias) a 15% (acima de 720 dias). FGC garante ate R$ 250 mil.","resposta":""},
{"id":"6508","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"LCI e LCA","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A principal vantagem da LCI (Letra de Credito Imobiliario) e da LCA (Letra de Credito do Agronegocio) para pessoa fisica e:","alternativa_a":"Isencao de Imposto de Renda sobre os rendimentos","alternativa_b":"Rentabilidade superior a renda variavel","alternativa_c":"Liquidez diaria garantida","alternativa_d":"Prazo maximo de 90 dias","alternativa_e":"Garantia ilimitada do FGC","resposta_correta":"a","explicacao":"LCI e LCA sao isentas de IR para pessoas fisicas, o que aumenta a rentabilidade liquida frente ao CDB.","resposta":""},
{"id":"6509","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"PGBL e VGBL","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A diferenca fundamental entre PGBL e VGBL na previdencia privada e:","alternativa_a":"No PGBL as contribuicoes sao dedutivas no IR (ate 12% da renda bruta); no VGBL so incide IR sobre o rendimento","alternativa_b":"No VGBL ha deducao no IR e no PGBL nao","alternativa_c":"Ambos sao identicos","alternativa_d":"O PGBL e para servidores publicos apenas","alternativa_e":"O VGBL e isento de IR em qualquer caso","resposta_correta":"a","explicacao":"PGBL: deduz ate 12% da renda bruta no IR (ideal para quem faz declaracao completa). VGBL: IR so sobre rendimento (ideal para declaracao simplificada).","resposta":""},
{"id":"6510","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"FGC","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O Fundo Garantidor de Creditos (FGC) garante o reembolso de depositos por investidor por conglomerado financeiro de ate:","alternativa_a":"R$ 250.000,00","alternativa_b":"R$ 100.000,00","alternativa_c":"R$ 500.000,00","alternativa_d":"R$ 50.000,00","alternativa_e":"R$ 1.000.000,00","resposta_correta":"a","explicacao":"O FGC garante ate R$ 250 mil por CPF/CNPJ por conglomerado financeiro em depositos a vista, poupanca, CDB, LCI, LCA, etc.","resposta":""},
# --- PIX, TED, DOC ---
{"id":"6511","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"PIX","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O PIX e o sistema de pagamentos instantaneos do Banco Central. Uma de suas principais caracteristicas e:","alternativa_a":"Disponivel 24 horas por dia, 7 dias por semana, com liquidacao imediata","alternativa_b":"Funciona apenas em dias uteis no horario bancario","alternativa_c":"Cobra taxa em todas as transacoes","alternativa_d":"Tem limite de R$ 1.000,00 por transacao","alternativa_e":"Foi criado antes do TED","resposta_correta":"a","explicacao":"O PIX (lancado pelo BACEN em novembro de 2020) funciona 24/7, com liquidacao em segundos, e gratuito para PF.","resposta":""},
{"id":"6512","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Produtos Bancarios","subtema":"TED e DOC","dificuldade":"Facil","fonte":"FCC-CEF","ano":"2023","enunciado":"A principal diferenca entre TED e DOC nas transferencias bancarias e:","alternativa_a":"TED tem liquidacao no mesmo dia; DOC e liquidado no dia util seguinte","alternativa_b":"TED so funciona entre bancos iguais","alternativa_c":"DOC e mais rapido que TED","alternativa_d":"TED e exclusivo de empresas","alternativa_e":"Ambos sao liquidados no mesmo instante","resposta_correta":"a","explicacao":"TED: transferencia no mesmo dia util (se dentro do horario). DOC: liquidado no proximo dia util. O PIX substituiu grande parte dessas operacoes.","resposta":""},
# --- MERCADO DE CAPITAIS ---
{"id":"6513","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Mercado de Capitais","subtema":"Acoes","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2022","enunciado":"Uma acao ordinaria (ON) difere de uma acao preferencial (PN) porque a ON:","alternativa_a":"Concede direito a voto nas assembleias da empresa","alternativa_b":"Paga dividendos maiores","alternativa_c":"E negociada apenas no mercado primario","alternativa_d":"Possui preferencia na distribuicao de ativos em caso de falencia","alternativa_e":"Nao pode ser negociada na bolsa","resposta_correta":"a","explicacao":"ON: direito a voto (simbolo: XXXX3). PN: preferencia em dividendos, geralmente sem voto (XXXX4). Tag along.","resposta":""},
{"id":"6514","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Mercado de Capitais","subtema":"Debentures","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"As debentures sao titulos de renda fixa emitidos por empresas para:","alternativa_a":"Captar recursos de longo prazo diretamente no mercado","alternativa_b":"Financiar o governo federal","alternativa_c":"Garantir depositos bancarios","alternativa_d":"Pagar dividendos aos acionistas","alternativa_e":"Emitir acoes novas","resposta_correta":"a","explicacao":"Debentures: divida corporativa. A empresa emite para captar dinheiro, pagando juros ao investidor.","resposta":""},
{"id":"6515","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Mercado de Capitais","subtema":"Fundos de investimento","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Em um fundo de investimento, o gestor toma decisoes de aplicacao dos recursos dos:","alternativa_a":"Cotistas, que assumem os riscos de acordo com o tipo de fundo","alternativa_b":"Bancos, que garantem o capital investido","alternativa_c":"Governo, que define a carteira","alternativa_d":"Seguradoras, que cobrem perdas","alternativa_e":"Banco Central, que gerencia diretamente","resposta_correta":"a","explicacao":"No fundo, os cotistas (investidores) compartilham recursos; o gestor aplica na carteira. O risco e dos cotistas.","resposta":""},
# --- CAMBIO ---
{"id":"6516","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Cambio","subtema":"Taxa de cambio","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Quando a taxa de cambio do dolar sobe (o real se desvaloriza), o efeito imediato sobre as exportacoes brasileiras e:","alternativa_a":"As exportacoes ficam mais competitivas (produto brasileiro fica mais barato para o exterior)","alternativa_b":"As exportacoes diminuem","alternativa_c":"As exportacoes nao sao afetadas","alternativa_d":"O Banco Central intervem sempre","alternativa_e":"As importacoes tambem ficam mais baratas","resposta_correta":"a","explicacao":"Real desvalorizado: dolar alto. Exportador recebe mais reais por cada dolar, tornando o produto mais competitivo.","resposta":""},
# --- CREDITO ---
{"id":"6517","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Credito","subtema":"Credito consignado","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O credito consignado tem juros menores que o credito pessoal porque:","alternativa_a":"A parcela e descontada diretamente da folha de pagamento, reduzindo o risco de inadimplencia","alternativa_b":"E regulamentado pelo Governo Federal","alternativa_c":"Nao ha cobranca de IOF","alternativa_d":"O valor e mais alto","alternativa_e":"So existe para empresarios","resposta_correta":"a","explicacao":"No consignado, o banco desconta a parcela direto do salario/beneficio, eliminando risco de nao pagamento.","resposta":""},
{"id":"6518","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Credito","subtema":"Microcrédito","dificuldade":"Medio","fonte":"FCC-CEF","ano":"2023","enunciado":"O microcrédito destina-se principalmente a:","alternativa_a":"Pequenos empreendedores de baixa renda que nao tem acesso ao credito tradicional","alternativa_b":"Grandes empresas em expansao","alternativa_c":"Importadores de alta tecnologia","alternativa_d":"Fundos de investimento","alternativa_e":"Servidores publicos federais","resposta_correta":"a","explicacao":"O microcrédito (ex: CrediAmigo da CEF e Banco do Nordeste) apoia empreendedores informais e microempresas.","resposta":""},
# --- LGPD E COMPLIANCE ---
{"id":"6519","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Compliance","subtema":"LGPD","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A Lei Geral de Protecao de Dados (LGPD - Lei 13.709/2018) regula:","alternativa_a":"O tratamento de dados pessoais por empresas e orgaos publicos, garantindo direitos ao titular","alternativa_b":"Apenas o compartilhamento de dados bancarios","alternativa_c":"A transmissao de dados em redes sociais apenas","alternativa_d":"Somente dados de saude","alternativa_e":"A emissao de moeda digital","resposta_correta":"a","explicacao":"A LGPD estabelece regras para coleta, uso, armazenamento e compartilhamento de dados pessoais. Inspirada no GDPR europeu.","resposta":""},
{"id":"6520","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Compliance","subtema":"Prevencao lavagem de dinheiro","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O COAF (Conselho de Controle de Atividades Financeiras) tem como funcao:","alternativa_a":"Receber, examinar e identificar ocorrencias suspeitas de lavagem de dinheiro","alternativa_b":"Emitir novas cedulas de real","alternativa_c":"Fiscalizar o mercado de acoes","alternativa_d":"Definir a taxa de juros","alternativa_e":"Garantir depositos bancarios","resposta_correta":"a","explicacao":"COAF (vinculado ao BACEN): inteligencia financeira brasileira, combate lavagem de dinheiro e terrorismo.","resposta":""},
{"id":"6521","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Compliance","subtema":"Sigilo bancario","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O sigilo bancario no Brasil e regulado pela Lei Complementar 105/2001, que permite sua quebra por:","alternativa_a":"Determinacao judicial ou por autoridades com previsao legal (Receita Federal, CPI)","alternativa_b":"Qualquer cidadao que requeira","alternativa_c":"Apenas o Banco Central","alternativa_d":"Solicitacao dos proprios bancos","alternativa_e":"Resolucao do CMN","resposta_correta":"a","explicacao":"LC 105/2001: sigilo e regra, mas pode ser quebrado por ordem judicial, Receita Federal, CPI e BACEN.","resposta":""},
# --- ATENDIMENTO E VENDAS ---
{"id":"6522","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Vendas Bancarias","subtema":"Necessidades do cliente","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"No atendimento bancario, antes de oferecer um produto, o banco deve prioritariamente:","alternativa_a":"Conhecer o perfil e as necessidades financeiras do cliente (Suitability)","alternativa_b":"Oferecer o produto mais caro do portfolio","alternativa_c":"Apresentar todos os produtos disponiveis sem filtro","alternativa_d":"Ignorar a situacao financeira do cliente","alternativa_e":"Focar apenas em clientes de alta renda","resposta_correta":"a","explicacao":"Suitability (adequacao): identificar o perfil de risco e necessidade do cliente antes de indicar investimentos ou credito.","resposta":""},
{"id":"6523","tipo":"multipla","disciplina":"Conhecimentos Bancarios","tema":"Vendas Bancarias","subtema":"Canais digitais","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"O Internet Banking e o Mobile Banking permitem ao cliente:","alternativa_a":"Realizar operacoes bancarias de qualquer lugar com acesso a internet, 24 horas","alternativa_b":"Apenas consultar o saldo","alternativa_c":"Realizar saques em dinheiro","alternativa_d":"Negociar taxas com o gerente diretamente","alternativa_e":"Contratar financiamentos imobiliarios sem aprovacao de credito","resposta_correta":"a","explicacao":"Internet e mobile banking: transferencias, pagamentos, investimentos, contratacao de produtos - 24/7.","resposta":""},
# --- RACIOCINIO LOGICO ---
{"id":"6524","tipo":"multipla","disciplina":"Raciocinio Logico","tema":"Logica Proposicional","subtema":"Condicional","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Se chover, entao a rua ficara molhada. Sabe-se que a rua esta seca. Podemos concluir que:","alternativa_a":"Nao choveu","alternativa_b":"Choveu","alternativa_c":"Pode ter chovido ou nao","alternativa_d":"A rua nunca fica molhada","alternativa_e":"Nao e possivel concluir nada","resposta_correta":"a","explicacao":"Contraposicao: se P->Q e valida, entao nao-Q->nao-P tambem e. Rua seca (nao-Q) logo nao choveu (nao-P).","resposta":""},
{"id":"6525","tipo":"multipla","disciplina":"Raciocinio Logico","tema":"Logica Proposicional","subtema":"Negacao","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A negacao de Todos os funcionarios sao pontuais e:","alternativa_a":"Algum funcionario nao e pontual","alternativa_b":"Nenhum funcionario e pontual","alternativa_c":"Todos os funcionarios nao sao pontuais","alternativa_d":"Alguns funcionarios sao pontuais","alternativa_e":"A maioria dos funcionarios nao e pontual","resposta_correta":"a","explicacao":"Negacao de TODOS: ALGUM NAO. Negacao de ALGUM: NENHUM. Regra dos quantificadores.","resposta":""},
{"id":"6526","tipo":"multipla","disciplina":"Raciocinio Logico","tema":"Sequencias","subtema":"Serie numerica","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Qual o proximo numero na sequencia: 2, 4, 8, 16, 32, __?","alternativa_a":"64","alternativa_b":"48","alternativa_c":"36","alternativa_d":"56","alternativa_e":"40","resposta_correta":"a","explicacao":"Progressao geometrica de razao 2: cada termo e o dobro do anterior. 32 x 2 = 64.","resposta":""},
{"id":"6527","tipo":"multipla","disciplina":"Raciocinio Logico","tema":"Sequencias","subtema":"Serie alfanumerica","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Na sequencia A1, B2, C3, D4, qual e o proximo elemento?","alternativa_a":"E5","alternativa_b":"D5","alternativa_c":"E4","alternativa_d":"F5","alternativa_e":"E6","resposta_correta":"a","explicacao":"Letra avanca em ordem alfabetica (A B C D E) e numero aumenta de 1 em 1 (1 2 3 4 5). Logo: E5.","resposta":""},
# --- INFORMATICA ---
{"id":"6528","tipo":"multipla","disciplina":"Informatica","tema":"Seguranca Digital","subtema":"Phishing","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Phishing e uma tecnica de ataque cibernetico que consiste em:","alternativa_a":"Enganar o usuario para obter dados sensiveis por meio de mensagens e sites falsos","alternativa_b":"Bloquear o computador e exigir resgate","alternativa_c":"Espionar o trafego de rede","alternativa_d":"Sobrecarregar servidores com requisicoes","alternativa_e":"Instalar atualizacoes maliciosas","resposta_correta":"a","explicacao":"Phishing (pesca): e-mails, SMS ou sites falsos imitam bancos e empresas para roubar senhas e dados.","resposta":""},
{"id":"6529","tipo":"multipla","disciplina":"Informatica","tema":"Seguranca Digital","subtema":"Ransomware","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"Um ransomware e um tipo de malware que:","alternativa_a":"Criptografa os arquivos da vitima e exige pagamento (resgate) para libera-los","alternativa_b":"Exibe propagandas nao solicitadas","alternativa_c":"Espiona as atividades do usuario","alternativa_d":"Envia e-mails spam","alternativa_e":"Copia arquivos para um servidor remoto","resposta_correta":"a","explicacao":"Ransomware (ransom=resgate): sequestra dados criptografando-os. O atacante exige criptomoeda para descriptografar.","resposta":""},
{"id":"6530","tipo":"multipla","disciplina":"Informatica","tema":"Ferramentas Office","subtema":"Excel - funcoes","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"No Excel, a funcao que calcula a soma de valores em um intervalo condicionado a criterios e:","alternativa_a":"SOMASE","alternativa_b":"SOMA","alternativa_c":"CONT.SE","alternativa_d":"MEDIA","alternativa_e":"PROCV","resposta_correta":"a","explicacao":"SOMASE(intervalo;criterio;[intervalo_soma]): soma apenas celulas que atendem a uma condicao especificada.","resposta":""},
{"id":"6531","tipo":"multipla","disciplina":"Informatica","tema":"Ferramentas Office","subtema":"Excel - PROCV","dificuldade":"Medio","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A funcao PROCV no Excel serve para:","alternativa_a":"Buscar um valor em uma coluna e retornar um valor correspondente de outra coluna","alternativa_b":"Calcular a media de um intervalo","alternativa_c":"Contar valores maiores que zero","alternativa_d":"Criar graficos automaticamente","alternativa_e":"Formatar celulas condicionalmente","resposta_correta":"a","explicacao":"PROCV(valor_proc;tabela;num_col;0): busca vertical. Essencial em tabelas de dados bancarios.","resposta":""},
{"id":"6532","tipo":"multipla","disciplina":"Informatica","tema":"Internet","subtema":"HTTPS e seguranca","dificuldade":"Facil","fonte":"Cesgranrio-BB","ano":"2023","enunciado":"A presenca do HTTPS no endereco de um site bancario indica que:","alternativa_a":"A comunicacao entre o navegador e o servidor e criptografada (protocolo TLS/SSL)","alternativa_b":"O site e certificado pelo Governo","alternativa_c":"A velocidade de acesso e maior","alternativa_d":"O site nao pode ser invadido","alternativa_e":"O usuario tem acesso gratuito","resposta_correta":"a","explicacao":"HTTPS usa certificado TLS/SSL para criptografar os dados em transito, protegendo senhas e dados bancarios.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote59.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 59 criado: {len(rows)} questoes")
