# -*- coding: utf-8 -*-
# Lote 57 - Historia, Geografia, Filosofia, Sociologia subtopicos
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- HISTORIA: BRASIL COLONIA ---
{"id":"6301","tipo":"multipla","disciplina":"Historia","tema":"Brasil Colonia","subtema":"Pau-brasil e ciclos","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O primeiro ciclo economico do Brasil colonial foi baseado na extracao de:","alternativa_a":"Pau-brasil","alternativa_b":"Ouro","alternativa_c":"Cana-de-acucar","alternativa_d":"Borracha","alternativa_e":"Cafe","resposta_correta":"a","explicacao":"O ciclo do pau-brasil (1500-1530) foi o primeiro ciclo economico, com exploração da madeira para corante.","resposta":""},
{"id":"6302","tipo":"multipla","disciplina":"Historia","tema":"Brasil Colonia","subtema":"Capitanias hereditarias","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"As capitanias hereditarias foram criadas em 1534 com o objetivo de:","alternativa_a":"Colonizar e defender o territorio brasileiro","alternativa_b":"Abolir a escravidao","alternativa_c":"Criar provincias independentes","alternativa_d":"Garantir liberdade aos indigenas","alternativa_e":"Instalar o Governo-Geral","resposta_correta":"a","explicacao":"As capitanias foram doadas a donatarios para colonizar o Brasil, que corriam seus proprios custos.","resposta":""},
{"id":"6303","tipo":"multipla","disciplina":"Historia","tema":"Brasil Colonia","subtema":"Escravidao africana","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A escravidao africana no Brasil colonial se justificava economicamente porque:","alternativa_a":"Era mao de obra barata e abundante para a producao agricola exportavel","alternativa_b":"Os africanos eram fisicamente superiores","alternativa_c":"A Igreja apoiava oficialmente a escravidao indigena","alternativa_d":"Os portugueses nao tinham colonos","alternativa_e":"Os africanos escolhiam vir ao Brasil","resposta_correta":"a","explicacao":"A escravidao africana sustentou a economia colonial, especialmente a cana-de-acucar no Nordeste.","resposta":""},
# --- BRASIL IMPERIO ---
{"id":"6304","tipo":"multipla","disciplina":"Historia","tema":"Brasil Imperio","subtema":"Independencia","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Independencia do Brasil foi proclamada em:","alternativa_a":"7 de setembro de 1822, por D. Pedro I","alternativa_b":"15 de novembro de 1889","alternativa_c":"7 de setembro de 1889","alternativa_d":"22 de abril de 1500","alternativa_e":"13 de maio de 1888","resposta_correta":"a","explicacao":"Em 7/9/1822, D. Pedro I proclamou a independencia as margens do rio Ipiranga (Grito do Ipiranga).","resposta":""},
{"id":"6305","tipo":"multipla","disciplina":"Historia","tema":"Brasil Imperio","subtema":"Abolicao da escravidao","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Lei Aurea, que aboliu a escravidao no Brasil, foi assinada em:","alternativa_a":"13 de maio de 1888, pela Princesa Isabel","alternativa_b":"7 de setembro de 1822","alternativa_c":"15 de novembro de 1889","alternativa_d":"28 de setembro de 1871","alternativa_e":"13 de maio de 1889","resposta_correta":"a","explicacao":"A Lei Aurea (Lei 3.353/1888) foi assinada pela Princesa Isabel, encerrando a escravidao no Brasil.","resposta":""},
# --- REPUBLICA ---
{"id":"6306","tipo":"multipla","disciplina":"Historia","tema":"Brasil Republica","subtema":"Proclamacao da Republica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Republica foi proclamada no Brasil em:","alternativa_a":"15 de novembro de 1889, pelo Marechal Deodoro da Fonseca","alternativa_b":"7 de setembro de 1822","alternativa_c":"13 de maio de 1888","alternativa_d":"1 de janeiro de 1890","alternativa_e":"1 de novembro de 1889","resposta_correta":"a","explicacao":"Marechal Deodoro liderou o golpe que encerrou o Imperio e proclamou a Republica em 15/11/1889.","resposta":""},
{"id":"6307","tipo":"multipla","disciplina":"Historia","tema":"Brasil Republica","subtema":"Republica Velha","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A politica do cafe com leite, durante a Republica Velha, representava o rodizio de poder entre:","alternativa_a":"Sao Paulo (cafe) e Minas Gerais (leite)","alternativa_b":"Rio de Janeiro e Bahia","alternativa_c":"Nordeste e Sul","alternativa_d":"Exercito e Igreja","alternativa_e":"Rio e Pernambuco","resposta_correta":"a","explicacao":"SP e MG alternavam a presidencia na Republica Velha (1889-1930), dominada pelas oligarquias agrarias.","resposta":""},
# --- ERA VARGAS ---
{"id":"6308","tipo":"multipla","disciplina":"Historia","tema":"Brasil Republica","subtema":"Estado Novo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Estado Novo (1937-1945) foi o periodo da ditadura de Getulio Vargas caracterizado por:","alternativa_a":"Centralizacao politica, censura e suspensao das liberdades civis","alternativa_b":"Plena democracia e eleicoes livres","alternativa_c":"Abertura economica ao capital estrangeiro","alternativa_d":"Fim dos partidos politicos e da Constituicao","alternativa_e":"Industrializacao sem intervencao estatal","resposta_correta":"a","explicacao":"O Estado Novo (1937-45): ditadura varguista com constituicao outorgada, censura, DOPS e corporativismo.","resposta":""},
# --- DITADURA MILITAR ---
{"id":"6309","tipo":"multipla","disciplina":"Historia","tema":"Brasil Republica","subtema":"Ditadura militar","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O movimento que depOS Joao Goulart e iniciou a ditadura militar no Brasil ocorreu em:","alternativa_a":"1 de abril de 1964","alternativa_b":"1 de abril de 1968","alternativa_c":"1 de abril de 1954","alternativa_d":"15 de novembro de 1964","alternativa_e":"31 de marco de 1985","resposta_correta":"a","explicacao":"O golpe militar que depOS Jango ocorreu em 31/3 e 1/4/1964, iniciando 21 anos de ditadura.","resposta":""},
{"id":"6310","tipo":"multipla","disciplina":"Historia","tema":"Brasil Republica","subtema":"Abertura politica","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A redemocratizacao do Brasil culminou na eleicao de Tancredo Neves (1985) e na promulgacao da:","alternativa_a":"Constituicao Federal de 1988 (Constituicao Cidada)","alternativa_b":"Constituicao de 1937","alternativa_c":"Lei Aurea","alternativa_d":"Constituicao de 1946","alternativa_e":"Lei do AI-5","resposta_correta":"a","explicacao":"A CF/1988 marcou o fim da ditadura e garantiu direitos fundamentais amplos, sendo chamada de Constituicao Cidada.","resposta":""},
# --- HISTORIA GERAL ---
{"id":"6311","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Revolucao Francesa","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Os tres ideais da Revolucao Francesa (1789) sao:","alternativa_a":"Liberdade, igualdade e fraternidade","alternativa_b":"Forca, terra e capital","alternativa_c":"Monarquia, religio e territorio","alternativa_d":"Paz, ordem e progresso","alternativa_e":"Democracia, socialismo e poder","resposta_correta":"a","explicacao":"Liberte, Egalite, Fraternite: os principios da Revolucao Francesa que influenciaram a modernidade politica.","resposta":""},
{"id":"6312","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Revolucao Industrial","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Revolucao Industrial iniciou-se no seculo XVIII na:","alternativa_a":"Inglaterra","alternativa_b":"Franca","alternativa_c":"Alemanha","alternativa_d":"Estados Unidos","alternativa_e":"Italia","resposta_correta":"a","explicacao":"A Rev. Industrial comecou na Inglaterra (sec. XVIII) com a maquina a vapor e a fabricas texteis.","resposta":""},
{"id":"6313","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Primeira Guerra Mundial","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O estopim da Primeira Guerra Mundial (1914-1918) foi:","alternativa_a":"O assassinato do Arquiduque Francisco Fernando em Sarajevo","alternativa_b":"A invasao da Polonia pela Alemanha","alternativa_c":"A Revolucao Russa","alternativa_d":"A conquista da Africa pela Europa","alternativa_e":"A crise da bolsa de 1929","resposta_correta":"a","explicacao":"O assassinato de Francisco Fernando (28/6/1914) serviu de pretexto para o conflito, que ja era esperado.","resposta":""},
{"id":"6314","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Guerra Fria","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A Guerra Fria foi o conflito entre EUA e URSS caracterizado principalmente por:","alternativa_a":"Disputa ideologica, tecnologica e geopolitica sem confronto militar direto","alternativa_b":"Guerra aberta entre as superpotencias","alternativa_c":"Conflito economico exclusivamente","alternativa_d":"Alianca entre os dois paises","alternativa_e":"Disputa apenas cultural","resposta_correta":"a","explicacao":"Guerra Fria (1947-1991): tensao entre capitalismo (EUA) e socialismo (URSS) sem guerra direta entre eles.","resposta":""},
# --- GEOGRAFIA: GEOPOLITICA ---
{"id":"6315","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Organizacao das Nacoes Unidas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A ONU foi criada em 1945 com o objetivo principal de:","alternativa_a":"Manter a paz e a seguranca internacional apos a 2a Guerra","alternativa_b":"Criar uma moeda mundial","alternativa_c":"Unificar as nacoes em um unico governo","alternativa_d":"Regular o comercio global","alternativa_e":"Criar o Euro","resposta_correta":"a","explicacao":"A ONU foi criada em 1945 para prevenir novos conflitos mundiais, com sede em Nova York.","resposta":""},
{"id":"6316","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Conflitos internacionais","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O conflito entre Israel e Palestina esta relacionado principalmente a:","alternativa_a":"Disputas territoriais e religiosas na regiao do Oriente Medio","alternativa_b":"Controle de recursos petroliferos","alternativa_c":"Rivalidade entre EUA e Russia","alternativa_d":"Questoes de comercio maritimo","alternativa_e":"Apenas divergencias religiosas","resposta_correta":"a","explicacao":"O conflito israelense-palestino envolve disputas sobre territorio, reconhecimento estatal e questoes religiosas.","resposta":""},
# --- BLOCOS ECONOMICOS ---
{"id":"6317","tipo":"multipla","disciplina":"Geografia","tema":"Blocos economicos","subtema":"Brics","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O BRICS e formado por:","alternativa_a":"Brasil, Russia, India, China e Africa do Sul","alternativa_b":"Brasil, Argentina, Chile, Peru e Colombia","alternativa_c":"EUA, Canada, Mexico, Brasil e Argentina","alternativa_d":"Alemanha, Franca, Italia, Espanha e Portugal","alternativa_e":"Japao, China, Coreia, India e Brasil","resposta_correta":"a","explicacao":"BRICS: economias emergentes - Brasil, Russia, India, China, Africa do Sul (e novos membros desde 2024).","resposta":""},
# --- URBANIZACAO ---
{"id":"6318","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Urbanizacao brasileira","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O Brasil e hoje considerado um pais predominantemente:","alternativa_a":"Urbano (mais de 85% da populacao nas cidades)","alternativa_b":"Rural","alternativa_c":"Semi-rural","alternativa_d":"Com populacao igualmente distribuida","alternativa_e":"Nomade","resposta_correta":"a","explicacao":"Segundo o IBGE, cerca de 85-87% dos brasileiros vivem em areas urbanas, fruto da industrializacao.","resposta":""},
{"id":"6319","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Metropolizacao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O processo de metropolizacao gera problemas socioambientais como:","alternativa_a":"Favelizacao, congestionamentos, poluicao e desigualdade","alternativa_b":"Desertificacao e queda demografica","alternativa_c":"Excesso de espaco verde","alternativa_d":"Queda do PIB","alternativa_e":"Reducao das migrações","resposta_correta":"a","explicacao":"O crescimento urbano desordenado gera segregacao social, violencia, falta de saneamento e trafego.","resposta":""},
# --- QUESTOES AMBIENTAIS ---
{"id":"6320","tipo":"multipla","disciplina":"Geografia","tema":"Meio ambiente","subtema":"Aquecimento global","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O principal gas responsavel pelo aumento do efeito estufa e o:","alternativa_a":"Dioxido de carbono (CO2)","alternativa_b":"Oxigenio (O2)","alternativa_c":"Nitrogenio (N2)","alternativa_d":"Gas neon","alternativa_e":"Vapor d agua puro","resposta_correta":"a","explicacao":"O CO2 emitido por queima de combustiveis fosseis e o principal gas de efeito estufa antropogenico.","resposta":""},
{"id":"6321","tipo":"multipla","disciplina":"Geografia","tema":"Meio ambiente","subtema":"Desertificacao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A desertificacao e causada principalmente pela:","alternativa_a":"Combinacao de secas, desmatamento e uso inadequado do solo","alternativa_b":"Excesso de chuvas","alternativa_c":"Urbanizacao nas areas tropicais","alternativa_d":"Expansao das florestas","alternativa_e":"Reducao das queimadas","resposta_correta":"a","explicacao":"A desertificacao transforma areas ferteis em desertas por acao humana e climatica combinadas.","resposta":""},
# --- DEMOGRAFIA ---
{"id":"6322","tipo":"multipla","disciplina":"Geografia","tema":"Demografia","subtema":"Transicao demografica","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A transicao demografica no Brasil e caracterizada por:","alternativa_a":"Reducao da natalidade e aumento da expectativa de vida, gerando envelhecimento da populacao","alternativa_b":"Aumento rapido da natalidade","alternativa_c":"Emigracao em massa","alternativa_d":"Populacao jovem crescente","alternativa_e":"Alta mortalidade infantil","resposta_correta":"a","explicacao":"O Brasil vive transicao demografica: menos nascimentos, mais longevidade, populacao envelhecendo.","resposta":""},
# --- FILOSOFIA: ANTIGA ---
{"id":"6323","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Antiga","subtema":"Socrates","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Qual o lema da filosofia socrática que apela para o autoconhecimento?","alternativa_a":"Conhece-te a ti mesmo","alternativa_b":"Penso, logo existo","alternativa_c":"O homem e a medida de todas as coisas","alternativa_d":"Nada sei","alternativa_e":"A virtude e o bem supremo","resposta_correta":"a","explicacao":"A maxima grega conhece-te a ti mesmo, associada a Socrates, convida a reflexao sobre a propria natureza.","resposta":""},
{"id":"6324","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Antiga","subtema":"Platao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Para Platao, o conhecimento verdadeiro so e possivel no mundo das:","alternativa_a":"Ideias (mundo inteligivel)","alternativa_b":"Sensacoes (mundo sensivel)","alternativa_c":"Opinioes (doxa)","alternativa_d":"Emocoes","alternativa_e":"Experiencias praticas","resposta_correta":"a","explicacao":"Platao: o mundo sensivel e mutavel e ilusorio; o conhecimento verdadeiro vem do mundo das ideias eternas.","resposta":""},
{"id":"6325","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Antiga","subtema":"Aristoteles","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Aristoteles definia o ser humano como um animal politico porque:","alternativa_a":"Os humanos necessitam da vida em comunidade para se realizar plenamente","alternativa_b":"Todos os humanos governam","alternativa_c":"O homem e naturalmente guerreiro","alternativa_d":"A politica e inata nos animais","alternativa_e":"Os humanos sao racionais mas solitarios","resposta_correta":"a","explicacao":"Para Aristoteles, o homem so alcanca a eudaimonia (felicidade/realizacao) na polis, vivendo com outros.","resposta":""},
# --- FILOSOFIA MODERNA ---
{"id":"6326","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Moderna","subtema":"Descartes","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O metodo da duvida cartesiana (hiperbólica) busca:","alternativa_a":"Encontrar uma certeza indubitavel ao duvidar de tudo que pode ser duvidado","alternativa_b":"Negar toda possibilidade de conhecimento","alternativa_c":"Confirmar os dogmas religiosos","alternativa_d":"Refutar a existencia de Deus","alternativa_e":"Valorizar apenas a experiencia","resposta_correta":"a","explicacao":"Descartes duvida de tudo ate encontrar algo indubitavel: o cogito (penso, logo existo).","resposta":""},
{"id":"6327","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Moderna","subtema":"Iluminismo e Locke","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"John Locke defendia que o conhecimento humano vem:","alternativa_a":"Da experiencia sensorial (empirismo: a mente e uma tabula rasa)","alternativa_b":"Das ideias inatas","alternativa_c":"Da razao pura sem experiencia","alternativa_d":"Da revelacao divina","alternativa_e":"Da cultura coletiva","resposta_correta":"a","explicacao":"Locke, pai do empirismo: nascemos sem ideias inatas. Todo conhecimento vem da experiencia (tabula rasa).","resposta":""},
{"id":"6328","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Moderna","subtema":"Rousseau e Contrato Social","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Para Rousseau, o contrato social e o acordo pelo qual:","alternativa_a":"Os individuos cedem parte de sua liberdade para viver em sociedade e receber protecao","alternativa_b":"O rei governa sem limites","alternativa_c":"A Igreja controla o Estado","alternativa_d":"Os mais fortes dominam os mais fracos","alternativa_e":"A propriedade privada e abolida","resposta_correta":"a","explicacao":"Rousseau: a vontade geral (soberania popular) legitima o poder, nao a forca ou a heranca.","resposta":""},
# --- ETICA E CIDADANIA ---
{"id":"6329","tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Etica kantiana","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O imperativo categorico de Kant diz para agir de forma que:","alternativa_a":"Sua acao possa se tornar lei universal para todos os seres racionais","alternativa_b":"Maximize o prazer pessoal","alternativa_c":"Siga as leis do Estado","alternativa_d":"Atenda ao bem da maioria","alternativa_e":"Obedeça a Deus","resposta_correta":"a","explicacao":"Kant: age somente segundo maximas que possas querer que se tornem leis universais. Etica deontologica.","resposta":""},
# --- SOCIOLOGIA: CULTURA ---
{"id":"6330","tipo":"multipla","disciplina":"Sociologia","tema":"Cultura","subtema":"Etnocentrismo e relativismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O etnocentrismo consiste em:","alternativa_a":"Julgar outras culturas pela logica e valores da propria cultura","alternativa_b":"Valorizar todas as culturas igualmente","alternativa_c":"Adotar outra cultura como superior","alternativa_d":"Estudar culturas sem emitir julgamentos","alternativa_e":"Misturar elementos de duas culturas","resposta_correta":"a","explicacao":"Etnocentrismo: ver a propria cultura como referencia e superior, avaliando as outras por esse padrao.","resposta":""},
{"id":"6331","tipo":"multipla","disciplina":"Sociologia","tema":"Cultura","subtema":"Identidade cultural","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O conceito de cultura nas Ciencias Sociais se refere a:","alternativa_a":"Todo o conjunto de praticas, valores, crencas e simbolos compartilhados por um grupo","alternativa_b":"Apenas as artes e a literatura","alternativa_c":"O nivel educacional de uma populacao","alternativa_d":"Apenas os habitos alimentares","alternativa_e":"A genetica de uma populacao","resposta_correta":"a","explicacao":"Cultura: conjunto de producoes humanas materiais e imateriais (lingua, religio, costumes, arte, valores).","resposta":""},
# --- DESIGUALDADE SOCIAL ---
{"id":"6332","tipo":"multipla","disciplina":"Sociologia","tema":"Desigualdade Social","subtema":"Estratificacao social","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Indice de Gini mede:","alternativa_a":"A desigualdade de distribuicao de renda (0 = igualdade total; 1 = desigualdade maxima)","alternativa_b":"O crescimento economico","alternativa_c":"A taxa de pobreza","alternativa_d":"O desenvolvimento humano","alternativa_e":"O acesso a educacao","resposta_correta":"a","explicacao":"O Gini indica concentracao de renda. Quanto mais proximo de 1, maior a desigualdade. O Brasil historicamente tem Gini alto.","resposta":""},
# --- MOVIMENTOS SOCIAIS ---
{"id":"6333","tipo":"multipla","disciplina":"Sociologia","tema":"Movimentos Sociais","subtema":"Feminismo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O movimento feminista busca principalmente:","alternativa_a":"A igualdade de direitos, oportunidades e representacao entre homens e mulheres","alternativa_b":"A superioridade feminina","alternativa_c":"Apenas o direito ao voto","alternativa_d":"A separacao dos sexos","alternativa_e":"A extincao do casamento","resposta_correta":"a","explicacao":"O feminismo, em suas multiplas ondas, luta por igualdade de genero em politica, economia, cultura e vida cotidiana.","resposta":""},
# --- TRABALHO E INDUSTRIA CULTURAL ---
{"id":"6334","tipo":"multipla","disciplina":"Sociologia","tema":"Trabalho","subtema":"Uberizacao do trabalho","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A uberizacao do trabalho refere-se ao fenomeno de:","alternativa_a":"Precarizacao via plataformas digitais sem vinculo empregaticio formal","alternativa_b":"Industrializacao acelerada","alternativa_c":"Formalizacao dos trabalhadores informais","alternativa_d":"Robotizacao total da producao","alternativa_e":"Aumento do salario minimo","resposta_correta":"a","explicacao":"A uberizacao cria trabalhadores formalmente autonomos mas economicamente dependentes de plataformas.","resposta":""},
{"id":"6335","tipo":"multipla","disciplina":"Sociologia","tema":"Industria Cultural","subtema":"Mass media","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A industria cultural, conceito de Adorno e Horkheimer, critica:","alternativa_a":"A producao em serie de bens culturais que padroniza gostos e reduz a capacidade critica","alternativa_b":"A arte artesanal e popular","alternativa_c":"O excesso de producao literaria autonoma","alternativa_d":"A liberdade de imprensa","alternativa_e":"A criatividade individual","resposta_correta":"a","explicacao":"Para a Escola de Frankfurt, a industria cultural transforma arte em mercadoria e aliena o publico.","resposta":""},
# --- DIREITOS HUMANOS ---
{"id":"6336","tipo":"multipla","disciplina":"Sociologia","tema":"Direitos Humanos","subtema":"Declaracao Universal","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Declaracao Universal dos Direitos Humanos foi adotada pela ONU em:","alternativa_a":"1948","alternativa_b":"1945","alternativa_c":"1789","alternativa_d":"1988","alternativa_e":"1960","resposta_correta":"a","explicacao":"A DUDH foi proclamada em 10/12/1948 como resposta aos horrores da 2a Guerra. Direitos universais e inalienáveis.","resposta":""},
{"id":"6337","tipo":"multipla","disciplina":"Sociologia","tema":"Direitos Humanos","subtema":"Racismo estrutural","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O conceito de racismo estrutural indica que o racismo:","alternativa_a":"Esta incorporado nas instituicoes, leis e praticas sociais, nao apenas em individuos","alternativa_b":"E apenas uma questao de atitudes individuais","alternativa_c":"Nao existe mais no Brasil","alternativa_d":"E exclusivo de grupos marginalizados","alternativa_e":"Desapareceu com a abolicao","resposta_correta":"a","explicacao":"Racismo estrutural (Silvio Almeida): o racismo e modo de operacao da estrutura social, nao so ato individual.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote57.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 57 criado: {len(rows)} questoes")
