# -*- coding: utf-8 -*-
# Lote 55 - Matematica: estatistica, funcoes, mat. financeira + Fisica subtopicos
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- ESTATISTICA ---
{"id":"6101","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Media aritmetica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"As notas de um aluno foram 6, 7, 8 e 9. Qual e a media aritmetica?","alternativa_a":"7,5","alternativa_b":"7","alternativa_c":"8","alternativa_d":"7,75","alternativa_e":"8,5","resposta_correta":"a","explicacao":"Media = (6+7+8+9)/4 = 30/4 = 7,5.","resposta":""},
{"id":"6102","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Mediana","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Os dados 3, 5, 7, 9, 11 estao em ordem crescente. Qual e a mediana?","alternativa_a":"7","alternativa_b":"5","alternativa_c":"9","alternativa_d":"6","alternativa_e":"8","resposta_correta":"a","explicacao":"Mediana e o valor central: 3 5 [7] 9 11 => mediana = 7.","resposta":""},
{"id":"6103","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Moda","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"No conjunto 2, 3, 3, 4, 5, 5, 5, 6, a moda e:","alternativa_a":"5","alternativa_b":"3","alternativa_c":"4","alternativa_d":"6","alternativa_e":"2","resposta_correta":"a","explicacao":"Moda e o valor que mais se repete: 5 aparece 3 vezes.","resposta":""},
{"id":"6104","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Interpretacao de graficos","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um grafico de barras mostra vendas mensais: Jan=100, Fev=120, Mar=80. Qual mes teve menor venda?","alternativa_a":"Marco","alternativa_b":"Janeiro","alternativa_c":"Fevereiro","alternativa_d":"Todos iguais","alternativa_e":"Nao e possivel determinar","resposta_correta":"a","explicacao":"Marco teve 80 unidades, o menor valor entre os tres meses.","resposta":""},
{"id":"6105","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Probabilidade simples","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Lancando um dado justo (6 faces), qual a probabilidade de sair numero par?","alternativa_a":"1/2","alternativa_b":"1/3","alternativa_c":"2/3","alternativa_d":"1/6","alternativa_e":"3/4","resposta_correta":"a","explicacao":"Pares: 2, 4, 6 (3 casos). Total: 6. P = 3/6 = 1/2.","resposta":""},
{"id":"6106","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Probabilidade de evento complementar","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A probabilidade de chover amanha e 0,3. A probabilidade de NAO chover e:","alternativa_a":"0,7","alternativa_b":"0,3","alternativa_c":"0,5","alternativa_d":"0,6","alternativa_e":"0,4","resposta_correta":"a","explicacao":"P(nao chover) = 1 - P(chover) = 1 - 0,3 = 0,7.","resposta":""},
# --- ANALISE COMBINATORIA ---
{"id":"6107","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Fatorial","dificuldade":"Facil","fonte":"ENEM","ano":"2022","enunciado":"Quanto e 5! (5 fatorial)?","alternativa_a":"120","alternativa_b":"60","alternativa_c":"24","alternativa_d":"100","alternativa_e":"20","resposta_correta":"a","explicacao":"5! = 5 x 4 x 3 x 2 x 1 = 120.","resposta":""},
{"id":"6108","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Arranjo simples","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"De quantas maneiras podemos escolher 2 pessoas em uma fila com ordem importando de um grupo de 4?","alternativa_a":"12","alternativa_b":"6","alternativa_c":"8","alternativa_d":"24","alternativa_e":"10","resposta_correta":"a","explicacao":"A(4,2) = 4!/(4-2)! = 4!/2! = 12.","resposta":""},
{"id":"6109","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Combinacao simples","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"De quantas formas podemos escolher 2 alunos de um grupo de 5 (sem importar a ordem)?","alternativa_a":"10","alternativa_b":"20","alternativa_c":"15","alternativa_d":"5","alternativa_e":"25","resposta_correta":"a","explicacao":"C(5,2) = 5!/(2! x 3!) = 10.","resposta":""},
# --- FUNCOES ---
{"id":"6110","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao do 1 grau","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Dada f(x) = 2x + 3, qual e f(4)?","alternativa_a":"11","alternativa_b":"9","alternativa_c":"10","alternativa_d":"12","alternativa_e":"8","resposta_correta":"a","explicacao":"f(4) = 2(4) + 3 = 8 + 3 = 11.","resposta":""},
{"id":"6111","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Zero da funcao do 1 grau","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O zero da funcao f(x) = 3x - 9 e:","alternativa_a":"3","alternativa_b":"9","alternativa_c":"-3","alternativa_d":"6","alternativa_e":"-9","resposta_correta":"a","explicacao":"3x - 9 = 0 => 3x = 9 => x = 3.","resposta":""},
{"id":"6112","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao do 2 grau - vertice","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A funcao f(x) = x^2 - 4x + 3 tem vertice em x =","alternativa_a":"2","alternativa_b":"3","alternativa_c":"1","alternativa_d":"-2","alternativa_e":"4","resposta_correta":"a","explicacao":"x_v = -b/(2a) = -(-4)/(2x1) = 4/2 = 2.","resposta":""},
{"id":"6113","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao exponencial","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"O valor de f(3) para f(x) = 2^x e:","alternativa_a":"8","alternativa_b":"6","alternativa_c":"9","alternativa_d":"16","alternativa_e":"4","resposta_correta":"a","explicacao":"f(3) = 2^3 = 8.","resposta":""},
{"id":"6114","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao logaritmica","dificuldade":"Medio","fonte":"Vestibular","ano":"2022","enunciado":"O valor de log base 2 de 32 e:","alternativa_a":"5","alternativa_b":"4","alternativa_c":"6","alternativa_d":"3","alternativa_e":"7","resposta_correta":"a","explicacao":"2^5 = 32, logo log base 2 de 32 = 5.","resposta":""},
# --- MATEMATICA FINANCEIRA ---
{"id":"6115","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Juro simples","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um capital de R$ 2.000,00 e aplicado a juros simples de 3% ao mes por 4 meses. O juro total e:","alternativa_a":"R$ 240,00","alternativa_b":"R$ 120,00","alternativa_c":"R$ 200,00","alternativa_d":"R$ 180,00","alternativa_e":"R$ 300,00","resposta_correta":"a","explicacao":"J = C x i x t = 2000 x 0,03 x 4 = 240.","resposta":""},
{"id":"6116","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Montante juro simples","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Capital de R$ 1.000,00 a 5% ao mes por 3 meses (juro simples). O montante e:","alternativa_a":"R$ 1.150,00","alternativa_b":"R$ 1.100,00","alternativa_c":"R$ 1.050,00","alternativa_d":"R$ 1.200,00","alternativa_e":"R$ 1.250,00","resposta_correta":"a","explicacao":"J = 1000 x 0,05 x 3 = 150. M = 1000 + 150 = 1.150.","resposta":""},
{"id":"6117","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Juro composto","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um capital de R$ 1.000,00 e aplicado a juros compostos de 10% ao periodo por 2 periodos. O montante e:","alternativa_a":"R$ 1.210,00","alternativa_b":"R$ 1.200,00","alternativa_c":"R$ 1.100,00","alternativa_d":"R$ 1.150,00","alternativa_e":"R$ 1.250,00","resposta_correta":"a","explicacao":"M = C x (1+i)^t = 1000 x 1,1^2 = 1000 x 1,21 = 1.210.","resposta":""},
{"id":"6118","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Desconto comercial","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Um titulo de R$ 500,00 e descontado a 5% ao mes por 2 meses (desconto simples comercial). O desconto e:","alternativa_a":"R$ 50,00","alternativa_b":"R$ 25,00","alternativa_c":"R$ 100,00","alternativa_d":"R$ 75,00","alternativa_e":"R$ 40,00","resposta_correta":"a","explicacao":"D = N x i x t = 500 x 0,05 x 2 = 50.","resposta":""},
{"id":"6119","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Taxa equivalente","dificuldade":"Dificil","fonte":"Vestibular","ano":"2022","enunciado":"Uma taxa de 1% ao mes e equivalente, em regime de juros compostos, a aproximadamente qual taxa anual?","alternativa_a":"12,68% ao ano","alternativa_b":"12% ao ano","alternativa_c":"15% ao ano","alternativa_d":"10% ao ano","alternativa_e":"13% ao ano","resposta_correta":"a","explicacao":"(1,01)^12 - 1 = 1,1268 - 1 = 12,68% ao ano.","resposta":""},
{"id":"6120","tipo":"multipla","disciplina":"Matematica","tema":"Matematica Financeira","subtema":"Inflacao e poder de compra","dificuldade":"Medio","fonte":"ENEM","ano":"2023","enunciado":"Se a inflacao anual e de 10% e seu salario subiu 5%, seu poder de compra:","alternativa_a":"Diminuiu","alternativa_b":"Aumentou","alternativa_c":"Ficou igual","alternativa_d":"Dobrou","alternativa_e":"Nao e possivel calcular","resposta_correta":"a","explicacao":"O aumento real foi negativo: 1,05/1,10 - 1 = -4,5%. O poder de compra caiu.","resposta":""},
# --- FISICA: CINEMATICA ---
{"id":"6121","tipo":"multipla","disciplina":"Fisica","tema":"Cinematica","subtema":"Velocidade media","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um carro percorre 240 km em 3 horas. Qual e sua velocidade media?","alternativa_a":"80 km/h","alternativa_b":"60 km/h","alternativa_c":"90 km/h","alternativa_d":"120 km/h","alternativa_e":"100 km/h","resposta_correta":"a","explicacao":"Vm = distancia/tempo = 240/3 = 80 km/h.","resposta":""},
{"id":"6122","tipo":"multipla","disciplina":"Fisica","tema":"Cinematica","subtema":"Movimento uniforme","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Em movimento uniforme, a aceleracao e:","alternativa_a":"Nula (zero)","alternativa_b":"Constante e positiva","alternativa_c":"Variavel","alternativa_d":"Negativa","alternativa_e":"Infinita","resposta_correta":"a","explicacao":"No MU a velocidade e constante, portanto a aceleracao e nula.","resposta":""},
{"id":"6123","tipo":"multipla","disciplina":"Fisica","tema":"Cinematica","subtema":"Queda livre","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um objeto e largado do repouso e cai em queda livre (g = 10 m/s2) por 3 s. Qual e sua velocidade final?","alternativa_a":"30 m/s","alternativa_b":"20 m/s","alternativa_c":"15 m/s","alternativa_d":"10 m/s","alternativa_e":"25 m/s","resposta_correta":"a","explicacao":"v = g x t = 10 x 3 = 30 m/s.","resposta":""},
{"id":"6124","tipo":"multipla","disciplina":"Fisica","tema":"Cinematica","subtema":"Lancamento horizontal","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"No lancamento horizontal, o componente horizontal da velocidade:","alternativa_a":"Permanece constante","alternativa_b":"Aumenta linearmente","alternativa_c":"E zero","alternativa_d":"Diminui","alternativa_e":"Varia com a massa","resposta_correta":"a","explicacao":"Na horizontal nao ha forca (desprezando o ar), entao a velocidade horizontal e constante.","resposta":""},
# --- LEIS DE NEWTON ---
{"id":"6125","tipo":"multipla","disciplina":"Fisica","tema":"Dinamica","subtema":"1a Lei de Newton","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Primeira Lei de Newton, chamada lei da inercia, afirma que:","alternativa_a":"Um objeto em repouso ou em MU permanece assim se a forca resultante for nula","alternativa_b":"Forca e igual a massa vezes aceleracao","alternativa_c":"Acao e reacao sao forcas de mesma intensidade e sentidos opostos","alternativa_d":"A velocidade e sempre constante","alternativa_e":"A aceleracao e inversamente proporcional a forca","resposta_correta":"a","explicacao":"1a Lei: principio da inercia. Um corpo tende a manter seu estado de repouso ou MRU se a resultante for nula.","resposta":""},
{"id":"6126","tipo":"multipla","disciplina":"Fisica","tema":"Dinamica","subtema":"2a Lei de Newton","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um objeto de 5 kg sofre uma forca resultante de 20 N. Qual e sua aceleracao?","alternativa_a":"4 m/s2","alternativa_b":"2 m/s2","alternativa_c":"10 m/s2","alternativa_d":"8 m/s2","alternativa_e":"5 m/s2","resposta_correta":"a","explicacao":"F = m x a => a = F/m = 20/5 = 4 m/s2.","resposta":""},
{"id":"6127","tipo":"multipla","disciplina":"Fisica","tema":"Dinamica","subtema":"3a Lei de Newton","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"De acordo com a 3a Lei de Newton (acao e reacao):","alternativa_a":"Se A exerce forca sobre B, entao B exerce forca igual e oposta sobre A","alternativa_b":"Duas forcas iguais se cancelam sempre","alternativa_c":"A forca maior vence","alternativa_d":"A reacao e sempre menor que a acao","alternativa_e":"As forcas atuam no mesmo ponto","resposta_correta":"a","explicacao":"3a Lei: para toda acao ha uma reacao de mesma intensidade, mesma direcao e sentido oposto, em corpos diferentes.","resposta":""},
# --- TRABALHO E ENERGIA ---
{"id":"6128","tipo":"multipla","disciplina":"Fisica","tema":"Trabalho e Energia","subtema":"Trabalho","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Uma forca de 10 N desloca um objeto 5 m na mesma direcao da forca. O trabalho realizado e:","alternativa_a":"50 J","alternativa_b":"15 J","alternativa_c":"2 J","alternativa_d":"100 J","alternativa_e":"25 J","resposta_correta":"a","explicacao":"T = F x d = 10 x 5 = 50 J.","resposta":""},
{"id":"6129","tipo":"multipla","disciplina":"Fisica","tema":"Trabalho e Energia","subtema":"Energia cinetica","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um objeto de 2 kg se move a 10 m/s. Sua energia cinetica e:","alternativa_a":"100 J","alternativa_b":"20 J","alternativa_c":"200 J","alternativa_d":"50 J","alternativa_e":"40 J","resposta_correta":"a","explicacao":"Ec = m v^2 / 2 = 2 x 100 / 2 = 100 J.","resposta":""},
{"id":"6130","tipo":"multipla","disciplina":"Fisica","tema":"Trabalho e Energia","subtema":"Energia potencial gravitacional","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Um objeto de 3 kg esta a 10 m de altura (g=10 m/s2). Sua energia potencial gravitacional e:","alternativa_a":"300 J","alternativa_b":"30 J","alternativa_c":"150 J","alternativa_d":"600 J","alternativa_e":"100 J","resposta_correta":"a","explicacao":"Ep = m x g x h = 3 x 10 x 10 = 300 J.","resposta":""},
# --- HIDROSTÁTICA ---
{"id":"6131","tipo":"multipla","disciplina":"Fisica","tema":"Hidrostatica","subtema":"Pressao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Uma forca de 100 N e aplicada uniformemente sobre uma area de 0,5 m2. A pressao e:","alternativa_a":"200 Pa","alternativa_b":"50 Pa","alternativa_c":"100 Pa","alternativa_d":"500 Pa","alternativa_e":"150 Pa","resposta_correta":"a","explicacao":"P = F/A = 100/0,5 = 200 Pa.","resposta":""},
{"id":"6132","tipo":"multipla","disciplina":"Fisica","tema":"Hidrostatica","subtema":"Empuxo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O principio de Arquimedes afirma que um corpo imerso em fluido recebe um empuxo igual a:","alternativa_a":"O peso do fluido deslocado pelo corpo","alternativa_b":"O peso do proprio corpo","alternativa_c":"O volume do corpo","alternativa_d":"A pressao no fundo do liquido","alternativa_e":"A massa do fluido","resposta_correta":"a","explicacao":"Principio de Arquimedes: E = d_fluido x V_imerso x g (peso do fluido deslocado).","resposta":""},
# --- TERMOLOGIA ---
{"id":"6133","tipo":"multipla","disciplina":"Fisica","tema":"Termologia","subtema":"Temperatura e escalas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A temperatura de 100 graus Celsius, convertida para Kelvin, e:","alternativa_a":"373 K","alternativa_b":"273 K","alternativa_c":"100 K","alternativa_d":"473 K","alternativa_e":"173 K","resposta_correta":"a","explicacao":"K = C + 273 = 100 + 273 = 373 K.","resposta":""},
{"id":"6134","tipo":"multipla","disciplina":"Fisica","tema":"Termologia","subtema":"Dilatacao termica","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A dilatacao linear de um solido depende principalmente de:","alternativa_a":"O comprimento inicial, o coeficiente de dilatacao e a variacao de temperatura","alternativa_b":"Apenas da massa do solido","alternativa_c":"Apenas da variacao de temperatura","alternativa_d":"Da cor e da textura do material","alternativa_e":"Da pressao sobre o solido","resposta_correta":"a","explicacao":"DeltaL = L0 x alfa x DeltaT. Os tres fatores determinam a dilatacao.","resposta":""},
# --- ONDULATORIA ---
{"id":"6135","tipo":"multipla","disciplina":"Fisica","tema":"Ondulatoria","subtema":"Velocidade de onda","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Uma onda tem frequencia de 5 Hz e comprimento de onda de 4 m. Qual e sua velocidade?","alternativa_a":"20 m/s","alternativa_b":"1,25 m/s","alternativa_c":"9 m/s","alternativa_d":"25 m/s","alternativa_e":"15 m/s","resposta_correta":"a","explicacao":"v = lambda x f = 4 x 5 = 20 m/s.","resposta":""},
{"id":"6136","tipo":"multipla","disciplina":"Fisica","tema":"Ondulatoria","subtema":"Classificacao das ondas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O som e um exemplo de onda:","alternativa_a":"Longitudinal e mecanica","alternativa_b":"Transversal e eletromagnetica","alternativa_c":"Longitudinal e eletromagnetica","alternativa_d":"Transversal e mecanica","alternativa_e":"Eletromagnetica e luminosa","resposta_correta":"a","explicacao":"O som e uma onda mecanica (precisa de meio material) e longitudinal (vibracao paralela a propagacao).","resposta":""},
# --- OPTICA ---
{"id":"6137","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Reflexao da luz","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A lei de reflexao afirma que o angulo de incidencia e igual ao:","alternativa_a":"Angulo de reflexao","alternativa_b":"Angulo de refracao","alternativa_c":"Angulo critico","alternativa_d":"Angulo de polarizacao","alternativa_e":"Angulo de difusao","resposta_correta":"a","explicacao":"1a lei da reflexao: angulo de incidencia = angulo de reflexao (em relacao a normal).","resposta":""},
{"id":"6138","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Refracao da luz","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Quando a luz passa do ar para a agua, ela:","alternativa_a":"Reduz a velocidade e pode mudar de direcao","alternativa_b":"Aumenta a velocidade","alternativa_c":"Nao muda de direcao","alternativa_d":"Perde sua frequencia","alternativa_e":"Aumenta o comprimento de onda","resposta_correta":"a","explicacao":"Na refracao, ao mudar de meio, a velocidade da luz muda, podendo alterar sua direcao.","resposta":""},
# --- ELETROSTATICA ---
{"id":"6139","tipo":"multipla","disciplina":"Fisica","tema":"Eletrostatica","subtema":"Lei de Coulomb","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A lei de Coulomb afirma que a forca entre cargas eletricas e:","alternativa_a":"Proporcional ao produto das cargas e inversamente proporcional ao quadrado da distancia","alternativa_b":"Proporcional ao quadrado das cargas","alternativa_c":"Inversamente proporcional ao produto das cargas","alternativa_d":"Sempre atrativa","alternativa_e":"Independente da distancia","resposta_correta":"a","explicacao":"F = k x q1 x q2 / d^2. Lei de Coulomb: F proporcional a q1xq2 e a 1/d^2.","resposta":""},
{"id":"6140","tipo":"multipla","disciplina":"Fisica","tema":"Eletrostatica","subtema":"Tipos de cargas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Cargas eletricas de mesmo sinal se:","alternativa_a":"Repelem","alternativa_b":"Atraem","alternativa_c":"Se anulam","alternativa_d":"Formam neutrons","alternativa_e":"Nao interagem","resposta_correta":"a","explicacao":"Cargas iguais se repelem; cargas opostas se atraem.","resposta":""},
# --- ELETRODINAMICA E CIRCUITOS ---
{"id":"6141","tipo":"multipla","disciplina":"Fisica","tema":"Eletrodinamica","subtema":"Lei de Ohm","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um resistor de 10 Ohms recebe uma tensao de 20 V. A corrente que o percorre e:","alternativa_a":"2 A","alternativa_b":"10 A","alternativa_c":"0,5 A","alternativa_d":"200 A","alternativa_e":"4 A","resposta_correta":"a","explicacao":"1a Lei de Ohm: I = V/R = 20/10 = 2 A.","resposta":""},
{"id":"6142","tipo":"multipla","disciplina":"Fisica","tema":"Circuitos Eletricos","subtema":"Resistores em serie","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Dois resistores de 4 Ohms e 6 Ohms estao em serie. A resistencia equivalente e:","alternativa_a":"10 Ohms","alternativa_b":"2,4 Ohms","alternativa_c":"5 Ohms","alternativa_d":"24 Ohms","alternativa_e":"8 Ohms","resposta_correta":"a","explicacao":"Em serie, Req = R1 + R2 = 4 + 6 = 10 Ohms.","resposta":""},
{"id":"6143","tipo":"multipla","disciplina":"Fisica","tema":"Circuitos Eletricos","subtema":"Resistores em paralelo","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Dois resistores de 6 Ohms em paralelo. A resistencia equivalente e:","alternativa_a":"3 Ohms","alternativa_b":"12 Ohms","alternativa_c":"6 Ohms","alternativa_d":"9 Ohms","alternativa_e":"4 Ohms","resposta_correta":"a","explicacao":"Em paralelo com resistores iguais: Req = R/n = 6/2 = 3 Ohms.","resposta":""},
# --- IMPULSO E QUANTIDADE DE MOVIMENTO ---
{"id":"6144","tipo":"multipla","disciplina":"Fisica","tema":"Dinamica","subtema":"Quantidade de movimento","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um objeto de 4 kg se move a 5 m/s. Sua quantidade de movimento (momento linear) e:","alternativa_a":"20 kg.m/s","alternativa_b":"9 kg.m/s","alternativa_c":"1,25 kg.m/s","alternativa_d":"40 kg.m/s","alternativa_e":"10 kg.m/s","resposta_correta":"a","explicacao":"p = m x v = 4 x 5 = 20 kg.m/s.","resposta":""},
{"id":"6145","tipo":"multipla","disciplina":"Fisica","tema":"Dinamica","subtema":"Conservacao do momento","dificuldade":"Medio","fonte":"Vestibular","ano":"2022","enunciado":"O principio da conservacao da quantidade de movimento afirma que em um sistema isolado:","alternativa_a":"O momento total antes e apos a colisao e igual","alternativa_b":"A energia cinetica total se conserva sempre","alternativa_c":"O momento aumenta na colisao","alternativa_d":"As velocidades sao sempre iguais apos o choque","alternativa_e":"As massas se conservam separadamente","resposta_correta":"a","explicacao":"Em sistemas isolados (sem forcas externas), o momento total se conserva: p_antes = p_depois.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote55.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 55 criado: {len(rows)} questoes")
