# -*- coding: utf-8 -*-
# Lote 56 - Quimica e Biologia: subtopicos especificos
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- QUIMICA: ESTRUTURA ATOMICA ---
{"id":"6201","tipo":"multipla","disciplina":"Quimica","tema":"Estrutura Atomica","subtema":"Particulas subatomicas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O nucleo atomico e composto por:","alternativa_a":"Protons e neutrons","alternativa_b":"Protons e eletrons","alternativa_c":"Eletrons e neutrons","alternativa_d":"Apenas protons","alternativa_e":"Apenas eletrons","resposta_correta":"a","explicacao":"O nucleo contem protons (carga +) e neutrons (neutros). Os eletrons orbitam ao redor do nucleo.","resposta":""},
{"id":"6202","tipo":"multipla","disciplina":"Quimica","tema":"Estrutura Atomica","subtema":"Numero atomico e massa","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O numero atomico (Z) de um elemento e igual ao numero de:","alternativa_a":"Protons (e igual ao numero de eletrons no atomo neutro)","alternativa_b":"Neutrons","alternativa_c":"Eletrons mais neutrons","alternativa_d":"Protons mais neutrons","alternativa_e":"Nucleons","resposta_correta":"a","explicacao":"Z = numero de protons = numero de eletrons (no atomo neutro). A = Z + N (neutrons).","resposta":""},
{"id":"6203","tipo":"multipla","disciplina":"Quimica","tema":"Estrutura Atomica","subtema":"Isotopos","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Isotopos sao atomos do mesmo elemento que diferem no numero de:","alternativa_a":"Neutrons","alternativa_b":"Protons","alternativa_c":"Eletrons","alternativa_d":"Protons e eletrons","alternativa_e":"Protons e neutrons","resposta_correta":"a","explicacao":"Isotopos: mesmo Z (mesmo elemento), diferente N (neutrons), portanto diferente massa atomica.","resposta":""},
# --- LIGACOES QUIMICAS ---
{"id":"6204","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Ligacao ionica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A ligacao ionica ocorre entre:","alternativa_a":"Metal e nao metal (transferencia de eletrons)","alternativa_b":"Dois nao metais (compartilhamento)","alternativa_c":"Dois metais","alternativa_d":"Metal e gas nobre","alternativa_e":"Dois gases nobres","resposta_correta":"a","explicacao":"Na ligacao ionica, um metal perde eletrons (cation) e um nao metal ganha (anion), formando ions de cargas opostas.","resposta":""},
{"id":"6205","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Ligacao covalente","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A ligacao covalente envolve:","alternativa_a":"Compartilhamento de pares de eletrons entre nao metais","alternativa_b":"Transferencia total de eletrons","alternativa_c":"Nuvem eletronica livre","alternativa_d":"Apenas metais","alternativa_e":"Ions positivos","resposta_correta":"a","explicacao":"Na ligacao covalente, atomos compartilham pares de eletrons para completar o octeto.","resposta":""},
{"id":"6206","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Ligacao metalica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A ligacao metalica explica propriedades como condutividade eletrica e maleabilidade porque:","alternativa_a":"Os eletrons livres circulam entre os captions metalicos","alternativa_b":"Os atomos compartilham eletrons em pares definidos","alternativa_c":"Ions se repelem","alternativa_d":"Os eletrons estao fixos nos atomos","alternativa_e":"Ha transferencia completa de eletrons","resposta_correta":"a","explicacao":"Nos metais, eletrons de valencia formam um mar de eletrons livres, conferindo condutividade e maleabilidade.","resposta":""},
# --- FUNCOES INORGANICAS ---
{"id":"6207","tipo":"multipla","disciplina":"Quimica","tema":"Funcoes Inorganicas","subtema":"Acidos","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"De acordo com a teoria de Arrhenius, um acido e uma substancia que, em agua, libera ions:","alternativa_a":"H+ (hidrogenio)","alternativa_b":"OH-","alternativa_c":"Na+","alternativa_d":"Cl-","alternativa_e":"O2-","resposta_correta":"a","explicacao":"Segundo Arrhenius, acido libera H+ em agua. Exemplo: HCl -> H+ + Cl-.","resposta":""},
{"id":"6208","tipo":"multipla","disciplina":"Quimica","tema":"Funcoes Inorganicas","subtema":"Bases","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Uma base, segundo Arrhenius, e uma substancia que em agua libera ions:","alternativa_a":"OH- (hidroxila)","alternativa_b":"H+","alternativa_c":"SO4 2-","alternativa_d":"Na+","alternativa_e":"Ca2+","resposta_correta":"a","explicacao":"Segundo Arrhenius, base libera OH- em agua. Exemplo: NaOH -> Na+ + OH-.","resposta":""},
{"id":"6209","tipo":"multipla","disciplina":"Quimica","tema":"Funcoes Inorganicas","subtema":"pH","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Uma solucao com pH 4 e considerada:","alternativa_a":"Acida","alternativa_b":"Basica","alternativa_c":"Neutra","alternativa_d":"Alcalina","alternativa_e":"Indeterminada","resposta_correta":"a","explicacao":"pH < 7: acida. pH = 7: neutra. pH > 7: basica. pH 4 e acida.","resposta":""},
# --- ESTEQUIOMETRIA ---
{"id":"6210","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Mol e numero de Avogadro","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um mol de qualquer substancia contem aproximadamente:","alternativa_a":"6,02 x 10^23 entidades (numero de Avogadro)","alternativa_b":"12 gramas","alternativa_c":"22,4 gramas","alternativa_d":"1 grama","alternativa_e":"1000 entidades","resposta_correta":"a","explicacao":"1 mol = 6,02 x 10^23 particulas (atomo, molec, ions), independente da substancia.","resposta":""},
{"id":"6211","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Calculo estequiometrico","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Na reacao 2H2 + O2 -> 2H2O, quantos moles de H2O sao produzidos a partir de 4 moles de H2?","alternativa_a":"4 moles","alternativa_b":"2 moles","alternativa_c":"8 moles","alternativa_d":"1 mol","alternativa_e":"6 moles","resposta_correta":"a","explicacao":"Proporcao: 2 H2 : 2 H2O. Para 4 H2: 4 H2O.","resposta":""},
# --- SOLUCOES ---
{"id":"6212","tipo":"multipla","disciplina":"Quimica","tema":"Solucoes","subtema":"Concentracao molar","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Dissolve-se 1 mol de NaCl em agua ate completar 1 litro. A concentracao molar e:","alternativa_a":"1 mol/L","alternativa_b":"0,5 mol/L","alternativa_c":"2 mol/L","alternativa_d":"1,5 mol/L","alternativa_e":"0,1 mol/L","resposta_correta":"a","explicacao":"Molaridade (M) = n moles / volume em litros = 1/1 = 1 mol/L.","resposta":""},
{"id":"6213","tipo":"multipla","disciplina":"Quimica","tema":"Solucoes","subtema":"Solubilidade","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Uma solucao saturada e aquela que:","alternativa_a":"Nao consegue dissolver mais soluto a determinada temperatura","alternativa_b":"Tem menos soluto que o maximo possivel","alternativa_c":"Esta em ebulicao","alternativa_d":"Tem pH neutro","alternativa_e":"Contem apenas gas dissolvido","resposta_correta":"a","explicacao":"Solucao saturada: contendo a quantidade maxima de soluto possivel a dada temperatura.","resposta":""},
# --- TERMOQUIMICA ---
{"id":"6214","tipo":"multipla","disciplina":"Quimica","tema":"Termoquimica","subtema":"Reacao exotermica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Uma reacao exotermica e aquela que:","alternativa_a":"Libera calor para o ambiente (delta H < 0)","alternativa_b":"Absorve calor do ambiente (delta H > 0)","alternativa_c":"Nao envolve variacao de energia","alternativa_d":"Ocorre so em altas temperaturas","alternativa_e":"Produz frio","resposta_correta":"a","explicacao":"Exotermica: libera energia (deltaH < 0). Endotermica: absorve (deltaH > 0).","resposta":""},
{"id":"6215","tipo":"multipla","disciplina":"Quimica","tema":"Termoquimica","subtema":"Lei de Hess","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A Lei de Hess afirma que a variacao de entalpia de uma reacao:","alternativa_a":"Independe do caminho reacional, dependendo apenas do estado inicial e final","alternativa_b":"Depende do catalisador utilizado","alternativa_c":"E sempre negativa","alternativa_d":"Depende da velocidade da reacao","alternativa_e":"Muda conforme a pressao","resposta_correta":"a","explicacao":"Lei de Hess: DeltaH total e igual a soma dos DeltaH das etapas, independente do caminho.","resposta":""},
# --- CINETICA QUIMICA ---
{"id":"6216","tipo":"multipla","disciplina":"Quimica","tema":"Cinetica Quimica","subtema":"Fatores que influenciam a velocidade","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Aumentar a temperatura de uma reacao quimica normalmente:","alternativa_a":"Aumenta a velocidade da reacao","alternativa_b":"Reduz a velocidade","alternativa_c":"Nao afeta a velocidade","alternativa_d":"Para a reacao","alternativa_e":"Aumenta o pH","resposta_correta":"a","explicacao":"O aumento de temperatura aumenta a energia cinetica das particulas, aumentando colisoes efetivas.","resposta":""},
{"id":"6217","tipo":"multipla","disciplina":"Quimica","tema":"Cinetica Quimica","subtema":"Catalisador","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um catalisador aumenta a velocidade de uma reacao porque:","alternativa_a":"Diminui a energia de ativacao necessaria","alternativa_b":"Fornece mais energia para as moleculas","alternativa_c":"Aumenta a concentracao dos reagentes","alternativa_d":"Aumenta a temperatura do sistema","alternativa_e":"Altera os produtos da reacao","resposta_correta":"a","explicacao":"Catalisador abre um caminho alternativo com menor energia de ativacao, acelerando a reacao sem ser consumido.","resposta":""},
# --- EQUILIBRIO QUIMICO ---
{"id":"6218","tipo":"multipla","disciplina":"Quimica","tema":"Equilibrio Quimico","subtema":"Principio de Le Chatelier","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"O Principio de Le Chatelier afirma que, ao se pertrubar um equilibrio, o sistema:","alternativa_a":"Reage de forma a minimizar a perturbacao e atingir novo equilibrio","alternativa_b":"Para a reacao","alternativa_c":"Acelera sempre para a direita","alternativa_d":"Permanece inalterado","alternativa_e":"Aumenta a temperatura sempre","resposta_correta":"a","explicacao":"Le Chatelier: um sistema em equilibrio ao sofrer perturbacao (pressao, temp, conc) evolui para compensar.","resposta":""},
# --- ELETROQUIMICA ---
{"id":"6219","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Pilha galvanica","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Em uma pilha galvanica (eletroquimica), o anodo e o polo onde ocorre:","alternativa_a":"Oxidacao (perda de eletrons)","alternativa_b":"Reducao (ganho de eletrons)","alternativa_c":"Producao de gas hidrogenio","alternativa_d":"Deposicao de metal","alternativa_e":"Nenhuma reacao","resposta_correta":"a","explicacao":"Mnemonica: AnOx (Anodo-Oxidacao) e RedCat (Reducao-Catodo).","resposta":""},
{"id":"6220","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Eletrolicidade","dificuldade":"Facil","fonte":"ENEM","ano":"2022","enunciado":"A corrosao de metais e um processo de:","alternativa_a":"Oxidacao","alternativa_b":"Reducao","alternativa_c":"Neutralizacao","alternativa_d":"Sintese","alternativa_e":"Decomposicao","resposta_correta":"a","explicacao":"Corrosao e a oxidacao espontanea do metal pelo ambiente, principalmente pelo oxigenio e agua.","resposta":""},
# --- QUIMICA ORGANICA ---
{"id":"6221","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Hidrocarb - funcoes organicas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Os alcanos sao hidrocarbonetos caracterizados por:","alternativa_a":"Possuirem apenas ligacoes simples entre os carbonos (C-C)","alternativa_b":"Terem uma ligacao dupla","alternativa_c":"Terem ligacao tripla","alternativa_d":"Conterem nitrogenio","alternativa_e":"Serem aromaticos","resposta_correta":"a","explicacao":"Alcanos: CnH(2n+2), apenas ligacoes simples. Sao saturados. Ex: metano, etano, propano.","resposta":""},
{"id":"6222","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Isomeria","dificuldade":"Medio","fonte":"Vestibular","ano":"2022","enunciado":"Isomeros sao compostos que possuem:","alternativa_a":"A mesma formula molecular mas estruturas diferentes","alternativa_b":"A mesma estrutura e formulas iguais","alternativa_c":"Formulas moleculares diferentes","alternativa_d":"Os mesmos pontos de fusao","alternativa_e":"Os mesmos nomes IUPAC","resposta_correta":"a","explicacao":"Isomeros: mesma formula molecular (ex: C2H6O), mas estruturas e propriedades diferentes.","resposta":""},
# --- POLIMEROS E QUIMICA AMBIENTAL ---
{"id":"6223","tipo":"multipla","disciplina":"Quimica","tema":"Polimeros","subtema":"Polimeros sinteticos","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O plastico e formado por longas cadeias de moleculas chamadas:","alternativa_a":"Polimeros","alternativa_b":"Monomeros","alternativa_c":"Isomeros","alternativa_d":"Catalisadores","alternativa_e":"Eletrolitons","resposta_correta":"a","explicacao":"Polimeros sao macromoleculas formadas por repeticao de monomeros. Plasticos sao polimeros sinteticos.","resposta":""},
{"id":"6224","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Chuva acida","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A chuva acida e causada principalmente pelas emissoes de:","alternativa_a":"SO2 e NOx que formam acidos ao reagirem com a agua da chuva","alternativa_b":"CO2 e metano","alternativa_c":"Gas nobre e vapor d agua","alternativa_d":"Oxigenio e nitrogenio","alternativa_e":"CFC e ozonio","resposta_correta":"a","explicacao":"SO2 (queima de combustiveis) e NOx formam H2SO4 e HNO3 na atmosfera, causando chuva acida.","resposta":""},
{"id":"6225","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Camada de ozonio","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A destruicao da camada de ozonio e causada principalmente pelo gas:","alternativa_a":"CFC (clorofluorcarbono)","alternativa_b":"CO2","alternativa_c":"SO2","alternativa_d":"Metano","alternativa_e":"Vapor d agua","resposta_correta":"a","explicacao":"O CFC libera cloro que catalisa a decomposicao do ozonio (O3) na estratosfera.","resposta":""},
# --- BIOLOGIA: CITOLOGIA ---
{"id":"6226","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Celula procariontica e eucariontica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A principal diferenca entre celulas procarionticas e eucarionticas e:","alternativa_a":"As eucarionticas possuem nucleo definido por membrana e as procarionticas nao","alternativa_b":"As procarionticas sao maiores","alternativa_c":"As eucarionticas nao possuem DNA","alternativa_d":"As procarionticas possuem mitocondrias","alternativa_e":"Ambas possuem nucleo definido","resposta_correta":"a","explicacao":"Procarionte: sem nucleo envolto por membrana (bacteria). Eucarionte: com nucleo verdadeiro.","resposta":""},
{"id":"6227","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Membrana plasmatica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A membrana plasmatica e composta principalmente por:","alternativa_a":"Bicamada fosfolipidica com proteinas inseridas","alternativa_b":"Polissacarideos e lipidios","alternativa_c":"DNA e proteinas","alternativa_d":"Celulose e lignina","alternativa_e":"Calda de silica","resposta_correta":"a","explicacao":"Modelo do mosaico fluido: bicamada de fosfolipidios com proteinas perifericas e integrais.","resposta":""},
{"id":"6228","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Mitocondria","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A mitocondria e conhecida como a usina de energia da celula porque:","alternativa_a":"Realiza a respiracao celular e produz ATP","alternativa_b":"Faz a fotossintese","alternativa_c":"Sintetiza proteinas","alternativa_d":"Armazena DNA nuclear","alternativa_e":"Forma o citoesqueleto","resposta_correta":"a","explicacao":"A mitocondria realiza a respiracao aerobica, produzindo ATP (energia quimica) a partir de glicose e O2.","resposta":""},
# --- BIOQUIMICA ---
{"id":"6229","tipo":"multipla","disciplina":"Biologia","tema":"Bioquimica","subtema":"Proteinas","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"As proteinas sao formadas por unidades basicas chamadas:","alternativa_a":"Aminoacidos","alternativa_b":"Glicerol","alternativa_c":"Nucleotideos","alternativa_d":"Glicose","alternativa_e":"Acidos graxos","resposta_correta":"a","explicacao":"Proteinas = cadeias de aminoacidos ligados por ligacoes peptidicas. Existem 20 aminoacidos essenciais.","resposta":""},
{"id":"6230","tipo":"multipla","disciplina":"Biologia","tema":"Bioquimica","subtema":"DNA e RNA","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O DNA e composto por nucleotideos que contem as bases nitrogenadas:","alternativa_a":"Adenina, Timina, Guanina e Citosina","alternativa_b":"Adenina, Uracila, Guanina e Citosina","alternativa_c":"Glicose, Fosfato, Adenina e Guanina","alternativa_d":"Aminoacidos e bases nitrogenadas","alternativa_e":"Ribose, Uracila e Adenina","resposta_correta":"a","explicacao":"DNA: A, T, G, C (Timina e exclusiva do DNA). RNA: A, U, G, C (Uracila no lugar de Timina).","resposta":""},
# --- GENETICA ---
{"id":"6231","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"1a Lei de Mendel","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A Primeira Lei de Mendel (segregacao) afirma que:","alternativa_a":"Os alelos de um par se segregam na formacao dos gametas","alternativa_b":"Genes de cromossomos diferentes se distribuem de forma independente","alternativa_c":"O alelo dominante sempre aparece no fenot.","alternativa_d":"Todos os filhos F1 sao identicos","alternativa_e":"O DNA e transmitido apenas pela mae","resposta_correta":"a","explicacao":"1a Lei: cada individuo diploid. tem dois alelos para cada gene, que se separam na meiose (gametas haploides).","resposta":""},
{"id":"6232","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Cruzamento Mendeliano","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"No cruzamento entre dois individuos heterozigotos Aa x Aa, a proporcao fenotipica esperada e:","alternativa_a":"3 dominantes para 1 recessivo","alternativa_b":"1:1","alternativa_c":"todos dominantes","alternativa_d":"todos recessivos","alternativa_e":"2:2","resposta_correta":"a","explicacao":"Aa x Aa => AA:Aa:aa = 1:2:1 (genotipica). Fenotipica: 3 com A_ (dominante) : 1 com aa.","resposta":""},
{"id":"6233","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Mutacao","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A radiacao UV pode causar mutacoes no DNA porque:","alternativa_a":"Provoca dimerizacao de timina, alterando a sequencia do DNA","alternativa_b":"Desnatura as proteinas","alternativa_c":"Destroi o nucleo celular","alternativa_d":"Impede a fotossintese","alternativa_e":"Aumenta a taxa de meiose","resposta_correta":"a","explicacao":"A UV causa ligacoes cruzadas entre bases de timina adjacentes, gerando mutacoes se nao reparadas.","resposta":""},
# --- EVOLUCAO ---
{"id":"6234","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Selecao natural","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O principal mecanismo de evolucao proposto por Darwin e Wallace e:","alternativa_a":"Selecao natural","alternativa_b":"Mutacao dirigida","alternativa_c":"Heranca de caracteres adquiridos","alternativa_d":"Deriva genetica","alternativa_e":"Recombinacao","resposta_correta":"a","explicacao":"Darwin: selecao natural - individuos com caracteristicas vantajosas sobrevivem e se reproduzem mais.","resposta":""},
{"id":"6235","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Evidencias de evolucao","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Orgaos vestigiais (como o cocix humano) sao evidencias de evolucao porque:","alternativa_a":"Indicam ancestrais comuns e perda de funcao ao longo da evolucao","alternativa_b":"Sao estruturas sem origem biologica","alternativa_c":"Provam a criacao especial","alternativa_d":"Nao tem relacao com outros grupos","alternativa_e":"Sao exclusivos de mamiferos","resposta_correta":"a","explicacao":"Orgaos vestigiais sao estruturas reduzidas sem funcao atual, mas funcionais em ancestrais.","resposta":""},
# --- ECOLOGIA ---
{"id":"6236","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Cadeia alimentar","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Em uma cadeia alimentar capim -> gafanhoto -> sapo -> cobra -> gaviao, os produtores sao:","alternativa_a":"O capim","alternativa_b":"Os gafanhotos","alternativa_c":"Os sapos","alternativa_d":"As cobras","alternativa_e":"Os gaviaes","resposta_correta":"a","explicacao":"Produtores sao os autotrofos (realizam fotossintese). Na cadeia: capim e o produtor.","resposta":""},
{"id":"6237","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Biomas brasileiros","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A Mata Atlantica e um dos biomas mais ameacados do Brasil. Hoje, restam aproximadamente:","alternativa_a":"12 a 15% da cobertura original","alternativa_b":"50%","alternativa_c":"70%","alternativa_d":"30%","alternativa_e":"80%","resposta_correta":"a","explicacao":"A Mata Atlantica perdeu mais de 85% de sua area original; restam apenas 12-15% de remanescentes.","resposta":""},
{"id":"6238","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Ciclos biogeoquimicos","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A decomposicao de materia organica devolve nutrientes ao solo e e realizada principalmente por:","alternativa_a":"Bacterias e fungos decompositores","alternativa_b":"Herbivoros","alternativa_c":"Carnivoros","alternativa_d":"Vegetais","alternativa_e":"Algas marinhas","resposta_correta":"a","explicacao":"Decompositores (bacterias e fungos) reciclam a materia organica, devolvendo minerais ao solo.","resposta":""},
{"id":"6239","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Desmatamento e impacto","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O desmatamento aumenta o efeito estufa principalmente porque:","alternativa_a":"Reduz a absorcao de CO2 e libera carbono estocado nas arvores","alternativa_b":"Aumenta a producao de O2","alternativa_c":"Nao afeta os gases atmosfericos","alternativa_d":"Aumenta a biodiversidade","alternativa_e":"Resfria o planeta","resposta_correta":"a","explicacao":"As arvores absorvem CO2; ao serem derrubadas, liberam o carbono estocado e reduzem a captura futura.","resposta":""},
# --- FISIOLOGIA HUMANA ---
{"id":"6240","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema digestivo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A digestao quimica de proteinas comeca no:","alternativa_a":"Estomago (pela pepsina em meio acido)","alternativa_b":"Boca","alternativa_c":"Intestino delgado","alternativa_d":"Intestino grosso","alternativa_e":"Esofago","resposta_correta":"a","explicacao":"No estomago, a pepsina (ativada pelo HCl) inicia a digestao proteica. Na boca so ha digestao de amido.","resposta":""},
{"id":"6241","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema circulatorio","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A circulacao pulmonar transporta sangue do coracao para os pulmoes para:","alternativa_a":"Oxigenar o sangue e eliminar CO2","alternativa_b":"Levar nutrientes aos pulmoes","alternativa_c":"Filtrar o sangue","alternativa_d":"Produzir hormonios","alternativa_e":"Distribuir calor","resposta_correta":"a","explicacao":"Na circulacao pulmonar, o sangue venoso vai do VD aos pulmoes, onde recebe O2 e libera CO2.","resposta":""},
# --- BOTÂNICA ---
{"id":"6242","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Fotossintese","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A fotossintese ocorre principalmente nos cloroplastos e transforma:","alternativa_a":"Luz solar, CO2 e agua em glicose e O2","alternativa_b":"Glicose e O2 em CO2 e agua","alternativa_c":"Proteinas em aminoacidos","alternativa_d":"O2 em CO2","alternativa_e":"Solo em nutrientes","resposta_correta":"a","explicacao":"Equacao geral: 6CO2 + 6H2O + luz -> C6H12O6 + 6O2. Organismos autotrofos fixam o carbono atmosferico.","resposta":""},
# --- BIOTECNOLOGIA E SAUDE ---
{"id":"6243","tipo":"multipla","disciplina":"Biologia","tema":"Biotecnologia","subtema":"DNA recombinante","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"A tecnologia do DNA recombinante permite:","alternativa_a":"Inserir genes de um organismo em outro para produzir proteinas uteis (ex: insulina)","alternativa_b":"Clonar orgaos naturais sem alteracao genetica","alternativa_c":"Criar vida do zero","alternativa_d":"Eliminar todas as doencas geneticas","alternativa_e":"Aumentar a biodiversidade sem intervencao","resposta_correta":"a","explicacao":"DNA recombinante: unir DNA de diferentes origens. Usado para producao de insulina, vacinas, etc.","resposta":""},
{"id":"6244","tipo":"multipla","disciplina":"Biologia","tema":"Saude","subtema":"Vacinacao","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A imunidade coletiva (efeito de rebanho) ocorre quando:","alternativa_a":"Uma proporcao suficiente da populacao esta imunizada, protegendo inclusive os nao vacinados","alternativa_b":"Todos os individuos sao naturalmente imunes","alternativa_c":"O virus muta e se torna inofensivo","alternativa_d":"Apenas criancas sao vacinadas","alternativa_e":"Os antibioticos eliminam o agente infeccioso","resposta_correta":"a","explicacao":"Quando suficientes pessoas estao imunes, a transmissao cai tanto que protege os vulneraveis nao vacinados.","resposta":""},
{"id":"6245","tipo":"multipla","disciplina":"Biologia","tema":"Saude","subtema":"Saude publica","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"O vetor transmissor da dengue, zika e chikungunya no Brasil e:","alternativa_a":"O mosquito Aedes aegypti","alternativa_b":"O barbeiro","alternativa_c":"O Anopheles","alternativa_d":"O pernilongo comum","alternativa_e":"A mosca tse-tse","resposta_correta":"a","explicacao":"O Aedes aegypti transmite dengue, zika, chikungunya e febre amarela. Prolifera em agua parada.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote56.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 56 criado: {len(rows)} questoes")
