# -*- coding: utf-8 -*-
# Lote 54 - Matematica: subtopicos especificos (porcentagem, fracoes, equacoes, geometria, trigonometria)
import csv, os
BASE = '/Users/dennysrian_/Desktop/aprova-ia'

rows = [
# --- PORCENTAGEM ---
{"id":"6001","tipo":"multipla","disciplina":"Matematica","tema":"Porcentagem","subtema":"Calculo de porcentagem","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um produto custava R$ 200,00 e teve aumento de 15%. Qual o novo preco?","alternativa_a":"R$ 230,00","alternativa_b":"R$ 215,00","alternativa_c":"R$ 220,00","alternativa_d":"R$ 240,00","alternativa_e":"R$ 235,00","resposta_correta":"a","explicacao":"200 x 1,15 = 230. Aumento de 15% sobre 200 e 30, logo 200 + 30 = 230.","resposta":""},
{"id":"6002","tipo":"multipla","disciplina":"Matematica","tema":"Porcentagem","subtema":"Desconto","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um produto de R$ 500,00 teve desconto de 20%. Quanto custa apos o desconto?","alternativa_a":"R$ 400,00","alternativa_b":"R$ 480,00","alternativa_c":"R$ 450,00","alternativa_d":"R$ 420,00","alternativa_e":"R$ 380,00","resposta_correta":"a","explicacao":"500 x 0,80 = 400. Desconto de 20% e 100, logo 500 - 100 = 400.","resposta":""},
{"id":"6003","tipo":"multipla","disciplina":"Matematica","tema":"Porcentagem","subtema":"Porcentagem inversa","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Apos um aumento de 25%, um produto passou a custar R$ 250,00. Qual era o preco original?","alternativa_a":"R$ 200,00","alternativa_b":"R$ 225,00","alternativa_c":"R$ 187,50","alternativa_d":"R$ 210,00","alternativa_e":"R$ 195,00","resposta_correta":"a","explicacao":"x * 1,25 = 250 => x = 250/1,25 = 200.","resposta":""},
{"id":"6004","tipo":"multipla","disciplina":"Matematica","tema":"Porcentagem","subtema":"Porcentagem composta","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um produto teve aumento de 10% e depois de 20%. O aumento total percentual foi de:","alternativa_a":"32%","alternativa_b":"30%","alternativa_c":"31%","alternativa_d":"33%","alternativa_e":"28%","resposta_correta":"a","explicacao":"1,10 x 1,20 = 1,32 => aumento de 32%.","resposta":""},
{"id":"6005","tipo":"multipla","disciplina":"Matematica","tema":"Porcentagem","subtema":"Porcentagem de uma quantidade","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Em uma turma de 40 alunos, 30% faltaram. Quantos alunos faltaram?","alternativa_a":"12","alternativa_b":"10","alternativa_c":"14","alternativa_d":"8","alternativa_e":"15","resposta_correta":"a","explicacao":"30% de 40 = 0,30 x 40 = 12.","resposta":""},
# --- RAZAO E PROPORCAO ---
{"id":"6006","tipo":"multipla","disciplina":"Matematica","tema":"Razao e Proporcao","subtema":"Razao","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A razao entre 12 e 4 e:","alternativa_a":"3","alternativa_b":"2","alternativa_c":"4","alternativa_d":"6","alternativa_e":"8","resposta_correta":"a","explicacao":"Razao = 12/4 = 3.","resposta":""},
{"id":"6007","tipo":"multipla","disciplina":"Matematica","tema":"Razao e Proporcao","subtema":"Proporcao direta","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Se 3 livros custam R$ 45,00, quanto custam 7 livros ao mesmo preco?","alternativa_a":"R$ 105,00","alternativa_b":"R$ 90,00","alternativa_c":"R$ 100,00","alternativa_d":"R$ 112,00","alternativa_e":"R$ 95,00","resposta_correta":"a","explicacao":"Proporcao direta: 45/3 = 15 por livro. 7 x 15 = 105.","resposta":""},
{"id":"6008","tipo":"multipla","disciplina":"Matematica","tema":"Razao e Proporcao","subtema":"Proporcao inversa","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"5 pedreiros constroem um muro em 12 dias. Em quantos dias 10 pedreiros constroem o mesmo muro?","alternativa_a":"6 dias","alternativa_b":"8 dias","alternativa_c":"10 dias","alternativa_d":"4 dias","alternativa_e":"7 dias","resposta_correta":"a","explicacao":"Proporcao inversa: 5 x 12 = 10 x d => d = 60/10 = 6.","resposta":""},
{"id":"6009","tipo":"multipla","disciplina":"Matematica","tema":"Razao e Proporcao","subtema":"Divisao proporcional","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Divida R$ 120,00 entre Ana e Bia na razao 1:2. Ana recebe:","alternativa_a":"R$ 40,00","alternativa_b":"R$ 60,00","alternativa_c":"R$ 80,00","alternativa_d":"R$ 30,00","alternativa_e":"R$ 50,00","resposta_correta":"a","explicacao":"Total de partes: 1+2=3. Ana: 1/3 de 120 = 40.","resposta":""},
{"id":"6010","tipo":"multipla","disciplina":"Matematica","tema":"Razao e Proporcao","subtema":"Escala","dificuldade":"Facil","fonte":"Vestibular","ano":"2023","enunciado":"Em um mapa na escala 1:50.000, uma distancia de 4 cm representa, na realidade:","alternativa_a":"2 km","alternativa_b":"4 km","alternativa_c":"5 km","alternativa_d":"1 km","alternativa_e":"3 km","resposta_correta":"a","explicacao":"4 cm x 50.000 = 200.000 cm = 2.000 m = 2 km.","resposta":""},
# --- REGRA DE TRES ---
{"id":"6011","tipo":"multipla","disciplina":"Matematica","tema":"Regra de Tres","subtema":"Regra de tres simples direta","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Se um carro percorre 300 km com 30 litros de gasolina, quantos litros serao necessarios para percorrer 500 km?","alternativa_a":"50 litros","alternativa_b":"45 litros","alternativa_c":"60 litros","alternativa_d":"40 litros","alternativa_e":"55 litros","resposta_correta":"a","explicacao":"300/30 = 500/x => x = 500*30/300 = 50.","resposta":""},
{"id":"6012","tipo":"multipla","disciplina":"Matematica","tema":"Regra de Tres","subtema":"Regra de tres simples inversa","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um trabalho e concluido por 8 operarios em 15 dias. Se 12 operarios forem usados, em quantos dias termina?","alternativa_a":"10 dias","alternativa_b":"12 dias","alternativa_c":"9 dias","alternativa_d":"8 dias","alternativa_e":"11 dias","resposta_correta":"a","explicacao":"8 x 15 = 12 x d => d = 120/12 = 10.","resposta":""},
{"id":"6013","tipo":"multipla","disciplina":"Matematica","tema":"Regra de Tres","subtema":"Regra de tres composta","dificuldade":"Dificil","fonte":"Vestibular","ano":"2022","enunciado":"4 maquinas produzem 400 pecas em 5 horas. Quantas pecas 6 maquinas produzem em 8 horas?","alternativa_a":"960","alternativa_b":"800","alternativa_c":"1200","alternativa_d":"720","alternativa_e":"840","resposta_correta":"a","explicacao":"400/(4x5) = x/(6x8) => x = 400*48/20 = 960.","resposta":""},
# --- FRACOES ---
{"id":"6014","tipo":"multipla","disciplina":"Matematica","tema":"Fracoes","subtema":"Operacoes com fracoes","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Quanto e 1/2 + 1/3?","alternativa_a":"5/6","alternativa_b":"2/5","alternativa_c":"2/6","alternativa_d":"1/5","alternativa_e":"3/5","resposta_correta":"a","explicacao":"MMC(2,3)=6. 3/6 + 2/6 = 5/6.","resposta":""},
{"id":"6015","tipo":"multipla","disciplina":"Matematica","tema":"Fracoes","subtema":"Multiplicacao de fracoes","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"3/4 multiplicado por 8/9 e igual a:","alternativa_a":"2/3","alternativa_b":"1/2","alternativa_c":"3/4","alternativa_d":"5/6","alternativa_e":"4/5","resposta_correta":"a","explicacao":"(3x8)/(4x9) = 24/36 = 2/3.","resposta":""},
{"id":"6016","tipo":"multipla","disciplina":"Matematica","tema":"Fracoes","subtema":"Fracao de um numero","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Qual e 3/5 de 40?","alternativa_a":"24","alternativa_b":"20","alternativa_c":"30","alternativa_d":"16","alternativa_e":"28","resposta_correta":"a","explicacao":"3/5 * 40 = 120/5 = 24.","resposta":""},
{"id":"6017","tipo":"multipla","disciplina":"Matematica","tema":"Fracoes","subtema":"Fracao decimal","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"A fracao 3/4 equivale a qual decimal?","alternativa_a":"0,75","alternativa_b":"0,60","alternativa_c":"0,80","alternativa_d":"0,50","alternativa_e":"0,70","resposta_correta":"a","explicacao":"3/4 = 3 dividido por 4 = 0,75.","resposta":""},
# --- POTENCIACAO E RADICIACAO ---
{"id":"6018","tipo":"multipla","disciplina":"Matematica","tema":"Potenciacao","subtema":"Potencia de numero natural","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Qual e o valor de 2 elevado a 8?","alternativa_a":"256","alternativa_b":"128","alternativa_c":"512","alternativa_d":"64","alternativa_e":"32","resposta_correta":"a","explicacao":"2^8 = 256 (2,4,8,16,32,64,128,256).","resposta":""},
{"id":"6019","tipo":"multipla","disciplina":"Matematica","tema":"Potenciacao","subtema":"Produto de potencias de mesma base","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"2^3 x 2^4 e igual a:","alternativa_a":"2^7","alternativa_b":"2^12","alternativa_c":"4^7","alternativa_d":"2^6","alternativa_e":"4^12","resposta_correta":"a","explicacao":"Produto de potencias de mesma base: soma os expoentes. 2^(3+4) = 2^7.","resposta":""},
{"id":"6020","tipo":"multipla","disciplina":"Matematica","tema":"Radiciacao","subtema":"Raiz quadrada","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Qual e a raiz quadrada de 196?","alternativa_a":"14","alternativa_b":"12","alternativa_c":"16","alternativa_d":"13","alternativa_e":"15","resposta_correta":"a","explicacao":"14 x 14 = 196.","resposta":""},
{"id":"6021","tipo":"multipla","disciplina":"Matematica","tema":"Radiciacao","subtema":"Raiz cubica","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A raiz cubica de 125 e:","alternativa_a":"5","alternativa_b":"4","alternativa_c":"6","alternativa_d":"7","alternativa_e":"3","resposta_correta":"a","explicacao":"5^3 = 125.","resposta":""},
# --- EQUACOES 1 GRAU ---
{"id":"6022","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 1 grau","subtema":"Equacao do 1 grau","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Qual o valor de x em: 3x + 6 = 21?","alternativa_a":"5","alternativa_b":"7","alternativa_c":"4","alternativa_d":"6","alternativa_e":"3","resposta_correta":"a","explicacao":"3x = 21 - 6 = 15; x = 5.","resposta":""},
{"id":"6023","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 1 grau","subtema":"Equacao com parenteses","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Resolva: 2(x - 3) = 4x - 14. O valor de x e:","alternativa_a":"4","alternativa_b":"5","alternativa_c":"3","alternativa_d":"6","alternativa_e":"2","resposta_correta":"a","explicacao":"2x - 6 = 4x - 14 => -2x = -8 => x = 4.","resposta":""},
{"id":"6024","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 1 grau","subtema":"Sistema de equacoes 1 grau","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Resolva o sistema: x + y = 10 e x - y = 2. O valor de x e:","alternativa_a":"6","alternativa_b":"4","alternativa_c":"8","alternativa_d":"5","alternativa_e":"7","resposta_correta":"a","explicacao":"Somando: 2x = 12 => x = 6. Verificando: 6 + y = 10 => y = 4.","resposta":""},
# --- EQUACOES 2 GRAU ---
{"id":"6025","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 2 grau","subtema":"Formula de Bhaskara","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"As raizes de x^2 - 5x + 6 = 0 sao:","alternativa_a":"2 e 3","alternativa_b":"1 e 6","alternativa_c":"-2 e -3","alternativa_d":"3 e 4","alternativa_e":"1 e 4","resposta_correta":"a","explicacao":"delta = 25 - 24 = 1. x = (5+-1)/2. x1=3, x2=2.","resposta":""},
{"id":"6026","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 2 grau","subtema":"Soma e produto das raizes","dificuldade":"Medio","fonte":"Vestibular","ano":"2022","enunciado":"Na equacao x^2 - 7x + 12 = 0, a soma das raizes e:","alternativa_a":"7","alternativa_b":"12","alternativa_c":"5","alternativa_d":"3","alternativa_e":"4","resposta_correta":"a","explicacao":"Pela relacao de Girard: soma das raizes = -b/a = 7/1 = 7.","resposta":""},
{"id":"6027","tipo":"multipla","disciplina":"Matematica","tema":"Equacoes 2 grau","subtema":"Discriminante","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A equacao x^2 - 4x + 5 = 0 tem:","alternativa_a":"Nenhuma raiz real","alternativa_b":"Duas raizes reais distintas","alternativa_c":"Duas raizes reais iguais","alternativa_d":"Uma raiz real","alternativa_e":"Tres raizes reais","resposta_correta":"a","explicacao":"delta = 16 - 20 = -4 < 0. Sem raizes reais.","resposta":""},
# --- GEOMETRIA PLANA ---
{"id":"6028","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Area do retangulo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um retangulo tem base 8 m e altura 5 m. Qual sua area?","alternativa_a":"40 m2","alternativa_b":"26 m2","alternativa_c":"35 m2","alternativa_d":"45 m2","alternativa_e":"30 m2","resposta_correta":"a","explicacao":"Area = base x altura = 8 x 5 = 40 m2.","resposta":""},
{"id":"6029","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Area do triangulo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um triangulo tem base 10 m e altura 6 m. Sua area e:","alternativa_a":"30 m2","alternativa_b":"60 m2","alternativa_c":"25 m2","alternativa_d":"40 m2","alternativa_e":"20 m2","resposta_correta":"a","explicacao":"Area = (base x altura)/2 = (10 x 6)/2 = 30 m2.","resposta":""},
{"id":"6030","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Perimetro do quadrado","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um quadrado tem lado 7 cm. Qual seu perimetro?","alternativa_a":"28 cm","alternativa_b":"14 cm","alternativa_c":"49 cm","alternativa_d":"21 cm","alternativa_e":"35 cm","resposta_correta":"a","explicacao":"Perimetro = 4 x lado = 4 x 7 = 28 cm.","resposta":""},
{"id":"6031","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Area do circulo","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um circulo tem raio de 5 m. Sua area (use pi = 3,14) e aproximadamente:","alternativa_a":"78,5 m2","alternativa_b":"31,4 m2","alternativa_c":"50,3 m2","alternativa_d":"94,2 m2","alternativa_e":"62,8 m2","resposta_correta":"a","explicacao":"Area = pi x r^2 = 3,14 x 25 = 78,5 m2.","resposta":""},
# --- GEOMETRIA ESPACIAL ---
{"id":"6032","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Volume do cubo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Um cubo tem aresta de 3 cm. Qual seu volume?","alternativa_a":"27 cm3","alternativa_b":"9 cm3","alternativa_c":"18 cm3","alternativa_d":"54 cm3","alternativa_e":"12 cm3","resposta_correta":"a","explicacao":"Volume = aresta^3 = 3^3 = 27 cm3.","resposta":""},
{"id":"6033","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Volume do paralelepipedo","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Uma caixa retangular mede 4 m x 3 m x 2 m. Qual seu volume?","alternativa_a":"24 m3","alternativa_b":"26 m3","alternativa_c":"18 m3","alternativa_d":"36 m3","alternativa_e":"20 m3","resposta_correta":"a","explicacao":"V = comprimento x largura x altura = 4 x 3 x 2 = 24 m3.","resposta":""},
{"id":"6034","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Volume do cilindro","dificuldade":"Medio","fonte":"Vestibular","ano":"2022","enunciado":"Um cilindro tem raio 3 cm e altura 10 cm. Seu volume (pi = 3,14) e:","alternativa_a":"282,6 cm3","alternativa_b":"94,2 cm3","alternativa_c":"188,4 cm3","alternativa_d":"314 cm3","alternativa_e":"150 cm3","resposta_correta":"a","explicacao":"V = pi x r^2 x h = 3,14 x 9 x 10 = 282,6 cm3.","resposta":""},
# --- TEOREMA DE PITAGORAS ---
{"id":"6035","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Teorema de Pitagoras","dificuldade":"Facil","fonte":"ENEM","ano":"2023","enunciado":"Em um triangulo retangulo, os catetos medem 3 cm e 4 cm. A hipotenusa mede:","alternativa_a":"5 cm","alternativa_b":"6 cm","alternativa_c":"7 cm","alternativa_d":"4,5 cm","alternativa_e":"8 cm","resposta_correta":"a","explicacao":"h^2 = 3^2 + 4^2 = 9 + 16 = 25 => h = 5. (Triangulo 3-4-5)","resposta":""},
{"id":"6036","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Teorema de Pitagoras","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Um retangulo mede 6 m por 8 m. Qual e o comprimento de sua diagonal?","alternativa_a":"10 m","alternativa_b":"12 m","alternativa_c":"14 m","alternativa_d":"7 m","alternativa_e":"9 m","resposta_correta":"a","explicacao":"d^2 = 6^2 + 8^2 = 36 + 64 = 100 => d = 10 m.","resposta":""},
# --- SEMELHANCA DE TRIANGULOS ---
{"id":"6037","tipo":"multipla","disciplina":"Matematica","tema":"Semelhanca de triangulos","subtema":"Fator de semelhanca","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"Dois triangulos semelhantes tem lados correspondentes de 4 cm e 6 cm. A razao de semelhanca e:","alternativa_a":"2/3","alternativa_b":"1/2","alternativa_c":"3/4","alternativa_d":"4/5","alternativa_e":"1/3","resposta_correta":"a","explicacao":"Razao de semelhanca = 4/6 = 2/3.","resposta":""},
{"id":"6038","tipo":"multipla","disciplina":"Matematica","tema":"Semelhanca de triangulos","subtema":"Criterios de semelhanca","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Dois triangulos sao semelhantes (AA) quando:","alternativa_a":"Dois angulos de um sao iguais a dois angulos do outro","alternativa_b":"Os tres lados sao iguais","alternativa_c":"Os tres angulos sao iguais","alternativa_d":"Dois lados e o angulo entre eles sao iguais","alternativa_e":"Apenas um angulo e igual","resposta_correta":"a","explicacao":"O criterio AA (angulo-angulo) garante semelhanca, pois o terceiro angulo e determinado.","resposta":""},
# --- TRIGONOMETRIA BASICA ---
{"id":"6039","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Seno cosseno tangente","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Em um triangulo retangulo, o cateto oposto mede 3 cm e a hipotenusa mede 5 cm. O seno do angulo oposto a esse cateto e:","alternativa_a":"3/5","alternativa_b":"4/5","alternativa_c":"3/4","alternativa_d":"5/3","alternativa_e":"4/3","resposta_correta":"a","explicacao":"seno = cateto oposto / hipotenusa = 3/5.","resposta":""},
{"id":"6040","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Angulos notaveis","dificuldade":"Medio","fonte":"ENEM","ano":"2022","enunciado":"Qual e o valor do seno de 30 graus?","alternativa_a":"1/2","alternativa_b":"raiz de 3 dividido por 2","alternativa_c":"raiz de 2 dividido por 2","alternativa_d":"1","alternativa_e":"raiz de 3 dividido por 3","resposta_correta":"a","explicacao":"sen 30 graus = 1/2. Esse e um angulo notavel essencial.","resposta":""},
{"id":"6041","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Tangente de angulo","dificuldade":"Medio","fonte":"Vestibular","ano":"2023","enunciado":"A tangente de 45 graus e igual a:","alternativa_a":"1","alternativa_b":"0","alternativa_c":"raiz de 3","alternativa_d":"1/2","alternativa_e":"raiz de 2","resposta_correta":"a","explicacao":"tg 45 = sen 45 / cos 45 = (raiz 2 / 2) / (raiz 2 / 2) = 1.","resposta":""},
]

path = os.path.join(BASE, 'questoes_lote54.csv')
fieldnames = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
              'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
              'resposta_correta','explicacao','resposta']
with open(path, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writeheader()
    w.writerows(rows)
print(f"Lote 54 criado: {len(rows)} questoes")
