# -*- coding: utf-8 -*-
# Gerador de questoes multipla escolha - formato simples
# IDs multipla: 3911 em diante
import csv, os

def gerar_lote(lote_num, questoes, id_inicio):
    out = f'/Users/dennysrian_/Desktop/aprova-ia/questoes_lote{lote_num}.csv'
    cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado',
            'alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e',
            'resposta_correta','explicacao','resposta']
    with open(out,'w',newline='',encoding='utf-8') as f:
        w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
        w.writerow(cols)
        for i, q in enumerate(questoes):
            q['id'] = str(id_inicio + i)
            w.writerow([q.get(c,'') for c in cols])
    print(f'Lote {lote_num}: {len(questoes)} questoes -> {out}')
    return len(questoes)

# LOTE 33 - 50 questoes multipla escolha (IDs 3911-3960)
lote33 = [
  {"tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Equacoes do 2 grau","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"As raizes da equacao x2 - 5x + 6 = 0 sao:","alternativa_a":"2 e 3","alternativa_b":"1 e 6","alternativa_c":"-2 e -3","alternativa_d":"2 e -3","alternativa_e":"1 e -6","resposta_correta":"a","explicacao":"x2 - 5x + 6 = 0 => (x-2)(x-3) = 0 => x=2 ou x=3.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Sistemas lineares","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A solucao do sistema x + y = 10 e x - y = 4 e:","alternativa_a":"x=7, y=3","alternativa_b":"x=3, y=7","alternativa_c":"x=6, y=4","alternativa_d":"x=8, y=2","alternativa_e":"x=5, y=5","resposta_correta":"a","explicacao":"Somando as equacoes: 2x = 14, x = 7. Substituindo: 7 + y = 10, y = 3.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Area do triangulo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um triangulo tem base 8 cm e altura 5 cm. Sua area e:","alternativa_a":"20 cm2","alternativa_b":"40 cm2","alternativa_c":"13 cm2","alternativa_d":"10 cm2","alternativa_e":"16 cm2","resposta_correta":"a","explicacao":"A = (b x h)/2 = (8 x 5)/2 = 40/2 = 20 cm2.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Progressao Aritmetica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Na PA (2, 5, 8, 11, ...), o decimo termo e:","alternativa_a":"29","alternativa_b":"27","alternativa_c":"32","alternativa_d":"20","alternativa_e":"31","resposta_correta":"a","explicacao":"an = a1 + (n-1)r = 2 + (10-1)3 = 2 + 27 = 29.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Progressao Geometrica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na PG (3, 6, 12, 24, ...), o sexto termo e:","alternativa_a":"96","alternativa_b":"48","alternativa_c":"192","alternativa_d":"72","alternativa_e":"144","resposta_correta":"a","explicacao":"an = a1 * r^(n-1) = 3 * 2^5 = 3 * 32 = 96.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Velocidade media","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um carro percorre 120 km em 2 horas. Sua velocidade media e:","alternativa_a":"60 km/h","alternativa_b":"240 km/h","alternativa_c":"30 km/h","alternativa_d":"90 km/h","alternativa_e":"45 km/h","resposta_correta":"a","explicacao":"Vm = Ds/Dt = 120/2 = 60 km/h.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Leis de Newton","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Pela Segunda Lei de Newton, se a massa de um objeto e 5 kg e a forca aplicada e 20 N, a aceleracao e:","alternativa_a":"4 m/s2","alternativa_b":"100 m/s2","alternativa_c":"0,25 m/s2","alternativa_d":"2 m/s2","alternativa_e":"25 m/s2","resposta_correta":"a","explicacao":"F = ma => a = F/m = 20/5 = 4 m/s2.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Escala termometrica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A temperatura de 100 graus Celsius corresponde, em Kelvin, a:","alternativa_a":"373 K","alternativa_b":"273 K","alternativa_c":"100 K","alternativa_d":"473 K","alternativa_e":"173 K","resposta_correta":"a","explicacao":"K = C + 273 = 100 + 273 = 373 K.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Ondulatoria","subtema":"Velocidade de onda","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Uma onda tem frequencia 50 Hz e comprimento de onda 2 m. Sua velocidade e:","alternativa_a":"100 m/s","alternativa_b":"25 m/s","alternativa_c":"52 m/s","alternativa_d":"48 m/s","alternativa_e":"0,04 m/s","resposta_correta":"a","explicacao":"v = f * lambda = 50 * 2 = 100 m/s.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Lei de Ohm","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um resistor de 10 ohms recebe uma tensao de 30 V. A corrente que o percorre e:","alternativa_a":"3 A","alternativa_b":"0,33 A","alternativa_c":"300 A","alternativa_d":"300 mA","alternativa_e":"30 A","resposta_correta":"a","explicacao":"I = V/R = 30/10 = 3 A.","resposta":""},
  {"tipo":"multipla","disciplina":"Quimica","tema":"Quimica Geral","subtema":"Tabela periodica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O elemento de numero atomico 8 pertence ao grupo dos:","alternativa_a":"Calcogenios","alternativa_b":"Halogenos","alternativa_c":"Gases nobres","alternativa_d":"Alcalinos","alternativa_e":"Metais de transicao","resposta_correta":"a","explicacao":"O elemento de Z=8 e o oxigenio (O), que pertence ao grupo 16, chamado calcogenios (junto com S, Se, Te, Po).","resposta":""},
  {"tipo":"multipla","disciplina":"Quimica","tema":"Quimica Geral","subtema":"Ligacoes quimicas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A molecula de H2O possui ligacao do tipo:","alternativa_a":"Covalente polar","alternativa_b":"Ionica","alternativa_c":"Metalica","alternativa_d":"Covalente apolar","alternativa_e":"Dativa","resposta_correta":"a","explicacao":"Na agua, O e H compartilham eletrons (ligacao covalente). Como o oxigenio e mais eletronegativo, a ligacao e polar. A molecula e angular e tem momento dipolar resultante nao nulo.","resposta":""},
  {"tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Nomenclatura","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O composto CH3-CH2-CH2-OH e classificado como:","alternativa_a":"Alcool primario","alternativa_b":"Alcool secundario","alternativa_c":"Aldeido","alternativa_d":"Cetona","alternativa_e":"Acido carboxilico","resposta_correta":"a","explicacao":"O grupo -OH esta ligado a um carbono primario (ligado a apenas um outro carbono). Trata-se do 1-propanol (propan-1-ol), um alcool primario.","resposta":""},
  {"tipo":"multipla","disciplina":"Quimica","tema":"Quimica Geral","subtema":"Solucoes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Dissolve-se 10 g de NaCl em agua suficiente para 500 mL de solucao. A molaridade da solucao e (MM NaCl = 58,5 g/mol):","alternativa_a":"0,34 mol/L","alternativa_b":"0,17 mol/L","alternativa_c":"1 mol/L","alternativa_d":"0,5 mol/L","alternativa_e":"2 mol/L","resposta_correta":"a","explicacao":"n = m/MM = 10/58,5 = 0,171 mol. C = n/V = 0,171/0,5 = 0,342 mol/L ~ 0,34 mol/L.","resposta":""},
  {"tipo":"multipla","disciplina":"Quimica","tema":"Quimica Geral","subtema":"Reacoes quimicas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Na reacao Zn + CuSO4 -> ZnSO4 + Cu, o zinco sofre:","alternativa_a":"Oxidacao","alternativa_b":"Reducao","alternativa_c":"Precipitacao","alternativa_d":"Neutralizacao","alternativa_e":"Decomposicao","resposta_correta":"a","explicacao":"O Zn passa de estado 0 para +2 (ZnSO4), perdendo eletrons. Perda de eletrons = oxidacao. O cobre e reduzido (Cu2+ -> Cu0).","resposta":""},
  {"tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Organelas celulares","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A organela responsavel pela sintese de proteinas nas celulas e:","alternativa_a":"Ribossomo","alternativa_b":"Mitocondria","alternativa_c":"Lisossomo","alternativa_d":"Vacuolo","alternativa_e":"Peroxissomo","resposta_correta":"a","explicacao":"Os ribossomos sao organelas (na verdade complexos de RNA e proteinas) presentes em todas as celulas, responsaveis pela traducao do mRNA em proteinas. Podem estar livres no citoplasma ou ligados ao reticulo endoplasmatico rugoso.","resposta":""},
  {"tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Membrana plasmatica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O modelo atual da membrana plasmatica e denominado:","alternativa_a":"Mosaico fluido","alternativa_b":"Bicamada rigida","alternativa_c":"Trilaminar","alternativa_d":"Unidade de membrana","alternativa_e":"Sandwich lipoproteico","resposta_correta":"a","explicacao":"O modelo do mosaico fluido, proposto por Singer e Nicolson em 1972, descreve a membrana como uma bicamada de fosfolipidios na qual proteinas estao embebidas e podem se mover lateralmente, conferindo fluidez e funcionalidade dinamica a membrana.","resposta":""},
  {"tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia","subtema":"Sistema nervoso","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O impulso nervoso e transmitido entre neuronios por meio de:","alternativa_a":"Sinapses","alternativa_b":"Mitoses","alternativa_c":"Osmose","alternativa_d":"Difusao simples","alternativa_e":"Endocitose","resposta_correta":"a","explicacao":"As sinapses sao juncoes especializadas entre neuronios (ou entre neuronio e celula efetora). Na sinapse quimica, neurotransmissores sao liberados pelo neuronio pre-sinaptico e se ligam a receptores no neuronio pos-sinaptico, propagando ou inibindo o impulso.","resposta":""},
  {"tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Nicho ecologico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O nicho ecologico de uma especie refere-se a:","alternativa_a":"O conjunto de condicoes ambientais e recursos que uma especie utiliza e ocupa no ecossistema","alternativa_b":"O local fisico onde a especie habita","alternativa_c":"A populacao total da especie em determinada area","alternativa_d":"A dieta alimentar exclusiva da especie","alternativa_e":"A area geografica de distribuicao da especie","resposta_correta":"a","explicacao":"O nicho ecologico e mais amplo que o habitat: representa o papel funcional da especie no ecossistema, incluindo o que ela come, o que a consome, como interage com o ambiente abiotico, seu horario de atividade, etc. Duas especies nao podem ocupar o mesmo nicho no mesmo local (principio de exclusao competitiva de Gause).","resposta":""},
  {"tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Leis de Mendel","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No cruzamento entre dois individuos heterozigotos (Aa x Aa), a proporcao fenotipica esperada na descendencia e:","alternativa_a":"3:1 (dominante:recessivo)","alternativa_b":"1:2:1","alternativa_c":"1:1","alternativa_d":"Todos dominantes","alternativa_e":"Todos recessivos","resposta_correta":"a","explicacao":"Aa x Aa: gametas A e a de cada progenitor. Combinacoes: AA (1/4), Aa (2/4), aa (1/4). Fenotipicamente: 3/4 apresentam o fenotipo dominante (AA + Aa) e 1/4 o fenotipo recessivo (aa) -> proporcao 3:1.","resposta":""},
  {"tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Revolucao Francesa","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O lema da Revolucao Francesa era:","alternativa_a":"Liberdade, Igualdade, Fraternidade","alternativa_b":"Paz, Terra e Pao","alternativa_c":"Trabalhadores do mundo, uni-vos","alternativa_d":"Liberdade ou Morte","alternativa_e":"Ordem e Progresso","resposta_correta":"a","explicacao":"'Liberte, Egalite, Fraternite' (Liberdade, Igualdade, Fraternidade) e o lema historico da Revolucao Francesa (1789), que expressa os ideais iluministas que embasaram o movimento contra o Antigo Regime. Tornou-se o lema oficial da Republica Francesa.","resposta":""},
  {"tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Revolucao Industrial","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Primeira Revolucao Industrial ocorreu primeiramente em:","alternativa_a":"Inglaterra","alternativa_b":"Franca","alternativa_c":"Alemanha","alternativa_d":"Estados Unidos","alternativa_e":"Belgica","resposta_correta":"a","explicacao":"A Primeira Revolucao Industrial (meados seculo XVIII - inicio do XIX) teve origem na Inglaterra, favorecida por fatores como acumulacao de capital, disponibilidade de carvao e ferro, legislacao trabalhista liberal, imperialismo e mercado consumidor colonial.","resposta":""},
  {"tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Proclamacao da Republica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Proclamacao da Republica no Brasil ocorreu em:","alternativa_a":"15 de novembro de 1889","alternativa_b":"7 de setembro de 1822","alternativa_c":"13 de maio de 1888","alternativa_d":"22 de abril de 1500","alternativa_e":"15 de novembro de 1900","resposta_correta":"a","explicacao":"A Republica foi proclamada em 15 de novembro de 1889 pelo Marechal Deodoro da Fonseca, encerrando o Imperio de D. Pedro II. Antecedentes incluem a crise do escravismo pos-Abolicao (1888), questao militar e questao religiosa.","resposta":""},
  {"tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Era Vargas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Estado Novo (1937-1945), periodo mais autoritario da Era Vargas, caracterizou-se por:","alternativa_a":"Fechamento do Congresso, repressao politica, propaganda e industrializacao","alternativa_b":"Democracia participativa e liberdade de imprensa","alternativa_c":"Eleicoes diretas e bipartidarismo","alternativa_d":"Descentralizacao politica e autonomia estadual","alternativa_e":"Liberalismo economico e privatizacoes","resposta_correta":"a","explicacao":"O Estado Novo foi implantado por Vargas em 10/11/1937 com um golpe que fechou o Congresso e outorgou uma nova Constituicao (a 'Polaca'). Caracterizou-se por: censura pela DIP, repressao a oposicao (especialmente comunistas), culto a personalidade, mas tambem industrializacao e legislacao trabalhista (CLT em 1943).","resposta":""},
  {"tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Guerra Fria","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Guerra Fria foi um periodo de tensao entre:","alternativa_a":"Estados Unidos e Uniao Sovietica","alternativa_b":"Alemanha e Franca","alternativa_c":"Inglaterra e Japao","alternativa_d":"China e India","alternativa_e":"Brasil e Argentina","resposta_correta":"a","explicacao":"A Guerra Fria (1947-1991) foi a disputa ideologica, politica e militar entre os EUA (capitalismo) e a URSS (socialismo) apos a 2a Guerra Mundial. Caracterizou-se pela corrida armamentista nuclear, espacial e por guerras por procuracao (Coreia, Vietna, Angola etc.).","resposta":""},
  {"tipo":"multipla","disciplina":"Geografia","tema":"Cartografia","subtema":"Escalas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Num mapa na escala 1:100.000, uma distancia de 5 cm no mapa corresponde na realidade a:","alternativa_a":"5 km","alternativa_b":"500 m","alternativa_c":"50 km","alternativa_d":"0,5 km","alternativa_e":"500 km","resposta_correta":"a","explicacao":"1 cm no mapa = 100.000 cm = 1 km na realidade. Portanto 5 cm = 5 km.","resposta":""},
  {"tipo":"multipla","disciplina":"Geografia","tema":"Climatologia","subtema":"Tipos climaticos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O clima predominante na regiao amazonica brasileira e:","alternativa_a":"Equatorial umido","alternativa_b":"Tropical seco","alternativa_c":"Semiarido","alternativa_d":"Subtropical","alternativa_e":"Mediterraneo","resposta_correta":"a","explicacao":"A Amazonia possui clima equatorial umido, caracterizado por altas temperaturas (media ~27C), precipitacoes elevadas (>2000 mm/ano) e ausencia de estacao seca definida. E favorecido pela posicao equatorial, evapotranspiracao da floresta e influencia de massas de ar umido.","resposta":""},
  {"tipo":"multipla","disciplina":"Geografia","tema":"Geomorfologia","subtema":"Tipos de relevo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O Pantanal, maior planicie alagavel do mundo, localiza-se nos estados brasileiros de:","alternativa_a":"Mato Grosso e Mato Grosso do Sul","alternativa_b":"Para e Amazonas","alternativa_c":"Goias e Tocantins","alternativa_d":"Minas Gerais e Sao Paulo","alternativa_e":"Bahia e Piaui","resposta_correta":"a","explicacao":"O Pantanal ocupa principalmente os estados de Mato Grosso e Mato Grosso do Sul, com uma pequena area na Bolivia e Paraguai. E Patrimonio Natural da Humanidade (UNESCO) e Reserva da Biosfera, abrigando uma das maiores biodiversidades do planeta.","resposta":""},
  {"tipo":"multipla","disciplina":"Geografia","tema":"Populacao","subtema":"Transicao demografica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A transicao demografica e caracterizada pela:","alternativa_a":"Queda das taxas de mortalidade seguida pela queda das taxas de natalidade","alternativa_b":"Aumento simultâneo de natalidade e mortalidade","alternativa_c":"Queda da natalidade antes da queda da mortalidade","alternativa_d":"Estabilidade de natalidade com aumento da mortalidade","alternativa_e":"Migracao entre zonas rurais e urbanas","resposta_correta":"a","explicacao":"A teoria da transicao demografica descreve o processo historico em que paises passam de altas taxas de natalidade e mortalidade para baixas taxas. Primeiro cai a mortalidade (melhorias sanitarias e medicas), gerando crescimento populacional acelerado; depois cai a natalidade (desenvolvimento economico e social), estabilizando a populacao.","resposta":""},
  {"tipo":"multipla","disciplina":"Geografia","tema":"Geografia Economica","subtema":"Setor primario","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O Brasil e um dos maiores produtores e exportadores mundiais de:","alternativa_a":"Soja, carne bovina e cana-de-acucar","alternativa_b":"Petroleo, gas natural e trigo","alternativa_c":"Armas, tecnologia e farmacos","alternativa_d":"Automoveis, avioes e navios","alternativa_e":"Ouro, prata e platina","resposta_correta":"a","explicacao":"O agronegocio e um dos pilares da economia brasileira. O Brasil e lider mundial na exportacao de soja, carne bovina, carne de frango, suco de laranja, cafe, acucar e etanol. O setor agropecuario responde por cerca de 25% do PIB brasileiro.","resposta":""},
  {"tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Classes gramaticais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Em 'Ela correu rapidamente', a palavra 'rapidamente' e um:","alternativa_a":"Adverbio","alternativa_b":"Adjetivo","alternativa_c":"Substantivo","alternativa_d":"Verbo","alternativa_e":"Conjuncao","resposta_correta":"a","explicacao":"'Rapidamente' e um adverbio de modo (formado pelo adjetivo 'rapida' + sufixo '-mente'). Modifica o verbo 'correu', indicando a maneira como a acao foi realizada. Adverbios modificam verbos, adjetivos ou outros adverbios.","resposta":""},
  {"tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Pontuacao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O uso da virgula e obrigatorio para separar:","alternativa_a":"Apostos e vocativos do restante da oracao","alternativa_b":"Sujeito do predicado","alternativa_c":"Verbo do objeto direto","alternativa_d":"Auxiliar do verbo principal","alternativa_e":"Artigo do substantivo","resposta_correta":"a","explicacao":"Segundo a norma culta, a virgula e obrigatoria para isolar apostos e vocativos. Nao se usa virgula entre sujeito e predicado, nem entre verbo e seus complementos, salvo em casos especificos (oracao adjetiva explicativa, inversao etc.).","resposta":""},
  {"tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura Brasileira","subtema":"Modernismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Semana de Arte Moderna de 1922 ocorreu em:","alternativa_a":"Sao Paulo","alternativa_b":"Rio de Janeiro","alternativa_c":"Salvador","alternativa_d":"Belo Horizonte","alternativa_e":"Recife","resposta_correta":"a","explicacao":"A Semana de Arte Moderna de 1922 ocorreu no Teatro Municipal de Sao Paulo, de 13 a 17 de fevereiro. Reuniu artistas como Mario de Andrade, Oswald de Andrade, Anita Malfatti e Heitor Villa-Lobos, e marcou o inicio do Modernismo brasileiro, propondo ruptura com o academicismo.","resposta":""},
  {"tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura Brasileira","subtema":"Realismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Machado de Assis e considerado o principal representante do Realismo brasileiro. Sua obra 'Dom Casmurro' e narrada em primeira pessoa por:","alternativa_a":"Bentinho (Capitu)","alternativa_b":"Capitu","alternativa_c":"Jose Dias","alternativa_d":"Escobar","alternativa_e":"Glorinha","resposta_correta":"a","explicacao":"Em Dom Casmurro, o narrador e Bentinho (Dom Casmurro), que conta sua historia em retrospecto. A narracao em primeira pessoa e nao confiavel: o leitor nao sabe se Capitu realmente traiu Bentinho, pois a historia e filtrada pela subjetividade do ciume do narrador. Essa ambiguidade e o nucleo central da obra.","resposta":""},
  {"tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Textualidade","subtema":"Intertextualidade","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A intertextualidade ocorre quando:","alternativa_a":"Um texto dialoga com outro, citando, aludindo ou parodiando-o","alternativa_b":"Um texto e escrito por varios autores","alternativa_c":"Um texto usa apenas vocabulario tecnico","alternativa_d":"Um texto e traduzido para outra lingua","alternativa_e":"Um texto nao tem coesao","resposta_correta":"a","explicacao":"A intertextualidade e a relacao entre textos: um texto absorve, transforma ou dialoga com outros textos anteriores. Pode ocorrer por citacao, alusao, parodia, estilizacao, plagio ou referencia implicita. E um fenomeno universal na literatura e em outros discursos.","resposta":""},
  {"tipo":"multipla","disciplina":"Filosofia","tema":"Ontologia","subtema":"Ser em Aristoteles","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Aristoteles, a forma e a materia sao inseparaveis. Esse principio e chamado de:","alternativa_a":"Hilemorfismo","alternativa_b":"Dualismo platonico","alternativa_c":"Monismo espinosista","alternativa_d":"Idealismo kantiano","alternativa_e":"Empirismo","resposta_correta":"a","explicacao":"O hilemorfismo (do grego hyle = materia + morphe = forma) e a doutrina aristotelica segundo a qual todo ser e composto de materia (o que algo e feito) e forma (o que o organiza e define). Materia e forma nao existem separadas — ao contrario do dualismo platonico, onde as formas existem num mundo separado.","resposta":""},
  {"tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia da Ciencia","subtema":"Falsificacionismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Karl Popper defendeu que uma teoria cientifica valida deve ser:","alternativa_a":"Falsificavel (refutavel)","alternativa_b":"Verificavel por indução completa","alternativa_c":"Verdadeira e irrefutavel","alternativa_d":"Baseada apenas em autoridade","alternativa_e":"Compativel com todas as observacoes","resposta_correta":"a","explicacao":"Para Popper, o criterio de demarcacao entre ciencia e pseudo-ciencia e a falsificabilidade: uma teoria e cientifica se pode ser testada e potencialmente refutada. Teorias que nao admitem refutacao (como certas versoes da psicanalise e marxismo na visao de Popper) nao sao cientificas. A ciencia avanca por tentativa e erro.","resposta":""},
  {"tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Etica de Aristoteles","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Aristoteles, a felicidade (eudaimonia) e:","alternativa_a":"O fim ultimo da vida humana, alcancado pelo exercicio das virtudes","alternativa_b":"O prazer sensorial maximo","alternativa_c":"A ausencia de sofrimento","alternativa_d":"A obediencia a lei moral universal","alternativa_e":"A riqueza material","resposta_correta":"a","explicacao":"Na Etica a Nicomaco, Aristoteles define eudaimonia (felicidade/florescimento humano) como o bem supremo e fim ultimo de todas as acoes humanas. E alcancada pelo exercicio continuo das virtudes (coragem, justica, moderacao) em conformidade com a razao, ao longo de uma vida completa.","resposta":""},
  {"tipo":"multipla","disciplina":"Filosofia","tema":"Logica","subtema":"Silogismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O silogismo aristotelico e composto por:","alternativa_a":"Premissa maior, premissa menor e conclusao","alternativa_b":"Tese, antitese e sintese","alternativa_c":"Hipotese, experimento e resultado","alternativa_d":"Sujeito, verbo e objeto","alternativa_e":"Inducao, deducao e abducao","resposta_correta":"a","explicacao":"O silogismo e uma forma de argumento dedutivo com tres proposicoes: premissa maior (declaracao geral), premissa menor (caso especifico) e conclusao (derivada logicamente das premissas). Exemplo classico: Todos os homens sao mortais (P. maior) / Socrates e homem (P. menor) / Logo, Socrates e mortal (conclusao).","resposta":""},
  {"tipo":"multipla","disciplina":"Sociologia","tema":"Sociologia Classica","subtema":"Marx e alienacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Karl Marx, a alienacao do trabalhador no capitalismo significa que:","alternativa_a":"O trabalhador e separado do produto de seu trabalho, da atividade produtiva e de sua natureza humana","alternativa_b":"O trabalhador e integrado ao processo produtivo de forma harmoniosa","alternativa_c":"O trabalhador tem total controle sobre os meios de producao","alternativa_d":"O trabalhador se identifica plenamente com sua funcao social","alternativa_e":"O trabalhador recebe salario justo pelo seu esforco","resposta_correta":"a","explicacao":"Marx descreve quatro dimensoes da alienacao: (1) do produto — o trabalhador nao possui o que fabrica; (2) do processo produtivo — o trabalho nao e realizacao, mas sofrimento; (3) do genero humano — o trabalho deixa de ser livre e consciente; (4) dos outros homens — a relacao social e mediada pela competicao. A alienacao e estrutural ao capitalismo.","resposta":""},
  {"tipo":"multipla","disciplina":"Sociologia","tema":"Sociologia Classica","subtema":"Fato social em Durkheim","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Segundo Durkheim, fato social e:","alternativa_a":"Toda maneira de agir, pensar e sentir exterior ao individuo, que exerce coercao sobre ele","alternativa_b":"Qualquer evento que ocorre na sociedade","alternativa_c":"O comportamento individual isolado de influencias sociais","alternativa_d":"A pratica economica dos grupos sociais","alternativa_e":"O conjunto de leis aprovadas pelo parlamento","resposta_correta":"a","explicacao":"Em 'As Regras do Metodo Sociologico', Durkheim define fato social por tres caracteristicas: exterioridade (existe fora do individuo), coercao (impoe-se ao individuo) e generalidade (e comum a todos os membros da sociedade). Exemplos: lingua, moralidade, religiao, moda.","resposta":""},
  {"tipo":"multipla","disciplina":"Sociologia","tema":"Sociologia Contemporanea","subtema":"Cultura de massa","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'industria cultural', criado por Adorno e Horkheimer, critica:","alternativa_a":"A producao padronizada e mercantilizada da cultura, que aliena e manipula o consumidor","alternativa_b":"O acesso democratico da populacao a bens culturais","alternativa_c":"A importacao de cultura estrangeira por paises perifericos","alternativa_d":"O financiamento publico das artes","alternativa_e":"A preservacao das tradicoes culturais populares","resposta_correta":"a","explicacao":"Adorno e Horkheimer, da Escola de Frankfurt, cunharam o termo 'industria cultural' em 'Dialetica do Esclarecimento' (1944). Criticam a producao cultural capitalista que transforma a arte em mercadoria, padroniza produtos culturais para o consumo de massa, aliena o receptor e refraca a capacidade critica, funcionando ideologicamente para reproduzir o status quo.","resposta":""},
  {"tipo":"multipla","disciplina":"Sociologia","tema":"Sociologia Classica","subtema":"Tipos de acao social Weber","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Weber, a acao orientada por valores morais ou religiosos, independente de suas consequencias, e denominada:","alternativa_a":"Acao racional com relacao a valores","alternativa_b":"Acao racional com relacao a fins","alternativa_c":"Acao tradicional","alternativa_d":"Acao afetiva","alternativa_e":"Acao instrumental","resposta_correta":"a","explicacao":"Weber classifica a acao social em quatro tipos: (1) racional com relacao a fins (instrumentalmente racional): orientada por objetivos calculados; (2) racional com relacao a valores: orientada por valores eticos, religiosos ou esteticos, independente dos resultados; (3) afetiva: motivada por emocoes; (4) tradicional: guiada pelo habito e costume.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao exponencial","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma populacao de bacterias dobra a cada hora. Se inicialmente ha 100 bacterias, quantas havera apos 5 horas?","alternativa_a":"3200","alternativa_b":"500","alternativa_c":"1000","alternativa_d":"6400","alternativa_e":"200","resposta_correta":"a","explicacao":"P(t) = P0 * 2^t = 100 * 2^5 = 100 * 32 = 3200 bacterias.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Teorema de Pitagoras","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Num triangulo retangulo, os catetos medem 3 e 4 cm. A hipotenusa mede:","alternativa_a":"5 cm","alternativa_b":"7 cm","alternativa_c":"25 cm","alternativa_d":"12 cm","alternativa_e":"3,5 cm","resposta_correta":"a","explicacao":"h2 = c12 + c22 = 9 + 16 = 25, h = 5 cm. Este e o triangulo pitagorico 3-4-5.","resposta":""},
  {"tipo":"multipla","disciplina":"Matematica","tema":"Combinatoria","subtema":"Combinacao simples","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"De quantas maneiras podemos escolher 2 pessoas entre 5 para formar uma comissao?","alternativa_a":"10","alternativa_b":"20","alternativa_c":"25","alternativa_d":"5","alternativa_e":"15","resposta_correta":"a","explicacao":"C(5,2) = 5! / (2! * 3!) = (5*4) / (2*1) = 20/2 = 10 maneiras.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Lancamento de projeteis","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um objeto e lancado horizontalmente a partir de uma altura de 20 m com velocidade horizontal de 10 m/s. O alcance horizontal (g = 10 m/s2) e:","alternativa_a":"20 m","alternativa_b":"10 m","alternativa_c":"40 m","alternativa_d":"100 m","alternativa_e":"200 m","resposta_correta":"a","explicacao":"Tempo de queda: h = gt2/2 => 20 = 5t2 => t = 2 s. Alcance: x = v0 * t = 10 * 2 = 20 m.","resposta":""},
  {"tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Indice de refracao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A velocidade da luz no vacuo e 3x10^8 m/s. Num meio com indice de refracao n=1,5, a velocidade da luz e:","alternativa_a":"2x10^8 m/s","alternativa_b":"3x10^8 m/s","alternativa_c":"4,5x10^8 m/s","alternativa_d":"1,5x10^8 m/s","alternativa_e":"1x10^8 m/s","resposta_correta":"a","explicacao":"n = c/v => v = c/n = (3x10^8)/1,5 = 2x10^8 m/s.","resposta":""},
]

gerar_lote(33, lote33, 3911)
