# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"3901","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Identidades trigonometricas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Sabendo que sen(x) = 3/5 e que x pertence ao segundo quadrante, o valor de cos(x) e:","alternativa_a":"-4/5","alternativa_b":"4/5","alternativa_c":"-3/5","alternativa_d":"3/4","alternativa_e":"-3/4","resposta_correta":"a","explicacao":"Pela identidade fundamental: sen2(x) + cos2(x) = 1. Assim, cos2(x) = 1 - (3/5)2 = 1 - 9/25 = 16/25, logo cos(x) = +/-4/5. Como x esta no segundo quadrante, cos(x) < 0, portanto cos(x) = -4/5.","resposta":""},
  {"id":"3902","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Trabalho e energia","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um bloco de 2 kg e acelerado do repouso ate 10 m/s. O trabalho realizado sobre o bloco foi:","alternativa_a":"100 J","alternativa_b":"200 J","alternativa_c":"50 J","alternativa_d":"20 J","alternativa_e":"10 J","resposta_correta":"a","explicacao":"Pelo teorema trabalho-energia: W = DeltaEc = (1/2)mv2 - (1/2)mv02 = (1/2)(2)(10)2 - 0 = 100 J.","resposta":""},
  {"id":"3903","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Eletrolise","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na eletrolise aquosa do NaCl, os produtos formados no anodo e no catodo sao, respectivamente:","alternativa_a":"Cl2 e H2","alternativa_b":"Na e Cl2","alternativa_c":"O2 e Na","alternativa_d":"H2 e O2","alternativa_e":"NaOH e HCl","resposta_correta":"a","explicacao":"Na eletrolise aquosa do NaCl: no catodo ocorre reducao preferencial da agua (2H2O + 2e- -> H2 + 2OH-), produzindo H2. No anodo ocorre oxidacao dos ions Cl- (2Cl- -> Cl2 + 2e-) pois a sobretensao favorece a oxidacao do Cl- em relacao a da agua. Produz-se tambem NaOH em solucao.","resposta":""},
  {"id":"3904","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Mutacao genica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A anemia falciforme e um exemplo classico de mutacao do tipo:","alternativa_a":"Transposicao","alternativa_b":"Delecao de cromossomo","alternativa_c":"Substituicao de uma base nitrogenada (mutacao de ponto)","alternativa_d":"Duplicacao cromosomica","alternativa_e":"Poliploidia","resposta_correta":"c","explicacao":"A anemia falciforme e causada pela substituicao de uma unica base nitrogenada no gene da beta-globina: o codon GAG (glutamato) e substituido por GUG (valina). Essa mutacao de ponto altera a proteina hemoglobina, tornando-a insolavel e fazando as hemacias assumirem formato de foice sob baixa tensao de oxigenio.","resposta":""},
  {"id":"3905","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Republica Velha","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A politica dos governadores, caracteristica da Republica Velha (1894-1930), consistia em:","alternativa_a":"Eleicoes diretas com voto secreto para todos os cidadaos","alternativa_b":"Acordo entre o governo federal e os governadores estaduais para garantir apoio mutuo e manter as oligarquias no poder","alternativa_c":"Intervencao federal nos estados para combater corrupcao","alternativa_d":"Sistema de bipartidarismo entre republicanos e monarquistas","alternativa_e":"Eleicao direta para presidente sem influencia dos estados","resposta_correta":"b","explicacao":"A politica dos governadores, criada por Campos Sales, era um acordo entre o presidente da Republica e os governadores estaduais: o governo federal apoiava os governadores eleitos, e estes garantiam bancadas favoraveis ao presidente no Congresso. Isso consolidou o poder das oligarquias regionais, especialmente a politica cafe-com-leite (SP e MG).","resposta":""},
  {"id":"3906","tipo":"multipla","disciplina":"Geografia","tema":"Geografia Economica","subtema":"Matriz energetica brasileira","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A principal fonte de energia eletrica do Brasil e:","alternativa_a":"Termica (gas natural e carvao)","alternativa_b":"Nuclear","alternativa_c":"Eolica","alternativa_d":"Hidraulica (hidroeletrica)","alternativa_e":"Solar","resposta_correta":"d","explicacao":"O Brasil tem uma das matrizes eletricas mais renovaveis do mundo, com predominancia das usinas hidroeletricas, que respondem por cerca de 60-65% da geracao de energia eletrica nacional. Itaipu, Belo Monte e Tucurui sao exemplos de grandes hidreletricas. Essa dependencia hidreletrica torna o Brasil vulneravel a periodos de seca.","resposta":""},
  {"id":"3907","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Concordancia verbal","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Assinale a alternativa com concordancia verbal correta:","alternativa_a":"Fazem dez anos que nao o vejo.","alternativa_b":"Faz dez anos que nao o vejo.","alternativa_c":"Ha dez anos atras que nao o vejo.","alternativa_d":"Fazem dez anos atras que nao o vejo.","alternativa_e":"Ha dez anos que nao o viam.","resposta_correta":"b","explicacao":"O verbo 'fazer' indicando tempo decorrido e impessoal, ou seja, nao tem sujeito e deve ser conjugado na 3a pessoa do singular: 'Faz dez anos que nao o vejo.' As formas com 'fazem' sao incorretas pois o verbo nao concorda com 'dez anos' como sujeito. 'Ha dez anos atras' e pleona stico e incorreto.","resposta":""},
  {"id":"3908","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Politica","subtema":"Contrato social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Jean-Jacques Rousseau, o estado de natureza humano era caracterizado por:","alternativa_a":"Guerra de todos contra todos, onde a vida era solitaria, pobre e brutal","alternativa_b":"Bondade natural e liberdade, corrompidos pelo advento da sociedade civil e propriedade privada","alternativa_c":"Razao pura e sociabilidade natural entre os individuos","alternativa_d":"Obediencia a lei natural divina e hierarquia social","alternativa_e":"Contrato implicito de protecao mutua entre individuos racionais","resposta_correta":"b","explicacao":"Rousseau, ao contrario de Hobbes, acreditava que o ser humano era naturalmente bom (bom selvagem). O estado de natureza era de liberdade e igualdade. A corrupcao surgiu com a propriedade privada e a sociedade civil, que geraram desigualdade e dominacao. O Contrato Social buscava recuperar a liberdade por meio de uma vontade geral que expressasse o bem comum.","resposta":""},
  {"id":"3909","tipo":"multipla","disciplina":"Sociologia","tema":"Sociologia Classica","subtema":"Burocracia em Weber","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Max Weber caracterizou a burocracia moderna como o tipo mais racional de dominacao legal. Entre suas caracteristicas, NAO se inclui:","alternativa_a":"Hierarquia de cargos com competencias definidas","alternativa_b":"Separacao entre o cargo e a pessoa que o ocupa","alternativa_c":"Selecao por merito e competencia tecnica","alternativa_d":"Dominacao baseada no carisma pessoal do lider","alternativa_e":"Normas e regulamentos escritos e sistematizados","resposta_correta":"d","explicacao":"Weber identificou tres tipos de dominacao legitima: tradicional, legal-racional (burocracia) e carismatica. A dominacao carismatica baseia-se em qualidades pessoais extraordinarias do lider, sendo o oposto da burocracia. As demais opcoes sao caracteristicas classicas da burocracia weberiana: hierarquia, impessoalidade, merito e normatizacao.","resposta":""},
  {"id":"3910","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Permutacoes com repeticao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Quantos anagramas tem a palavra BANANA?","alternativa_a":"60","alternativa_b":"120","alternativa_c":"720","alternativa_d":"30","alternativa_e":"360","resposta_correta":"a","explicacao":"BANANA tem 6 letras: B(1), A(3), N(2). O numero de anagramas e P(6; 1,3,2) = 6! / (1! x 3! x 2!) = 720 / (1 x 6 x 2) = 720/12 = 60.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote32.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
