# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4660","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao exponencial - crescimento","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma populacao de bacterias dobra a cada hora. Partindo de 100 bacterias, quantas existirao apos 5 horas?","alternativa_a":"3200","alternativa_b":"500","alternativa_c":"1600","alternativa_d":"6400","alternativa_e":"1000","resposta_correta":"a","explicacao":"P(t) = 100 * 2^t. P(5) = 100 * 2^5 = 100 * 32 = 3200.","resposta":""},
  {"id":"4661","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Poligonos - diagonais","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O numero de diagonais de um polígono de n lados e dado por n(n-3)/2. Um octogono (8 lados) tem quantas diagonais?","alternativa_a":"20","alternativa_b":"8","alternativa_c":"16","alternativa_d":"28","alternativa_e":"12","resposta_correta":"a","explicacao":"D = n(n-3)/2 = 8*(8-3)/2 = 8*5/2 = 40/2 = 20.","resposta":""},
  {"id":"4662","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Equacao do 2o grau - soma e produto","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Em uma equacao ax^2 + bx + c = 0, a soma das raizes e -b/a e o produto e c/a. Na equacao x^2 - 5x + 6 = 0, a soma das raizes e:","alternativa_a":"5","alternativa_b":"-5","alternativa_c":"6","alternativa_d":"-6","alternativa_e":"1","resposta_correta":"a","explicacao":"Soma = -b/a = -(-5)/1 = 5. (As raizes sao 2 e 3, cuja soma e 5.)","resposta":""},
  {"id":"4663","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Arco duplo","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A formula do seno do arco duplo e:","alternativa_a":"sen(2x) = 2*sen(x)*cos(x)","alternativa_b":"sen(2x) = sen^2(x) - cos^2(x)","alternativa_c":"sen(2x) = cos^2(x) - sen^2(x)","alternativa_d":"sen(2x) = 2*cos^2(x)","alternativa_e":"sen(2x) = 1 - 2*sen^2(x)","resposta_correta":"a","explicacao":"Formula do arco duplo: sen(2x) = 2*sen(x)*cos(x). E cos(2x) = cos^2(x) - sen^2(x) = 2cos^2(x) - 1 = 1 - 2sen^2(x).","resposta":""},
  {"id":"4664","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Variancia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Qual e a relacao entre variancia e desvio padrao?","alternativa_a":"O desvio padrao e a raiz quadrada da variancia","alternativa_b":"A variancia e a raiz quadrada do desvio padrao","alternativa_c":"Sao grandezas iguais","alternativa_d":"O desvio padrao e o quadrado da variancia","alternativa_e":"Nao ha relacao matematica","resposta_correta":"a","explicacao":"Desvio padrao (sigma) = sqrt(variancia). Ou: variancia = sigma^2. O desvio padrao tem a mesma unidade dos dados, enquanto a variancia esta em unidades ao quadrado.","resposta":""},
  {"id":"4665","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Relacoes metricas no tetraedro","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Um tetraedro regular tem quatro faces triangulares equilateras. O numero de vertices de um tetraedro regular e:","alternativa_a":"4","alternativa_b":"6","alternativa_c":"8","alternativa_d":"12","alternativa_e":"3","resposta_correta":"a","explicacao":"O tetraedro regular tem 4 vertices, 6 arestas e 4 faces triangulares equilateras (poliedro de Platao mais simples).","resposta":""},
  {"id":"4666","tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Numeros irracionais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual dos seguintes numeros e irracional?","alternativa_a":"sqrt(2)","alternativa_b":"sqrt(4)","alternativa_c":"1/3","alternativa_d":"0,5","alternativa_e":"22/7","resposta_correta":"a","explicacao":"sqrt(2) = 1,41421... e irracional (nao termina e nao e periodico). sqrt(4) = 2 (racional), 1/3 = 0,333... (periodico, racional), 0,5 = 1/2 (racional).","resposta":""},
  {"id":"4667","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Injuncoes e bijecoes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma funcao bijetora (bijecao) e aquela que e simultaneamente:","alternativa_a":"Injetora e sobrejetora","alternativa_b":"Par e impar","alternativa_c":"Crescente e decrescente","alternativa_d":"Continua e derivavel","alternativa_e":"Periodica e limitada","resposta_correta":"a","explicacao":"Bijecao = injetora + sobrejetora. Injetora: elementos distintos tem imagens distintas. Sobrejetora: todo elemento do contradominio tem preimagem. A bijecao admite funcao inversa.","resposta":""},
  {"id":"4668","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Principio aditivo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um aluno pode ir ao cinema ou ao teatro. Ha 3 opcoes de filme e 2 opcoes de peca. O total de opcoes e:","alternativa_a":"5","alternativa_b":"6","alternativa_c":"3","alternativa_d":"2","alternativa_e":"1","resposta_correta":"a","explicacao":"Pelo principio aditivo (eventos mutuamente exclusivos): 3 + 2 = 5 opcoes. (Nao confundir com o principio multiplicativo, usado quando ocorrem eventos simultaneamente.)","resposta":""},
  {"id":"4669","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Continuidade","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma funcao f e continua em x=a se:","alternativa_a":"O limite existe, f(a) existe e lim(x->a) f(x) = f(a)","alternativa_b":"A funcao e diferenciavel em a","alternativa_c":"O limite e infinito","alternativa_d":"A funcao e monotona","alternativa_e":"O limite so existe pela direita","resposta_correta":"a","explicacao":"Para continuidade em x=a, tres condicoes: 1) f(a) esta definida; 2) o limite existe (limites laterais iguais); 3) o limite igual ao valor da funcao: lim f(x) = f(a).","resposta":""},
  {"id":"4670","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Satelites artificiais","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Para um satelite em orbita circular a altura h acima da Terra, a velocidade orbital depende de:","alternativa_a":"Massa da Terra e raio da orbita","alternativa_b":"Massa do satelite","alternativa_c":"Velocidade inicial de lancamento","alternativa_d":"Temperatura do satelite","alternativa_e":"Forma do satelite","resposta_correta":"a","explicacao":"Velocidade orbital: v = sqrt(G*M_Terra / r), onde r = R_Terra + h. Independe da massa do satelite (principio equivalente ao galileano).","resposta":""},
  {"id":"4671","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Energia eletrica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A unidade de energia eletrica usada nas contas de luz e o:","alternativa_a":"Quilowatt-hora (kWh)","alternativa_b":"Watt (W)","alternativa_c":"Joule (J)","alternativa_d":"Volt (V)","alternativa_e":"Ampere (A)","resposta_correta":"a","explicacao":"O quilowatt-hora (kWh) e a unidade comercial de energia. 1 kWh = 1 kW * 1 hora = 1000 W * 3600 s = 3,6 x 10^6 J.","resposta":""},
  {"id":"4672","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Vapor saturado","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O ponto triplo de uma substancia e aquele em que:","alternativa_a":"Os tres estados fisicos coexistem em equilibrio","alternativa_b":"A substancia se decompoe","alternativa_c":"Ocorre a ebulicao a pressao atmosferica","alternativa_d":"Solido e liquido tem mesma densidade","alternativa_e":"Gas e liquido ficam indiferenciados","resposta_correta":"a","explicacao":"O ponto triplo e a combinacao de temperatura e pressao em que os tres estados (solido, liquido e gasoso) coexistem em equilibrio termodinamico. Para a agua: 0,01 oC e 611,73 Pa.","resposta":""},
  {"id":"4673","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Ondas eletromagneticas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As ondas de radio, ao contrario do som, sao ondas:","alternativa_a":"Eletromagneticas que se propagam no vacuo","alternativa_b":"Mecanicas longitudinais","alternativa_c":"Que necessitam de meio material","alternativa_d":"Com frequencia inferior ao infravermelho","alternativa_e":"Superficiais como ondas do mar","resposta_correta":"a","explicacao":"Ondas de radio sao ondas eletromagneticas (campo eletrico + magnetico oscilantes) e se propagam no vacuo a velocidade da luz, ao contrario do som que e onda mecanica.","resposta":""},
  {"id":"4674","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Forca gravitacional","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Segundo a Lei da Gravitacao Universal de Newton, a forca entre dois corpos e proporcional ao produto das massas e inversamente proporcional:","alternativa_a":"Ao quadrado da distancia entre eles","alternativa_b":"A distancia entre eles","alternativa_c":"Ao cubo da distancia","alternativa_d":"A raiz da distancia","alternativa_e":"A diferenca das massas","resposta_correta":"a","explicacao":"Lei de Newton: F = G*m1*m2/d^2. A forca e inversamente proporcional ao quadrado da distancia (lei do inverso do quadrado).","resposta":""},
  {"id":"4675","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Miragem","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O fenomeno da miragem (como a 'agua' vista no asfalto quente) e causado pela:","alternativa_a":"Refracao total interna da luz no ar quente","alternativa_b":"Reflexao especular no asfalto","alternativa_c":"Difracao da luz pelo ar","alternativa_d":"Interferencia construtiva","alternativa_e":"Absorcao seletiva de comprimentos de onda","resposta_correta":"a","explicacao":"A miragem ocorre quando a luz sofre refracao continua (curvando-se) ao passar por camadas de ar com temperaturas e densidades diferentes, causando reflexao total interna.","resposta":""},
  {"id":"4676","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Coeficiente de restitucao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma colisao e dita perfeitamente elastica quando o coeficiente de restituicao e:","alternativa_a":"Igual a 1","alternativa_b":"Igual a 0","alternativa_c":"Entre 0 e 1","alternativa_d":"Maior que 1","alternativa_e":"Negativo","resposta_correta":"a","explicacao":"Coeficiente de restitucao e = 1: colisao perfeitamente elastica (conserva energia cinetica). e = 0: perfeitamente inelastica. 0 < e < 1: parcialmente inelastica.","resposta":""},
  {"id":"4677","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Supercondutividade","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A supercondutividade e um fenomeno em que:","alternativa_a":"A resistencia eletrica cai a zero abaixo de uma temperatura critica","alternativa_b":"A resistencia aumenta com temperatura","alternativa_c":"O material se torna magnetico","alternativa_d":"A corrente eletrica e zero","alternativa_e":"Ocorre somente em metais alcalinos","resposta_correta":"a","explicacao":"Supercondutividade: abaixo da temperatura critica (Tc), certos materiais tem resistencia eletrica exatamente zero, permitindo correntes sem dissipacao. Descoberta por Onnes em 1911.","resposta":""},
  {"id":"4678","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Principio de Pascal","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O principio de Pascal afirma que a pressao aplicada a um fluido em repouso se transmite:","alternativa_a":"Igualmente a todos os pontos do fluido","alternativa_b":"Apenas na direcao vertical","alternativa_c":"Apenas nas paredes do recipiente","alternativa_d":"Proporcionalmente a densidade do fluido","alternativa_e":"Somente para fluidos inviscidos","resposta_correta":"a","explicacao":"Principio de Pascal: a pressao aplicada a um fluido confinado se transmite integralmente e igualmente a todos os pontos do fluido (base da prensa hidraulica).","resposta":""},
  {"id":"4679","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Conducao termica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A conducao termica ocorre principalmente em:","alternativa_a":"Solidos","alternativa_b":"Gases","alternativa_c":"Vacuo","alternativa_d":"Plasmas","alternativa_e":"Liquidos em movimento","resposta_correta":"a","explicacao":"A conducao e o mecanismo predominante de transferencia de calor em solidos, via colisoes entre atomos/eletrons. Em fluidos, predomina a conveccao. No vacuo, a radiacao.","resposta":""},
  {"id":"4680","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Etanol","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O etanol (alcool etilico), principal componente das bebidas alcoolicas e do combustivel alcool, tem formula:","alternativa_a":"C2H5OH","alternativa_b":"CH3OH","alternativa_c":"C3H7OH","alternativa_d":"C6H12O6","alternativa_e":"C2H2","resposta_correta":"a","explicacao":"O etanol e C2H5OH (ou CH3-CH2-OH). O metanol e CH3OH (muito toxicos). O propanol e C3H7OH.","resposta":""},
  {"id":"4681","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Acidos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O acido sulfurico (H2SO4) e o acido mais produzido no mundo e e classificado como:","alternativa_a":"Acido oxacido","alternativa_b":"Acido hidroacido","alternativa_c":"Base forte","alternativa_d":"Sal neutro","alternativa_e":"Oxido acido","resposta_correta":"a","explicacao":"O H2SO4 e um oxacido (contem oxigenio) forte e diprotico. E amplamente usado na industria quimica, producao de fertilizantes e baterias de chumbo.","resposta":""},
  {"id":"4682","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Gasolina e petroleo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A gasolina e obtida do petroleo pelo processo de:","alternativa_a":"Destilacao fracionada","alternativa_b":"Cracking","alternativa_c":"Polimerização","alternativa_d":"Saponificacao","alternativa_e":"Fermentacao","resposta_correta":"a","explicacao":"O petroleo bruto e separado em frações com diferentes pontos de ebulicao pelo processo de destilacao fracionada. A gasolina e coletada na faixa de 70-200 oC.","resposta":""},
  {"id":"4683","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Forcas intermoleculares","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A ponte de hidrogenio e uma interacao intermolecular que ocorre entre moleculas que contem H ligado a:","alternativa_a":"F, O ou N (elementos muito eletronegativos)","alternativa_b":"Carbono","alternativa_c":"Metais","alternativa_d":"Enxofre ou fosforo","alternativa_e":"Qualquer eletronegativo","resposta_correta":"a","explicacao":"Pontes de hidrogenio formam-se quando H esta ligado a F, O ou N (muito eletronegativos), criando uma dipolizacao intensa. Ex.: agua, amonia, acido fluoridrico.","resposta":""},
  {"id":"4684","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Reacoes de dupla troca","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A reacao AB + CD -> AD + CB e um exemplo de reacao de:","alternativa_a":"Dupla troca","alternativa_b":"Simples troca","alternativa_c":"Sintese","alternativa_d":"Analise","alternativa_e":"Combustao","resposta_correta":"a","explicacao":"Reacoes de dupla troca (metátese): dois compostos trocam seus ions entre si. Ocorre geralmente com formacao de precipitado, gas ou substancia nao ionizavel (como agua).","resposta":""},
  {"id":"4685","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Aromaticidade","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Para uma molecula ser aromatica, deve atender a regra de Huckel: ter 4n+2 eletrons pi. O benzeno tem 6 eletrons pi (n=1). O numero de eletrons do naftaleno aromatico e:","alternativa_a":"10","alternativa_b":"6","alternativa_c":"8","alternativa_d":"12","alternativa_e":"14","resposta_correta":"a","explicacao":"Naftaleno (C10H8) tem 10 eletrons pi, satisfazendo a regra de Huckel com n=2 (4*2+2=10), confirmando sua aromaticidade.","resposta":""},
  {"id":"4686","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Poluicao da agua","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A demanda bioquimica de oxigenio (DBO) e um indicador de poluicao da agua que mede:","alternativa_a":"A quantidade de O2 consumida por microrganismos para decompor materia organica","alternativa_b":"A quantidade de O2 dissolvido na agua","alternativa_c":"A turbidez da agua","alternativa_d":"O pH da agua","alternativa_e":"A concentracao de metais pesados","resposta_correta":"a","explicacao":"A DBO mede o oxigenio consumido por microrganismos aerobicos para decompor materia organica. Alta DBO indica alta poluicao organica e baixo teor de O2 disponivel.","resposta":""},
  {"id":"4687","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Metais de transicao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os metais de transicao (bloco d da tabela periodica) sao caracterizados por:","alternativa_a":"Formarem multiplos estados de oxidacao e complexos coloridos","alternativa_b":"Serem todos magneticos","alternativa_c":"Nao conduzirem eletricidade","alternativa_d":"Reagirem violentamente com agua","alternativa_e":"Terem apenas um eletron de valencia","resposta_correta":"a","explicacao":"Metais de transicao (Fe, Cu, Mn, Co, etc.) formam varios estados de oxidacao e compostos de coordenacao (complexos) geralmente coloridos, devido a transicoes eletrônicas no orbital d.","resposta":""},
  {"id":"4688","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Classificacao dos hidretos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O HCl gasoso e classificado como:","alternativa_a":"Hidreto nao-metalico (hidroacido)","alternativa_b":"Hidroxido","alternativa_c":"Sal","alternativa_d":"Oxido acido","alternativa_e":"Hidreto metalico","resposta_correta":"a","explicacao":"HCl gasoso e um hidreto nao-metalico. Quando dissolvido em agua, forma o acido cloridrico (acido forte). Sua classificacao e como hidreto nao-metalico ou hidroacido.","resposta":""},
  {"id":"4689","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Fermentacao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A fermentacao alcoolica, realizada por leveduras, converte glicose em:","alternativa_a":"Etanol e CO2","alternativa_b":"Acido latico","alternativa_c":"Acido acetico","alternativa_d":"Metanol e O2","alternativa_e":"Glicerol e H2","resposta_correta":"a","explicacao":"Fermentacao alcoolica: C6H12O6 -> 2C2H5OH + 2CO2. Usada na producao de vinho, cerveja, pao e biocombustivel (etanol).","resposta":""},
  {"id":"4690","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Transporte ativo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O transporte ativo e um processo que:","alternativa_a":"Requer energia (ATP) e ocorre contra o gradiente de concentracao","alternativa_b":"Ocorre a favor do gradiente sem gasto de energia","alternativa_c":"E realizado por osmose","alternativa_d":"Ocorre apenas em celulas vegetais","alternativa_e":"Nao envolve proteinas de membrana","resposta_correta":"a","explicacao":"Transporte ativo: move substancias do menor para o maior gradiente de concentracao (contra o gradiente), necessitando de energia (ATP) e proteinas transportadoras (bombas).","resposta":""},
  {"id":"4691","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema reprodutor","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na espermatogenese, as espermatogonias sofrem divisoes e diferenciacoes ate originar espermatozoides. Esse processo ocorre nos:","alternativa_a":"Tubulos seminiferos dos testiculos","alternativa_b":"Epidídimo","alternativa_c":"Vesiculas seminais","alternativa_d":"Prostata","alternativa_e":"Uretra","resposta_correta":"a","explicacao":"A espermatogenese ocorre nos tubulos seminiferos dos testiculos, onde as espermatogonias se dividem (mitose), crescem e sofrem meiose para originar espermatozoides.","resposta":""},
  {"id":"4692","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Impacto ambiental","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O desmatamento da Amazonia tem impacto global pois:","alternativa_a":"Reduz a absorcao de CO2 e aumenta o efeito estufa","alternativa_b":"Aumenta a producao de O2 global","alternativa_c":"Melhora o regime de chuvas global","alternativa_d":"Nao tem impacto fora da America do Sul","alternativa_e":"Aumenta a biodiversidade global","resposta_correta":"a","explicacao":"A Amazonia e um sumidouro de carbono: arvores armazenam CO2. O desmatamento libera carbono, reduz a absorcao futura e altera o ciclo hidrologico regional e global.","resposta":""},
  {"id":"4693","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Epigenetica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A epigenetica estuda alteracoes na expressao genica que:","alternativa_a":"Nao envolvem mudancas na sequencia do DNA mas podem ser herdadas","alternativa_b":"Sempre causam mutacoes permanentes no DNA","alternativa_c":"Ocorrem apenas em celulas cancerosas","alternativa_d":"Sao causadas exclusivamente por radiacoes","alternativa_e":"Eliminam os genes responsaveis","resposta_correta":"a","explicacao":"A epigenetica trata de modificacoes hereditarias na expressao genica (metilacao do DNA, modificacao de histonas) que nao alteram a sequencia nucleotidica mas regulam quais genes sao expressos.","resposta":""},
  {"id":"4694","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sangue","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O componente do sangue responsavel pelo transporte de oxigenio e:","alternativa_a":"Hemoglobina nos eritrocitos","alternativa_b":"Leucocitos","alternativa_c":"Plaquetas","alternativa_d":"Plasma","alternativa_e":"Fibrinogenio","resposta_correta":"a","explicacao":"A hemoglobina e uma proteina presente nos eritrocitos (globulos vermelhos/hemácias) que se liga ao O2 nos pulmoes e o transporta para os tecidos.","resposta":""},
  {"id":"4695","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Nutricao das plantas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A fixacao de nitrogenio por bacterias simbiontes em raizes de leguminosas ocorre em estruturas chamadas:","alternativa_a":"Nodulos radiculares","alternativa_b":"Plastos","alternativa_c":"Rizomas","alternativa_d":"Estoloes","alternativa_e":"Tricomas","resposta_correta":"a","explicacao":"As bacterias do genero Rhizobium formam nodulos nas raizes de leguminosas (feijao, soja, amendoim), onde fixam N2 atmosferico em amonia utilizavel pela planta.","resposta":""},
  {"id":"4696","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema hormonal","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O hormonio do crescimento (GH) e produzido pela:","alternativa_a":"Hipofise anterior","alternativa_b":"Tireoide","alternativa_c":"Suprarrenal","alternativa_d":"Pancreas","alternativa_e":"Hipofise posterior","resposta_correta":"a","explicacao":"O GH (somatotropina) e produzido pela hipofise anterior (adenohipofise) e estimula o crescimento osseo e muscular, especialmente durante a infancia e adolescencia.","resposta":""},
  {"id":"4697","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Imigração","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A imigracao japonesa para o Brasil, iniciada em 1908, teve como principal destino inicial as fazendas de cafe no estado de:","alternativa_a":"Sao Paulo","alternativa_b":"Rio de Janeiro","alternativa_c":"Minas Gerais","alternativa_d":"Parana","alternativa_e":"Espirito Santo","resposta_correta":"a","explicacao":"Em 1908, o navio Kasato Maru trouxe os primeiros 781 imigrantes japoneses para trabalhar nas fazendas de cafe de Sao Paulo, substituindo a mao de obra escrava e europeia.","resposta":""},
  {"id":"4698","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Colonizacao da Asia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A politica do Apartheid na Africa do Sul (1948-1994) era um sistema de:","alternativa_a":"Segregacao racial institucionalizada","alternativa_b":"Ditadura militar","alternativa_c":"Socialismo africano","alternativa_d":"Colonialismo interno","alternativa_e":"Democracia racial","resposta_correta":"a","explicacao":"O Apartheid foi um regime de segregacao racial na Africa do Sul, onde a minoria branca mantinha controle politico e economico, negando direitos basicos a populacao negra majoritaria.","resposta":""},
  {"id":"4699","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Retomada Democratica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Constituicao Federal Brasileira atual, conhecida como 'Constituicao Cidada', foi promulgada em:","alternativa_a":"1988","alternativa_b":"1964","alternativa_c":"1946","alternativa_d":"1891","alternativa_e":"1824","resposta_correta":"a","explicacao":"A Constituicao de 1988 (Constituicao Cidada) foi promulgada em 5 de outubro de 1988, marcando a redemocratizacao apos a ditadura militar e ampliando direitos fundamentais.","resposta":""},
  {"id":"4700","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Neoliberalismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O neoliberalismo, politica economica que prevaleceu nas decadas de 1980-90, defende a:","alternativa_a":"Reducao do Estado e privatizacoes","alternativa_b":"Expansao do Estado na economia","alternativa_c":"Intervencao estatal no comercio externo","alternativa_d":"Economia planificada centralizada","alternativa_e":"Distribuicao de renda pelo Estado","resposta_correta":"a","explicacao":"O neoliberalismo (Thatcher, Reagan, Consenso de Washington) defende privatizacoes, reducao do Estado, abertura comercial e financeira, e desregulamentacao dos mercados.","resposta":""},
  {"id":"4701","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Renascimento artistico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O autor da obra 'A Ultima Ceia' e do 'Homem Vitruviano' foi:","alternativa_a":"Leonardo da Vinci","alternativa_b":"Michelangelo","alternativa_c":"Rafael Sanzio","alternativa_d":"Botticelli","alternativa_e":"Donatello","resposta_correta":"a","explicacao":"Leonardo da Vinci (1452-1519) e um dos maiores gênios do Renascimento, autor da Ultima Ceia, do Homem Vitruviano e da Mona Lisa.","resposta":""},
  {"id":"4702","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Globalizacao cultural","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'aldeia global', cunhado por Marshall McLuhan, refere-se ao:","alternativa_a":"Encolhimento das distancias culturais pelos meios de comunicacao","alternativa_b":"Movimento de volta a vida rural","alternativa_c":"Criacao de aldeias sustentaveis","alternativa_d":"Troca economica entre tribos primitivas","alternativa_e":"Rede de viagens globais de turismo","resposta_correta":"a","explicacao":"Marshall McLuhan criou o conceito de 'aldeia global' nos anos 1960 para descrever como os meios de comunicacao de massa conectavam o mundo, tornando-o uma aldeia interconectada.","resposta":""},
  {"id":"4703","tipo":"multipla","disciplina":"Geografia","tema":"Transporte","subtema":"Logistica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O modal de transporte que apresenta maior capacidade de carga e menor custo por tonelada-quilometro e o:","alternativa_a":"Hidroviario","alternativa_b":"Rodoviario","alternativa_c":"Ferroviario","alternativa_d":"Aereo","alternativa_e":"Dutoviario","resposta_correta":"a","explicacao":"O transporte hidroviario (fluvial e maritimo) tem a maior capacidade de carga e o menor custo por tonelada-km, sendo o mais eficiente para grandes volumes a longas distancias.","resposta":""},
  {"id":"4704","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Blocos economicos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Uniao Europeia (UE) e um bloco de integracao economica e politica. Qual moeda e adotada pela maioria dos paises membros?","alternativa_a":"Euro","alternativa_b":"Franco","alternativa_c":"Libra","alternativa_d":"Marco","alternativa_e":"Florim","resposta_correta":"a","explicacao":"O euro e a moeda comum adotada por 20 dos 27 paises membros da UE (zona do euro). Paises como UK, Suecia e Dinamarca mantiveram suas moedas nacionais.","resposta":""},
  {"id":"4705","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Oracao subordinada substantiva","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em 'E necessario que voce estude', a oracao 'que voce estude' e uma oracao subordinada substantiva:","alternativa_a":"Subjetiva","alternativa_b":"Objetiva direta","alternativa_c":"Completiva nominal","alternativa_d":"Predicativa","alternativa_e":"Apositiva","resposta_correta":"a","explicacao":"A oracao e subjetiva pois funciona como sujeito do verbo impessoal 'ser' (sujeito oculto: 'que voce estude' e necessario). Oracao subordinada substantiva subjetiva.","resposta":""},
  {"id":"4706","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Arcadismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Arcadismo (Neoclassicismo) brasileiro teve como principal nome:","alternativa_a":"Tomas Antonio Gonzaga","alternativa_b":"Gregorio de Matos","alternativa_c":"Jose de Alencar","alternativa_d":"Machado de Assis","alternativa_e":"Olavo Bilac","resposta_correta":"a","explicacao":"Tomas Antonio Gonzaga (1744-1810) e o principal poeta arcadico brasileiro, autor de 'Marilia de Dirceu', obra que celebra o amor e os ideais classicos sob pseudônimo Dirceu.","resposta":""},
  {"id":"4707","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia da Mente","subtema":"Consciencia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O 'problema dificil da consciencia', formulado por David Chalmers, questiona:","alternativa_a":"Por que estados fisicos geram experiencia subjetiva","alternativa_b":"Se os humanos tem livre-arbitrio","alternativa_c":"Como a memoria funciona neurologicamente","alternativa_d":"Se maquinas podem pensar","alternativa_e":"Por que sonhamos","resposta_correta":"a","explicacao":"Chalmers distingue os 'problemas faceis' (funcoes cognitivas) do 'problema dificil': por que e como processos fisicos cerebrais dao origem a experiencia subjetiva consciente (qualia).","resposta":""},
  {"id":"4708","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Moderna","subtema":"Kant","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O imperativo categorico de Kant determina que devemos agir apenas segundo a maxima que possamos querer que se torne uma:","alternativa_a":"Lei universal","alternativa_b":"Lei divina","alternativa_c":"Norma cultural","alternativa_d":"Regra de utilidade","alternativa_e":"Convencao social","resposta_correta":"a","explicacao":"O imperativo categorico de Kant (1o formulacao): 'Age apenas segundo aquela maxima pela qual possas ao mesmo tempo querer que ela se torne uma lei universal.' E o principio fundamental da etica kantiana.","resposta":""},
  {"id":"4709","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Anomia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de anomia, desenvolvido por Emile Durkheim, refere-se a:","alternativa_a":"Estado de falta de normas ou enfraquecimento das normas sociais","alternativa_b":"Excesso de regulamentacao social","alternativa_c":"Conflito entre classes opostas","alternativa_d":"Integracao social maxima","alternativa_e":"Transicao de sociedades tradicionais para modernas","resposta_correta":"a","explicacao":"Anomia (Durkheim): estado em que as normas sociais estao ausentes, enfraquecidas ou em conflito, causando desorientacao nos individuos. Usou o conceito para explicar o suicidio anomico.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote48.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
