# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4410","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Sistemas lineares","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Resolva o sistema: x + y = 7 e x - y = 3. O valor de x e:","alternativa_a":"5","alternativa_b":"4","alternativa_c":"3","alternativa_d":"6","alternativa_e":"2","resposta_correta":"a","explicacao":"Somando as equacoes: 2x = 10, logo x = 5. Entao y = 7 - 5 = 2.","resposta":""},
  {"id":"4411","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Trapezio","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A area de um trapezio com bases 6 cm e 10 cm e altura 4 cm e:","alternativa_a":"32 cm2","alternativa_b":"24 cm2","alternativa_c":"40 cm2","alternativa_d":"16 cm2","alternativa_e":"60 cm2","resposta_correta":"a","explicacao":"A = (B+b)*h/2 = (10+6)*4/2 = 16*2 = 32 cm2.","resposta":""},
  {"id":"4412","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao exponencial","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A solucao de 2^x = 32 e:","alternativa_a":"5","alternativa_b":"4","alternativa_c":"6","alternativa_d":"3","alternativa_e":"7","resposta_correta":"a","explicacao":"2^5 = 32, portanto x = 5.","resposta":""},
  {"id":"4413","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Permutacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"De quantas formas diferentes 4 pessoas podem se sentar em 4 cadeiras distintas?","alternativa_a":"24","alternativa_b":"12","alternativa_c":"16","alternativa_d":"8","alternativa_e":"6","resposta_correta":"a","explicacao":"P(4) = 4! = 4*3*2*1 = 24.","resposta":""},
  {"id":"4414","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Espaco amostral","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um dado honesto e lancado. A probabilidade de sair um numero par e:","alternativa_a":"1/2","alternativa_b":"1/3","alternativa_c":"2/3","alternativa_d":"1/6","alternativa_e":"5/6","resposta_correta":"a","explicacao":"Numeros pares: 2, 4, 6 (3 casos). Total: 6. P = 3/6 = 1/2.","resposta":""},
  {"id":"4415","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Limites","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O limite lim(x->2) (x^2 - 4)/(x - 2) e igual a:","alternativa_a":"4","alternativa_b":"2","alternativa_c":"0","alternativa_d":"indefinido","alternativa_e":"1","resposta_correta":"a","explicacao":"(x^2-4)/(x-2) = (x+2)(x-2)/(x-2) = x+2. Quando x->2: 2+2 = 4.","resposta":""},
  {"id":"4416","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Identidades trigonometricas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O valor de sen^2(x) + cos^2(x) e sempre igual a:","alternativa_a":"1","alternativa_b":"0","alternativa_c":"2","alternativa_d":"sen(2x)","alternativa_e":"cos(2x)","resposta_correta":"a","explicacao":"Esta e a identidade trigonometrica fundamental: sen^2(x) + cos^2(x) = 1.","resposta":""},
  {"id":"4417","tipo":"multipla","disciplina":"Matematica","tema":"Matrizes","subtema":"Determinante","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O determinante da matriz [[2,3],[1,4]] e:","alternativa_a":"5","alternativa_b":"8","alternativa_c":"3","alternativa_d":"11","alternativa_e":"6","resposta_correta":"a","explicacao":"det = 2*4 - 3*1 = 8 - 3 = 5.","resposta":""},
  {"id":"4418","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Analitica","subtema":"Equacao da circunferencia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A equacao da circunferencia de centro (2, -1) e raio 3 e:","alternativa_a":"(x-2)^2 + (y+1)^2 = 9","alternativa_b":"(x+2)^2 + (y-1)^2 = 9","alternativa_c":"(x-2)^2 + (y-1)^2 = 3","alternativa_d":"x^2 + y^2 = 9","alternativa_e":"(x-2)^2 + (y+1)^2 = 3","resposta_correta":"a","explicacao":"A forma geral e (x-a)^2 + (y-b)^2 = r^2. Com centro (2,-1) e r=3: (x-2)^2 + (y+1)^2 = 9.","resposta":""},
  {"id":"4419","tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Divisibilidade","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um numero e divisivel por 9 quando:","alternativa_a":"A soma de seus algarismos e divisivel por 9","alternativa_b":"Termina em 0 ou 9","alternativa_c":"E par","alternativa_d":"Termina em 9","alternativa_e":"A soma dos algarismos e divisivel por 3","resposta_correta":"a","explicacao":"A regra de divisibilidade por 9: a soma dos algarismos deve ser divisivel por 9.","resposta":""},
  {"id":"4420","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Lancamento obliquo","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"No lancamento obliquo, no ponto mais alto da trajetoria, a velocidade vertical e:","alternativa_a":"Zero","alternativa_b":"Maxima","alternativa_c":"Igual a velocidade horizontal","alternativa_d":"Negativa","alternativa_e":"Igual a velocidade inicial","resposta_correta":"a","explicacao":"No ponto mais alto, o objeto muda de subida para descida. Nesse instante, a componente vertical da velocidade e zero.","resposta":""},
  {"id":"4421","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Lei de Ohm","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Segundo a Lei de Ohm, a tensao em um resistor e igual a:","alternativa_a":"Resistencia multiplicada pela corrente","alternativa_b":"Corrente dividida pela resistencia","alternativa_c":"Resistencia dividida pela corrente","alternativa_d":"Potencia dividida pela corrente","alternativa_e":"Corrente ao quadrado vezes resistencia","resposta_correta":"a","explicacao":"Lei de Ohm: U = R*I. A tensao e igual a resistencia multiplicada pela corrente.","resposta":""},
  {"id":"4422","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Maquina termica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A eficiencia de uma maquina de Carnot que opera entre 500 K e 300 K e:","alternativa_a":"40%","alternativa_b":"60%","alternativa_c":"50%","alternativa_d":"30%","alternativa_e":"20%","resposta_correta":"a","explicacao":"Eficiencia de Carnot: n = 1 - Tf/Tq = 1 - 300/500 = 1 - 0,6 = 0,4 = 40%.","resposta":""},
  {"id":"4423","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Efeito Doppler","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Quando uma fonte sonora se aproxima de um observador estatico, a frequencia percebida pelo observador e:","alternativa_a":"Maior que a frequencia da fonte","alternativa_b":"Menor que a frequencia da fonte","alternativa_c":"Igual a frequencia da fonte","alternativa_d":"Zero","alternativa_e":"Depende da amplitude","resposta_correta":"a","explicacao":"Pelo efeito Doppler, quando a fonte se aproxima do observador, as ondas se comprimem e o observador percebe uma frequencia maior.","resposta":""},
  {"id":"4424","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Inducao eletromagnetica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A lei de Faraday estabelece que a forca eletromotriz induzida em um circuito e proporcional a:","alternativa_a":"Taxa de variacao do fluxo magnetico","alternativa_b":"Intensidade do campo eletrico","alternativa_c":"Resistencia do circuito","alternativa_d":"Carga armazenada no capacitor","alternativa_e":"Frequencia da corrente","resposta_correta":"a","explicacao":"Lei de Faraday: EMF = -dFi/dt. A FEM induzida e proporcional a taxa de variacao do fluxo magnetico.","resposta":""},
  {"id":"4425","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Momento angular","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma bailarina gira com os bracos abertos. Ao fechar os bracos, sem atrito externo, sua velocidade angular:","alternativa_a":"Aumenta","alternativa_b":"Diminui","alternativa_c":"Permanece constante","alternativa_d":"Vai a zero","alternativa_e":"Torna-se negativa","resposta_correta":"a","explicacao":"Pela conservacao do momento angular (L=I*w), ao fechar os bracos o momento de inercia I diminui, portanto a velocidade angular w aumenta.","resposta":""},
  {"id":"4426","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Cores da luz","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A cor da luz visivel com maior comprimento de onda e:","alternativa_a":"Vermelho","alternativa_b":"Violeta","alternativa_c":"Azul","alternativa_d":"Verde","alternativa_e":"Amarelo","resposta_correta":"a","explicacao":"No espectro visivel, a luz vermelha tem maior comprimento de onda (aprox. 700 nm) e a violeta tem o menor (aprox. 400 nm).","resposta":""},
  {"id":"4427","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica dos Fluidos","subtema":"Principio de Arquimedes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um objeto submerso em um fluido sofre um empuxo igual a:","alternativa_a":"Peso do fluido deslocado","alternativa_b":"Peso do objeto","alternativa_c":"Pressao do fluido","alternativa_d":"Volume do objeto","alternativa_e":"Densidade do fluido","resposta_correta":"a","explicacao":"Principio de Arquimedes: o empuxo e igual ao peso do fluido deslocado pelo objeto: E = d_fluido * V_submerso * g.","resposta":""},
  {"id":"4428","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Energia potencial elastica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A energia armazenada em uma mola com constante elastica k=200 N/m comprimida 0,1 m e:","alternativa_a":"1 J","alternativa_b":"2 J","alternativa_c":"10 J","alternativa_d":"20 J","alternativa_e":"0,5 J","resposta_correta":"a","explicacao":"Ep = (1/2)*k*x^2 = (1/2)*200*(0,1)^2 = 100*0,01 = 1 J.","resposta":""},
  {"id":"4429","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Potencial eletrico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O potencial eletrico e uma grandeza:","alternativa_a":"Escalar","alternativa_b":"Vetorial","alternativa_c":"Tensorial","alternativa_d":"Dependente da carga de prova","alternativa_e":"Sempre negativa","resposta_correta":"a","explicacao":"O potencial eletrico e uma grandeza escalar (nao tem direcao), ao contrario do campo eletrico que e vetorial.","resposta":""},
  {"id":"4430","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Alcenos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os alcenos sao hidrocarbonetos que possuem em sua estrutura:","alternativa_a":"Uma dupla ligacao entre carbonos","alternativa_b":"Uma tripla ligacao entre carbonos","alternativa_c":"Apenas ligacoes simples","alternativa_d":"Um anel aromatico","alternativa_e":"Dois aneis","resposta_correta":"a","explicacao":"Alcenos (ou olefinas) possuem pelo menos uma dupla ligacao entre carbonos. Sua formula geral e CnH2n.","resposta":""},
  {"id":"4431","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Acidos e bases","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Segundo Bronsted-Lowry, um acido e uma substancia que:","alternativa_a":"Doa protons (H+)","alternativa_b":"Aceita protons (H+)","alternativa_c":"Doa eletrons","alternativa_d":"Aceita eletrons","alternativa_e":"Libera OH-","resposta_correta":"a","explicacao":"Na teoria de Bronsted-Lowry, acido e toda especie capaz de doar protons (H+) e base e toda especie capaz de aceitar protons.","resposta":""},
  {"id":"4432","tipo":"multipla","disciplina":"Quimica","tema":"Radioatividade","subtema":"Tipos de radiacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A radiacao que possui maior poder de penetracao e:","alternativa_a":"Gama","alternativa_b":"Alfa","alternativa_c":"Beta","alternativa_d":"Ultravioleta","alternativa_e":"Infravermelho","resposta_correta":"a","explicacao":"A radiacao gama (ondas eletromagneticas) possui o maior poder de penetracao, sendo capaz de atravessar concreto e chumbo. A alfa tem o menor poder.","resposta":""},
  {"id":"4433","tipo":"multipla","disciplina":"Quimica","tema":"Solucoes","subtema":"pH","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma solucao com pH = 3 e considerada:","alternativa_a":"Acida","alternativa_b":"Basica","alternativa_c":"Neutra","alternativa_d":"Tampao","alternativa_e":"Supersaturada","resposta_correta":"a","explicacao":"Solucoes com pH < 7 sao acidas, pH = 7 sao neutras e pH > 7 sao basicas. pH = 3 indica solucao acida.","resposta":""},
  {"id":"4434","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Alcinos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O mais simples dos alcinos e o etino (acetileno), com formula:","alternativa_a":"C2H2","alternativa_b":"C2H4","alternativa_c":"C2H6","alternativa_d":"CH4","alternativa_e":"C3H4","resposta_correta":"a","explicacao":"O etino (acetileno) tem formula C2H2: H-C≡C-H. Possui uma tripla ligacao entre os dois carbonos.","resposta":""},
  {"id":"4435","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Pilhas","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma pilha eletroquimica, a oxidacao ocorre no:","alternativa_a":"Anodo","alternativa_b":"Catodo","alternativa_c":"Eletrodo inerte","alternativa_d":"Ponte salina","alternativa_e":"Eletrolitodo","resposta_correta":"a","explicacao":"No anodo ocorre a reacao de oxidacao (perda de eletrons). No catodo ocorre a reducao (ganho de eletrons).","resposta":""},
  {"id":"4436","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Chuva acida","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A chuva acida e causada principalmente pela presenca de quais gases na atmosfera?","alternativa_a":"SO2 e NOx","alternativa_b":"O2 e CO2","alternativa_c":"N2 e H2","alternativa_d":"CH4 e NH3","alternativa_e":"Cl2 e F2","resposta_correta":"a","explicacao":"A chuva acida resulta da reacao de SO2 (dioxido de enxofre) e NOx (oxidos de nitrogenio) com a agua atmosferica, formando acidos sulfurico e nitrico.","resposta":""},
  {"id":"4437","tipo":"multipla","disciplina":"Quimica","tema":"Polimeros","subtema":"Polimerizacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O polietileno e obtido pela polimerizacao do:","alternativa_a":"Eteno","alternativa_b":"Propeno","alternativa_c":"Etanol","alternativa_d":"Benzeno","alternativa_e":"Metanol","resposta_correta":"a","explicacao":"O polietileno (PE) e obtido pela polimerizacao de adicao do eteno (CH2=CH2), formando longas cadeias -[CH2-CH2]n-.","resposta":""},
  {"id":"4438","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Sais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O cloreto de sodio (NaCl) e um exemplo de:","alternativa_a":"Sal","alternativa_b":"Acido","alternativa_c":"Base","alternativa_d":"Oxido","alternativa_e":"Hidroxido","resposta_correta":"a","explicacao":"NaCl e um sal, resultado da reacao entre o acido cloridrico (HCl) e a base hidroxido de sodio (NaOH).","resposta":""},
  {"id":"4439","tipo":"multipla","disciplina":"Quimica","tema":"Modelo Atomico","subtema":"Distribuicao eletronica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O elemento com numero atomico 11 (Sodio) possui quantos eletrons na camada de valencia?","alternativa_a":"1","alternativa_b":"2","alternativa_c":"3","alternativa_d":"7","alternativa_e":"8","resposta_correta":"a","explicacao":"Na (Z=11) tem configuracao 1s2 2s2 2p6 3s1. Tem 1 eletron na ultima camada (3s1), portanto 1 eletron de valencia.","resposta":""},
  {"id":"4440","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Selecao natural","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O mecanismo central da teoria evolutiva de Darwin e Wallace e:","alternativa_a":"Selecao natural","alternativa_b":"Mutacao dirigida","alternativa_c":"Heranca de caracteres adquiridos","alternativa_d":"Deriva genetica","alternativa_e":"Uso e desuso","resposta_correta":"a","explicacao":"A selecao natural e o mecanismo central do darwinismo: individuos com caracteristicas mais vantajosas sobrevivem e se reproduzem mais, transmitindo essas caracteristicas.","resposta":""},
  {"id":"4441","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Mutacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A falcemia e causada por uma mutacao que altera:","alternativa_a":"Um unico par de bases do DNA","alternativa_b":"Um cromossomo inteiro","alternativa_c":"O numero de cromossomos","alternativa_d":"A estrutura da membrana","alternativa_e":"O numero de mitocondrias","resposta_correta":"a","explicacao":"A anemia falciforme e causada por uma mutacao de ponto (substituicao de um unico nucleotideo) no gene da beta-globina da hemoglobina.","resposta":""},
  {"id":"4442","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Biomas brasileiros","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O Pantanal, considerado uma das maiores areas umidas do mundo, localiza-se principalmente no estado de:","alternativa_a":"Mato Grosso do Sul e Mato Grosso","alternativa_b":"Amazonas e Para","alternativa_c":"Bahia e Minas Gerais","alternativa_d":"Goias e Tocantins","alternativa_e":"Rio Grande do Sul e Santa Catarina","resposta_correta":"a","explicacao":"O Pantanal se estende principalmente pelos estados de Mato Grosso do Sul e Mato Grosso, alem de partes da Bolivia e do Paraguai.","resposta":""},
  {"id":"4443","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema nervoso","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sistema nervoso autonomo e dividido em sistema simpatico e:","alternativa_a":"Parassimpatico","alternativa_b":"Somatico","alternativa_c":"Central","alternativa_d":"Periferico","alternativa_e":"Enterico","resposta_correta":"a","explicacao":"O sistema nervoso autonomo regula funcoes involuntarias e se divide em sistema simpatico (reacao de luta ou fuga) e parassimpatico (descanso e digestao).","resposta":""},
  {"id":"4444","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Mitocondria","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A mitocondria e o organulo responsavel pela:","alternativa_a":"Respiracao celular aerobica","alternativa_b":"Sintese de proteinas","alternativa_c":"Fotossintese","alternativa_d":"Digestao intracelular","alternativa_e":"Divisao celular","resposta_correta":"a","explicacao":"A mitocondria e o organulo onde ocorre a respiracao celular aerobica, produzindo ATP atraves da fosforilacao oxidativa.","resposta":""},
  {"id":"4445","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Angiospermas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"As angiospermas se diferenciam das gimnospermas por possuirem:","alternativa_a":"Sementes envolvidas pelo fruto","alternativa_b":"Sementes nuas (sem fruto)","alternativa_c":"Ausencia de sementes","alternativa_d":"Reproducao por esporos","alternativa_e":"Ausencia de vasos condutores","resposta_correta":"a","explicacao":"Angiospermas possuem ovulo encerrado dentro de um ovario, que apos a fecundacao se torna o fruto contendo a semente.","resposta":""},
  {"id":"4446","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema imunologico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os anticorpos sao proteinas produzidas por:","alternativa_a":"Linfocitos B","alternativa_b":"Linfocitos T","alternativa_c":"Neutrofilos","alternativa_d":"Eritrocitos","alternativa_e":"Plaquetas","resposta_correta":"a","explicacao":"Os linfocitos B se diferenciam em plasmocitos, que produzem e secretam anticorpos (imunoglobulinas) especificos contra antigenos.","resposta":""},
  {"id":"4447","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Relacoes ecologicas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A relacao entre o palhaço e a anemona-do-mar, em que ambos se beneficiam, e chamada de:","alternativa_a":"Mutualismo","alternativa_b":"Comensalismo","alternativa_c":"Parasitismo","alternativa_d":"Predatismo","alternativa_e":"Amensalismo","resposta_correta":"a","explicacao":"O mutualismo e uma relacao harmonica interespecifica em que ambas as especies se beneficiam, como o peixe-palhaço e a anemona.","resposta":""},
  {"id":"4448","tipo":"multipla","disciplina":"Biologia","tema":"Bioquimica","subtema":"Lipidios","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os triglicerideos sao formados pela uniao de glicerol com:","alternativa_a":"Tres acidos graxos","alternativa_b":"Dois acidos graxos","alternativa_c":"Um acido graxo","alternativa_d":"Tres aminoacidos","alternativa_e":"Tres monossacarideos","resposta_correta":"a","explicacao":"Triglicerideos (gorduras neutras) sao formados pela uniao de uma molecula de glicerol com tres moleculas de acidos graxos, por meio de ligacoes ester.","resposta":""},
  {"id":"4449","tipo":"multipla","disciplina":"Biologia","tema":"Reproducao","subtema":"Meiose","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A meiose resulta na formacao de celulas com:","alternativa_a":"Metade do numero de cromossomos (n)","alternativa_b":"O mesmo numero de cromossomos (2n)","alternativa_c":"O dobro de cromossomos (4n)","alternativa_d":"Nenhum cromossomo","alternativa_e":"Numero variavel de cromossomos","resposta_correta":"a","explicacao":"A meiose e uma divisao reducional: a celula diploide (2n) origina 4 celulas haploides (n), com metade do numero de cromossomos.","resposta":""},
  {"id":"4450","tipo":"multipla","disciplina":"Historia","tema":"Pre-Historia","subtema":"Neolitico","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Revolucao Neolitica e marcada principalmente pelo surgimento da:","alternativa_a":"Agricultura e pecuaria","alternativa_b":"Escrita cuneiforme","alternativa_c":"Metalurgia do ferro","alternativa_d":"Democracia ateniense","alternativa_e":"Rota da Seda","resposta_correta":"a","explicacao":"A Revolucao Neolitica (aproximadamente 10.000 a.C.) foi marcada pelo desenvolvimento da agricultura e da domesticacao de animais, permitindo o sedentarismo humano.","resposta":""},
  {"id":"4451","tipo":"multipla","disciplina":"Historia","tema":"Historia Antiga","subtema":"Grecia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A batalha de Maratona (490 a.C.) foi um confronto entre gregos e:","alternativa_a":"Persas","alternativa_b":"Egipcios","alternativa_c":"Romanos","alternativa_d":"Macedonios","alternativa_e":"Cartagineses","resposta_correta":"a","explicacao":"A batalha de Maratona foi um confronto das Guerras Medicas entre atenienses/plataicos e o Imperio Persa, resultando em vitoria grega.","resposta":""},
  {"id":"4452","tipo":"multipla","disciplina":"Historia","tema":"Historia Medieval","subtema":"Islam","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O islamismo foi fundado pelo profeta Maome no seculo VII d.C. O livro sagrado dos muculmanos e:","alternativa_a":"Alcorao","alternativa_b":"Biblia","alternativa_c":"Tora","alternativa_d":"Veda","alternativa_e":"Upanixade","resposta_correta":"a","explicacao":"O Alcorao (Quran) e o livro sagrado do islamismo, considerado pelos muculmanos como a palavra de Alah revelada ao profeta Maome.","resposta":""},
  {"id":"4453","tipo":"multipla","disciplina":"Historia","tema":"Historia Moderna","subtema":"Reforma Protestante","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Reforma Protestante foi iniciada em 1517 por:","alternativa_a":"Martinho Lutero","alternativa_b":"Joao Calvino","alternativa_c":"Henrique VIII","alternativa_d":"Ignacio de Loyola","alternativa_e":"Zwinglio","resposta_correta":"a","explicacao":"Martinho Lutero iniciou a Reforma Protestante ao publicar as 95 Teses em 1517, questionando as praticas da Igreja Catolica, especialmente a venda de indulgencias.","resposta":""},
  {"id":"4454","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Brasil Colonial","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sistema de capitanias hereditarias no Brasil Colonial foi implementado pelo rei portugues:","alternativa_a":"Dom Joao III","alternativa_b":"Dom Pedro I","alternativa_c":"Dom Manuel I","alternativa_d":"Dom Joao VI","alternativa_e":"Dom Sebastiao","resposta_correta":"a","explicacao":"Dom Joao III criou o sistema de capitanias hereditarias em 1534 para colonizar o Brasil, dividindo o territorio em 15 lotes doados a donatarios.","resposta":""},
  {"id":"4455","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"ONU","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Organizacao das Nacoes Unidas (ONU) foi fundada em:","alternativa_a":"1945","alternativa_b":"1919","alternativa_c":"1939","alternativa_d":"1948","alternativa_e":"1950","resposta_correta":"a","explicacao":"A ONU foi fundada em 1945, apos o fim da Segunda Guerra Mundial, com o objetivo de promover a paz, a seguranca e a cooperacao internacional.","resposta":""},
  {"id":"4456","tipo":"multipla","disciplina":"Geografia","tema":"Geologia","subtema":"Placas tectonicas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A teoria das placas tectonicas explica fenomenos como terremotos e vulcanismo. Quem propôs a teoria da deriva continental?","alternativa_a":"Alfred Wegener","alternativa_b":"Charles Darwin","alternativa_c":"Alexander von Humboldt","alternativa_d":"James Hutton","alternativa_e":"Nicolas Steno","resposta_correta":"a","explicacao":"Alfred Wegener propôs a teoria da deriva continental em 1912, base da moderna teoria das placas tectonicas, explicando a movimentacao dos continentes.","resposta":""},
  {"id":"4457","tipo":"multipla","disciplina":"Geografia","tema":"Hidrografia","subtema":"Bacias hidrograficas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A maior bacia hidrografica do mundo em area e a:","alternativa_a":"Bacia Amazonica","alternativa_b":"Bacia do Congo","alternativa_c":"Bacia do Mississippi","alternativa_d":"Bacia do Rio Nilo","alternativa_e":"Bacia do Ob","resposta_correta":"a","explicacao":"A Bacia Amazonica e a maior bacia hidrografica do mundo, com cerca de 6 milhoes de km2, concentrando 20% da agua doce superficial do planeta.","resposta":""},
  {"id":"4458","tipo":"multipla","disciplina":"Geografia","tema":"Populacao","subtema":"Transicao demografica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No modelo de transicao demografica, o estagio em que tanto as taxas de natalidade quanto de mortalidade sao baixas caracteriza:","alternativa_a":"Populacoes desenvolvidas","alternativa_b":"Populacoes em desenvolvimento","alternativa_c":"Populacoes pre-industriais","alternativa_d":"Populacoes em expansao acelerada","alternativa_e":"Populacoes rurais","resposta_correta":"a","explicacao":"No 4o estagio da transicao demografica, ambas as taxas sao baixas, resultando em crescimento vegetativo proximo de zero, tipico de paises desenvolvidos.","resposta":""},
  {"id":"4459","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Pontuacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O ponto e virgula e utilizado principalmente para:","alternativa_a":"Separar oracoes coordenadas que ja contem virgulas internas","alternativa_b":"Indicar pausa curta entre palavras","alternativa_c":"Encerrar um periodo","alternativa_d":"Indicar citacao direta","alternativa_e":"Substituir o ponto final","resposta_correta":"a","explicacao":"O ponto e virgula separa oracoes coordenadas de certa extensao ou que ja possuem virgulas internamente, indicando uma pausa maior que a virgula.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote43.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
