# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4610","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Produtos notaveis","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O resultado de (a + b)^2 e:","alternativa_a":"a^2 + 2ab + b^2","alternativa_b":"a^2 + b^2","alternativa_c":"a^2 - 2ab + b^2","alternativa_d":"a^2 + ab + b^2","alternativa_e":"2a + 2b","resposta_correta":"a","explicacao":"(a+b)^2 = a^2 + 2ab + b^2. Este e um dos produtos notaveis fundamentais.","resposta":""},
  {"id":"4611","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao par e impar","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma funcao e par quando, para todo x do dominio, f(-x) = f(x). Um exemplo de funcao par e:","alternativa_a":"f(x) = x^2","alternativa_b":"f(x) = x^3","alternativa_c":"f(x) = x","alternativa_d":"f(x) = x^5","alternativa_e":"f(x) = sen(x)","resposta_correta":"a","explicacao":"f(x) = x^2: f(-x) = (-x)^2 = x^2 = f(x). Portanto e par. Funcoes par sao simetricas em relacao ao eixo y.","resposta":""},
  {"id":"4612","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Circulo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A area de um circulo de raio 5 cm e: (use pi=3,14)","alternativa_a":"78,5 cm2","alternativa_b":"31,4 cm2","alternativa_c":"157 cm2","alternativa_d":"25 cm2","alternativa_e":"50 cm2","resposta_correta":"a","explicacao":"A = pi*r^2 = 3,14 * 5^2 = 3,14 * 25 = 78,5 cm2.","resposta":""},
  {"id":"4613","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Tangente","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No triangulo retangulo, a tangente de um angulo agudo e definida como:","alternativa_a":"Cateto oposto dividido pelo cateto adjacente","alternativa_b":"Cateto oposto dividido pela hipotenusa","alternativa_c":"Cateto adjacente dividido pela hipotenusa","alternativa_d":"Hipotenusa dividida pelo cateto oposto","alternativa_e":"Hipotenusa dividida pelo cateto adjacente","resposta_correta":"a","explicacao":"tg(θ) = cateto oposto / cateto adjacente. sen(θ) = cateto oposto / hipotenusa. cos(θ) = cateto adjacente / hipotenusa.","resposta":""},
  {"id":"4614","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Eventos independentes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A probabilidade de lancar um dado e obter 6, e em seguida lancar uma moeda e obter cara, e:","alternativa_a":"1/12","alternativa_b":"1/6","alternativa_c":"1/2","alternativa_d":"7/12","alternativa_e":"1/3","resposta_correta":"a","explicacao":"Eventos independentes: P(A e B) = P(A)*P(B) = (1/6)*(1/2) = 1/12.","resposta":""},
  {"id":"4615","tipo":"multipla","disciplina":"Matematica","tema":"Matrizes","subtema":"Matriz inversa","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma matriz quadrada A possui inversa se e somente se:","alternativa_a":"Seu determinante e diferente de zero","alternativa_b":"Seu determinante e zero","alternativa_c":"E uma matriz identidade","alternativa_d":"Todos os elementos sao positivos","alternativa_e":"E uma matriz diagonal","resposta_correta":"a","explicacao":"Uma matriz quadrada possui inversa (e invertivel ou nao-singular) se e somente se seu determinante e diferente de zero.","resposta":""},
  {"id":"4616","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Analitica","subtema":"Parabola","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A parabola y^2 = 4px tem foco em:","alternativa_a":"(p, 0)","alternativa_b":"(0, p)","alternativa_c":"(-p, 0)","alternativa_d":"(0, -p)","alternativa_e":"(2p, 0)","resposta_correta":"a","explicacao":"Para a parabola y^2 = 4px (eixo na horizontal), o foco esta em (p, 0) e a diretriz e x = -p.","resposta":""},
  {"id":"4617","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Arranjo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"De quantas maneiras diferentes podemos dispor 3 objetos distintos retirados de um conjunto de 5?","alternativa_a":"60","alternativa_b":"10","alternativa_c":"20","alternativa_d":"30","alternativa_e":"15","resposta_correta":"a","explicacao":"Arranjo simples: A(5,3) = 5!/(5-3)! = 5!/2! = 120/2 = 60.","resposta":""},
  {"id":"4618","tipo":"multipla","disciplina":"Matematica","tema":"Financeira","subtema":"Porcentagem","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um produto custava R$ 80 e teve um aumento de 15%. Seu novo preco e:","alternativa_a":"R$ 92","alternativa_b":"R$ 95","alternativa_c":"R$ 88","alternativa_d":"R$ 96","alternativa_e":"R$ 85","resposta_correta":"a","explicacao":"Aumento = 80 * 0,15 = 12. Novo preco = 80 + 12 = R$ 92. Ou: 80 * 1,15 = R$ 92.","resposta":""},
  {"id":"4619","tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"MMC e MDC","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O MMC (Minimo Multiplo Comum) de 4 e 6 e:","alternativa_a":"12","alternativa_b":"24","alternativa_c":"2","alternativa_d":"6","alternativa_e":"8","resposta_correta":"a","explicacao":"Multiplos de 4: 4, 8, 12, 16... Multiplos de 6: 6, 12, 18... O menor multiplo comum e 12.","resposta":""},
  {"id":"4620","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Colisao perfeitamente inelastica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na colisao perfeitamente inelastica, os dois corpos ficam unidos apos o impacto. Nesse tipo de colisao:","alternativa_a":"A quantidade de movimento se conserva, mas a energia cinetica nao","alternativa_b":"Ambas se conservam","alternativa_c":"Nenhuma se conserva","alternativa_d":"Apenas a energia cinetica se conserva","alternativa_e":"O momento angular se conserva","resposta_correta":"a","explicacao":"Em toda colisao (incluindo a inelastica), a quantidade de movimento total se conserva (nao ha forcas externas). Porem, na inelastica, parte da energia cinetica e convertida em calor/deformacao.","resposta":""},
  {"id":"4621","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Corrente eletrica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A corrente eletrica e definida como:","alternativa_a":"Carga eletrica por unidade de tempo","alternativa_b":"Tensao por unidade de resistencia","alternativa_c":"Potencia por unidade de tensao","alternativa_d":"Energia por unidade de carga","alternativa_e":"Forca por unidade de carga","resposta_correta":"a","explicacao":"Corrente eletrica I = Q/t (carga em coulombs dividida pelo tempo em segundos). Unidade: Ampere (A).","resposta":""},
  {"id":"4622","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Ciclo de Carnot","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O ciclo de Carnot e composto por quatro processos em sequencia:","alternativa_a":"Expansao isotermica, expansao adiabatica, compressao isotermica e compressao adiabatica","alternativa_b":"Aquecimento isobarico, expansao adiabatica, resfriamento isobarico e compressao adiabatica","alternativa_c":"Expansao isotermica, compressao isotermica, expansao adiabatica e compressao adiabatica","alternativa_d":"Quatro processos isocorricos alternados","alternativa_e":"Dois processos isocorricos e dois adiabáticos","resposta_correta":"a","explicacao":"O ciclo de Carnot consiste em: 1) expansao isotermica (absorve Q_h), 2) expansao adiabatica, 3) compressao isotermica (libera Q_c), 4) compressao adiabatica.","resposta":""},
  {"id":"4623","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Transformadores","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Em um transformador ideal, a relacao entre tensoes e numero de espiras e:","alternativa_a":"V1/V2 = N1/N2","alternativa_b":"V1/V2 = N2/N1","alternativa_c":"V1*V2 = N1*N2","alternativa_d":"V1+V2 = N1+N2","alternativa_e":"V1/N1 = V2*N2","resposta_correta":"a","explicacao":"No transformador ideal: V1/V2 = N1/N2 (proporcao direta entre tensao e numero de espiras). Para potencia: V1*I1 = V2*I2.","resposta":""},
  {"id":"4624","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Forca centripeta","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um objeto em MCU de raio R com velocidade angular w experimenta uma aceleracao centripeta de:","alternativa_a":"w^2 * R","alternativa_b":"w * R","alternativa_c":"w^2 / R","alternativa_d":"R / w^2","alternativa_e":"2*w*R","resposta_correta":"a","explicacao":"A aceleracao centripeta e ac = w^2 * R = v^2/R, dirigida para o centro da circunferencia.","resposta":""},
  {"id":"4625","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Difracao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A difracao da luz e o fenomeno pelo qual a luz:","alternativa_a":"Contorna obstaculos e se propaga por frestas","alternativa_b":"Muda de direcao ao mudar de meio","alternativa_c":"Volta ao meio de origem","alternativa_d":"Divide-se em componentes de frequencias diferentes","alternativa_e":"E absorvida pelo obstáculo","resposta_correta":"a","explicacao":"A difracao e o fenomeno pelo qual ondas (incluindo a luz) contornam obstaculos ou se espalham ao passar por aberturas. Evidencia o comportamento ondulatorio da luz.","resposta":""},
  {"id":"4626","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Leis de Newton - 3a lei","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A 3a Lei de Newton (acao e reacao) afirma que:","alternativa_a":"Para toda acao ha uma reacao igual e oposta","alternativa_b":"Forca = massa x aceleracao","alternativa_c":"Corpos em repouso tendem a permanecer em repouso","alternativa_d":"Trabalho = forca x deslocamento","alternativa_e":"Energia e sempre conservada","resposta_correta":"a","explicacao":"3a Lei de Newton: se um corpo A exerce uma forca sobre B, entao B exerce uma forca de igual modulo, mesma direcao e sentido oposto sobre A (par acao-reacao).","resposta":""},
  {"id":"4627","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Condutividade termica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Entre os metais, o melhor condutor de calor e:","alternativa_a":"Prata","alternativa_b":"Ouro","alternativa_c":"Cobre","alternativa_d":"Ferro","alternativa_e":"Aluminio","resposta_correta":"a","explicacao":"A prata e o melhor condutor termico entre os metais (condutividade termica ≈ 429 W/m.K), seguida pelo cobre (385 W/m.K) e ouro (314 W/m.K).","resposta":""},
  {"id":"4628","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Semicondutores","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Os transistores sao fabricados com materiais semicondutores como:","alternativa_a":"Silicio e germanio","alternativa_b":"Cobre e aluminio","alternativa_c":"Ouro e prata","alternativa_d":"Ferro e niquel","alternativa_e":"Sodio e cloro","resposta_correta":"a","explicacao":"Silicio (Si) e germanio (Ge) sao os semicondutores mais usados na eletronica. O silicio e o principal, base de chips, transistores e circuitos integrados.","resposta":""},
  {"id":"4629","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Grandezas escalares e vetoriais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual das seguintes grandezas e escalar (nao tem direcao)?","alternativa_a":"Temperatura","alternativa_b":"Forca","alternativa_c":"Velocidade","alternativa_d":"Aceleracao","alternativa_e":"Deslocamento","resposta_correta":"a","explicacao":"Grandezas escalares (apenas modulo): temperatura, massa, volume, energia, tempo, pressao. Grandezas vetoriais (modulo + direcao + sentido): forca, velocidade, aceleracao, deslocamento.","resposta":""},
  {"id":"4630","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Hidrocarbonetos aromaticos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O naftaleno, presente em naftalina, e um hidrocarboneto aromatico policiclico formado por dois aneis de benzeno. Sua formula e:","alternativa_a":"C10H8","alternativa_b":"C6H6","alternativa_c":"C8H8","alternativa_d":"C12H10","alternativa_e":"C10H6","resposta_correta":"a","explicacao":"O naftaleno tem formula C10H8, formado por dois aneis benzenicos fundidos. E o principal componente da naftalina (repelente de traças).","resposta":""},
  {"id":"4631","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Solubilidade","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O principio 'semelhante dissolve semelhante' significa que:","alternativa_a":"Solventes polares dissolvem solutos polares","alternativa_b":"Acidos dissolvem bases","alternativa_c":"Solucoes saturadas dissolvem mais soluto","alternativa_d":"O calor aumenta a dissolucao","alternativa_e":"A pressao aumenta a solubilidade","resposta_correta":"a","explicacao":"Substancias polares se dissolvem em solventes polares (ex.: NaCl em agua) e substancias apolares em solventes apolares (ex.: gordura em benzeno). 'Like dissolves like'.","resposta":""},
  {"id":"4632","tipo":"multipla","disciplina":"Quimica","tema":"Bioquimica","subtema":"DNA e RNA","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A base nitrogenada presente no RNA mas ausente no DNA e o:","alternativa_a":"Uracil","alternativa_b":"Timina","alternativa_c":"Guanina","alternativa_d":"Citosina","alternativa_e":"Adenina","resposta_correta":"a","explicacao":"O RNA contem uracil (U) no lugar da timina (T). Ambos tem adenina, guanina e citosina. No DNA: A-T e G-C. No RNA: A-U e G-C.","resposta":""},
  {"id":"4633","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Saponificacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A saponificacao e a reacao de producao de sabao a partir de gordura (ester) com:","alternativa_a":"Base forte (NaOH ou KOH)","alternativa_b":"Acido forte","alternativa_c":"Agua quente","alternativa_d":"Alcool","alternativa_e":"Enzimas","resposta_correta":"a","explicacao":"A saponificacao e a reacao de hidrolise basica de gorduras (triglicerideos): gordura + NaOH -> glicerol + sabao (sal de acido graxo).","resposta":""},
  {"id":"4634","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Hidroxidos","dificuldide":"Facil","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O hidroxido de sodio (NaOH) e popularmente conhecido como:","alternativa_a":"Soda caustica","alternativa_b":"Cal virgem","alternativa_c":"Agua sanitaria","alternativa_d":"Agua-forte","alternativa_e":"Barrilha","resposta_correta":"a","explicacao":"O NaOH (hidroxido de sodio) e a soda caustica, base forte amplamente usada na industria, em saponificacao e como desentupidor.","resposta":""},
  {"id":"4635","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Descarte de residuos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O descarte inadequado de baterias e pilhas causa poluicao por metais pesados como mercurio, cadmio e chumbo. Qual a forma correta de descarte?","alternativa_a":"Pontos de coleta especializados","alternativa_b":"Lixo organico","alternativa_c":"Lixo comum","alternativa_d":"Esgoto sanitario","alternativa_e":"Queima a ceu aberto","resposta_correta":"a","explicacao":"Baterias e pilhas devem ser descartadas em pontos de coleta especializados (estabelecimentos comerciais ou postos de coleta), pois contem metais toxicos que contaminam o solo e a agua.","resposta":""},
  {"id":"4636","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Gases nobres","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os gases nobres (grupo 18) sao quimicamente inertes porque:","alternativa_a":"Possuem a camada de valencia completa","alternativa_b":"Sao muito pesados","alternativa_c":"Nao possuem eletrons","alternativa_d":"Tem alta eletronegatividade","alternativa_e":"Existem apenas como atomos isolados","resposta_correta":"a","explicacao":"Gases nobres (He, Ne, Ar, Kr, Xe, Rn) tem 8 eletrons na camada de valencia (exceto He, com 2), configuracao estavel que nao favorece reacoes quimicas.","resposta":""},
  {"id":"4637","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Polimeros sinteticos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O nylon e um polimero sintetico classificado como:","alternativa_a":"Poliamida","alternativa_b":"Poliester","alternativa_c":"Polietileno","alternativa_d":"Polipropileno","alternativa_e":"Policarbonato","resposta_correta":"a","explicacao":"O nylon e uma poliamida sintetica: seus monomeros sao unidos por ligacoes amida (-CO-NH-). Foi o primeiro polimero sintetico a ser produzido industrialmente (DuPont, 1935).","resposta":""},
  {"id":"4638","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Reacoes de reducao e oxidacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na reacao Fe + CuSO4 -> FeSO4 + Cu, o ferro e:","alternativa_a":"Oxidado (agente redutor)","alternativa_b":"Reduzido (agente oxidante)","alternativa_c":"Nao participa da reacao redox","alternativa_d":"Catalisador","alternativa_e":"Produto","resposta_correta":"a","explicacao":"Fe perde eletrons (Fe -> Fe^2+ + 2e-): e oxidado. O agente redutor e o que cede eletrons e se oxida. O cobre (Cu^2+) ganha eletrons e e reduzido.","resposta":""},
  {"id":"4639","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Isomeria","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A isomeria geometrica cis-trans ocorre em compostos com:","alternativa_a":"Dupla ligacao e substituintes diferentes nos carbonos sp2","alternativa_b":"Carbono quiral","alternativa_c":"Aneis ciclicos","alternativa_d":"Ligacoes triplas","alternativa_e":"Heteroatomos","resposta_correta":"a","explicacao":"A isomeria geometrica (cis-trans ou Z/E) ocorre em alcenos com dois substituintes diferentes em cada carbono da dupla ligacao, impedindo a rotacao livre.","resposta":""},
  {"id":"4640","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Respiracao celular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo que produz a maior quantidade de ATP na respiracao celular aerobica e:","alternativa_a":"Fosforilacao oxidativa (cadeia respiratoria)","alternativa_b":"Glicólise","alternativa_c":"Ciclo de Krebs","alternativa_d":"Fermentacao lactica","alternativa_e":"Fotossintese","resposta_correta":"a","explicacao":"A fosforilacao oxidativa (cadeia de transporte de eletrons) na membrana interna da mitocondria e responsavel por cerca de 32-34 dos 36-38 ATP gerados na respiracao aerobica.","resposta":""},
  {"id":"4641","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Projeto Genoma","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Projeto Genoma Humano (concluido em 2003) sequenciou todo o DNA humano e revelou que o numero aproximado de genes e:","alternativa_a":"Cerca de 20-25 mil genes","alternativa_b":"Cerca de 100 mil genes","alternativa_c":"Cerca de 3 bilhoes de genes","alternativa_d":"Apenas 1.000 genes","alternativa_e":"Cerca de 3 mil genes","resposta_correta":"a","explicacao":"O Projeto Genoma revelou que humanos tem cerca de 20-25 mil genes codificantes de proteinas (muito menos que o esperado), num genoma com 3 bilhoes de pares de bases.","resposta":""},
  {"id":"4642","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Desequilibrio ecologico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A introducao de especies exoticas em novos habitats pode causar desequilibrio ecologico porque:","alternativa_a":"Podem se tornar invasoras, competindo com especies nativas","alternativa_b":"Sempre sao extintas rapidamente","alternativa_c":"Melhoram a biodiversidade local","alternativa_d":"Sao imunes a predadores","alternativa_e":"Nao interagem com especies locais","resposta_correta":"a","explicacao":"Especies exoticas invasoras podem causar graves desequilibrios: competem com especies nativas por recursos, predam-nas, transmitem doencas ou alteram habitats.","resposta":""},
  {"id":"4643","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema osmoregulacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O hormonio ADH (hormonio antidiuretico) atua nos tubulos renais para:","alternativa_a":"Aumentar a reabsorcao de agua","alternativa_b":"Aumentar a eliminacao de sodio","alternativa_c":"Diminuir a filtracao glomerular","alternativa_d":"Estimular a producao de urina diluida","alternativa_e":"Reduzir a pressao arterial","resposta_correta":"a","explicacao":"O ADH (vasopressina) e produzido pela hipofise e age nos tubulos coletores renais, aumentando a permeabilidade a agua, o que aumenta a reabsorcao de agua e concentra a urina.","resposta":""},
  {"id":"4644","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Especiacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A especiacao alopatrica ocorre quando:","alternativa_a":"Populacoes sao separadas por barreiras geograficas","alternativa_b":"Duas populacoes se separam no mesmo territorio","alternativa_c":"A mutacao e o unico mecanismo envolvido","alternativa_d":"Especies se hibridizam","alternativa_e":"A selecao artificial e aplicada","resposta_correta":"a","explicacao":"Especiacao alopatrica: populacoes se tornam geograficamente isoladas, evoluem independentemente e eventualmente acumulam diferencas suficientes para nao mais se reproduzir entre si.","resposta":""},
  {"id":"4645","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Gimnospermas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O pinheiro-do-parana (Araucaria angustifolia) e uma gimnosperma. As sementes das gimnospermas estao:","alternativa_a":"Nuas, nao envolvidas pelo fruto","alternativa_b":"Dentro do fruto","alternativa_c":"Nas flores","alternativa_d":"Nas folhas","alternativa_e":"No caule","resposta_correta":"a","explicacao":"Gimnospermas (pinheiros, ciprestes, ginkgo) tem sementes 'nuas', nao protegidas por fruto. O nome vem do grego: gymnos = nu, sperma = semente.","resposta":""},
  {"id":"4646","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema muscular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A proteina responsavel pela contracao muscular, que desliza sobre a actina, e a:","alternativa_a":"Miosina","alternativa_b":"Queratina","alternativa_c":"Colágeno","alternativa_d":"Elastina","alternativa_e":"Troponina","resposta_correta":"a","explicacao":"Na contracao muscular (teoria dos filamentos deslizantes), as cabecas de miosina se ligam a actina e deslizam, encurtando o sarcômero. A miosina e o motor molecular.","resposta":""},
  {"id":"4647","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Bioma Mata Atlantica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Mata Atlantica e considerada um dos biomas mais ameacados do mundo. Qual percentual de sua cobertura original foi preservada?","alternativa_a":"Cerca de 12-15%","alternativa_b":"Cerca de 50%","alternativa_c":"Cerca de 80%","alternativa_d":"Menos de 1%","alternativa_e":"Cerca de 30%","resposta_correta":"a","explicacao":"A Mata Atlantica perdeu cerca de 85-88% de sua cobertura original por desmatamento. Restam fragmentos de 12-15%, concentrados no SE e Sul do Brasil, ainda com alta biodiversidade.","resposta":""},
  {"id":"4648","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Bandeirantismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As bandeiras de apresamento, que percorreram o interior do Brasil no seculo XVII, tinham como objetivo principal:","alternativa_a":"Capturar indigenas para escravidao","alternativa_b":"Encontrar ouro e pedras preciosas","alternativa_c":"Fundar missoes jesuiticas","alternativa_d":"Combater invasores estrangeiros","alternativa_e":"Cartografar o territorio","resposta_correta":"a","explicacao":"As bandeiras de apresamento (sec. XVII) saiam de Sao Paulo para capturar indigenas das missoes jesuiticas e aldeias para trabalho escravo nas fazendas paulistas.","resposta":""},
  {"id":"4649","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Iluminismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Iluminismo do seculo XVIII defendia a supremacia da:","alternativa_a":"Razao","alternativa_b":"Fe","alternativa_c":"Tradicao","alternativa_d":"Nobreza","alternativa_e":"Revelacao divina","resposta_correta":"a","explicacao":"O Iluminismo (Seculo das Luzes) colocava a razao humana como instrumento supremo de conhecimento e transformacao social, criticando o absolutismo, a Igreja e a superstição.","resposta":""},
  {"id":"4650","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Imperialismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O imperialismo do final do seculo XIX foi motivado, entre outros fatores, pela necessidade de:","alternativa_a":"Matérias-primas e novos mercados consumidores","alternativa_b":"Missoes religiosas em outros continentes","alternativa_c":"Refugio para populacoes excedentes","alternativa_d":"Expansao territorial por motivos culturais","alternativa_e":"Controle das rotas de peregrinacao","resposta_correta":"a","explicacao":"O imperialismo foi impulsionado pelo capitalismo industrial: necessidade de materias-primas para as industrias, mercados consumidores para produtos manufaturados e investimentos de capital.","resposta":""},
  {"id":"4651","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Vargas - Era Democratica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Getulio Vargas retornou ao poder em 1950 pelo voto popular. Seu segundo governo foi marcado pela criacao de:","alternativa_a":"Petrobras","alternativa_b":"BNDES","alternativa_c":"Vale do Rio Doce","alternativa_d":"Embraer","alternativa_e":"CSN","resposta_correta":"a","explicacao":"No segundo governo Vargas (1951-1954), foi criada a Petrobras (1953), sob o lema 'O petroleo e nosso', representando o projeto nacionalista e desenvolvimentista de Vargas.","resposta":""},
  {"id":"4652","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Descolonizacao asiatica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A India conquistou sua independencia do dominio britanico em 1947, liderada por:","alternativa_a":"Mahatma Gandhi e Jawaharlal Nehru","alternativa_b":"Muhammad Ali Jinnah e Nehru","alternativa_c":"Jawaharlal Nehru e Indira Gandhi","alternativa_d":"Subhas Chandra Bose e Gandhi","alternativa_e":"Nehru e Ho Chi Minh","resposta_correta":"a","explicacao":"A independencia da India foi resultado da luta de Mahatma Gandhi (resistencia nao-violenta, satyagraha) e Jawaharlal Nehru (primeiro Primeiro-Ministro da India independente).","resposta":""},
  {"id":"4653","tipo":"multipla","disciplina":"Geografia","tema":"Industria","subtema":"Revolucao Industrial","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Primeira Revolucao Industrial teve inicio no seculo XVIII em:","alternativa_a":"Inglaterra","alternativa_b":"Franca","alternativa_c":"Alemanha","alternativa_d":"Estados Unidos","alternativa_e":"Italia","resposta_correta":"a","explicacao":"A Primeira Revolucao Industrial iniciou-se na Inglaterra no seculo XVIII, com a substituicao do trabalho artesanal pela maquina a vapor e producao em escala fabril.","resposta":""},
  {"id":"4654","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Terrorismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O atentado de 11 de setembro de 2001 em Nova York desencadeou um novo ciclo de politica externa americana, com a chamada 'Guerra ao Terror'. Qual pais foi invadido em seguida?","alternativa_a":"Afeganistao","alternativa_b":"Iraque","alternativa_c":"Siria","alternativa_d":"Irao","alternativa_e":"Arabia Saudita","resposta_correta":"a","explicacao":"Apos o 11/09/2001, os EUA invadiram o Afeganistao em outubro de 2001 para destruir o Al-Qaeda e o regime taliba que o abrigava. O Iraque foi invadido em 2003.","resposta":""},
  {"id":"4655","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Primate city","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'cidade primaz' (primate city) refere-se a uma cidade que:","alternativa_a":"Domina desproporcionalmente a rede urbana nacional","alternativa_b":"Tem a maior area territorial do pais","alternativa_c":"E a capital politica do pais","alternativa_d":"Foi fundada primeiro no territorio","alternativa_e":"Tem maior numero de monumentos historicos","resposta_correta":"a","explicacao":"Cidade primaz (Mark Jefferson, 1939) e a cidade que domina desproporcionalmente a rede urbana, sendo muito maior que as demais em populacao, economia e funcoes. Ex.: Paris, Buenos Aires.","resposta":""},
  {"id":"4656","tipo":"multipla","disciplina":"Geografia","tema":"Agua","subtema":"Escassez hidrica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Apesar de o Brasil possuir a maior reserva de agua doce do mundo, enfrenta problemas de escassez em:","alternativa_a":"Nordeste semiárido","alternativa_b":"Regiao Amazonica","alternativa_c":"Pantanal","alternativa_d":"Sul do pais","alternativa_e":"Rio Grande do Sul","resposta_correta":"a","explicacao":"O Nordeste semiárido (poligono das secas) sofre com escassez hidrica estrutural, com precipitacoes irregulares, alta evaporacao e baixa disponibilidade de agua superficial.","resposta":""},
  {"id":"4657","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Paralelismo sintático","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O paralelismo sintatico exige que elementos coordenados pertencam a:","alternativa_a":"Mesma classe gramatical ou estrutura sintatica","alternativa_b":"Campos semanticos diferentes","alternativa_c":"Periodos distintos","alternativa_d":"Ordens inversas de sujeito e predicado","alternativa_e":"Vozes verbais opostas","resposta_correta":"a","explicacao":"O paralelismo sintatico e um principio de harmonia estrutural: elementos coordenados devem ter a mesma funcao e estrutura. Ex.: 'Gosto de nadar, correr e pedalar' (3 verbos no infinitivo).","resposta":""},
  {"id":"4658","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia da Linguagem","subtema":"Wittgenstein","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Ludwig Wittgenstein, em seu Tractatus Logico-Philosophicus, afirma que 'os limites da minha linguagem sao os limites do meu mundo'. Essa proposicao sugere que:","alternativa_a":"O que nao pode ser dito nao pode ser pensado","alternativa_b":"Linguagem e realidade sao independentes","alternativa_c":"A logica nao se aplica a linguagem ordinaria","alternativa_d":"A matematica explica toda a linguagem","alternativa_e":"As emocoes transcendem a linguagem logica","resposta_correta":"a","explicacao":"Para Wittgenstein no Tractatus, a linguagem e a representacao logica do mundo. O que nao pode ser representado na linguagem nao pode ser pensado ou expresso com sentido.","resposta":""},
  {"id":"4659","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Interacionismo simbolico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O interacionismo simbolico, desenvolvido por George Herbert Mead e Herbert Blumer, estuda:","alternativa_a":"Como os individuos criam significados atraves da interacao social","alternativa_b":"As estruturas macrossociais de dominacao","alternativa_c":"Os efeitos economicos sobre a cultura","alternativa_d":"A biologizacao do comportamento social","alternativa_e":"Os conflitos entre classes sociais","resposta_correta":"a","explicacao":"O interacionismo simbolico foca nos significados que os individuos atribuem as suas acoes e interacoes cotidianas, e como esses significados sao criados e modificados socialmente.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote47.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
