# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4510","tipo":"multipla","disciplina":"Matematica","tema":"Conjuntos","subtema":"Operacoes com conjuntos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Dados A = {1, 2, 3, 4} e B = {3, 4, 5, 6}, o conjunto A ∩ B (interseccao) e:","alternativa_a":"{3, 4}","alternativa_b":"{1, 2, 5, 6}","alternativa_c":"{1, 2, 3, 4, 5, 6}","alternativa_d":"{1, 2}","alternativa_e":"{5, 6}","resposta_correta":"a","explicacao":"A interseccao de A e B contem apenas os elementos comuns a ambos: A ∩ B = {3, 4}.","resposta":""},
  {"id":"4511","tipo":"multipla","disciplina":"Matematica","tema":"Numeros Reais","subtema":"Potenciacao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O valor de 2^(-3) e:","alternativa_a":"1/8","alternativa_b":"-8","alternativa_c":"1/6","alternativa_d":"-6","alternativa_e":"8","resposta_correta":"a","explicacao":"2^(-3) = 1/2^3 = 1/8.","resposta":""},
  {"id":"4512","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Semelhanca de triangulos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Dois triangulos semelhantes possuem lados 3 e 6 no primeiro e 5 e x no segundo. O valor de x e:","alternativa_a":"10","alternativa_b":"8","alternativa_c":"12","alternativa_d":"15","alternativa_e":"6","resposta_correta":"a","explicacao":"Pela proporcionalidade dos lados: 3/5 = 6/x. Logo x = 6*5/3 = 10.","resposta":""},
  {"id":"4513","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Dominio e imagem","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O dominio da funcao f(x) = sqrt(x - 2) e:","alternativa_a":"x >= 2","alternativa_b":"x > 2","alternativa_c":"x <= 2","alternativa_d":"x > 0","alternativa_e":"Todos os reais","resposta_correta":"a","explicacao":"Para que a raiz seja real, o radicando deve ser nao-negativo: x - 2 >= 0, logo x >= 2.","resposta":""},
  {"id":"4514","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Circunferencia trigonometrica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No 2o quadrante, o seno e:","alternativa_a":"Positivo","alternativa_b":"Negativo","alternativa_c":"Zero","alternativa_d":"Indefinido","alternativa_e":"Igual ao coseno","resposta_correta":"a","explicacao":"No 2o quadrante (entre 90 e 180 graus): seno e positivo, coseno e negativo, tangente e negativa.","resposta":""},
  {"id":"4515","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Combinacao simples","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O numero de comissoes de 3 pessoas escolhidas de um grupo de 5 pessoas e:","alternativa_a":"10","alternativa_b":"15","alternativa_c":"20","alternativa_d":"60","alternativa_e":"6","resposta_correta":"a","explicacao":"C(5,3) = 5!/(3!*2!) = 120/(6*2) = 120/12 = 10.","resposta":""},
  {"id":"4516","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Prisma","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O volume de um prisma de base triangular com area da base 12 cm2 e altura 5 cm e:","alternativa_a":"60 cm3","alternativa_b":"30 cm3","alternativa_c":"120 cm3","alternativa_d":"24 cm3","alternativa_e":"36 cm3","resposta_correta":"a","explicacao":"Volume do prisma = Area da base * altura = 12 * 5 = 60 cm3.","resposta":""},
  {"id":"4517","tipo":"multipla","disciplina":"Matematica","tema":"Inequacoes","subtema":"Inequacao de 1o grau","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A solucao de 3x - 6 > 0 e:","alternativa_a":"x > 2","alternativa_b":"x < 2","alternativa_c":"x > -2","alternativa_d":"x >= 2","alternativa_e":"x < -2","resposta_correta":"a","explicacao":"3x > 6, logo x > 2.","resposta":""},
  {"id":"4518","tipo":"multipla","disciplina":"Matematica","tema":"Matrizes","subtema":"Multiplicacao de matrizes","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O produto das matrizes [[1,2],[3,4]] e [[5],[6]] resulta em:","alternativa_a":"[[17],[39]]","alternativa_b":"[[5,12],[15,24]]","alternativa_c":"[[11],[27]]","alternativa_d":"[[17,12],[39,24]]","alternativa_e":"[[5],[6]]","resposta_correta":"a","explicacao":"[1*5+2*6] = [17] e [3*5+4*6] = [15+24] = [39]. Resultado: [[17],[39]].","resposta":""},
  {"id":"4519","tipo":"multipla","disciplina":"Matematica","tema":"Financeira","subtema":"Juros simples","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um capital de R$ 2.000 a uma taxa de 5% ao mes por 3 meses em juros simples gera juro de:","alternativa_a":"R$ 300","alternativa_b":"R$ 315,25","alternativa_c":"R$ 200","alternativa_d":"R$ 500","alternativa_e":"R$ 100","resposta_correta":"a","explicacao":"J = C*i*t = 2000 * 0,05 * 3 = R$ 300.","resposta":""},
  {"id":"4520","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica Quantica","subtema":"Dualidade onda-particula","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O efeito fotoeletrico demonstrou que a luz possui comportamento de:","alternativa_a":"Particula (foton)","alternativa_b":"Apenas onda","alternativa_c":"Gas ideal","alternativa_d":"Fluido viscoso","alternativa_e":"Campo magnetico","resposta_correta":"a","explicacao":"Einstein explicou o efeito fotoeletrico em 1905 propondo que a luz e composta por quantos de energia (fotons), demonstrando seu comportamento de particula. Isso lhe rendeu o Premio Nobel.","resposta":""},
  {"id":"4521","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Primeira lei","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A primeira lei da termodinamica estabelece que a variacao de energia interna de um sistema e igual a:","alternativa_a":"Calor absorvido menos trabalho realizado","alternativa_b":"Calor absorvido mais trabalho realizado","alternativa_c":"Trabalho realizado menos calor absorvido","alternativa_d":"Entropia vezes temperatura","alternativa_e":"Massa vezes calor especifico","resposta_correta":"a","explicacao":"1a lei da termodinamica: DeltaU = Q - W. A variacao de energia interna e igual ao calor absorvido menos o trabalho realizado pelo sistema.","resposta":""},
  {"id":"4522","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Lentes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As lentes convergentes (convexas) sao usadas para corrigir qual defeito visual?","alternativa_a":"Hipermetropia","alternativa_b":"Miopia","alternativa_c":"Astigmatismo","alternativa_d":"Presbiopia","alternativa_e":"Daltonismo","resposta_correta":"a","explicacao":"A hipermetropia (dificuldade de enxergar de perto) e corrigida com lentes convergentes (convexas), que aumentam a convergencia do sistema ocular.","resposta":""},
  {"id":"4523","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Campo eletrico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O campo eletrico criado por uma carga puntiforme Q a uma distancia r e dado por:","alternativa_a":"E = kQ/r^2","alternativa_b":"E = kQ/r","alternativa_c":"E = kQr","alternativa_d":"E = kQ^2/r","alternativa_e":"E = Q/kr","resposta_correta":"a","explicacao":"O campo eletrico de uma carga puntiforme e E = kQ/r^2, onde k e a constante eletrostatica (9x10^9 N.m^2/C^2).","resposta":""},
  {"id":"4524","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"MRU","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"No Movimento Retilineo Uniforme (MRU), a aceleracao e:","alternativa_a":"Zero","alternativa_b":"Constante e positiva","alternativa_c":"Constante e negativa","alternativa_d":"Variavel","alternativa_e":"Igual a g","resposta_correta":"a","explicacao":"No MRU, a velocidade e constante, portanto a aceleracao e zero. Nao ha variacao de velocidade.","resposta":""},
  {"id":"4525","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Som","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"As ondas sonoras sao ondas:","alternativa_a":"Mecanicas longitudinais","alternativa_b":"Eletromagneticas transversais","alternativa_c":"Mecanicas transversais","alternativa_d":"Eletromagneticas longitudinais","alternativa_e":"Gravitacionais","resposta_correta":"a","explicacao":"O som e uma onda mecanica (necessita de meio material) e longitudinal (a perturbacao ocorre na mesma direcao da propagacao).","resposta":""},
  {"id":"4526","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Escalas termometricas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A temperatura de 100 oC em Kelvin equivale a:","alternativa_a":"373 K","alternativa_b":"273 K","alternativa_c":"100 K","alternativa_d":"473 K","alternativa_e":"173 K","resposta_correta":"a","explicacao":"Conversao: K = oC + 273. Logo 100 oC = 100 + 273 = 373 K.","resposta":""},
  {"id":"4527","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Corrente alternada","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A frequencia da corrente eletrica alternada na rede domestica brasileira e:","alternativa_a":"60 Hz","alternativa_b":"50 Hz","alternativa_c":"100 Hz","alternativa_d":"120 Hz","alternativa_e":"220 Hz","resposta_correta":"a","explicacao":"No Brasil, a frequencia da corrente alternada na rede eletrica e 60 Hz (60 ciclos por segundo). Na Europa a frequencia e 50 Hz.","resposta":""},
  {"id":"4528","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica dos Fluidos","subtema":"Pressao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A pressao e definida como a razao entre a forca e:","alternativa_a":"Area","alternativa_b":"Volume","alternativa_c":"Massa","alternativa_d":"Velocidade","alternativa_e":"Temperatura","resposta_correta":"a","explicacao":"Pressao P = F/A (forca dividida pela area). Unidade no SI: pascal (Pa = N/m^2).","resposta":""},
  {"id":"4529","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Velocidade da luz","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A velocidade da luz no vacuo e aproximadamente:","alternativa_a":"3 x 10^8 m/s","alternativa_b":"3 x 10^6 m/s","alternativa_c":"3 x 10^10 m/s","alternativa_d":"3 x 10^4 m/s","alternativa_e":"343 m/s","resposta_correta":"a","explicacao":"A velocidade da luz no vacuo (c) e aproximadamente 3 x 10^8 m/s = 300.000 km/s.","resposta":""},
  {"id":"4530","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Esteres","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de esterificacao ocorre entre um acido carboxilico e:","alternativa_a":"Um alcool","alternativa_b":"Uma base","alternativa_c":"Um aldeido","alternativa_d":"Uma amina","alternativa_e":"Um alcano","resposta_correta":"a","explicacao":"Esterificacao: acido carboxilico + alcool -> ester + agua. Ex.: CH3COOH + CH3OH -> CH3COOCH3 + H2O (acetato de metila).","resposta":""},
  {"id":"4531","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Aminas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As aminas sao derivados organicos da:","alternativa_a":"Amonia (NH3)","alternativa_b":"Agua (H2O)","alternativa_c":"Amido","alternativa_d":"Aminoxido","alternativa_e":"Urea","resposta_correta":"a","explicacao":"Aminas sao compostos organicos derivados da amonia (NH3), em que um ou mais hidrogenios sao substituidos por grupos organicos (R-NH2, R2NH, R3N).","resposta":""},
  {"id":"4532","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Reacoes de precipitacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Ao adicionar solucao de AgNO3 a uma solucao de NaCl, forma-se um precipitado branco de:","alternativa_a":"AgCl","alternativa_b":"NaNO3","alternativa_c":"AgNO2","alternativa_d":"NaCl2","alternativa_e":"Ag2Cl","resposta_correta":"a","explicacao":"A reacao e: AgNO3 + NaCl -> AgCl(precipitado) + NaNO3. O cloreto de prata (AgCl) e um precipitado branco insolúvel em agua.","resposta":""},
  {"id":"4533","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Propriedades periodicas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A eletronegatividade de um elemento aumenta ao longo de um periodo da tabela periodica da esquerda para a direita porque:","alternativa_a":"O numero de protons aumenta sem aumentar as camadas eletronicas","alternativa_b":"O raio atomico aumenta","alternativa_c":"O numero de eletrons de valencia diminui","alternativa_d":"A massa atomica diminui","alternativa_e":"O numero de neutrons diminui","resposta_correta":"a","explicacao":"Ao longo de um periodo, o numero atomico (protons) aumenta, aumentando a atracao do nucleo pelos eletrons, mas o numero de camadas nao muda, logo a eletronegatividade aumenta.","resposta":""},
  {"id":"4534","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Geometria molecular","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A molecula de agua (H2O) tem geometria:","alternativa_a":"Angular","alternativa_b":"Linear","alternativa_c":"Trigonal plana","alternativa_d":"Tetraedrica","alternativa_e":"Piramidal","resposta_correta":"a","explicacao":"A agua tem geometria angular (em V) devido aos 2 pares de eletrons nao-ligantes no oxigenio, que repelem as ligacoes O-H, resultando em angulo de 104,5 graus.","resposta":""},
  {"id":"4535","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Camada de ozonio","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A destruicao da camada de ozonio esta associada principalmente a emissao de:","alternativa_a":"CFC (clorofluorcarbonetos)","alternativa_b":"CO2","alternativa_c":"SO2","alternativa_d":"CH4","alternativa_e":"NOx","resposta_correta":"a","explicacao":"Os CFCs, usados em refrigeradores e sprays, liberam cloro na estratosfera que catalisa a destruicao do ozonio. O Protocolo de Montreal (1987) baniu seu uso.","resposta":""},
  {"id":"4536","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Cetonas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As cetonas possuem o grupo funcional carbonila entre dois radicais organicos. A acetona (propanona) tem formula:","alternativa_a":"CH3-CO-CH3","alternativa_b":"CH3-CHO","alternativa_c":"CH3-COOH","alternativa_d":"CH3-O-CH3","alternativa_e":"CH3-COO-CH3","resposta_correta":"a","explicacao":"A acetona (propanona) e CH3-CO-CH3. E a cetona mais simples, com o grupo carbonila (C=O) entre dois grupos metila.","resposta":""},
  {"id":"4537","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Balanceamento","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na reacao balanceada 2H2 + O2 -> 2H2O, a razao molar entre H2 e H2O e:","alternativa_a":"1:1","alternativa_b":"2:1","alternativa_c":"1:2","alternativa_d":"2:3","alternativa_e":"3:2","resposta_correta":"a","explicacao":"Na equacao 2H2 + O2 -> 2H2O, para cada 2 mols de H2 formam-se 2 mols de H2O. Portanto a razao H2:H2O = 2:2 = 1:1.","resposta":""},
  {"id":"4538","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Aldeidos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O formol (metanal) e uma solucao aquosa de um aldeido. Sua formula e:","alternativa_a":"HCHO","alternativa_b":"CH3CHO","alternativa_c":"C2H5OH","alternativa_d":"HCOOH","alternativa_e":"CH3OH","resposta_correta":"a","explicacao":"O metanal (formaldeido/formol) tem formula HCHO (H-CHO). E o aldeido mais simples, com o grupo -CHO ligado a hidrogenio.","resposta":""},
  {"id":"4539","tipo":"multipla","disciplina":"Quimica","tema":"Termodinamica Quimica","subtema":"Energia de ativacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Os catalisadores aumentam a velocidade de uma reacao quimica ao:","alternativa_a":"Diminuir a energia de ativacao","alternativa_b":"Aumentar a temperatura do sistema","alternativa_c":"Aumentar a concentracao dos reagentes","alternativa_d":"Modificar o DH da reacao","alternativa_e":"Aumentar a pressao","resposta_correta":"a","explicacao":"Os catalisadores oferecem um caminho reacional alternativo com menor energia de ativacao, aumentando a velocidade sem ser consumidos.","resposta":""},
  {"id":"4540","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema endocrino","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O hormonio insulina, produzido pelo pancreas, tem como funcao principal:","alternativa_a":"Diminuir a glicemia (glicose no sangue)","alternativa_b":"Aumentar a glicemia","alternativa_c":"Regular a frequencia cardiaca","alternativa_d":"Controlar a pressao arterial","alternativa_e":"Regular o crescimento osseo","resposta_correta":"a","explicacao":"A insulina e produzida pelas celulas beta das ilhotas de Langerhans do pancreas e diminui a glicemia, facilitando a entrada de glicose nas celulas.","resposta":""},
  {"id":"4541","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Heranca ligada ao sexo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O daltonismo e uma doenca ligada ao cromossomo X. Um homem daltônico tem genótipo:","alternativa_a":"XdY","alternativa_b":"XDXd","alternativa_c":"XDXD","alternativa_d":"XdXd","alternativa_e":"XDY","resposta_correta":"a","explicacao":"Os homens possuem um X e um Y. Um homem daltônico tem o alelo para daltonismo no unico cromossomo X: genótipo XdY. Mulheres precisam de dois alelos para ser daltônicas.","resposta":""},
  {"id":"4542","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Nicho ecologico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O nicho ecologico de uma especie refere-se a:","alternativa_a":"Sua funcao e posicao no ecossistema","alternativa_b":"Apenas ao local fisico que habita","alternativa_c":"Sua posicao na cadeia trófica","alternativa_d":"O territorio que defende","alternativa_e":"Sua populacao maxima","resposta_correta":"a","explicacao":"O nicho ecologico e mais amplo que habitat: inclui o papel funcional da especie no ecossistema (o que come, quem come, suas interacoes, tolerancias ambientais).","resposta":""},
  {"id":"4543","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Vegetal","subtema":"Transpiracao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A transpiracao nas plantas ocorre principalmente pelos:","alternativa_a":"Estomatos","alternativa_b":"Radices","alternativa_c":"Flores","alternativa_d":"Frutos","alternativa_e":"Caules","resposta_correta":"a","explicacao":"Os estomatos sao estruturas nas folhas (principalmente na face inferior) por onde ocorre a transpiracao e as trocas gasosas (CO2 e O2) nas plantas.","resposta":""},
  {"id":"4544","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Nucleo celular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O nucleo celular e delimitado por um envelope nuclear e contem o material genetico. O nucleo e ausente nas celulas:","alternativa_a":"Procariontes","alternativa_b":"Eucariontes animais","alternativa_c":"Eucariontes vegetais","alternativa_d":"Dos fungos","alternativa_e":"Dos protistas","resposta_correta":"a","explicacao":"Celulas procariontes (bacterias e arqueobacterias) nao possuem nucleo definido com membrana nuclear; seu DNA fica solto no citoplasma em regiao chamada nucleoide.","resposta":""},
  {"id":"4545","tipo":"multipla","disciplina":"Biologia","tema":"Bioquimica","subtema":"Proteinas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A estrutura primaria de uma proteina e definida pela:","alternativa_a":"Sequencia de aminoacidos","alternativa_b":"Dobramento em helice ou folha beta","alternativa_c":"Arranjo tridimensional","alternativa_d":"Associacao de cadeias polipeptidicas","alternativa_e":"Presenca de pontes dissulfeto","resposta_correta":"a","explicacao":"A estrutura primaria e a sequencia linear de aminoacidos ligados por ligacoes peptidicas. Ela determina todas as estruturas de ordem superior.","resposta":""},
  {"id":"4546","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Ciclo do azoto","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"As bacterias nitrificantes convertem amonia em nitratos no ciclo do nitrogenio. Esse processo e chamado de:","alternativa_a":"Nitrificacao","alternativa_b":"Denitrificacao","alternativa_c":"Fixacao de nitrogenio","alternativa_d":"Aminificacao","alternativa_e":"Assimilacao","resposta_correta":"a","explicacao":"A nitrificacao e realizada por bacterias (Nitrosomonas e Nitrobacter) e converte amonia (NH3) primeiro em nitrito e depois em nitrato, que pode ser absorvido pelas plantas.","resposta":""},
  {"id":"4547","tipo":"multipla","disciplina":"Historia","tema":"Historia Antiga","subtema":"Roma","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O periodo em que Roma foi governada por imperadores, comecando com Augusto, e conhecido como:","alternativa_a":"Principado","alternativa_b":"Republica","alternativa_c":"Monarquia","alternativa_d":"Dominato","alternativa_e":"Tetrarquia","resposta_correta":"a","explicacao":"O Principado (27 a.C. - 284 d.C.) foi a primeira fase do Imperio Romano, iniciada com Augusto, em que os imperadores mantinham aparencias republicanas.","resposta":""},
  {"id":"4548","tipo":"multipla","disciplina":"Historia","tema":"Historia Moderna","subtema":"Absolutismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O rei frances Luis XIV e associado ao absolutismo monárquico. Sua frase 'L'etat, c'est moi' (O Estado sou eu) sintetiza:","alternativa_a":"A concentracao total do poder no monarca","alternativa_b":"A monarquia parlamentar","alternativa_c":"O contrato social","alternativa_d":"A separacao de poderes","alternativa_e":"A democracia direta","resposta_correta":"a","explicacao":"Luis XIV (1638-1715), o Rei Sol, representou o absolutismo em sua forma mais completa, concentrando todo o poder politico, religioso e militar em sua pessoa.","resposta":""},
  {"id":"4549","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Abolicionismo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Lei Aurea, que aboliu a escravidao no Brasil, foi assinada em 13 de maio de 1888 pela:","alternativa_a":"Princesa Isabel","alternativa_b":"Dom Pedro II","alternativa_c":"Duquesa de Caxias","alternativa_d":"Zumbi dos Palmares","alternativa_e":"Jose do Patrocinio","resposta_correta":"a","explicacao":"A Princesa Isabel, regente do Imperio, assinou a Lei Aurea em 13 de maio de 1888, tornando o Brasil o ultimo pais das Americas a abolir a escravidao.","resposta":""},
  {"id":"4550","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Descolonizacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Conferencia de Bandung (1955) foi importante para:","alternativa_a":"Consolidar o Movimento dos Nao-Alinhados","alternativa_b":"Criar a ONU","alternativa_c":"Estabelecer o Plano Marshall","alternativa_d":"Fundar a OTAN","alternativa_e":"Dividir a Alemanha","resposta_correta":"a","explicacao":"A Conferencia de Bandung reuniu 29 paises africanos e asiaticos recém independentes, sendo a base para o Movimento dos Nao-Alinhados durante a Guerra Fria.","resposta":""},
  {"id":"4551","tipo":"multipla","disciplina":"Geografia","tema":"Biogeografia","subtema":"Cerrado","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Cerrado brasileiro e considerado um hotspot de biodiversidade e e o segundo maior bioma do Brasil. Qual ameaca principal enfrenta?","alternativa_a":"Expansao da agropecuaria","alternativa_b":"Salinizacao dos solos","alternativa_c":"Desertificacao natural","alternativa_d":"Inundacoes frequentes","alternativa_e":"Extrativismo mineral","resposta_correta":"a","explicacao":"O Cerrado perdeu mais de 50% de sua area original devido a expansao da agropecuaria, especialmente a soja e pecuaria bovina no Centro-Oeste brasileiro.","resposta":""},
  {"id":"4552","tipo":"multipla","disciplina":"Geografia","tema":"Cartografia","subtema":"Projecoes cartograficas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A projecao de Mercator, amplamente usada na navegacao, distorce especialmente:","alternativa_a":"As areas nas altas latitudes (polos)","alternativa_b":"As formas dos continentes tropicais","alternativa_c":"As distancias na linha do equador","alternativa_d":"A forma da Africa","alternativa_e":"A localizacao dos meridianos","resposta_correta":"a","explicacao":"A projecao de Mercator aumenta exageradamente as areas nas altas latitudes (como Groenlandia e Antarctica), distorcendo as proporcoes reais dos continentes.","resposta":""},
  {"id":"4553","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Conflitos contemporaneos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conflito israelo-palestino esta centrado principalmente na disputa por:","alternativa_a":"Territorio e soberania","alternativa_b":"Recursos minerais","alternativa_c":"Agua do Rio Jordao","alternativa_d":"Acesso ao petroleo","alternativa_e":"Rotas comerciais maritimas","resposta_correta":"a","explicacao":"O conflito israelo-palestino envolve fundamentalmente a disputa por territorio (especialmente Cisjordania, Faixa de Gaza e Jerusalem) e o reconhecimento de soberania estatal palestina.","resposta":""},
  {"id":"4554","tipo":"multipla","disciplina":"Geografia","tema":"Desenvolvimento","subtema":"IDH","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O IDH (Indice de Desenvolvimento Humano) e calculado a partir de tres dimensoes: longevidade, educacao e:","alternativa_a":"Renda","alternativa_b":"Seguranca","alternativa_c":"Democracia","alternativa_d":"Sustentabilidade","alternativa_e":"Infraestrutura","resposta_correta":"a","explicacao":"O IDH do PNUD/ONU combina tres dimensoes: saude (esperanca de vida), educacao (anos de estudo) e renda (RNB per capita). Varia de 0 a 1.","resposta":""},
  {"id":"4555","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Pronomes relativos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Assinale a alternativa em que o uso do pronome relativo esta CORRETO:","alternativa_a":"O livro que li era interessante","alternativa_b":"O livro qual li era interessante","alternativa_c":"O livro em que li era interessante","alternativa_d":"O livro o qual li era interessante sem preposicao","alternativa_e":"O livro cujo li era interessante","resposta_correta":"a","explicacao":"O pronome relativo 'que' substitui 'o livro', retomando o antecedente. A frase 'O livro que li era interessante' esta gramaticalmente correta.","resposta":""},
  {"id":"4556","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Simbolismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O principal representante do Simbolismo brasileiro foi:","alternativa_a":"Cruz e Sousa","alternativa_b":"Olavo Bilac","alternativa_c":"Machado de Assis","alternativa_d":"Jose de Alencar","alternativa_e":"Castro Alves","resposta_correta":"a","explicacao":"Cruz e Sousa (1861-1898) e o principal poeta simbolista brasileiro, conhecido como o 'Cisne Negro'. Sua obra 'Missal' e 'Broqueis' sao marcos do movimento.","resposta":""},
  {"id":"4557","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Fonetica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O estudo dos sons da fala, suas caracteristicas fisicas e articulatorias, e objeto de estudo da:","alternativa_a":"Fonetica","alternativa_b":"Fonologia","alternativa_c":"Morfologia","alternativa_d":"Sintaxe","alternativa_e":"Semantica","resposta_correta":"a","explicacao":"A fonetica estuda os sons da fala (fones) em seus aspectos fisicos, articulatorios e acusticos, sem considerar sua funcao distintiva no sistema linguístico.","resposta":""},
  {"id":"4558","tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Etica de Aristoteles","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Aristoteles, a virtude e um meio-termo entre dois extremos. A coragem, por exemplo, e o meio-termo entre a covardia e:","alternativa_a":"A temeridade","alternativa_b":"A prudencia","alternativa_c":"A justica","alternativa_d":"A frieza","alternativa_e":"A generosidade","resposta_correta":"a","explicacao":"Na etica das virtudes de Aristoteles, cada virtude e o justo meio entre dois vicios extremos: a coragem e o meio-termo entre a covardia (falta) e a temeridade (excesso).","resposta":""},
  {"id":"4559","tipo":"multipla","disciplina":"Sociologia","tema":"Desigualdade","subtema":"Exclusao social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sociologo frances Robert Castel analisou a exclusao social em termos de:","alternativa_a":"Zonas de coesao, vulnerabilidade e desfiliacao","alternativa_b":"Classes sociais no modo de producao capitalista","alternativa_c":"Habitus e campo social","alternativa_d":"Sistemas abertos e fechados","alternativa_e":"Redes de poder e disciplina","resposta_correta":"a","explicacao":"Robert Castel identificou tres zonas de coesao social: integracao, vulnerabilidade e desfiliacao, descrevendo o processo pelo qual individuos perdem vinculos sociais e laborais.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote45.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
