# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4810","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Logaritmos - mudanca de base","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A formula de mudança de base dos logaritmos e: logb(a) =","alternativa_a":"log(a) / log(b)","alternativa_b":"log(b) / log(a)","alternativa_c":"log(a) * log(b)","alternativa_d":"log(a - b)","alternativa_e":"log(a + b)","resposta_correta":"a","explicacao":"Mudança de base: logb(a) = log(a)/log(b) = ln(a)/ln(b). Permite calcular logaritmos em qualquer base usando logaritmos decimais ou naturais.","resposta":""},
  {"id":"4811","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Razao aurea","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A razao aurea (numero de ouro) phi e definida por phi = (1 + sqrt(5))/2. Seu valor aproximado e:","alternativa_a":"1,618","alternativa_b":"3,14","alternativa_c":"2,718","alternativa_d":"1,414","alternativa_e":"1,732","resposta_correta":"a","explicacao":"phi = (1 + sqrt(5))/2 ≈ 1,618. A razao aurea aparece em varias proporcoes na natureza, arte e arquitetura.","resposta":""},
  {"id":"4812","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao de 1o grau - Raiz","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A raiz (zero) da funcao f(x) = 3x - 6 e:","alternativa_a":"2","alternativa_b":"-2","alternativa_c":"6","alternativa_d":"-6","alternativa_e":"3","resposta_correta":"a","explicacao":"3x - 6 = 0. 3x = 6. x = 2.","resposta":""},
  {"id":"4813","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Regra da adicao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A probabilidade de um estudante passar em matematica e 0,7 e em portugues e 0,6. Se as probabilidades sao independentes, a probabilidade de passar nas duas materias e:","alternativa_a":"0,42","alternativa_b":"1,30","alternativa_c":"0,88","alternativa_d":"0,13","alternativa_e":"0,70","resposta_correta":"a","explicacao":"Eventos independentes: P(A e B) = P(A)*P(B) = 0,7*0,6 = 0,42.","resposta":""},
  {"id":"4814","tipo":"multipla","disciplina":"Matematica","tema":"Sequencias","subtema":"Fibonacci","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na sequencia de Fibonacci (1, 1, 2, 3, 5, 8, 13, ...), cada termo e a soma dos dois anteriores. O 8o termo e:","alternativa_a":"21","alternativa_b":"13","alternativa_c":"34","alternativa_d":"8","alternativa_e":"55","resposta_correta":"a","explicacao":"1,1,2,3,5,8,13,21... O 8o termo e 21.","resposta":""},
  {"id":"4815","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Tronco de cone","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O tronco de cone e obtido por um plano paralelo a base que corta um cone. Se o volume do cone completo e 36 pi e o cone menor removido tem volume 4 pi, o volume do tronco e:","alternativa_a":"32 pi","alternativa_b":"40 pi","alternativa_c":"32","alternativa_d":"4 pi","alternativa_e":"36 pi","resposta_correta":"a","explicacao":"Volume do tronco = Volume do cone completo - Volume do cone menor = 36 pi - 4 pi = 32 pi.","resposta":""},
  {"id":"4816","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Combinacoes com restricoes","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"De 5 homens e 4 mulheres, de quantas maneiras pode-se formar uma comissao de 3 pessoas com pelo menos 1 mulher?","alternativa_a":"74","alternativa_b":"40","alternativa_c":"60","alternativa_d":"36","alternativa_e":"84","resposta_correta":"a","explicacao":"Total sem restricao: C(9,3)=84. Apenas homens: C(5,3)=10. Com pelo menos 1 mulher: 84-10=74.","resposta":""},
  {"id":"4817","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Maximos e minimos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Para encontrar pontos criticos (maximo ou minimo) de f(x), calcula-se a derivada e resolve-se:","alternativa_a":"f'(x) = 0","alternativa_b":"f(x) = 0","alternativa_c":"f''(x) = 0","alternativa_d":"f'(x) = 1","alternativa_e":"f(x) = f'(x)","resposta_correta":"a","explicacao":"Pontos criticos: f'(x) = 0 (derivada nula). Para classificar: se f''(x) > 0 e minimo local; se f''(x) < 0 e maximo local.","resposta":""},
  {"id":"4818","tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Frações parciais","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Qual e o valor de 1/2 + 1/4 + 1/8 + 1/16 + ... (soma infinita)?","alternativa_a":"1","alternativa_b":"2","alternativa_c":"1/2","alternativa_d":"Infinito","alternativa_e":"3/4","resposta_correta":"a","explicacao":"PG infinita: a1=1/2, r=1/2. S = (1/2)/(1-1/2) = (1/2)/(1/2) = 1.","resposta":""},
  {"id":"4819","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Analitica","subtema":"Distancia entre dois pontos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A distancia entre os pontos A(0,0) e B(3,4) e:","alternativa_a":"5","alternativa_b":"7","alternativa_c":"12","alternativa_d":"3","alternativa_e":"4","resposta_correta":"a","explicacao":"d = sqrt((3-0)^2 + (4-0)^2) = sqrt(9+16) = sqrt(25) = 5.","resposta":""},
  {"id":"4820","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Ciclos cosmicos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A terceira lei de Kepler relaciona o periodo orbital T de um planeta com seu semieixo maior a por:","alternativa_a":"T^2 = k * a^3","alternativa_b":"T = k * a^2","alternativa_c":"T^3 = k * a^2","alternativa_d":"T = k / a^3","alternativa_e":"T^2 = k / a^3","resposta_correta":"a","explicacao":"Terceira lei de Kepler: T^2 / a^3 = constante (igual para todos os planetas ao redor de um mesmo astro). O quadrado do periodo e proporcional ao cubo do semieixo maior.","resposta":""},
  {"id":"4821","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Fio infinito","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O campo magnetico a uma distancia r de um fio condutor retilineo de comprimento infinito, percorrido por corrente I, e dado por:","alternativa_a":"B = (mu0 * I) / (2pi * r)","alternativa_b":"B = (mu0 * I * r) / (2pi)","alternativa_c":"B = mu0 * I / r","alternativa_d":"B = mu0 * I * 2pi / r","alternativa_e":"B = mu0 / (I * r)","resposta_correta":"a","explicacao":"Campo do fio: B = mu0*I/(2pi*r), onde mu0 = 4pi x 10^-7 T.m/A. O campo diminui com a distancia e as linhas formam circulos concêntricos ao redor do fio.","resposta":""},
  {"id":"4822","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Temperatura absoluta","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O zero absoluto (0 K) representa:","alternativa_a":"A temperatura mais baixa possivel, -273,15 oC","alternativa_b":"O ponto de fusao da agua","alternativa_c":"A temperatura do espaco sideral","alternativa_d":"-100 oC","alternativa_e":"A temperatura do nitrogenio liquido","resposta_correta":"a","explicacao":"O zero absoluto (0 K = -273,15 oC) e a temperatura teoricamente mais baixa possivel, onde o movimento termico das particulas cessa. Nunca foi atingido experimentalmente.","resposta":""},
  {"id":"4823","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Aparelhos opticos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O microscopio optico usa duas lentes convergentes: a objetiva e a ocular. A objetiva produz uma imagem:","alternativa_a":"Real, invertida e ampliada do objeto","alternativa_b":"Virtual, direta e reduzida","alternativa_c":"Real, direta e natural","alternativa_d":"Virtual, invertida e ampliada","alternativa_e":"Real, invertida e reduzida","resposta_correta":"a","explicacao":"A objetiva do microscopio forma uma imagem real, invertida e ampliada. Essa imagem serve de objeto para a ocular, que age como lupa e forma a imagem final virtual e ampliada.","resposta":""},
  {"id":"4824","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Variaveis de estado","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A densidade de um material e definida como:","alternativa_a":"Massa dividida pelo volume","alternativa_b":"Peso dividido pelo volume","alternativa_c":"Massa multiplicada pelo volume","alternativa_d":"Peso dividido pela area","alternativa_e":"Massa dividida pela area","resposta_correta":"a","explicacao":"Densidade d = m/V (massa por volume). Unidade no SI: kg/m3. Exemplo: densidade da agua = 1 g/cm3 = 1000 kg/m3.","resposta":""},
  {"id":"4825","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Energia magnetica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A energia armazenada em um indutor de indutancia L percorrido por corrente I e:","alternativa_a":"E = (1/2) * L * I^2","alternativa_b":"E = L * I","alternativa_c":"E = L^2 * I","alternativa_d":"E = (1/2) * L^2 * I","alternativa_e":"E = L * I^2","resposta_correta":"a","explicacao":"Energia armazenada no campo magnetico de um indutor: E = (1/2)*L*I^2. Analogia com a energia cinetica (1/2*m*v^2) na mecanica.","resposta":""},
  {"id":"4826","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Ondas electromagneticas - frequencias","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O smartphone usa ondas eletromagneticas para comunicacao (Wi-Fi, 4G, 5G). Essas ondas sao do tipo:","alternativa_a":"Micro-ondas e radio","alternativa_b":"Raios X","alternativa_c":"Ultravioleta","alternativa_d":"Infravermelho","alternativa_e":"Raios gama","resposta_correta":"a","explicacao":"Comunicacoes moveis (4G/5G) e Wi-Fi operam em frequencias de radio e micro-ondas (GHz). Sao seguras para uso diario (nao ionizantes).","resposta":""},
  {"id":"4827","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Conservacao de energia - pendulo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No ponto mais baixo da trajetoria de um pendulo em oscilacao, a energia cinetica e:","alternativa_a":"Maxima","alternativa_b":"Minima","alternativa_c":"Zero","alternativa_d":"Igual a energia potencial","alternativa_e":"Negativa","resposta_correta":"a","explicacao":"No ponto mais baixo do pendulo (posicao de equilibrio), toda energia potencial foi convertida em energia cinetica: Ec e maxima, Ep e minima (zero se tomarmos esse ponto como referencia).","resposta":""},
  {"id":"4828","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Efeito fotoeletrico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"No efeito fotoeletrico, a emissao de eletrons so ocorre quando a frequencia da luz incidente e:","alternativa_a":"Superior a frequencia de corte","alternativa_b":"Inferior a frequencia de corte","alternativa_c":"Igual a frequencia de corte","alternativa_d":"Independente da frequencia","alternativa_e":"Proporcional a intensidade da luz","resposta_correta":"a","explicacao":"No efeito fotoeletrico, cada material tem uma frequencia de corte (ou limiar) minima. Apenas fotons com frequencia acima desse valor tem energia suficiente para arrancar eletrons.","resposta":""},
  {"id":"4829","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Equacao de Van der Waals","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A equacao de Van der Waals e uma correcao ao gas ideal que leva em conta:","alternativa_a":"O volume proprio das moleculas e as interacoes intermoleculares","alternativa_b":"Apenas a temperatura absoluta","alternativa_c":"Apenas o numero de moles","alternativa_d":"A condutividade termica do gas","alternativa_e":"A velocidade das moleculas","resposta_correta":"a","explicacao":"Van der Waals corrigiu a lei dos gases ideais: (P + a/V^2)(V - b) = nRT, onde 'b' corrige o volume proprio das moleculas e 'a' corrige as forcas de atracao intermolecular.","resposta":""},
  {"id":"4830","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes de condensacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A formacao de peptideos (ligacao peptidica) entre aminoacidos e uma reacao de:","alternativa_a":"Condensacao (com eliminacao de agua)","alternativa_b":"Adicao","alternativa_c":"Substituicao","alternativa_d":"Oxidacao","alternativa_e":"Reducao","resposta_correta":"a","explicacao":"Ligacao peptidica: o grupo amino (-NH2) de um aminoacido reage com o grupo carboxila (-COOH) de outro, com eliminacao de agua (condensacao): -CO-NH-.","resposta":""},
  {"id":"4831","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Reacoes de combustao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Na combustao completa do metano (CH4), os produtos formados sao:","alternativa_a":"CO2 e H2O","alternativa_b":"CO e H2","alternativa_c":"C e H2O","alternativa_d":"CO e H2O","alternativa_e":"CO2 e H2","resposta_correta":"a","explicacao":"Combustao completa: CH4 + 2O2 -> CO2 + 2H2O. Forma dioxido de carbono e agua. Combustao incompleta (pouco O2) forma CO e C (particulas de fuligem).","resposta":""},
  {"id":"4832","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Biocombustiveis","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O biodiesel e um biocombustivel produzido a partir de:","alternativa_a":"Oleos vegetais ou gorduras animais por transesterificacao","alternativa_b":"Fermentacao de cana-de-acucar","alternativa_c":"Destilacao do petroleo","alternativa_d":"Gasificacao do carvao","alternativa_e":"Eletrólise da agua","resposta_correta":"a","explicacao":"O biodiesel e produzido pela transesterificacao de triglicerideos (oleos vegetais ou gorduras animais) com alcool (metanol ou etanol), na presenca de catalisador basico.","resposta":""},
  {"id":"4833","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Forças de London","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"As forcas de London (dispersao de van der Waals) sao interacoes que existem entre:","alternativa_a":"Todos os atomos e moleculas, inclusive apolares","alternativa_b":"Apenas moleculas polares","alternativa_c":"Apenas ions","alternativa_d":"Apenas atomos de mesmo elemento","alternativa_e":"Apenas metais","resposta_correta":"a","explicacao":"Forcas de dispersao de London resultam de dipolos instantaneos induzidos e existem entre todos os atomos e moleculas, independentemente de serem polares ou apolares.","resposta":""},
  {"id":"4834","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Grupos funcionais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O grupo funcional -NH2 caracteriza as:","alternativa_a":"Aminas","alternativa_b":"Amidas","alternativa_c":"Aminoacidos","alternativa_d":"Nitrilas","alternativa_e":"Nitrocompostos","resposta_correta":"a","explicacao":"O grupo amino (-NH2) e o grupo funcional das aminas (derivados organicos da amonia). Ex.: metilamina (CH3-NH2), etilamina (C2H5-NH2).","resposta":""},
  {"id":"4835","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Metais alcalino-terrosos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O calcio (Ca) pertence ao grupo dos metais alcalino-terrosos (grupo 2) e possui valência:","alternativa_a":"2","alternativa_b":"1","alternativa_c":"3","alternativa_d":"0","alternativa_e":"7","resposta_correta":"a","explicacao":"Metais alcalino-terrosos (Be, Mg, Ca, Sr, Ba, Ra) tem 2 eletrons de valencia e valencia 2, formando ions M^2+.","resposta":""},
  {"id":"4836","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Acido nitrico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O acido nitrico concentrado (HNO3) e um oxidante forte e dissolve a maioria dos metais. A mistura de HNO3 e HCl (3:1) capaz de dissolver ouro e platina e chamada de:","alternativa_a":"Agua regia","alternativa_b":"Agua forte","alternativa_c":"Agua de bromo","alternativa_d":"Agua de cal","alternativa_e":"Agua ozonizada","resposta_correta":"a","explicacao":"Agua regia (3 partes de HCl + 1 parte de HNO3) dissolve ouro e platina ('metais nobres'), pois gera cloro ativo e NOCl que atacam esses metais resistentes.","resposta":""},
  {"id":"4837","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Excesso de reagente","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma reacao entre 2 mols de H2 e 2 mols de O2 para formar H2O (2H2 + O2 -> 2H2O), qual reagente e o limitante?","alternativa_a":"H2 (2 mols sao necessarios para 1 mol de O2)","alternativa_b":"O2","alternativa_c":"Ambos estao em estequiometria exata","alternativa_d":"Nenhum e limitante","alternativa_e":"Depende da temperatura","resposta_correta":"a","explicacao":"Na reacao 2H2 + O2 -> 2H2O: 2 mols de H2 precisam de 1 mol de O2. Com 2 mols de H2 e 2 mols de O2: usa-se 2 mols de H2 e apenas 1 mol de O2. H2 e o limitante; O2 esta em excesso.","resposta":""},
  {"id":"4838","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes de alcoois","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de oxidacao branda de um alcool primario forma inicialmente:","alternativa_a":"Um aldeido","alternativa_b":"Uma cetona","alternativa_c":"Um acido carboxilico","alternativa_d":"Um ester","alternativa_e":"Um alceno","resposta_correta":"a","explicacao":"Oxidacao de alcoois: alcool primario -> aldeido (oxidacao branda) -> acido carboxilico (oxidacao energica). Alcool secundario -> cetona. Alcool terciario nao se oxida facilmente.","resposta":""},
  {"id":"4839","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Amonia","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A amonia (NH3) e sintetizada industrialmente pelo processo de Haber-Bosch a partir de:","alternativa_a":"N2 e H2","alternativa_b":"NO2 e H2O","alternativa_c":"HNO3 e H2","alternativa_d":"N2O e H2O","alternativa_e":"NH4Cl e H2","resposta_correta":"a","explicacao":"Processo Haber-Bosch: N2 + 3H2 -> 2NH3. Realizado em alta pressao, alta temperatura (400-500 oC) e catalisador de ferro. E a base da industria de fertilizantes.","resposta":""},
  {"id":"4840","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Metabolismo","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O glucagon, hormonio pancreatico, tem efeito oposto a insulina pois:","alternativa_a":"Aumenta a glicemia (estimula glicogenolise e gliconeogenese)","alternativa_b":"Diminui a glicemia","alternativa_c":"Inibe a digestao","alternativa_d":"Estimula a lipogenese","alternativa_e":"Reduz a frequencia cardiaca","resposta_correta":"a","explicacao":"Glucagon (celulas alfa do pancreas): libera glicose para o sangue estimulando a glicogenolise (quebra de glicogenio hepatico) e a gliconeogenese (sintese de glicose). Eleva a glicemia.","resposta":""},
  {"id":"4841","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Extravagancia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A heranca poligenica (ex.: cor da pele humana) e determinada por:","alternativa_a":"Multiplos pares de genes que interagem de forma aditiva","alternativa_b":"Um unico par de alelos dominante-recessivo","alternativa_c":"Genes ligados ao cromossomo X","alternativa_d":"Mutacoes somaticas","alternativa_e":"Pleiotropia","resposta_correta":"a","explicacao":"Heranca poligenica: caracteristicas com distribuicao continua (altura, cor da pele) sao determinadas por multiplos genes com efeitos aditivos. Geram distribuicao em curva de Gauss.","resposta":""},
  {"id":"4842","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Sucessao secundaria","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Apos um incendio em uma floresta, o processo de recuperacao da vegetacao e chamado de:","alternativa_a":"Sucessao ecologica secundaria","alternativa_b":"Sucessao ecologica primaria","alternativa_c":"Clímax","alternativa_d":"Regeneracao abiotica","alternativa_e":"Evolucao adaptativa","resposta_correta":"a","explicacao":"Sucessao secundaria: ocorre em ambientes que ja foram habitados e tem solo formado, mas foram perturbados (incendio, desmatamento). E mais rapida que a primaria.","resposta":""},
  {"id":"4843","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Pele","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A melanina, responsavel pela cor da pele e protecao contra UV, e produzida pelas celulas:","alternativa_a":"Melanocitos","alternativa_b":"Queratinócitos","alternativa_c":"Fibroblastos","alternativa_d":"Mastócitos","alternativa_e":"Celulas de Langerhans","resposta_correta":"a","explicacao":"Os melanocitos sao celulas presentes na epiderme que produzem melanina (pigmento). A quantidade de melanina determina a cor da pele, nao o numero de melanocitos.","resposta":""},
  {"id":"4844","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Divisao celular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A etapa da mitose em que os cromossomos se alinham na placa equatorial da celula e chamada de:","alternativa_a":"Metafase","alternativa_b":"Profase","alternativa_c":"Anafase","alternativa_d":"Telofase","alternativa_e":"Interfase","resposta_correta":"a","explicacao":"Fases da mitose: Profase (condensacao dos cromossomos), Metafase (alinhamento na placa equatorial), Anafase (separacao para os polos), Telofase (formacao de novas nucleos).","resposta":""},
  {"id":"4845","tipo":"multipla","disciplina":"Biologia","tema":"Zoologia","subtema":"Moluscos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O polvo, a lula e o nautilo sao moluscos da classe:","alternativa_a":"Cefalopodes","alternativa_b":"Gastropodes","alternativa_c":"Bivalves","alternativa_d":"Poliplacoforos","alternativa_e":"Escafopodes","resposta_correta":"a","explicacao":"Cefalopodes (polvo, lula, sepia, nautilo) sao moluscos com tentaculos ao redor da cabeca, sistema nervoso desenvolvido e alguns com capacidade de camuflagemmovimento rapido.","resposta":""},
  {"id":"4846","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Selecao sexual","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A selecao sexual (Darwin) explica o desenvolvimento de caracteristicas como a cauda do pavao macho, pois:","alternativa_a":"Aumenta o sucesso reprodutivo ao atrair femeas","alternativa_b":"Aumenta a sobrevivencia contra predadores","alternativa_c":"E selecionada naturalmente por ser eficiente","alternativa_d":"Aumenta a agilidade do animal","alternativa_e":"E neutra evolutivamente","resposta_correta":"a","explicacao":"Selecao sexual: pressao evolutiva resultante da escolha de parceiros. Caracteristicas que aumentam o sucesso na reproducao (como a cauda do pavao) sao selecionadas, mesmo que reduzam a sobrevivencia.","resposta":""},
  {"id":"4847","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Ciclo ovarico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O corpo luteo, formado apos a ovulacao, produz principalmente:","alternativa_a":"Progesterona","alternativa_b":"Estrogênio","alternativa_c":"FSH","alternativa_d":"LH","alternativa_e":"Prolactina","resposta_correta":"a","explicacao":"Apos a ovulacao, o foliculo vazio transforma-se em corpo luteo, que produz progesterona (e algum estrogênio), preparando o endometrio para a implantacao do embrião.","resposta":""},
  {"id":"4848","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Colonizacao - pau-brasil","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O pau-brasil foi o principal produto de exportacao do Brasil durante o chamado periodo de:","alternativa_a":"Extrativismo (1500-1534)","alternativa_b":"Ciclo da cana-de-acucar","alternativa_c":"Ciclo do ouro","alternativa_d":"Ciclo do cafe","alternativa_e":"Ciclo da borracha","resposta_correta":"a","explicacao":"O primeiro ciclo economico do Brasil colonial foi o extrativismo do pau-brasil (1500-1534), explorado inicialmente pelo sistema de feitorias com o trabalho indigena (escambo).","resposta":""},
  {"id":"4849","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Imperialismo americano","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Doutrina Monroe (1823), sintetizada por 'America para os americanos', visava principalmente:","alternativa_a":"Impedir a intervencao europeia na America","alternativa_b":"Unificar os paises americanos","alternativa_c":"Justificar a expansao territorial dos EUA","alternativa_d":"Criar a OEA","alternativa_e":"Estabelecer livre comercio no hemisfério","resposta_correta":"a","explicacao":"A Doutrina Monroe (Presidente Monroe, 1823) opunha-se a recolonizacao europeia das Americas. Defendia que qualquer intervencao europeia no hemisfério seria vista como ameaca aos EUA.","resposta":""},
  {"id":"4850","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Cangaco","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Lampiao foi o mais famoso lider do cangaco nordestino. O cangaco era um fenomeno social ligado a:","alternativa_a":"Seca, pobreza e coronelismo no sertao nordestino","alternativa_b":"Reforma agraria no Nordeste","alternativa_c":"Conflito entre escravos fugitivos","alternativa_d":"Movimento operario no sertao","alternativa_e":"Resistencia indigena ao colonizador","resposta_correta":"a","explicacao":"O cangaco (fin do sec. XIX - 1940) foi um fenomeno social nordestino relacionado a seca, pobreza extrema, ausencia do Estado e poder absoluto dos coroneis latifundiarios.","resposta":""},
  {"id":"4851","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Corrida espacial","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O primeiro ser humano a orbitar a Terra (1961) foi o cosmonauta soviético:","alternativa_a":"Yuri Gagarin","alternativa_b":"Neil Armstrong","alternativa_c":"Buzz Aldrin","alternativa_d":"Alan Shepard","alternativa_e":"John Glenn","resposta_correta":"a","explicacao":"Yuri Gagarin completou uma orbita em torno da Terra em 12 de abril de 1961, na nave Vostok 1, tornando-se o primeiro humano no espaco. Armstrong foi o primeiro na Lua (1969).","resposta":""},
  {"id":"4852","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Tratado de Versalhes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Tratado de Versalhes (1919), que encerrou a Primeira Guerra Mundial, impôs a Alemanha:","alternativa_a":"Pesadas reparacoes de guerra, perda de territorios e limitacao do exercito","alternativa_b":"A divisao em duas nações","alternativa_c":"Restituicao apenas de colonias africanas","alternativa_d":"Integracao a Liga das Nacoes imediatamente","alternativa_e":"Compensacoes financeiras da Franca","resposta_correta":"a","explicacao":"O Tratado de Versalhes humilhou a Alemanha: clausula de culpa de guerra, reparacoes bilionarias, perda de territorios e restricao das forcas armadas. Isso criou as condicoes para o nazismo.","resposta":""},
  {"id":"4853","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"OPEP","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A OPEP (Organizacao dos Paises Exportadores de Petroleo) foi fundada em 1960 para:","alternativa_a":"Controlar a producao e o preco do petroleo","alternativa_b":"Financiar o desenvolvimento de energias renovaveis","alternativa_c":"Regular o comercio internacional de commodities","alternativa_d":"Criar um banco de desenvolvimento","alternativa_e":"Estabelecer cotas de importacao de petroleo","resposta_correta":"a","explicacao":"A OPEP foi criada em 1960 por Arabia Saudita, Ira, Iraq, Kuwait e Venezuela para coordenar as politicas petroliferas, controlar a producao e defender os precos do petroleo.","resposta":""},
  {"id":"4854","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Cidades sustentaveis","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'smart city' (cidade inteligente) refere-se a:","alternativa_a":"Uso de tecnologia para tornar as cidades mais eficientes e sustentaveis","alternativa_b":"Cidades construidas inteiramente de modo digital","alternativa_c":"Metropoles com alta densidade populacional","alternativa_d":"Cidades sem carros","alternativa_e":"Zonas de livre comercio tecnologico","resposta_correta":"a","explicacao":"Smart cities integram tecnologias de informacao e comunicacao (IoT, big data, IA) na gestao urbana para melhorar mobilidade, energia, habitacao, saude e participacao cidada.","resposta":""},
  {"id":"4855","tipo":"multipla","disciplina":"Geografia","tema":"Recursos Naturais","subtema":"Mineracao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Brasil possui as maiores reservas mundiais de:","alternativa_a":"Ferro e niobio","alternativa_b":"Ouro e prata","alternativa_c":"Cobre e zinco","alternativa_d":"Petroleo e gas","alternativa_e":"Diamante e rubi","resposta_correta":"a","explicacao":"O Brasil possui as maiores reservas mundiais de minerio de ferro (Minas Gerais e Para) e de niobio (Goias), alem de reservas significativas de outros minerios.","resposta":""},
  {"id":"4856","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Acentuacao grafica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Segundo o Acordo Ortografico de 2009, o trema foi eliminado em palavras de origem portuguesa. Em quais palavras o trema e mantido?","alternativa_a":"Palavras estrangeiras e seus derivados (ex.: Muller)","alternativa_b":"Nunca e mais usado","alternativa_c":"Em toda palavra com u pronunciado","alternativa_d":"Apenas em poesia","alternativa_e":"Em verbos irregulares","resposta_correta":"a","explicacao":"Pelo Acordo Ortografico de 2009, o trema foi eliminado em palavras do portugues (ex.: linguica, aguentar). E mantido apenas em nomes proprios estrangeiros (Muller, Strauss) e seus derivados.","resposta":""},
  {"id":"4857","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Segunda geracao modernista","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Carlos Drummond de Andrade e o principal poeta da segunda geracao do Modernismo brasileiro. Uma de suas obras mais famosas e:","alternativa_a":"Alguma Poesia","alternativa_b":"Macunaima","alternativa_c":"Vidas Secas","alternativa_d":"Sagarana","alternativa_e":"Triste Fim de Policarpo Quaresma","resposta_correta":"a","explicacao":"'Alguma Poesia' (1930) e a estreia poetica de Carlos Drummond de Andrade, com o famoso poema 'No meio do caminho'. Macunaima e de Mario de Andrade; Vidas Secas e de Graciliano Ramos.","resposta":""},
  {"id":"4858","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Contemporanea","subtema":"Pos-modernismo","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Jean-Francois Lyotard define a pos-modernidade como o fim das 'grandes narrativas'. Isso significa:","alternativa_a":"A descrença nos projetos universais de emancipacao humana (iluminismo, marxismo)","alternativa_b":"O retorno as tradicoes religiosas","alternativa_c":"A valorizacao da historia linear","alternativa_d":"A unificacao das culturas globais","alternativa_e":"O triunfo do capitalismo sobre o socialismo","resposta_correta":"a","explicacao":"Para Lyotard ('A Condicao Pos-Moderna', 1979), a pos-modernidade e caracterizada pela incredulidade em relacao as metanarrativas (progresso, razao universal, revolucao marxista).","resposta":""},
  {"id":"4859","tipo":"multipla","disciplina":"Sociologia","tema":"Cultura","subtema":"Contracultura","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O movimento hippie dos anos 1960-70 foi uma expressao de contracultura que se opunha principalmente a:","alternativa_a":"Guerra do Vietna, consumismo e valores conservadores","alternativa_b":"Industrializacao e urbanizacao","alternativa_c":"Colonialismo europeu na Africa","alternativa_d":"Regimes comunistas","alternativa_e":"Movimento pelos direitos civis nos EUA","resposta_correta":"a","explicacao":"O movimento hippie se opunha a Guerra do Vietna, ao consumismo capitalista, ao materialismo e aos valores conservadores da sociedade americana dos anos 60, propondo paz, amor e vida comunitaria.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote51.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
