import csv

questions = [
  {"id":"3581","tipo":"multipla","disciplina":"Matemática","tema":"Geometria Plana","subtema":"Áreas e Perímetros","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Um retângulo tem base 12 cm e altura 5 cm. Qual é a medida de sua diagonal?","alternativa_a":"13 cm","alternativa_b":"17 cm","alternativa_c":"10 cm","alternativa_d":"15 cm","alternativa_e":"11 cm","resposta_correta":"a","explicacao":"Pela relação de Pitágoras: d² = 12² + 5² = 144 + 25 = 169, logo d = 13 cm.","resposta":""},
  {"id":"3582","tipo":"multipla","disciplina":"Física","tema":"Termodinâmica","subtema":"Lei Zero e Temperatura","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"Uma substância se encontra a 300 K. Qual é essa temperatura em graus Celsius?","alternativa_a":"27 °C","alternativa_b":"300 °C","alternativa_c":"573 °C","alternativa_d":"-27 °C","alternativa_e":"127 °C","resposta_correta":"a","explicacao":"A conversão é T(°C) = T(K) − 273. Logo, 300 − 273 = 27 °C.","resposta":""},
  {"id":"3583","tipo":"multipla","disciplina":"Química","tema":"Eletroquímica","subtema":"Pilha de Daniell","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma pilha de Daniell (Zn|Zn²⁺||Cu²⁺|Cu), qual eletrodo sofre oxidação?","alternativa_a":"Zinco (ânodo)","alternativa_b":"Cobre (ânodo)","alternativa_c":"Zinco (cátodo)","alternativa_d":"Cobre (cátodo)","alternativa_e":"Ambos sofrem oxidação","resposta_correta":"a","explicacao":"Na pilha de Daniell, o zinco é o ânodo: perde elétrons (oxidação). O cobre é o cátodo: ganha elétrons (redução).","resposta":""},
  {"id":"3584","tipo":"multipla","disciplina":"Biologia","tema":"Genética","subtema":"Herança Ligada ao Sexo","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Uma mulher portadora de hemofilia (X^H X^h) casa-se com um homem normal (X^H Y). Qual a probabilidade de um filho homem ser hemofílico?","alternativa_a":"50%","alternativa_b":"25%","alternativa_c":"100%","alternativa_d":"0%","alternativa_e":"75%","resposta_correta":"a","explicacao":"Os filhos homens recebem o Y do pai e X da mãe (50% X^H e 50% X^h). Logo, 50% dos filhos homens serão X^h Y (hemofílicos).","resposta":""},
  {"id":"3585","tipo":"multipla","disciplina":"História","tema":"Brasil República","subtema":"Era Vargas","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"O Estado Novo (1937–1945) foi um período de ditadura no Brasil. Qual documento marcou seu início?","alternativa_a":"Constituição de 1937 (Polaca)","alternativa_b":"Constituição de 1891","alternativa_c":"Ato Institucional nº 5","alternativa_d":"Carta de 1988","alternativa_e":"Manifesto dos Tenentes","resposta_correta":"a","explicacao":"Vargas outorgou a Constituição de 1937 (apelidada de 'Polaca' por inspiração fascista) para instaurar o Estado Novo, centralizando o poder e fechando o Congresso.","resposta":""},
  {"id":"3586","tipo":"multipla","disciplina":"Geografia","tema":"Geopolítica","subtema":"Blocos Econômicos","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"O MERCOSUL é um bloco econômico formado, entre outros países, por Brasil, Argentina, Uruguai e Paraguai. Qual é o seu principal objetivo?","alternativa_a":"Integração econômica e livre comércio regional","alternativa_b":"Defesa militar conjunta","alternativa_c":"Unificação política dos países-membros","alternativa_d":"Controle da produção de petróleo","alternativa_e":"Gestão ambiental da Amazônia","resposta_correta":"a","explicacao":"O MERCOSUL visa a integração econômica com livre circulação de bens, serviços e fatores produtivos entre os países-membros da América do Sul.","resposta":""},
  {"id":"3587","tipo":"multipla","disciplina":"Língua Portuguesa","tema":"Literatura Brasileira","subtema":"Romantismo","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"José de Alencar é considerado o principal romancista do Romantismo brasileiro. Qual obra indianista lhe é atribuída?","alternativa_a":"O Guarani","alternativa_b":"Dom Casmurro","alternativa_c":"Memórias Póstumas de Brás Cubas","alternativa_d":"A Moreninha","alternativa_e":"Iracema Pires","resposta_correta":"a","explicacao":"'O Guarani' (1857) é a obra mais célebre de José de Alencar, retratando o índio Peri e seu amor pela branca Ceci — símbolo do Indianismo romântico.","resposta":""},
  {"id":"3588","tipo":"multipla","disciplina":"Filosofia","tema":"Ética","subtema":"Utilitarismo","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Para John Stuart Mill, o critério de moralidade de uma ação é:","alternativa_a":"A quantidade e qualidade de felicidade que produz para o maior número","alternativa_b":"A conformidade com o dever moral absoluto","alternativa_c":"A virtude do agente que a pratica","alternativa_d":"A vontade divina expressa nas escrituras","alternativa_e":"O contrato social estabelecido pela maioria","resposta_correta":"a","explicacao":"Mill refinou o utilitarismo de Bentham introduzindo qualidades de prazer. A ação correta é aquela que produz maior felicidade (utilidade) para o maior número de pessoas.","resposta":""},
  {"id":"3589","tipo":"multipla","disciplina":"Sociologia","tema":"Teorias Sociológicas","subtema":"Funcionalismo","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Émile Durkheim defendia que os fatos sociais devem ser tratados:","alternativa_a":"Como coisas, com objetividade científica","alternativa_b":"Como expressões da consciência individual","alternativa_c":"Como resultado das forças econômicas","alternativa_d":"Como manifestações da vontade divina","alternativa_e":"Como construções puramente subjetivas","resposta_correta":"a","explicacao":"Durkheim propôs tratar os fatos sociais 'como coisas', ou seja, com objetividade e método científico, separando a sociologia da filosofia e da psicologia individual.","resposta":""},
  {"id":"3590","tipo":"multipla","disciplina":"Matemática","tema":"Funções","subtema":"Função Logarítmica","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Calcule log₂ 64.","alternativa_a":"6","alternativa_b":"8","alternativa_c":"4","alternativa_d":"32","alternativa_e":"5","resposta_correta":"a","explicacao":"log₂ 64 = x significa 2^x = 64 = 2^6, portanto x = 6.","resposta":""},
  {"id":"3591","tipo":"multipla","disciplina":"Física","tema":"Óptica","subtema":"Reflexão e Espelhos","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Um espelho côncavo com foco em f = 20 cm recebe um objeto a 40 cm. Onde se forma a imagem?","alternativa_a":"40 cm à frente do espelho (real e invertida)","alternativa_b":"20 cm atrás do espelho (virtual)","alternativa_c":"Infinito","alternativa_d":"10 cm à frente","alternativa_e":"80 cm atrás","resposta_correta":"a","explicacao":"Equação de Gauss: 1/f = 1/p + 1/p'. Com f=20 e p=40: 1/20 = 1/40 + 1/p' → 1/p' = 1/20 - 1/40 = 1/40 → p' = 40 cm. Imagem real e invertida.","resposta":""},
  {"id":"3592","tipo":"multipla","disciplina":"Química","tema":"Química Orgânica","subtema":"Álcoois","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"O grupo funcional característico dos álcoois é:","alternativa_a":"Hidroxila (–OH) ligada a carbono saturado","alternativa_b":"Carbonila (C=O) terminal","alternativa_c":"Carboxila (–COOH)","alternativa_d":"Amina (–NH₂)","alternativa_e":"Éter (–O–)","resposta_correta":"a","explicacao":"Álcoois possuem o grupo –OH (hidroxila) ligado a carbono sp³ (saturado). Não confundir com fenóis (–OH ligado a anel aromático).","resposta":""},
  {"id":"3593","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Cadeias Alimentares","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma cadeia alimentar, os organismos que produzem matéria orgânica a partir de energia solar são chamados de:","alternativa_a":"Produtores (autótrofos)","alternativa_b":"Consumidores primários","alternativa_c":"Decompositores","alternativa_d":"Consumidores terciários","alternativa_e":"Parasitas","resposta_correta":"a","explicacao":"Os produtores (plantas, algas, cianobactérias) são autótrofos que realizam fotossíntese, convertendo energia luminosa em energia química — base de todas as cadeias alimentares.","resposta":""},
  {"id":"3594","tipo":"multipla","disciplina":"História","tema":"História Geral","subtema":"Primeira Guerra Mundial","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"O sistema de alianças que antecedeu a Primeira Guerra Mundial dividia a Europa em dois blocos principais. Quais eram eles?","alternativa_a":"Tríplice Aliança (Alemanha, Áustria-Hungria, Itália) e Tríplice Entente (França, Reino Unido, Rússia)","alternativa_b":"OTAN e Pacto de Varsóvia","alternativa_c":"Eixo (Alemanha, Itália, Japão) e Aliados","alternativa_d":"Bloco Ocidental e Bloco Oriental","alternativa_e":"Liga das Nações e Sociedade das Nações","resposta_correta":"a","explicacao":"A Europa pré-1914 estava dividida entre a Tríplice Aliança (Alemanha, Áustria-Hungria, Itália) e a Tríplice Entente (França, Reino Unido, Rússia), que se enfrentaram na Grande Guerra.","resposta":""},
  {"id":"3595","tipo":"multipla","disciplina":"Língua Portuguesa","tema":"Gramática","subtema":"Concordância Verbal","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Assinale a alternativa com concordância verbal correta:","alternativa_a":"Fazem dois anos que não o vejo.","alternativa_b":"Fazem dois anos que não o vejo, conforme norma padrão (verbo no singular quando indica tempo).","alternativa_c":"Faz dois anos que não o vejo.","alternativa_d":"Faziam dois anos que não o vejo.","alternativa_e":"Faria dois anos que não o vejo.","resposta_correta":"c","explicacao":"Verbos que indicam tempo decorrido (como 'fazer', 'haver') funcionam como impessoais e ficam no singular: 'Faz dois anos que não o vejo.'","resposta":""},
  {"id":"3596","tipo":"multipla","disciplina":"Filosofia","tema":"Epistemologia","subtema":"Racionalismo","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"René Descartes, ao afirmar 'Cogito, ergo sum' ('Penso, logo existo'), estabelece como ponto de partida indubitável do conhecimento:","alternativa_a":"A existência do sujeito pensante","alternativa_b":"A percepção sensorial","alternativa_c":"A autoridade da Igreja","alternativa_d":"A tradição filosófica grega","alternativa_e":"O contrato social","resposta_correta":"a","explicacao":"Descartes, após duvidar de tudo, conclui que não pode duvidar do próprio ato de duvidar/pensar — logo, o sujeito pensante existe. Essa certeza é o fundamento de sua filosofia.","resposta":""},
  {"id":"3597","tipo":"multipla","disciplina":"Matemática","tema":"Trigonometria","subtema":"Razões Trigonométricas","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"Em um triângulo retângulo, o seno do ângulo A é definido como:","alternativa_a":"cateto oposto / hipotenusa","alternativa_b":"cateto adjacente / hipotenusa","alternativa_c":"cateto oposto / cateto adjacente","alternativa_d":"hipotenusa / cateto oposto","alternativa_e":"cateto adjacente / cateto oposto","resposta_correta":"a","explicacao":"sen A = cateto oposto / hipotenusa. Mnemônico: SOH (Seno = Oposto/Hipotenusa), CAH (Cosseno = Adjacente/Hipotenusa), TOA (Tangente = Oposto/Adjacente).","resposta":""},
  {"id":"3598","tipo":"multipla","disciplina":"Química","tema":"Termoquímica","subtema":"Entalpia","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Uma reação com ΔH < 0 é classificada como:","alternativa_a":"Exotérmica — libera calor para o ambiente","alternativa_b":"Endotérmica — absorve calor do ambiente","alternativa_c":"Isoentálpica — sem variação de calor","alternativa_d":"Reversível — sem variação de entalpia","alternativa_e":"Radioativa — emite radiação","resposta_correta":"a","explicacao":"ΔH < 0 significa que o sistema perde energia na forma de calor, aquecendo o ambiente. Reações exotérmicas têm ΔH negativo (ex.: combustão).","resposta":""},
  {"id":"3599","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema Nervoso","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Os neurônios transmitem impulsos nervosos por meio de:","alternativa_a":"Potencial de ação e sinapses químicas/elétricas","alternativa_b":"Difusão passiva de glicose","alternativa_c":"Contrações musculares","alternativa_d":"Secreção hormonal direta","alternativa_e":"Gradientes de temperatura","resposta_correta":"a","explicacao":"O impulso nervoso é o potencial de ação (variação no potencial elétrico da membrana). Entre neurônios, a transmissão ocorre nas sinapses, que podem ser químicas (neurotransmissores) ou elétricas.","resposta":""},
  {"id":"3600","tipo":"multipla","disciplina":"Geografia","tema":"Geografia do Brasil","subtema":"Clima e Vegetação","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"O bioma Cerrado é caracterizado por:","alternativa_a":"Vegetação savânica com árvores tortuosas e gramíneas, clima tropical estacional","alternativa_b":"Floresta densa e úmida, clima equatorial","alternativa_c":"Vegetação de cactáceas e clima semiárido","alternativa_d":"Campos temperados com pinheiro-do-paraná","alternativa_e":"Mangues e restingas no litoral","resposta_correta":"a","explicacao":"O Cerrado é uma savana tropical com árvores de cascas grossas e tortuosas, adaptadas ao fogo e à seca. Predomina no Brasil Central com clima tropical estacional (seco no inverno).","resposta":""},
  {"id":"4421","tipo":"dissertativa","disciplina":"Matemática","tema":"Geometria Espacial","subtema":"Volume de Sólidos","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Um cubo tem aresta de 4 cm. Calcule seu volume e a área total de suas faces.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"Volume do cubo: V = a³ = 4³ = 64 cm³. Área total: o cubo tem 6 faces quadradas, cada uma com área 4² = 16 cm². Logo, área total = 6 × 16 = 96 cm².","resposta":"V = 64 cm³; Área total = 96 cm²"},
  {"id":"4422","tipo":"dissertativa","disciplina":"Física","tema":"Mecânica","subtema":"Trabalho e Energia","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Uma força de 50 N é aplicada paralelamente ao deslocamento de um objeto por 8 m. Calcule o trabalho realizado e explique o conceito de trabalho em Física.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"Trabalho (τ) = F · d · cos θ. Como a força é paralela ao deslocamento, θ = 0°, cos 0° = 1. τ = 50 × 8 × 1 = 400 J. Em Física, trabalho é a transferência de energia resultante da ação de uma força sobre um deslocamento. Sua unidade é o Joule (J = N·m).","resposta":"Trabalho = 400 J; é a transferência de energia por força aplicada ao longo de um deslocamento"},
  {"id":"4423","tipo":"dissertativa","disciplina":"Química","tema":"Soluções","subtema":"Concentração Molar","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Calcule a concentração molar (mol/L) de uma solução obtida dissolvendo 5,85 g de NaCl (M = 58,5 g/mol) em água suficiente para 500 mL de solução.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"n(NaCl) = massa / M = 5,85 / 58,5 = 0,1 mol. Volume = 500 mL = 0,5 L. Concentração molar: C = n/V = 0,1 / 0,5 = 0,2 mol/L.","resposta":"C = 0,2 mol/L"},
  {"id":"4424","tipo":"dissertativa","disciplina":"Biologia","tema":"Botânica","subtema":"Fotossíntese","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Explique as duas etapas da fotossíntese (fase clara e fase escura) e indique em qual estrutura celular cada uma ocorre.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"A fotossíntese ocorre nos cloroplastos e divide-se em: (1) Fase clara (fotoquímica) — ocorre nas membranas dos tilacoides (grana); a energia luminosa é captada pela clorofila, gerando ATP, NADPH e O₂ (fotólise da água). (2) Fase escura (ciclo de Calvin) — ocorre no estroma do cloroplasto; utiliza ATP e NADPH para fixar o CO₂ em compostos orgânicos (glicose), sem necessitar diretamente de luz.","resposta":"Fase clara (tilacoides): produz ATP, NADPH e O₂. Fase escura (estroma): usa ATP e NADPH para fixar CO₂ e produzir glicose"},
  {"id":"4425","tipo":"dissertativa","disciplina":"História","tema":"História Geral","subtema":"Revolução Francesa","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Explique os três princípios do lema da Revolução Francesa ('Liberdade, Igualdade, Fraternidade') e seu impacto histórico.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"(1) Liberdade: fim do absolutismo e das restrições feudais, direito à livre expressão e propriedade. (2) Igualdade: eliminação dos privilégios da nobreza e do clero; igualdade perante a lei. (3) Fraternidade: solidariedade entre cidadãos, base para direitos sociais. Impacto: a Revolução Francesa (1789) inspirou movimentos democráticos e republicanos em todo o mundo, pondo fim ao Antigo Regime e consolidando os ideais iluministas.","resposta":"Liberdade (fim do absolutismo), Igualdade (perante a lei), Fraternidade (solidariedade); base dos ideais democráticos modernos"},
  {"id":"4426","tipo":"dissertativa","disciplina":"Língua Portuguesa","tema":"Redação","subtema":"Tipos Textuais","dificuldade":"Fácil","fonte":"Vestibular","ano":"2024","enunciado":"Diferencie texto dissertativo-argumentativo de texto narrativo, citando uma característica principal de cada um.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"O texto dissertativo-argumentativo tem como objetivo defender uma tese ou ponto de vista, utilizando argumentos e fundamentação lógica. Característica principal: presença de tese, argumentos e conclusão. O texto narrativo conta uma história ou sequência de eventos com personagens, tempo, espaço e enredo. Característica principal: presença de narrador, personagens e ação temporal.","resposta":"Dissertativo-argumentativo: defende tese com argumentos; Narrativo: conta história com personagens e enredo"},
  {"id":"4427","tipo":"dissertativa","disciplina":"Filosofia","tema":"Filosofia Política","subtema":"Contratualismo","dificuldade":"Difícil","fonte":"Vestibular","ano":"2024","enunciado":"Compare as concepções de 'estado de natureza' em Thomas Hobbes e Jean-Jacques Rousseau.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"Para Hobbes ('Leviatã'), o estado de natureza é de guerra de todos contra todos ('bellum omnium contra omnes'), pois o ser humano é naturalmente egoísta. Para fugir desse caos, os indivíduos cedem seus direitos a um soberano absoluto. Para Rousseau ('Discurso sobre a Desigualdade'), o ser humano é naturalmente bom (o 'bom selvagem'); a sociedade e a propriedade privada é que corrompem o homem. Assim, Hobbes vê a natureza humana como má, enquanto Rousseau a vê como boa.","resposta":"Hobbes: natureza humana má, guerra de todos contra todos. Rousseau: homem naturalmente bom, corrompido pela sociedade"},
  {"id":"4428","tipo":"dissertativa","disciplina":"Sociologia","tema":"Desigualdade Social","subtema":"Mobilidade Social","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"O que é mobilidade social e quais fatores podem dificultá-la em sociedades contemporâneas?","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"Mobilidade social é a capacidade de um indivíduo ou grupo de mudar de posição na hierarquia social, podendo ser ascendente (subida) ou descendente (queda). Fatores que dificultam: concentração de renda e riqueza, acesso desigual à educação de qualidade, discriminação racial e de gênero, herança de capital social e cultural, nepotismo e favorecimento de elites. Sociedades com alta desigualdade estrutural tendem a ter baixa mobilidade social.","resposta":"Mobilidade social = mudança de posição na hierarquia; barreiras incluem desigualdade de renda, educação precária e discriminação"},
  {"id":"4429","tipo":"dissertativa","disciplina":"Geografia","tema":"Urbanização","subtema":"Problemas Urbanos","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Discuta dois problemas socioambientais resultantes do processo de urbanização acelerada nas grandes cidades brasileiras.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"(1) Ilhas de calor: a substituição de vegetação por asfalto e concreto aumenta a absorção de calor e eleva a temperatura nas cidades, agravando o desconforto térmico e o consumo de energia. (2) Enchentes e deslizamentos: a impermeabilização do solo impede a infiltração de água; ocupações irregulares em encostas e áreas de várzea ficam expostas a riscos geológicos e hidrológicos durante chuvas intensas. Outros problemas: poluição do ar, déficit habitacional, violência urbana.","resposta":"Ilhas de calor (impermeabilização e falta de vegetação) e enchentes/deslizamentos (ocupação irregular e solo impermeável)"},
  {"id":"4430","tipo":"dissertativa","disciplina":"Matemática","tema":"Álgebra","subtema":"Equações do 2º Grau","dificuldade":"Médio","fonte":"Vestibular","ano":"2024","enunciado":"Resolva a equação x² − 5x + 6 = 0 pela fórmula de Bhaskara e interprete geometricamente as raízes como pontos de interseção de uma parábola com o eixo x.","alternativa_a":"","alternativa_b":"","alternativa_c":"","alternativa_d":"","alternativa_e":"","resposta_correta":"","explicacao":"Δ = b² − 4ac = 25 − 24 = 1. x = (5 ± 1)/2 → x₁ = 3 e x₂ = 2. Interpretação: a parábola y = x² − 5x + 6, aberta para cima, cruza o eixo x nos pontos (2, 0) e (3, 0), que são as raízes da equação. O vértice da parábola fica em x = 2,5 com y = −0,25 (ponto mínimo).","resposta":"x₁ = 3 e x₂ = 2; geometricamente são os pontos onde a parábola y = x² − 5x + 6 toca o eixo x"},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote15.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questões: {len(questions)}')
print(f'CSV gerado: {out}')
