# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4359","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Analitica","subtema":"Distancia entre ponto e reta","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A distancia do ponto P(3, 4) a reta 3x + 4y - 10 = 0 e:","alternativa_a":"1","alternativa_b":"2","alternativa_c":"3","alternativa_d":"4","alternativa_e":"5","resposta_correta":"a","explicacao":"d = |3(3) + 4(4) - 10| / sqrt(9+16) = |9+16-10|/5 = 15/5 = 3. Aguarda, d = |9+16-10|/sqrt(25) = 15/5 = 3. Resposta: 3.","resposta":""},
  {"id":"4360","tipo":"multipla","disciplina":"Matematica","tema":"Numeros Complexos","subtema":"Forma trigonometrica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O modulo do numero complexo z = 3 + 4i e:","alternativa_a":"5","alternativa_b":"7","alternativa_c":"sqrt(7)","alternativa_d":"25","alternativa_e":"1","resposta_correta":"a","explicacao":"|z| = sqrt(3^2 + 4^2) = sqrt(9+16) = sqrt(25) = 5.","resposta":""},
  {"id":"4361","tipo":"multipla","disciplina":"Matematica","tema":"Progressao Aritmetica","subtema":"Soma dos termos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Na PA (2, 5, 8, 11, ...), a soma dos 10 primeiros termos e:","alternativa_a":"155","alternativa_b":"140","alternativa_c":"120","alternativa_d":"170","alternativa_e":"100","resposta_correta":"a","explicacao":"a1=2, r=3, a10=2+9*3=29. S10=10*(2+29)/2=10*31/2=155.","resposta":""},
  {"id":"4362","tipo":"multipla","disciplina":"Matematica","tema":"Progressao Geometrica","subtema":"Termo geral","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na PG (3, 6, 12, 24, ...), o 8o termo e:","alternativa_a":"384","alternativa_b":"192","alternativa_c":"768","alternativa_d":"96","alternativa_e":"256","resposta_correta":"a","explicacao":"a1=3, q=2, a8=3*2^7=3*128=384.","resposta":""},
  {"id":"4363","tipo":"multipla","disciplina":"Matematica","tema":"Logaritmos","subtema":"Propriedades","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O valor de log2(64) e:","alternativa_a":"6","alternativa_b":"5","alternativa_c":"7","alternativa_d":"8","alternativa_e":"4","resposta_correta":"a","explicacao":"2^6 = 64, entao log2(64) = 6.","resposta":""},
  {"id":"4364","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Lei dos Cossenos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em um triangulo com lados a=5, b=7 e angulo C=60 graus, o lado c e aproximadamente:","alternativa_a":"6,24","alternativa_b":"7,55","alternativa_c":"5,00","alternativa_d":"8,00","alternativa_e":"4,58","resposta_correta":"a","explicacao":"c^2 = a^2 + b^2 - 2ab*cos(C) = 25+49-2(5)(7)(0,5) = 74-35 = 39. c = sqrt(39) ≈ 6,24.","resposta":""},
  {"id":"4365","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Media ponderada","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um aluno obteve notas 6, 7 e 9 com pesos 1, 2 e 3 respectivamente. Sua media ponderada e:","alternativa_a":"7,83","alternativa_b":"7,33","alternativa_c":"8,00","alternativa_d":"7,50","alternativa_e":"6,50","resposta_correta":"a","explicacao":"MP = (6*1 + 7*2 + 9*3)/(1+2+3) = (6+14+27)/6 = 47/6 ≈ 7,83.","resposta":""},
  {"id":"4366","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao modular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A solucao da equacao |2x - 3| = 5 e:","alternativa_a":"x=4 ou x=-1","alternativa_b":"x=4 ou x=1","alternativa_c":"x=-4 ou x=1","alternativa_d":"x=3 ou x=-2","alternativa_e":"x=2 ou x=-4","resposta_correta":"a","explicacao":"2x-3=5 => x=4; ou 2x-3=-5 => 2x=-2 => x=-1. Logo x=4 ou x=-1.","resposta":""},
  {"id":"4367","tipo":"multipla","disciplina":"Matematica","tema":"Combinatoria","subtema":"Principio multiplicativo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"De quantas formas diferentes podemos escolher 1 camisa (3 opcoes) e 1 calca (4 opcoes)?","alternativa_a":"12","alternativa_b":"7","alternativa_c":"10","alternativa_d":"6","alternativa_e":"8","resposta_correta":"a","explicacao":"Pelo principio multiplicativo: 3 x 4 = 12 formas.","resposta":""},
  {"id":"4368","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Cone","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O volume de um cone com raio da base r=3 e altura h=4 e: (use pi=3,14)","alternativa_a":"37,68","alternativa_b":"113,04","alternativa_c":"75,36","alternativa_d":"50,24","alternativa_e":"25,12","resposta_correta":"a","explicacao":"V = (1/3)*pi*r^2*h = (1/3)*3,14*9*4 = (1/3)*113,04 = 37,68.","resposta":""},
  {"id":"4369","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Reflexao e espelhos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um objeto e colocado a 30 cm de um espelho concavo de foco 10 cm. A imagem se forma a:","alternativa_a":"15 cm","alternativa_b":"10 cm","alternativa_c":"20 cm","alternativa_d":"30 cm","alternativa_e":"45 cm","resposta_correta":"a","explicacao":"1/f = 1/p + 1/p' => 1/10 = 1/30 + 1/p' => 1/p' = 1/10 - 1/30 = 3/30 - 1/30 = 2/30 => p' = 15 cm.","resposta":""},
  {"id":"4370","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Refracao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Um raio de luz passa do ar (n=1) para o vidro (n=1,5) com angulo de incidencia de 30 graus. O seno do angulo de refracao e:","alternativa_a":"1/3","alternativa_b":"1/2","alternativa_c":"sqrt(3)/3","alternativa_d":"2/3","alternativa_e":"sqrt(2)/2","resposta_correta":"a","explicacao":"Lei de Snell: n1*sen(i) = n2*sen(r) => 1*0,5 = 1,5*sen(r) => sen(r) = 0,5/1,5 = 1/3.","resposta":""},
  {"id":"4371","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Lei dos gases","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um gas ideal ocupa 2 L a 300 K. Mantendo a pressao constante, a que temperatura ocupara 3 L?","alternativa_a":"450 K","alternativa_b":"200 K","alternativa_c":"600 K","alternativa_d":"150 K","alternativa_e":"350 K","resposta_correta":"a","explicacao":"Lei de Charles: V1/T1 = V2/T2 => 2/300 = 3/T2 => T2 = 3*300/2 = 450 K.","resposta":""},
  {"id":"4372","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Campo magnetico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma carga q=2C move-se com velocidade v=3 m/s perpendicularmente a um campo magnetico B=4 T. A forca magnetica e:","alternativa_a":"24 N","alternativa_b":"12 N","alternativa_c":"6 N","alternativa_d":"48 N","alternativa_e":"8 N","resposta_correta":"a","explicacao":"F = q*v*B*sen(90) = 2*3*4*1 = 24 N.","resposta":""},
  {"id":"4373","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Trabalho e energia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma forca de 10 N desloca um objeto 5 m na direcao da forca. O trabalho realizado e:","alternativa_a":"50 J","alternativa_b":"15 J","alternativa_c":"2 J","alternativa_d":"100 J","alternativa_e":"25 J","resposta_correta":"a","explicacao":"T = F * d * cos(0) = 10 * 5 * 1 = 50 J.","resposta":""},
  {"id":"4374","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Potencia","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um motor realiza 600 J de trabalho em 2 minutos. Sua potencia e:","alternativa_a":"5 W","alternativa_b":"300 W","alternativa_c":"1200 W","alternativa_d":"0,05 W","alternativa_e":"10 W","resposta_correta":"a","explicacao":"P = T/t = 600 J / 120 s = 5 W.","resposta":""},
  {"id":"4375","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Velocidade de propagacao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Uma onda tem frequencia 50 Hz e comprimento de onda 4 m. Sua velocidade de propagacao e:","alternativa_a":"200 m/s","alternativa_b":"12,5 m/s","alternativa_c":"54 m/s","alternativa_d":"46 m/s","alternativa_e":"100 m/s","resposta_correta":"a","explicacao":"v = f * lambda = 50 * 4 = 200 m/s.","resposta":""},
  {"id":"4376","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Gravitacao universal","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Qual grandeza fisica esta associada ao peso de um objeto?","alternativa_a":"Forca gravitacional","alternativa_b":"Massa inercial","alternativa_c":"Densidade","alternativa_d":"Pressao","alternativa_e":"Volume","resposta_correta":"a","explicacao":"O peso e a forca gravitacional exercida pelo planeta sobre o objeto: P = m*g.","resposta":""},
  {"id":"4377","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Calorimetria","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Quantas calorias sao necessarias para aquecer 200 g de agua de 20 oC a 70 oC? (c=1 cal/g.oC)","alternativa_a":"10.000 cal","alternativa_b":"14.000 cal","alternativa_c":"4.000 cal","alternativa_d":"200 cal","alternativa_e":"1.000 cal","resposta_correta":"a","explicacao":"Q = m*c*DeltaT = 200*1*50 = 10.000 cal.","resposta":""},
  {"id":"4378","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Capacitores","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A energia armazenada em um capacitor de capacitancia C=4 F carregado com tensao V=3 V e:","alternativa_a":"18 J","alternativa_b":"12 J","alternativa_c":"6 J","alternativa_d":"36 J","alternativa_e":"9 J","resposta_correta":"a","explicacao":"E = (1/2)*C*V^2 = (1/2)*4*9 = 18 J.","resposta":""},
  {"id":"4379","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Calculos com mol","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Quantos mols ha em 44 g de CO2? (M: C=12, O=16)","alternativa_a":"1 mol","alternativa_b":"2 mol","alternativa_c":"0,5 mol","alternativa_d":"44 mol","alternativa_e":"3 mol","resposta_correta":"a","explicacao":"M(CO2) = 12 + 2*16 = 44 g/mol. n = m/M = 44/44 = 1 mol.","resposta":""},
  {"id":"4380","tipo":"multipla","disciplina":"Quimica","tema":"Solucoes","subtema":"Concentracao molar","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Qual a concentracao molar de uma solucao com 0,5 mol de NaCl em 250 mL?","alternativa_a":"2 mol/L","alternativa_b":"0,5 mol/L","alternativa_c":"1 mol/L","alternativa_d":"4 mol/L","alternativa_e":"0,25 mol/L","resposta_correta":"a","explicacao":"C = n/V = 0,5 mol / 0,25 L = 2 mol/L.","resposta":""},
  {"id":"4381","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Eletrolise","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na eletrolise da agua, o gas que se forma no catodo e:","alternativa_a":"Hidrogenio","alternativa_b":"Oxigenio","alternativa_c":"Ozonio","alternativa_d":"Vapor dagua","alternativa_e":"Nitrogenio","resposta_correta":"a","explicacao":"No catodo ocorre reducao: 2H2O + 2e- -> H2 + 2OH-. Forma-se hidrogenio.","resposta":""},
  {"id":"4382","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Alcanos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual a formula geral dos alcanos?","alternativa_a":"CnH2n+2","alternativa_b":"CnH2n","alternativa_c":"CnH2n-2","alternativa_d":"CnHn","alternativa_e":"CnH2n+1","resposta_correta":"a","explicacao":"Alcanos sao hidrocarbonetos de cadeia aberta saturada com formula geral CnH2n+2.","resposta":""},
  {"id":"4383","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes organicas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de adicao de HBr ao eteno (CH2=CH2) produz:","alternativa_a":"Bromoetano","alternativa_b":"Etanol","alternativa_c":"Dibromoetano","alternativa_d":"Etanal","alternativa_e":"Acido acetico","resposta_correta":"a","explicacao":"CH2=CH2 + HBr -> CH3-CH2Br (bromoetano). A adicao ocorre na dupla ligacao.","resposta":""},
  {"id":"4384","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Oxidos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O CO2 e um oxido classificado como:","alternativa_a":"Acido","alternativa_b":"Basico","alternativa_c":"Neutro","alternativa_d":"Anfotereo","alternativa_e":"Peroxido","resposta_correta":"a","explicacao":"CO2 e um oxido acido pois ao reagir com agua forma acido carbonico: CO2 + H2O -> H2CO3.","resposta":""},
  {"id":"4385","tipo":"multipla","disciplina":"Quimica","tema":"Termoquimica","subtema":"Entalpia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma reacao exotermica tem variacao de entalpia:","alternativa_a":"DH negativo","alternativa_b":"DH positivo","alternativa_c":"DH igual a zero","alternativa_d":"DH indefinido","alternativa_e":"DH depende da temperatura","resposta_correta":"a","explicacao":"Reacoes exotermicas liberam calor para o meio, portanto DH < 0 (negativo).","resposta":""},
  {"id":"4386","tipo":"multipla","disciplina":"Quimica","tema":"Equilibrio Quimico","subtema":"Principio de Le Chatelier","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Se aumentarmos a pressao em um sistema em equilibrio com gases, o equilibrio se deslocara para o lado que:","alternativa_a":"Tem menor numero de mols de gas","alternativa_b":"Tem maior numero de mols de gas","alternativa_c":"Nao se desloca","alternativa_d":"Tem maior temperatura","alternativa_e":"Tem menor entalpia","resposta_correta":"a","explicacao":"Pelo principio de Le Chatelier, o aumento de pressao desloca o equilibrio no sentido que diminui a pressao, ou seja, para o lado com menor numero de mols de gas.","resposta":""},
  {"id":"4387","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Efeito estufa","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual gas e o principal responsavel pelo efeito estufa de origem antropica?","alternativa_a":"Dioxido de carbono","alternativa_b":"Oxigenio","alternativa_c":"Nitrogenio","alternativa_d":"Argenio","alternativa_e":"Hidrogenio","resposta_correta":"a","explicacao":"O CO2 (dioxido de carbono) e o principal gas de efeito estufa emitido por atividades humanas, principalmente pela queima de combustiveis fosseis.","resposta":""},
  {"id":"4388","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Membrana plasmatica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O modelo de mosaico fluido da membrana plasmatica foi proposto por:","alternativa_a":"Singer e Nicolson","alternativa_b":"Watson e Crick","alternativa_c":"Schleiden e Schwann","alternativa_d":"Darwin e Wallace","alternativa_e":"Mendel e Morgan","resposta_correta":"a","explicacao":"Singer e Nicolson propuseram o modelo de mosaico fluido em 1972, descrevendo a membrana como uma bicamada lipidica com proteinas inseridas.","resposta":""},
  {"id":"4389","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Lei de Mendel","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"No cruzamento AaBb x AaBb, qual a proporcao de individuos com fenotipos dominantes para ambos os caracteres?","alternativa_a":"9/16","alternativa_b":"3/16","alternativa_c":"1/16","alternativa_d":"6/16","alternativa_e":"12/16","resposta_correta":"a","explicacao":"No diibridismo (9:3:3:1), 9/16 dos descendentes apresentam ambos os fenotipos dominantes (A_B_).","resposta":""},
  {"id":"4390","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Cadeia alimentar","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma cadeia alimentar, os organismos que produzem materia organica a partir de substancias inorganicas sao chamados de:","alternativa_a":"Produtores","alternativa_b":"Consumidores","alternativa_c":"Decompositores","alternativa_d":"Parasitas","alternativa_e":"Predadores","resposta_correta":"a","explicacao":"Os produtores (plantas, algas, bacterias fotosinteticas) realizam fotossintese ou quimiossintese, produzindo materia organica a partir de substancias inorganicas.","resposta":""},
  {"id":"4391","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Vegetal","subtema":"Fotossintese","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na fotossintese, a fase luminosa ocorre nas:","alternativa_a":"Membranas dos tilacoides","alternativa_b":"Estroma dos cloroplastos","alternativa_c":"Mitocondrias","alternativa_d":"Membrana plasmatica","alternativa_e":"Nucleo celular","resposta_correta":"a","explicacao":"A fase luminosa (clara) ocorre nas membranas dos tilacoides, onde esta a clorofila e os complexos de captacao de luz.","resposta":""},
  {"id":"4392","tipo":"multipla","disciplina":"Biologia","tema":"Zoologia","subtema":"Vertebrados","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual caracteristica e exclusiva dos mamiferos?","alternativa_a":"Presenca de glandulas mamarias","alternativa_b":"Respiracao pulmonar","alternativa_c":"Fecundacao interna","alternativa_d":"Sangue quente","alternativa_e":"Possuem coluna vertebral","resposta_correta":"a","explicacao":"As glandulas mamarias, que produzem leite para alimentar os filhotes, sao exclusivas dos mamiferos.","resposta":""},
  {"id":"4393","tipo":"multipla","disciplina":"Biologia","tema":"Microbiologia","subtema":"Bacterias","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As bacterias gram-positivas se diferenciam das gram-negativas pelo:","alternativa_a":"Maior espessura de peptidoglicano","alternativa_b":"Presenca de nucleo","alternativa_c":"Menor tamanho celular","alternativa_d":"Ausencia de membrana plasmatica","alternativa_e":"Presenca de mitocondrias","resposta_correta":"a","explicacao":"Bacterias gram-positivas possuem parede celular espessa de peptidoglicano e reteem o corante violeta de genciana, ficando roxas na coloracao de Gram.","resposta":""},
  {"id":"4394","tipo":"multipla","disciplina":"Biologia","tema":"Bioquimica","subtema":"Enzimas","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O local da enzima onde o substrato se liga e denominado:","alternativa_a":"Sitio ativo","alternativa_b":"Cofator","alternativa_c":"Prostet ico","alternativa_d":"Alosterico","alternativa_e":"Coenzima","resposta_correta":"a","explicacao":"O sitio ativo e a regiao especifica da enzima onde o substrato se liga para formar o complexo enzima-substrato e a reacao ocorre.","resposta":""},
  {"id":"4395","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Revolucao de 1930","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Revolucao de 1930 encerrou o periodo denominado:","alternativa_a":"Republica Velha","alternativa_b":"Imperio","alternativa_c":"Regime Militar","alternativa_d":"Nova Republica","alternativa_e":"Periodo Regencial","resposta_correta":"a","explicacao":"A Revolucao de 1930, liderada por Getulio Vargas, ps fim a Republica Velha (1889-1930), marcada pela politica cafe-com-leite.","resposta":""},
  {"id":"4396","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Estado Novo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Estado Novo (1937-1945) foi um regime ditatorial implantado por:","alternativa_a":"Getulio Vargas","alternativa_b":"Eurico Gaspar Dutra","alternativa_c":"Juscelino Kubitschek","alternativa_d":"Joao Goulart","alternativa_e":"Castello Branco","resposta_correta":"a","explicacao":"Getulio Vargas implantou o Estado Novo em novembro de 1937, com um golpe de Estado que instaurou uma ditadura inspirada no fascismo europeu.","resposta":""},
  {"id":"4397","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Primeira Guerra Mundial","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O estopim imediato da Primeira Guerra Mundial foi:","alternativa_a":"Assassinato do arquiduque Francisco Fernando","alternativa_b":"Invasao da Polonia","alternativa_c":"Ataque a Pearl Harbor","alternativa_d":"Queda da Bastilha","alternativa_e":"Crise dos misseis em Cuba","resposta_correta":"a","explicacao":"O assassinato do arquiduque Francisco Fernando do Imperio Austro-Hungaro em Sarajevo, em junho de 1914, desencadeou a Primeira Guerra Mundial.","resposta":""},
  {"id":"4398","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Nazismo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O regime nazista na Alemanha foi liderado por:","alternativa_a":"Adolf Hitler","alternativa_b":"Benito Mussolini","alternativa_c":"Joseph Stalin","alternativa_d":"Francisco Franco","alternativa_e":"Winston Churchill","resposta_correta":"a","explicacao":"Adolf Hitler liderou o regime nazista (Nacional-Socialismo) na Alemanha a partir de 1933, quando assumiu o cargo de chanceler.","resposta":""},
  {"id":"4399","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Guerra Fria","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A queda do Muro de Berlim em 1989 simbolizou o fim da:","alternativa_a":"Guerra Fria","alternativa_b":"Segunda Guerra Mundial","alternativa_c":"Primeira Guerra Mundial","alternativa_d":"Guerra do Vietna","alternativa_e":"Revolucao Cubana","resposta_correta":"a","explicacao":"A queda do Muro de Berlim em novembro de 1989 simbolizou o fim da Guerra Fria e da divisao entre o mundo capitalista e comunista.","resposta":""},
  {"id":"4400","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Ditadura Militar","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O AI-5 (Ato Institucional numero 5), decretado em 1968, e considerado o mais duro do periodo militar brasileiro pois:","alternativa_a":"Suspendeu garantias constitucionais e fechou o Congresso","alternativa_b":"Criou a censura a imprensa","alternativa_c":"Estabeleceu eleicoes diretas","alternativa_d":"Decretou anistia politica","alternativa_e":"Criou o bipartidarismo","resposta_correta":"a","explicacao":"O AI-5 suspendeu direitos constitucionais, fechou o Congresso Nacional, cassou mandatos e autorizou a perseguicao de opositores, inaugurando o periodo mais repressivo da ditadura.","resposta":""},
  {"id":"4401","tipo":"multipla","disciplina":"Geografia","tema":"Climatologia","subtema":"Tipos de clima","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O clima tropical e caracterizado por:","alternativa_a":"Duas estacoes bem definidas: seca e chuvosa","alternativa_b":"Quatro estacoes bem definidas","alternativa_c":"Chuvas uniformemente distribuidas ao longo do ano","alternativa_d":"Ausencia de chuvas","alternativa_e":"Temperatura constante abaixo de 0 graus","resposta_correta":"a","explicacao":"O clima tropical apresenta duas estacoes bem definidas: uma seca (inverno) e uma chuvosa (verao), com temperaturas elevadas durante todo o ano.","resposta":""},
  {"id":"4402","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"BRICS","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O grupo BRICS e formado pelas economias emergentes de Brasil, Russia, India, China e:","alternativa_a":"Africa do Sul","alternativa_b":"Mexico","alternativa_c":"Indonesia","alternativa_d":"Argentina","alternativa_e":"Nigeria","resposta_correta":"a","explicacao":"O BRICS e composto por Brasil, Russia, India, China e Africa do Sul (incluida em 2010). E um bloco de paises com economias em rapido desenvolvimento.","resposta":""},
  {"id":"4403","tipo":"multipla","disciplina":"Geografia","tema":"Geografia do Brasil","subtema":"Regioes brasileiras","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual regiao brasileira concentra o maior PIB do pais?","alternativa_a":"Sudeste","alternativa_b":"Sul","alternativa_c":"Centro-Oeste","alternativa_d":"Nordeste","alternativa_e":"Norte","resposta_correta":"a","explicacao":"A regiao Sudeste concentra aproximadamente 54% do PIB brasileiro, sendo o nucleo economico do pais, com destaque para Sao Paulo, Rio de Janeiro e Minas Gerais.","resposta":""},
  {"id":"4404","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Metropolizacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo de formacao de grandes regioes urbanas a partir de cidades que se expandem e se interligam e chamado de:","alternativa_a":"Metropolizacao","alternativa_b":"Ruralizacao","alternativa_c":"Litoralizacao","alternativa_d":"Interiorizacao","alternativa_e":"Suburbanizacao","resposta_correta":"a","explicacao":"A metropolizacao e o processo de crescimento e expansao das metropoles, que absorvem municipios vizinhos formando regioes metropolitanas.","resposta":""},
  {"id":"4405","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Romantismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Jose de Alencar e um dos principais autores do Romantismo brasileiro. Sua obra 'O Guarani' pertence ao chamado:","alternativa_a":"Indianismo","alternativa_b":"Ultrarromantismo","alternativa_c":"Condoreirismo","alternativa_d":"Realismo","alternativa_e":"Naturalismo","resposta_correta":"a","explicacao":"Jose de Alencar e um dos grandes nomes do indianismo romantico, que valorizava o indigena como simbolo da identidade nacional brasileira.","resposta":""},
  {"id":"4406","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Concordancia nominal","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Assinale a alternativa em que a concordancia nominal esta CORRETA:","alternativa_a":"As alunas estavam cansadas","alternativa_b":"As aluna estavam cansada","alternativa_c":"As aluna estava cansadas","alternativa_d":"A alunas estava cansado","alternativa_e":"A aluna estava cansados","resposta_correta":"a","explicacao":"O adjetivo 'cansadas' concorda em genero (feminino) e numero (plural) com o sujeito 'alunas'. Portanto 'As alunas estavam cansadas' esta correto.","resposta":""},
  {"id":"4407","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Regencia verbal","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O verbo 'visar' no sentido de 'ter em mira, objetivar' e regido pela preposicao:","alternativa_a":"a","alternativa_b":"de","alternativa_c":"em","alternativa_d":"por","alternativa_e":"sem preposicao","resposta_correta":"a","explicacao":"Quando 'visar' significa 'ter em mira, objetivar', e verbo transitivo indireto e exige a preposicao 'a': 'Visamos a um futuro melhor'.","resposta":""},
  {"id":"4408","tipo":"multipla","disciplina":"Filosofia","tema":"Epistemologia","subtema":"Empirismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O filosofo britanico que defendeu que o conhecimento deriva exclusivamente da experiencia sensivel, sem ideias inatas, foi:","alternativa_a":"John Locke","alternativa_b":"Rene Descartes","alternativa_c":"Plato","alternativa_d":"Aristoteles","alternativa_e":"Kant","resposta_correta":"a","explicacao":"John Locke e o principal representante do empirismo classico, defendendo que a mente e uma tabula rasa e todo conhecimento vem da experiencia.","resposta":""},
  {"id":"4409","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Fato Social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Emile Durkheim definiu fato social como toda maneira de agir, fixa ou nao, suscetivel de exercer sobre o individuo uma restricao exterior. Qual caracteristica fundamental do fato social esta descrita?","alternativa_a":"Coercitividade","alternativa_b":"Espontaneidade","alternativa_c":"Subjetividade","alternativa_d":"Individualidade","alternativa_e":"Voluntariedade","resposta_correta":"a","explicacao":"A coercitividade (restricao exterior) e uma das caracteristicas fundamentais do fato social segundo Durkheim, ao lado da exterioridade e da generalidade.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote42.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
