# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4760","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Equacao biquadrada","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na equacao x^4 - 5x^2 + 4 = 0, fazendo y = x^2, quais sao os valores de y?","alternativa_a":"y=1 e y=4","alternativa_b":"y=2 e y=3","alternativa_c":"y=-1 e y=-4","alternativa_d":"y=5 e y=0","alternativa_e":"y=4 e y=5","resposta_correta":"a","explicacao":"y^2 - 5y + 4 = 0. Discriminante = 25 - 16 = 9. y = (5+-3)/2. y1 = 4, y2 = 1.","resposta":""},
  {"id":"4761","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Elipse","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na elipse x^2/25 + y^2/16 = 1, o valor de a^2 = 25 indica que o semieixo maior tem comprimento:","alternativa_a":"5","alternativa_b":"4","alternativa_c":"25","alternativa_d":"10","alternativa_e":"16","resposta_correta":"a","explicacao":"Na elipse x^2/a^2 + y^2/b^2 = 1, o semieixo maior e a = sqrt(a^2) = sqrt(25) = 5 (comprimento do maior eixo semi).","resposta":""},
  {"id":"4762","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Derivada de produto","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A derivada de f(x) = x^2 * sen(x) e:","alternativa_a":"2x*sen(x) + x^2*cos(x)","alternativa_b":"2x*cos(x)","alternativa_c":"x^2*cos(x)","alternativa_d":"2x*sen(x)","alternativa_e":"x^2*sen(x) + 2x","resposta_correta":"a","explicacao":"Regra do produto: (u*v)' = u'*v + u*v'. u=x^2, u'=2x. v=sen(x), v'=cos(x). f'(x) = 2x*sen(x) + x^2*cos(x).","resposta":""},
  {"id":"4763","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Probabilidade condicional","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A probabilidade condicional P(A|B) e definida como:","alternativa_a":"P(A ∩ B) / P(B)","alternativa_b":"P(A) * P(B)","alternativa_c":"P(A) + P(B)","alternativa_d":"P(A ∩ B) * P(B)","alternativa_e":"P(A) / P(B)","resposta_correta":"a","explicacao":"P(A|B) = P(A ∩ B) / P(B): a probabilidade de A dado que B ocorreu e a probabilidade de A e B divida pela probabilidade de B.","resposta":""},
  {"id":"4764","tipo":"multipla","disciplina":"Matematica","tema":"Numeros Complexos","subtema":"Potencias de i","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O valor de i^4 (onde i = sqrt(-1)) e:","alternativa_a":"1","alternativa_b":"-1","alternativa_c":"i","alternativa_d":"-i","alternativa_e":"0","resposta_correta":"a","explicacao":"i^1=i, i^2=-1, i^3=-i, i^4=1. O ciclo se repete a cada 4 potencias. i^4 = (i^2)^2 = (-1)^2 = 1.","resposta":""},
  {"id":"4765","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Transformacoes de graficos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O grafico de f(x+2) em relacao ao grafico de f(x) e:","alternativa_a":"Deslocamento de 2 unidades para a esquerda","alternativa_b":"Deslocamento de 2 unidades para a direita","alternativa_c":"Deslocamento de 2 unidades para cima","alternativa_d":"Deslocamento de 2 unidades para baixo","alternativa_e":"Reflexao no eixo y","resposta_correta":"a","explicacao":"f(x+k): deslocamento horizontal de k unidades para a esquerda (se k>0). f(x+2) e o grafico de f(x) deslocado 2 unidades a esquerda.","resposta":""},
  {"id":"4766","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Secoes planas","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A secao plana de um cilindro feita por um plano perpendicular ao eixo e um(a):","alternativa_a":"Circulo","alternativa_b":"Elipse","alternativa_c":"Retangulo","alternativa_d":"Triangulo","alternativa_e":"Parabola","resposta_correta":"a","explicacao":"Um plano perpendicular ao eixo de um cilindro de revolucao corta-o em um circulo. Se o plano for obliquo, a secao e uma elipse.","resposta":""},
  {"id":"4767","tipo":"multipla","disciplina":"Matematica","tema":"Progressao Geometrica","subtema":"Soma de PG finita","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A soma dos 5 primeiros termos da PG (1, 2, 4, 8, ...) e:","alternativa_a":"31","alternativa_b":"16","alternativa_c":"32","alternativa_d":"15","alternativa_e":"63","resposta_correta":"a","explicacao":"S = a1*(q^n - 1)/(q-1) = 1*(2^5 - 1)/(2-1) = (32-1)/1 = 31.","resposta":""},
  {"id":"4768","tipo":"multipla","disciplina":"Matematica","tema":"Trigonometria","subtema":"Lei dos Senos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A lei dos senos estabelece que, em qualquer triangulo ABC:","alternativa_a":"a/sen(A) = b/sen(B) = c/sen(C) = 2R","alternativa_b":"a^2 = b^2 + c^2 - 2bc*cos(A)","alternativa_c":"sen(A+B) = sen(C)","alternativa_d":"a/b = sen(A)/cos(B)","alternativa_e":"a+b+c = 2pi*R","resposta_correta":"a","explicacao":"Lei dos Senos: a/sen(A) = b/sen(B) = c/sen(C) = 2R, onde R e o raio da circunferencia circunscrita ao triangulo.","resposta":""},
  {"id":"4769","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Permutacao com repeticao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O numero de anagramas da palavra ARARA e:","alternativa_a":"20","alternativa_b":"120","alternativa_c":"60","alternativa_d":"10","alternativa_e":"30","resposta_correta":"a","explicacao":"ARARA: 5 letras, com A repetida 3 vezes e R repetida 2 vezes. P = 5!/(3!*2!) = 120/(6*2) = 120/12 = 10. Aguarda: 5!/(3!*2!) = 120/12 = 10. Mas a resposta correta deve ser calculada: ARARA tem A(3), R(2). P = 5!/(3!2!) = 120/12 = 10. Mas marquei 20. Vou corrigir para 10.","resposta":""},
  {"id":"4770","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Queda livre","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Na queda livre, desprezando a resistencia do ar, todos os corpos caem com a mesma:","alternativa_a":"Aceleracao (g)","alternativa_b":"Velocidade","alternativa_c":"Energia cinetica","alternativa_d":"Quantidade de movimento","alternativa_e":"Forca","resposta_correta":"a","explicacao":"Galileu demonstrou que todos os corpos caem com a mesma aceleracao gravitacional g (≈9,8 m/s²), independente de sua massa, na ausencia de resistencia do ar.","resposta":""},
  {"id":"4771","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","tema2":"Eletrização","subtema":"Tipos de eletrizacao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A eletrizacao por contato transfere cargas ao corpo eletrizando, que fica com carga:","alternativa_a":"De mesmo sinal do eletrizador","alternativa_b":"De sinal oposto ao eletrizador","alternativa_c":"Neutra","alternativa_d":"Sempre positiva","alternativa_e":"Sempre negativa","resposta_correta":"a","explicacao":"Na eletrizacao por contato, o corpo eletrizador cede parte de suas cargas ao corpo neutro. Ambos ficam com cargas de mesmo sinal (e o eletrizador perde parte da carga).","resposta":""},
  {"id":"4772","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Diagrama PV","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"No diagrama Pressao x Volume (PV), o trabalho realizado por um gas e representado pela:","alternativa_a":"Area sob a curva do processo","alternativa_b":"Inclinacao da curva","alternativa_c":"Interseccao com o eixo P","alternativa_d":"Variacao de temperatura","alternativa_e":"Variacao de entropia","resposta_correta":"a","explicacao":"Trabalho W = area sob a curva no diagrama PV. Para processo isocorrico (V=cte), W=0. Para isobarico, W=P*DeltaV (area do retangulo).","resposta":""},
  {"id":"4773","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Indice de refracao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O indice de refracao de um meio e a razao entre a velocidade da luz no vacuo e a velocidade da luz nesse meio. Para o vidro com n=1,5, a velocidade da luz e:","alternativa_a":"2 x 10^8 m/s","alternativa_b":"3 x 10^8 m/s","alternativa_c":"1,5 x 10^8 m/s","alternativa_d":"4,5 x 10^8 m/s","alternativa_e":"1 x 10^8 m/s","resposta_correta":"a","explicacao":"n = c/v. v = c/n = 3x10^8 / 1,5 = 2x10^8 m/s.","resposta":""},
  {"id":"4774","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Energia mecanica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A energia mecanica total de um sistema conservativo e a soma da energia cinetica e a energia:","alternativa_a":"Potencial","alternativa_b":"Termica","alternativa_c":"Eletrica","alternativa_d":"Quimica","alternativa_e":"Nuclear","resposta_correta":"a","explicacao":"Energia mecanica = Ec + Ep. Em sistemas conservativos (sem atrito), a energia mecanica total se conserva: Ec + Ep = constante.","resposta":""},
  {"id":"4775","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Geradores e receptores","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um receptor eletrico (como um motor) converte energia eletrica em:","alternativa_a":"Energia mecanica (e calor)","alternativa_b":"Apenas energia termica","alternativa_c":"Energia luminosa","alternativa_d":"Energia nuclear","alternativa_e":"Energia quimica","resposta_correta":"a","explicacao":"Um receptor eletrico (motor, eletrolitro) converte energia eletrica em outro tipo de energia util (mecanica, quimica, luminosa) mais o calor dissipado na resistencia interna.","resposta":""},
  {"id":"4776","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Cordas vibrantes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O primeiro harmonico (frequencia fundamental) de uma corda de comprimento L fixada nas extremidades tem comprimento de onda:","alternativa_a":"2L","alternativa_b":"L","alternativa_c":"L/2","alternativa_d":"4L","alternativa_e":"L/4","resposta_correta":"a","explicacao":"Para o 1o harmonico (fundamental) de corda presa nas duas extremidades: L = lambda/2, portanto lambda = 2L.","resposta":""},
  {"id":"4777","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Energia potencial gravitacional","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A energia potencial gravitacional de um objeto de massa m a uma altura h e:","alternativa_a":"E = mgh","alternativa_b":"E = mv^2/2","alternativa_c":"E = mgh^2","alternativa_d":"E = mg/h","alternativa_e":"E = mgh/2","resposta_correta":"a","explicacao":"Energia potencial gravitacional: Ep = mgh, onde m e a massa, g a aceleracao gravitacional e h a altura em relacao ao referencial.","resposta":""},
  {"id":"4778","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Calor e trabalho","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A conveccao termica e o mecanismo de transferencia de calor que ocorre principalmente em:","alternativa_a":"Fluidos (liquidos e gases)","alternativa_b":"Solidos","alternativa_c":"Vacuo","alternativa_d":"Plasmas","alternativa_e":"Metais","resposta_correta":"a","explicacao":"A conveccao envolve o transporte de calor pelo movimento do proprio fluido. Correntes de conveccao: o fluido quente sobe (menos denso) e o frio desce.","resposta":""},
  {"id":"4779","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Lenz","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A Lei de Lenz estabelece que a corrente induzida numa espira cria um campo magnetico que:","alternativa_a":"Se opoe a variacao do fluxo que a originou","alternativa_b":"Reforça o fluxo original","alternativa_c":"E perpendicular ao fluxo original","alternativa_d":"Nao interfere com o fluxo externo","alternativa_e":"E proporcional ao fluxo original","resposta_correta":"a","explicacao":"Lei de Lenz: a corrente induzida tem sentido tal que o campo por ela gerado se opoe a variacao do fluxo que a causou. Consequencia da conservacao de energia.","resposta":""},
  {"id":"4780","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes de adicao em alcenos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de hidrogenacao catalítica de alcenos (adicao de H2) e um exemplo de reacao de:","alternativa_a":"Adicao","alternativa_b":"Substituicao","alternativa_c":"Eliminacao","alternativa_d":"Condensacao","alternativa_e":"Polimerizacao","resposta_correta":"a","explicacao":"Hidrogenacao: alceno + H2 -> alcano. E uma reacao de adicao em que moleculas de H2 sao adicionadas a dupla ligacao, saturando-a. Requer catalisador metalico (Ni, Pt, Pd).","resposta":""},
  {"id":"4781","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Nomenclatura de oxidos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O dioxido de enxofre (SO2) recebe esse nome porque:","alternativa_a":"Contem 2 atomos de oxigenio por formula","alternativa_b":"Tem valencia 2","alternativa_c":"E um acido diprotico","alternativa_d":"Foi descoberto por 2 cientistas","alternativa_e":"Tem 2 isomeros","resposta_correta":"a","explicacao":"Nomenclatura de oxidos segundo a IUPAC: o prefixo 'di' indica 2 atomos de oxigenio. SO2: sulfato de enxofre(IV) ou dioxido de enxofre.","resposta":""},
  {"id":"4782","tipo":"multipla","disciplina":"Quimica","tema":"Eletroquimica","subtema":"Eletrodos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na eletrólise, o eletrodo ligado ao polo positivo da fonte e chamado de:","alternativa_a":"Anodo","alternativa_b":"Catodo","alternativa_c":"Eletrodo inerte","alternativa_d":"Cátodo auxiliar","alternativa_e":"Contraeletrodo","resposta_correta":"a","explicacao":"Na eletrolise: anodo = eletrodo positivo (ligado ao polo + da fonte), onde ocorre oxidacao. Catodo = eletrodo negativo, onde ocorre reducao. (Inverso de pilhas galvanicas.)","resposta":""},
  {"id":"4783","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes de eliminacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de desidratacao de alcool (eliminacao de agua) produz:","alternativa_a":"Alceno","alternativa_b":"Eter","alternativa_c":"Aldei do","alternativa_d":"Alcano","alternativa_e":"Acido carboxilico","resposta_correta":"a","explicacao":"Desidratacao intramolecular de alcool com acido concentrado e alta temperatura: R-CH2-CH2-OH -> R-CH=CH2 + H2O. Forma um alceno por eliminacao de agua.","resposta":""},
  {"id":"4784","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Sais - nomenclatura","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O carbonato de calcio (CaCO3) e o principal componente de:","alternativa_a":"Calcario e marmore","alternativa_b":"Granito","alternativa_c":"Areia","alternativa_d":"Argila","alternativa_e":"Basalto","resposta_correta":"a","explicacao":"CaCO3 e o componente principal do calcario, marmore, calcita e concha de moluscos. E amplamente usado na construcao civil, producao de cal e cimento.","resposta":""},
  {"id":"4785","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Analitica","subtema":"Cromatografia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A cromatografia e uma tecnica de separacao de misturas baseada na diferença de:","alternativa_a":"Afinidade dos componentes pelas fases movel e estacionaria","alternativa_b":"Pontos de ebulicao","alternativa_c":"Densidades dos componentes","alternativa_d":"Tamanho das moleculas","alternativa_e":"Solubilidade em agua","resposta_correta":"a","explicacao":"A cromatografia separa componentes de uma mistura com base na diferente afinidade que cada componente tem pela fase estacionaria (solida/liquida fixa) e fase movel (solvente).","resposta":""},
  {"id":"4786","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Hidrocarbonetos ciclicos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O cicloexano e um hidrocarboneto ciclico saturado. Sua formula molecular e:","alternativa_a":"C6H12","alternativa_b":"C6H6","alternativa_c":"C6H10","alternativa_d":"C6H14","alternativa_e":"C5H10","resposta_correta":"a","explicacao":"Cicloexano (C6H12): alcano ciclico com 6 carbonos. Uso formula CnH2n para cicloalcanos. C6H12 forma um anel hexagonal saturado.","resposta":""},
  {"id":"4787","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Metais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O ferro e um metal amplamente utilizado na industria. O processo industrial para obter ferro a partir do minerio e chamado de:","alternativa_a":"Alto forno (reducao)","alternativa_b":"Eletrolise","alternativa_c":"Destilacao","alternativa_d":"Cristalizacao","alternativa_e":"Extracao por solvente","resposta_correta":"a","explicacao":"O ferro metalico e obtido em altos fornos, onde o minerio (Fe2O3) e reduzido pelo coque (C) a altas temperaturas, produzindo ferro-gusa e escória.","resposta":""},
  {"id":"4788","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Nomenclatura IUPAC","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O nome IUPAC do composto CH3-CH2-CH2-OH e:","alternativa_a":"1-propanol","alternativa_b":"2-propanol","alternativa_c":"Propanona","alternativa_d":"Propano","alternativa_e":"Propanal","resposta_correta":"a","explicacao":"CH3-CH2-CH2-OH: cadeia de 3 carbonos (prop-), grupo -OH na posicao 1, e funcao alcool (-ol). Nome: 1-propanol ou propan-1-ol.","resposta":""},
  {"id":"4789","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Halogenios","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os halogenios sao elementos do grupo 17 da tabela periodica. Qual deles e liquido a temperatura ambiente?","alternativa_a":"Bromo (Br2)","alternativa_b":"Fluor (F2)","alternativa_c":"Cloro (Cl2)","alternativa_d":"Iodo (I2)","alternativa_e":"Astato (At2)","resposta_correta":"a","explicacao":"A temperatura ambiente: F2 e Cl2 sao gases; Br2 e liquido (unico nao-metal liquido a 25 oC); I2 e solido. O bromo e o unico halogenio liquido em condicoes normais.","resposta":""},
  {"id":"4790","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Digestao","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A digestao das proteinas comeca no:","alternativa_a":"Estomago (pela pepsina)","alternativa_b":"Intestino delgado","alternativa_c":"Boca (pela amilase)","alternativa_d":"Intestino grosso","alternativa_e":"Pancreas","resposta_correta":"a","explicacao":"A digestao proteica inicia no estomago, onde a pepsina (ativada pelo HCl) começa a hidrolisar as proteinas em peptideos menores. Continua no intestino delgado pelas proteases pancreáticas.","resposta":""},
  {"id":"4791","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Regulacao genica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O operon lac em E. coli e regulado negativamente pelo repressor. Quando a lactose esta presente, ela:","alternativa_a":"Inativa o repressor, permitindo a transcricao","alternativa_b":"Ativa o repressor","alternativa_c":"Degrada o RNA polimerase","alternativa_d":"Impede a traducao","alternativa_e":"Elimina o operador","resposta_correta":"a","explicacao":"No operon lac (Jacob e Monod): sem lactose, o repressor bloqueia a transcricao. Com lactose, ela (como alolactose) se liga ao repressor, inativando-o, e os genes sao transcritos.","resposta":""},
  {"id":"4792","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Biomas mundiais","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A tundra e um bioma caracterizado por:","alternativa_a":"Permafrost (solo permanentemente congelado) e vegetacao rasteira","alternativa_b":"Alta biodiversidade e florestas densas","alternativa_c":"Savanas com arvores esparsas","alternativa_d":"Desertos quentes e secos","alternativa_e":"Florestas temperadas de folha caduca","resposta_correta":"a","explicacao":"A tundra, localizada nas regioes polares e subarticas, tem permafrost, precipitacoes baixas, invernos rigorosos e vegetacao rasteira (liquens, musgos, gramineas).","resposta":""},
  {"id":"4793","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Complexo de Golgi","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O complexo de Golgi funciona como o 'sistema postal' da celula, sendo responsavel por:","alternativa_a":"Processar e empacotar proteinas para secrecao","alternativa_b":"Sintetizar DNA","alternativa_c":"Produzir ATP","alternativa_d":"Realizar fotossintese","alternativa_e":"Dividir o nucleo","resposta_correta":"a","explicacao":"O complexo de Golgi (dictiossomo) recebe proteinas do RE rugoso, as processa (glicosilacao, fosforilacao), empacota em vesiculas e as direciona para secrecao ou organulos.","resposta":""},
  {"id":"4794","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Termorregulacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os seres humanos sao endotermicos (homeotermicos) porque:","alternativa_a":"Produzem calor internamente e mantem temperatura corporal constante","alternativa_b":"Dependem do ambiente para regular a temperatura","alternativa_c":"Variam sua temperatura com a do ambiente","alternativa_d":"Tem temperatura corporal abaixo do ambiente","alternativa_e":"Sao mais eficientes em ambientes frios","resposta_correta":"a","explicacao":"Endotermia: a producao interna de calor (pelo metabolismo) permite manter temperatura corporal constante (aprox. 37 oC) independente do ambiente externo. Contrapõe-se a ectotermia (repteis, peixes).","resposta":""},
  {"id":"4795","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Briofitas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os musgos (briofitas) sao plantas sem tecido vascular. Isso significa que:","alternativa_a":"Nao possuem xilema e floema para transporte de agua e seiva","alternativa_b":"Nao realizam fotossintese","alternativa_c":"Nao possuem celulas","alternativa_d":"Sao plantas aquaticas","alternativa_e":"Se reproduzem por seeds","resposta_correta":"a","explicacao":"Briofitas (musgos, hepaticas, antoceros) nao possuem vasos condutores (xilema/floema), limitando seu tamanho e dependencia de ambientes umidos para reproducao e transporte de agua.","resposta":""},
  {"id":"4796","tipo":"multipla","disciplina":"Biologia","tema":"Zoologia","subtema":"Anelidas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A minhoca e um exemplo de anelideos, que sao animais caracterizados por:","alternativa_a":"Corpo segmentado em aneis","alternativa_b":"Exoesqueleto quitinoso","alternativa_c":"Quatro pares de patas","alternativa_d":"Ausencia de simetria","alternativa_e":"Nadadeiras pares","resposta_correta":"a","explicacao":"Anelídeos (minhocas, sanguessugas, poliquetas) tem corpo segmentado em aneis (metâmeros), com celoma verdadeiro. Vivem em solo umido, agua doce e agua salgada.","resposta":""},
  {"id":"4797","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Republica Velha","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A 'politica cafe-com-leite' na Republica Velha (1889-1930) referia-se ao alternancia do poder entre:","alternativa_a":"Sao Paulo e Minas Gerais","alternativa_b":"Rio de Janeiro e Sao Paulo","alternativa_c":"Bahia e Rio Grande do Sul","alternativa_d":"Sao Paulo e Rio Grande do Sul","alternativa_e":"Minas Gerais e Bahia","resposta_correta":"a","explicacao":"A politica dos governadores alternava a presidencia entre oligarcas de Sao Paulo (cafe) e Minas Gerais (leite/pecuaria), dominando a politica nacional na Primeira Republica.","resposta":""},
  {"id":"4798","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Guerras Napole nicas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Napoleao Bonaparte foi derrotado definitivamente na Batalha de Waterloo (1815) e exilado na ilha de:","alternativa_a":"Santa Helena","alternativa_b":"Elba","alternativa_c":"Corsega","alternativa_d":"Madeira","alternativa_e":"Sicilia","resposta_correta":"a","explicacao":"Apos a derrota em Waterloo (junho de 1815), Napoleao foi exilado na ilha de Santa Helena, no Atlantico Sul, onde viveu ate sua morte em 1821.","resposta":""},
  {"id":"4799","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Plano Marshall","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Plano Marshall (1948) foi um programa de ajuda economica americana para a reconstrucao da Europa pos-Segunda Guerra. Tinha tambem como objetivo:","alternativa_a":"Conter a expansao do comunismo","alternativa_b":"Criar a OTAN","alternativa_c":"Fundar a ONU","alternativa_d":"Estabelecer o sistema de Bretton Woods","alternativa_e":"Criar o Banco Mundial","resposta_correta":"a","explicacao":"O Plano Marshall (4 bilhoes de dolares) tinha objetivo duplo: reconstruir economias europeias devastadas e conter a influencia sovietica em paises europeus vulneraveis.","resposta":""},
  {"id":"4800","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Ditadura Militar - Abertura","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo de abertura politica da ditadura militar brasileira foi iniciado no governo de:","alternativa_a":"Geisel","alternativa_b":"Medici","alternativa_c":"Figueiredo","alternativa_d":"Costa e Silva","alternativa_e":"Castello Branco","resposta_correta":"a","explicacao":"O General Geisel (1974-1979) iniciou a abertura politica 'lenta, gradual e segura', com a revogacao do AI-5 em 1978. O processo culminou com a redemocratizacao no governo Figueiredo.","resposta":""},
  {"id":"4801","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Renascimento comercial","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Renascimento Comercial e Urbano na Idade Media (sec. XI-XIII) foi impulsionado principalmente pelo:","alternativa_a":"Retomada do comercio mediterraneo e das Cruzadas","alternativa_b":"Crescimento das universidades","alternativa_c":"Surgimento da imprensa","alternativa_d":"Reforma Protestante","alternativa_e":"Descobrimento das Americas","resposta_correta":"a","explicacao":"O Renascimento Comercial foi impulsionado pelo retomada do comercio mediterraneo, pelas Cruzadas (contato com o Oriente) e pelo surgimento de feiras e cidades comerciais.","resposta":""},
  {"id":"4802","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Mao Tse-Tung","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Revolucao Comunista na China, liderada por Mao Tse-Tung, proclamou a Republica Popular da China em:","alternativa_a":"1949","alternativa_b":"1919","alternativa_c":"1937","alternativa_d":"1966","alternativa_e":"1989","resposta_correta":"a","explicacao":"Em 1o de outubro de 1949, Mao Tse-Tung proclamou a Republica Popular da China apos a vitoria dos comunistas na guerra civil contra os nacionalistas de Chiang Kai-shek.","resposta":""},
  {"id":"4803","tipo":"multipla","disciplina":"Geografia","tema":"Clima","subtema":"Zonas climaticas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A zona climatica intertropical e delimitada pelos:","alternativa_a":"Tropicos de Cancer e Capricornio","alternativa_b":"Circulos Articos e Antarticos","alternativa_c":"Equador e paralelo 30","alternativa_d":"Meridianos de 0 e 180 graus","alternativa_e":"Paralelos 45N e 45S","resposta_correta":"a","explicacao":"A zona intertropical (Torida) e delimitada pelo Tropico de Cancer (23,5 N) e Tropico de Capricornio (23,5 S). Recebe radiacao solar mais direta durante o ano.","resposta":""},
  {"id":"4804","tipo":"multipla","disciplina":"Geografia","tema":"Geomorfologia","subtema":"Erosao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo de erosao acelerada que forma sulcos profundos no solo, especialmente em areas desmatadas, e chamado de:","alternativa_a":"Vocorocamento","alternativa_b":"Assoreamento","alternativa_c":"Lixiviacao","alternativa_d":"Sedimentacao","alternativa_e":"Intemperismo","resposta_correta":"a","explicacao":"Vocorocamento (voroc ou ravina profunda) e uma forma severa de erosao que forma sulcos profundos e largos, comum em solos desprotegidos e argilosos no Brasil.","resposta":""},
  {"id":"4805","tipo":"multipla","disciplina":"Geografia","tema":"Industria","subtema":"Industrializacao no Brasil","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo de industrializacao brasileira concentrou-se inicialmente na regiao:","alternativa_a":"Sudeste, especialmente em Sao Paulo","alternativa_b":"Sul, especialmente no Rio Grande do Sul","alternativa_c":"Nordeste, especialmente na Bahia","alternativa_d":"Centro-Oeste, especialmente em Goias","alternativa_e":"Norte, especialmente no Para","resposta_correta":"a","explicacao":"Sao Paulo concentrou a industrializacao brasileira a partir de fins do sec. XIX, beneficiada pelo capital cafeeiro, imigracao europeia, ferrovia e energia hidroeletrica.","resposta":""},
  {"id":"4806","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Figuras de linguagem","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A figura de linguagem que consiste em atribuir caracteristicas humanas a seres inanimados e chamada de:","alternativa_a":"Prosopopeia (personificacao)","alternativa_b":"Metafora","alternativa_c":"Metonimia","alternativa_d":"Hiperbole","alternativa_e":"Ironia","resposta_correta":"a","explicacao":"Prosopopeia ou personificacao: atribuicao de caracteristicas humanas (sentimentos, acoes) a seres inanimados. Ex.: 'O vento gemia entre as arvores.'","resposta":""},
  {"id":"4807","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Vanguardas europeias","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Surrealismo, movimento artistico que exploravia o inconsciente e os sonhos, foi fundado por:","alternativa_a":"Andre Breton","alternativa_b":"Guillaume Apollinaire","alternativa_c":"Tristan Tzara","alternativa_d":"Filippo Marinetti","alternativa_e":"Ezra Pound","resposta_correta":"a","explicacao":"Andre Breton publicou o Manifesto Surrealista (1924), fundando o movimento que buscava revelar o inconsciente e superar a logica racional na arte e na literatura.","resposta":""},
  {"id":"4808","tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Nietzsche","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Nietzsche critica a moral crista como uma 'moral de escravos' e propoe a superacao pelo:","alternativa_a":"Ubermensch (super-homem)","alternativa_b":"Imperativo categorico","alternativa_c":"Utilitarismo universal","alternativa_d":"Contrato social","alternativa_e":"Virtude aristotelica","resposta_correta":"a","explicacao":"Nietzsche propoe a 'transvaloracão dos valores': superar a moral de rebanho (crista/niilista) pela vontade de poder e pelo Ubermensch, que cria seus proprios valores.","resposta":""},
  {"id":"4809","tipo":"multipla","disciplina":"Sociologia","tema":"Religiao","subtema":"Secularizacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O processo de secularizacao refere-se ao:","alternativa_a":"Declinio da influencia religiosa nas esferas publicas da vida moderna","alternativa_b":"Aumento do fundamentalismo religioso","alternativa_c":"Separacao entre religioes politeistas e monoteistas","alternativa_d":"Transformacao de templos em museus","alternativa_e":"Crescimento do ateismo na populacao","resposta_correta":"a","explicacao":"Secularizacao (Weber, Berger): processo pelo qual a religiao perde influencia sobre as esferas publicas da vida social (politica, ciencia, educacao, direito) na modernidade.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote50.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
