# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4460","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Modernismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Semana de Arte Moderna de 1922 ocorreu na cidade de:","alternativa_a":"Sao Paulo","alternativa_b":"Rio de Janeiro","alternativa_c":"Belo Horizonte","alternativa_d":"Salvador","alternativa_e":"Recife","resposta_correta":"a","explicacao":"A Semana de Arte Moderna de 1922 ocorreu no Teatro Municipal de Sao Paulo entre 13 e 17 de fevereiro, sendo o marco inicial do modernismo brasileiro.","resposta":""},
  {"id":"4461","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Morfologia - Substantivos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os substantivos que designam seres do mesmo genero para os dois sexos sao chamados de:","alternativa_a":"Epicenos","alternativa_b":"Bigeneros","alternativa_c":"Sobrecomuns","alternativa_d":"Comuns de dois generos","alternativa_e":"Heteronimos","resposta_correta":"a","explicacao":"Substantivos epicenos designam animais ou plantas com uma so forma para os dois sexos: a cobra (macho/femea), o jacare (macho/femea).","resposta":""},
  {"id":"4462","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Periodo composto","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Na oracao 'Embora estudasse muito, nao passou no vestibular', a oracao subordinada adverbial e:","alternativa_a":"Concessiva","alternativa_b":"Causal","alternativa_c":"Condicional","alternativa_d":"Consecutiva","alternativa_e":"Comparativa","resposta_correta":"a","explicacao":"A conjuncao 'embora' introduz oracao subordinada adverbial concessiva, que expressa uma ideia contraria ao que seria esperado na oração principal.","resposta":""},
  {"id":"4463","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Interpretacao de Texto","subtema":"Intertextualidade","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A intertextualidade ocorre quando um texto faz referencia a:","alternativa_a":"Outro texto anterior","alternativa_b":"Apenas imagens","alternativa_c":"O proprio autor","alternativa_d":"Somente textos do mesmo genero","alternativa_e":"Textos futuros","resposta_correta":"a","explicacao":"A intertextualidade e o dialogo entre textos: um texto referencia, cita, parodia ou alude a outro texto anterior, criando uma relacao de sentido.","resposta":""},
  {"id":"4464","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Barroco","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O principal poeta do Barroco brasileiro, autor de 'Boca do Inferno', foi:","alternativa_a":"Gregorio de Matos","alternativa_b":"Jose de Alencar","alternativa_c":"Casimiro de Abreu","alternativa_d":"Padre Antonio Vieira","alternativa_e":"Olavo Bilac","resposta_correta":"a","explicacao":"Gregorio de Matos (1636-1696), conhecido como 'Boca do Inferno', e o principal representante do barroco na literatura brasileira, com poesias satiricas, religiosas e liricas.","resposta":""},
  {"id":"4465","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Colocacao pronominal","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A norma culta exige prooclise (pronome antes do verbo) nas oracoes que iniciam com:","alternativa_a":"Palavras negativas","alternativa_b":"Verbos no infinitivo","alternativa_c":"Verbos no gerundio","alternativa_d":"Verbos no futuro do presente","alternativa_e":"Sujeito expresso","resposta_correta":"a","explicacao":"A proclise e obrigatoria apos palavras negativas (nao, nunca, jamais), conjuncoes subordinativas, pronomes relativos, interrogativos e indefinidos.","resposta":""},
  {"id":"4466","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Realismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Machado de Assis e considerado o maior representante do Realismo brasileiro. Seu romance 'Dom Casmurro' (1899) tem como narrador:","alternativa_a":"Bentinho/Casmurro","alternativa_b":"Capitu","alternativa_c":"Jose Dias","alternativa_d":"Um narrador onisciente","alternativa_e":"Escobar","resposta_correta":"a","explicacao":"Dom Casmurro e narrado em primeira pessoa por Bentinho (apelidado Dom Casmurro), um narrador nao confiavel cuja perspectiva e central para a ambiguidade da obra.","resposta":""},
  {"id":"4467","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Verbos - vozes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na oracao 'O livro foi lido pelo aluno', o verbo esta na voz:","alternativa_a":"Passiva analitica","alternativa_b":"Ativa","alternativa_c":"Reflexiva","alternativa_d":"Passiva sintetica","alternativa_e":"Media","resposta_correta":"a","explicacao":"A voz passiva analitica e formada por verbo auxiliar (ser/estar/ficar) + particípio do verbo principal: 'foi lido'. O agente da passiva e 'pelo aluno'.","resposta":""},
  {"id":"4468","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Parnasianismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Parnasianismo brasileiro valorizava, sobretudo, a:","alternativa_a":"Perfeicao formal e objetividade","alternativa_b":"Subjetividade e evasao","alternativa_c":"Critica social e realismo","alternativa_d":"Religiosidade e misticismo","alternativa_e":"Valorização do indigena","resposta_correta":"a","explicacao":"O Parnasianismo (2a metade do seculo XIX) valorizava a arte pela arte, a perfeicao formal, a objetividade, o equilíbrio e o culto a beleza, com rigor metrico e rimático.","resposta":""},
  {"id":"4469","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Redacao","subtema":"Texto dissertativo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A estrutura basica do texto dissertativo-argumentativo e composta por:","alternativa_a":"Introducao, desenvolvimento e conclusao","alternativa_b":"Exposicao, complicacao e desfecho","alternativa_c":"Orientacao, complicacao e resolucao","alternativa_d":"Apresentacao, tese e antitese","alternativa_e":"Inicio, meio e fim narrativo","resposta_correta":"a","explicacao":"O texto dissertativo-argumentativo se estrutura em: introducao (apresentacao da tese), desenvolvimento (argumentos) e conclusao (proposta de intervencao ou sintese).","resposta":""},
  {"id":"4470","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Antiga","subtema":"Socrates","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O metodo filosofico de Socrates, baseado no dialogo para descobrir a verdade, e chamado de:","alternativa_a":"Maieutica","alternativa_b":"Dialectica hegeliana","alternativa_c":"Fenomenologia","alternativa_d":"Reducao transcendental","alternativa_e":"Hermeneutica","resposta_correta":"a","explicacao":"A maieutica socrática (arte de parir ideias) e o metodo de dialogo por meio de perguntas que leva o interlocutor a descobrir a verdade por si mesmo.","resposta":""},
  {"id":"4471","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Antiga","subtema":"Plato","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A teoria das ideias de Plato divide a realidade em dois mundos: o mundo sensivel e o:","alternativa_a":"Mundo inteligivel","alternativa_b":"Mundo das formas fisicas","alternativa_c":"Mundo dos atomos","alternativa_d":"Mundo do caos","alternativa_e":"Mundo da materia","resposta_correta":"a","explicacao":"Para Plato, a realidade e dividida em: o mundo sensivel (material, imperfeito, apreendido pelos sentidos) e o mundo inteligivel (das ideias, perfeito, apreendido pela razao).","resposta":""},
  {"id":"4472","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Moderna","subtema":"Descartes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A proposicao 'Cogito, ergo sum' (Penso, logo existo) e atribuida a:","alternativa_a":"Rene Descartes","alternativa_b":"John Locke","alternativa_c":"Immanuel Kant","alternativa_d":"David Hume","alternativa_e":"Baruch Spinoza","resposta_correta":"a","explicacao":"Rene Descartes formulou 'Cogito, ergo sum' no 'Discurso do Metodo' (1637), como a certeza indubitavel a partir da qual construiu seu sistema filosofico racionalista.","resposta":""},
  {"id":"4473","tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Utilitarismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O utilitarismo, teoria etica que propoe maximizar a felicidade do maior numero de pessoas, foi desenvolvido por:","alternativa_a":"Jeremy Bentham e John Stuart Mill","alternativa_b":"Immanuel Kant e Hegel","alternativa_c":"Aristoteles e Plato","alternativa_d":"Nietzsche e Schopenhauer","alternativa_e":"Marx e Engels","resposta_correta":"a","explicacao":"O utilitarismo classico foi desenvolvido por Jeremy Bentham (principio da utilidade) e aprimorado por John Stuart Mill (qualidade dos prazeres).","resposta":""},
  {"id":"4474","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Contemporanea","subtema":"Existencialismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O filosofo frances que afirmou 'A existencia precede a essencia' e principal representante do existencialismo ateu e:","alternativa_a":"Jean-Paul Sartre","alternativa_b":"Albert Camus","alternativa_c":"Simone de Beauvoir","alternativa_d":"Maurice Merleau-Ponty","alternativa_e":"Gabriel Marcel","resposta_correta":"a","explicacao":"Jean-Paul Sartre, em 'O Existencialismo e um Humanismo' (1945), defende que o ser humano primeiro existe e depois define sua essencia por meio de suas escolhas.","resposta":""},
  {"id":"4475","tipo":"multipla","disciplina":"Filosofia","tema":"Logica","subtema":"Argumento dedutivo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O silogismo aristotelico e um tipo de argumento:","alternativa_a":"Dedutivo","alternativa_b":"Indutivo","alternativa_c":"Abductivo","alternativa_d":"Analogico","alternativa_e":"Empirico","resposta_correta":"a","explicacao":"O silogismo e um argumento dedutivo: a conclusao decorre necessariamente das premissas. Ex.: 'Todo homem e mortal; Socrates e homem; logo, Socrates e mortal.'","resposta":""},
  {"id":"4476","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Politica","subtema":"Contrato social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Jean-Jacques Rousseau defende que os seres humanos, no estado de natureza, sao:","alternativa_a":"Bons por natureza","alternativa_b":"Maus por natureza","alternativa_c":"Racionais e cooperativos","alternativa_d":"Belicosos e violentos","alternativa_e":"Indiferentes ao social","resposta_correta":"a","explicacao":"Para Rousseau, o homem nasce bom e e a sociedade que o corrompe. Em 'Do Contrato Social', defende que a vontade geral e a fonte da soberania legitima.","resposta":""},
  {"id":"4477","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia da Ciencia","subtema":"Falsificacionismo","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Karl Popper propôs que o criterio de demarcacao entre ciencia e pseudociencia e a:","alternativa_a":"Falseabilidade","alternativa_b":"Verificabilidade","alternativa_c":"Utilidade pratica","alternativa_d":"Consenso da comunidade cientifica","alternativa_e":"Compatibilidade com a religiao","resposta_correta":"a","explicacao":"Para Popper, uma teoria e cientifica se pode ser refutada (falsificada) por experimentos. Teorias irrefutaveis sao pseudocientificas.","resposta":""},
  {"id":"4478","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Acao social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Max Weber identificou quatro tipos de acao social. A acao orientada por valores morais, esteticos ou religiosos e chamada de acao:","alternativa_a":"Racional com relacao a valores","alternativa_b":"Racional com relacao a fins","alternativa_c":"Afetiva","alternativa_d":"Tradicional","alternativa_e":"Instrumental","resposta_correta":"a","explicacao":"Para Weber, a acao racional com relacao a valores (wertrational) e aquela orientada por convicoes eticas, esteticas ou religiosas, sem calculo de meios e fins.","resposta":""},
  {"id":"4479","tipo":"multipla","disciplina":"Sociologia","tema":"Estratificacao Social","subtema":"Mobilidade social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A mobilidade social vertical ascendente ocorre quando um individuo ou grupo:","alternativa_a":"Sobe na hierarquia social","alternativa_b":"Desce na hierarquia social","alternativa_c":"Muda de cidade mantendo o mesmo status","alternativa_d":"Muda de ocupacao no mesmo nivel social","alternativa_e":"Emigra para outro pais","resposta_correta":"a","explicacao":"A mobilidade social vertical ascendente e a mudanca de posicao social para um nivel hierarquicamente superior, como subir de classe trabalhadora para classe media.","resposta":""},
  {"id":"4480","tipo":"multipla","disciplina":"Sociologia","tema":"Cultura","subtema":"Etnocentrismo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A tendencia de julgar outras culturas com base nos valores e padroes da propria cultura e chamada de:","alternativa_a":"Etnocentrismo","alternativa_b":"Relativismo cultural","alternativa_c":"Multiculturalismo","alternativa_d":"Transculturacao","alternativa_e":"Aculturacao","resposta_correta":"a","explicacao":"O etnocentrismo e a visao de mundo que toma a propria cultura como referencia e centro, julgando as outras como inferiores ou erradas.","resposta":""},
  {"id":"4481","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Marx","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Karl Marx, a estrutura economica da sociedade (base) determina a:","alternativa_a":"Superestrutura (ideologia, politica, cultura)","alternativa_b":"Estrutura familiar","alternativa_c":"Divisao dos poderes","alternativa_d":"Organizacao religiosa","alternativa_e":"Estetica e arte","resposta_correta":"a","explicacao":"No materialismo historico de Marx, a base (relacoes de producao economica) determina a superestrutura (instituicoes politicas, juridicas, religiosas, culturais).","resposta":""},
  {"id":"4482","tipo":"multipla","disciplina":"Sociologia","tema":"Movimentos Sociais","subtema":"Feminismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'patriarcado', que designa um sistema de dominacao masculina sobre as mulheres, e central para a teoria:","alternativa_a":"Feminista","alternativa_b":"Marxista ortodoxa","alternativa_c":"Funcionalista","alternativa_d":"Positivista","alternativa_e":"Anarquista","resposta_correta":"a","explicacao":"O patriarcado e um conceito central da teoria feminista, descrevendo um sistema social em que homens detêm poder primario sobre mulheres nas esferas publicas e privadas.","resposta":""},
  {"id":"4483","tipo":"multipla","disciplina":"Sociologia","tema":"Globalizacao","subtema":"Cultura de massa","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O conceito de 'industria cultural', criado por Adorno e Horkheimer, critica a producao cultural capitalista por:","alternativa_a":"Padronizar e mercantilizar a cultura","alternativa_b":"Promover a diversidade cultural","alternativa_c":"Estimular o pensamento critico","alternativa_d":"Preservar as tradicoes populares","alternativa_e":"Democratizar o acesso a arte","resposta_correta":"a","explicacao":"Adorno e Horkheimer (Escola de Frankfurt) criaram o conceito de industria cultural para criticar como o capitalismo transforma a cultura em mercadoria padronizada que aliena.","resposta":""},
  {"id":"4484","tipo":"multipla","disciplina":"Sociologia","tema":"Teoria Sociologica","subtema":"Estrutural-funcionalismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Talcott Parsons e o principal representante do funcionalismo estrutural norte-americano. Para ele, a sociedade e um sistema que tende ao:","alternativa_a":"Equilibrio e estabilidade","alternativa_b":"Conflito e transformacao","alternativa_c":"Progresso linear","alternativa_d":"Caos e desordem","alternativa_e":"Declinio inevitavel","resposta_correta":"a","explicacao":"Parsons ve a sociedade como um sistema social em que as instituicoes cumprem funcoes essenciais para manter o equilibrio e a integracao social (homeostase social).","resposta":""},
  {"id":"4485","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao quadratica - vertice","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A coordenada x do vertice da parabola f(x) = 2x^2 - 8x + 5 e:","alternativa_a":"2","alternativa_b":"-2","alternativa_c":"4","alternativa_d":"-4","alternativa_e":"1","resposta_correta":"a","explicacao":"xv = -b/(2a) = -(-8)/(2*2) = 8/4 = 2.","resposta":""},
  {"id":"4486","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Poligonos regulares","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A soma dos angulos internos de um hexagono e:","alternativa_a":"720 graus","alternativa_b":"540 graus","alternativa_c":"900 graus","alternativa_d":"360 graus","alternativa_e":"1080 graus","resposta_correta":"a","explicacao":"Soma dos angulos internos = (n-2)*180 = (6-2)*180 = 4*180 = 720 graus.","resposta":""},
  {"id":"4487","tipo":"multipla","disciplina":"Matematica","tema":"Financeira","subtema":"Juros compostos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um capital de R$ 1.000 aplicado a uma taxa de 10% ao periodo, durante 3 periodos em regime de juros compostos, resulta em montante de:","alternativa_a":"R$ 1.331","alternativa_b":"R$ 1.300","alternativa_c":"R$ 1.310","alternativa_d":"R$ 1.100","alternativa_e":"R$ 1.030","resposta_correta":"a","explicacao":"M = C*(1+i)^n = 1000*(1,1)^3 = 1000*1,331 = R$ 1.331.","resposta":""},
  {"id":"4488","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Derivadas","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A derivada de f(x) = x^3 + 2x^2 - 5x + 1 e:","alternativa_a":"3x^2 + 4x - 5","alternativa_b":"3x^2 + 2x - 5","alternativa_c":"x^2 + 4x - 5","alternativa_d":"3x^3 + 4x - 5","alternativa_e":"3x^2 + 4x","resposta_correta":"a","explicacao":"Usando a regra da potencia: f'(x) = 3x^2 + 4x - 5.","resposta":""},
  {"id":"4489","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Esfera","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O volume de uma esfera de raio 3 cm e: (use pi=3,14)","alternativa_a":"113,04 cm3","alternativa_b":"75,36 cm3","alternativa_c":"37,68 cm3","alternativa_d":"226,08 cm3","alternativa_e":"56,52 cm3","resposta_correta":"a","explicacao":"V = (4/3)*pi*r^3 = (4/3)*3,14*27 = 4*3,14*9 = 113,04 cm3.","resposta":""},
  {"id":"4490","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Forca de atrito","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um bloco de 5 kg e puxado sobre uma superficie com coeficiente de atrito cinematico 0,2. A forca de atrito e: (g=10 m/s2)","alternativa_a":"10 N","alternativa_b":"5 N","alternativa_c":"20 N","alternativa_d":"1 N","alternativa_e":"100 N","resposta_correta":"a","explicacao":"Fat = u * N = u * m * g = 0,2 * 5 * 10 = 10 N.","resposta":""},
  {"id":"4491","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Dilatacao termica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um fio de ferro de 2 m e aquecido de 20 oC a 120 oC. Com coeficiente de dilatacao linear 12x10^-6 /oC, a variacao de comprimento e:","alternativa_a":"2,4 mm","alternativa_b":"24 mm","alternativa_c":"0,24 mm","alternativa_d":"24 cm","alternativa_e":"0,024 mm","resposta_correta":"a","explicacao":"DL = L0 * a * DT = 2 * 12x10^-6 * 100 = 2,4x10^-3 m = 2,4 mm.","resposta":""},
  {"id":"4492","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Circuito paralelo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Em um circuito com dois resistores de 6 ohm e 3 ohm em paralelo, a resistencia equivalente e:","alternativa_a":"2 ohm","alternativa_b":"9 ohm","alternativa_c":"4,5 ohm","alternativa_d":"3 ohm","alternativa_e":"6 ohm","resposta_correta":"a","explicacao":"1/Req = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2. Portanto Req = 2 ohm.","resposta":""},
  {"id":"4493","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Interferencia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Quando duas ondas de mesma amplitude e frequencia se encontram em fase, ocorre:","alternativa_a":"Interferencia construtiva","alternativa_b":"Interferencia destrutiva","alternativa_c":"Difracao","alternativa_d":"Reflexao","alternativa_e":"Refracao","resposta_correta":"a","explicacao":"Na interferencia construtiva, duas ondas em fase se somam, resultando em amplitude maxima (soma das amplitudes individuais).","resposta":""},
  {"id":"4494","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Estatica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para um corpo estar em equilibrio estatico, a resultante das forcas e a resultante dos torques devem ser:","alternativa_a":"Iguais a zero","alternativa_b":"Maximas","alternativa_c":"Opostas","alternativa_d":"Iguais entre si","alternativa_e":"Proporcionals a massa","resposta_correta":"a","explicacao":"Para equilibrio estatico: soma de todas as forcas = 0 (equilibrio de translacao) E soma de todos os torques = 0 (equilibrio de rotacao).","resposta":""},
  {"id":"4495","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Funcoes oxigenadas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os alcoois sao compostos organicos que possuem o grupo funcional:","alternativa_a":"OH (hidroxila)","alternativa_b":"COOH (carboxila)","alternativa_c":"CHO (aldeido)","alternativa_d":"CO (carbonila cetonica)","alternativa_e":"O (eter)","resposta_correta":"a","explicacao":"Alcoois possuem o grupo hidroxila (-OH) ligado a carbono saturado (sp3). Ex.: metanol (CH3-OH), etanol (C2H5-OH).","resposta":""},
  {"id":"4496","tipo":"multipla","disciplina":"Quimica","tema":"Estequiometria","subtema":"Rendimento da reacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Uma reacao com rendimento de 80% produz 40 g do produto esperado. A quantidade teorica esperada seria:","alternativa_a":"50 g","alternativa_b":"48 g","alternativa_c":"32 g","alternativa_d":"60 g","alternativa_e":"80 g","resposta_correta":"a","explicacao":"Rendimento = produzido / teorico * 100. 80 = 40/teorico * 100. Teorico = 4000/80 = 50 g.","resposta":""},
  {"id":"4497","tipo":"multipla","disciplina":"Quimica","tema":"Tabela Periodica","subtema":"Grupos e periodos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os elementos do grupo 1 da tabela periodica (metais alcalinos) possuem em comum:","alternativa_a":"1 eletron de valencia","alternativa_b":"2 eletrons de valencia","alternativa_c":"7 eletrons de valencia","alternativa_d":"8 eletrons de valencia","alternativa_e":"0 eletrons de valencia","resposta_correta":"a","explicacao":"Os metais alcalinos (Li, Na, K, Rb, Cs, Fr) pertencem ao grupo 1 e possuem 1 eletron na ultima camada eletronica (valência).","resposta":""},
  {"id":"4498","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Ligacao ionica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A ligacao ionica ocorre entre elementos com grande diferenca de:","alternativa_a":"Eletronegatividade","alternativa_b":"Massa atomica","alternativa_c":"Numero de neutrons","alternativa_d":"Raio atomico","alternativa_e":"Energia de ionizacao","resposta_correta":"a","explicacao":"A ligacao ionica ocorre tipicamente entre metais (baixa eletronegatividade) e nao-metais (alta eletronegatividade), com grande diferenca de eletronegatividade entre eles.","resposta":""},
  {"id":"4499","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema digestivo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A maioria dos nutrientes e absorvida no sistema digestivo no:","alternativa_a":"Intestino delgado","alternativa_b":"Estomago","alternativa_c":"Intestino grosso","alternativa_d":"Esofago","alternativa_e":"Boca","resposta_correta":"a","explicacao":"O intestino delgado (duodeno, jejuno e ileo) e o principal local de absorcao de nutrientes, com estruturas como vilis e microvilis que aumentam a superficie de contato.","resposta":""},
  {"id":"4500","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Codigo genetico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O codigo genetico e dito degenerado porque:","alternativa_a":"Varios codons podem codificar o mesmo aminoacido","alternativa_b":"Alguns aminoacidos nao tem codon","alternativa_c":"O mesmo codon codifica aminoacidos diferentes em organismos distintos","alternativa_d":"Existem mais aminoacidos que codons","alternativa_e":"Apenas 20 codons codificam aminoacidos","resposta_correta":"a","explicacao":"A degeneracao do codigo genetico significa que um mesmo aminoacido pode ser codificado por mais de um codon (sinonimos). Ex.: a leucina e codificada por 6 codons diferentes.","resposta":""},
  {"id":"4501","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Sucessao ecologica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A sucessao ecologica que se inicia em um ambiente sem vida previa e chamada de:","alternativa_a":"Primaria","alternativa_b":"Secundaria","alternativa_c":"Terciaria","alternativa_d":"Progressiva","alternativa_e":"Regressiva","resposta_correta":"a","explicacao":"A sucessao primaria ocorre em ambientes sem solo formado ou vida previa (rocha nua, dunas, lavas solidificadas). A secundaria ocorre em ambientes com solo ja existente.","resposta":""},
  {"id":"4502","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Reticulo endoplasmatico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O reticulo endoplasmatico rugoso e assim chamado por conter em sua superficie:","alternativa_a":"Ribossomos","alternativa_b":"Mitocondrias","alternativa_c":"Lisossomos","alternativa_d":"Peroxissomos","alternativa_e":"Vacuolos","resposta_correta":"a","explicacao":"O reticulo endoplasmatico rugoso (granular) tem sua membrana coberta por ribossomos, que sintetizam proteinas destinadas a exportacao ou para membranas.","resposta":""},
  {"id":"4503","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Inconfidencia Mineira","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O principal martir da Inconfidencia Mineira (1789), que foi enforcado e esquartejado, foi:","alternativa_a":"Tiradentes","alternativa_b":"Jose Bonifacio","alternativa_c":"Frei Caneca","alternativa_d":"Felipe dos Santos","alternativa_e":"Aleijadinho","resposta_correta":"a","explicacao":"Joaquim Jose da Silva Xavier, o Tiradentes, foi o unico condenado a morte e executado na Inconfidencia Mineira, tornando-se simbolo da luta pela independencia.","resposta":""},
  {"id":"4504","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Proclamacao da Republica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A Proclamacao da Republica no Brasil ocorreu em:","alternativa_a":"15 de novembro de 1889","alternativa_b":"7 de setembro de 1822","alternativa_c":"13 de maio de 1888","alternativa_d":"22 de abril de 1500","alternativa_e":"7 de abril de 1831","resposta_correta":"a","explicacao":"A Proclamacao da Republica ocorreu em 15 de novembro de 1889, liderada pelo Marechal Deodoro da Fonseca, encerrando o Imperio brasileiro.","resposta":""},
  {"id":"4505","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Revolucao Francesa","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Revolucao Francesa (1789) foi sintetizada pelos ideais de:","alternativa_a":"Liberdade, igualdade e fraternidade","alternativa_b":"Fe, esperanca e caridade","alternativa_c":"Paz, terra e pao","alternativa_d":"Honra, patria e familia","alternativa_e":"Trabalho, ordem e progresso","resposta_correta":"a","explicacao":"'Liberte, egalite, fraternite' foi o lema da Revolucao Francesa, representando os ideais iluministas que guiaram os revolucionarios contra a monarquia absolutista.","resposta":""},
  {"id":"4506","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Imperialismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Conferencia de Berlim (1884-1885) foi decisiva para o processo de colonizacao da Africa pelos paises europeus pois:","alternativa_a":"Dividiu o continente africano entre as potencias europeias","alternativa_b":"Liberou os escravos africanos","alternativa_c":"Criou a Liga Africana","alternativa_d":"Reconheceu a soberania dos reinos africanos","alternativa_e":"Estabeleceu fronteiras conforme etnias locais","resposta_correta":"a","explicacao":"A Conferencia de Berlim estabeleceu as regras para a partilha colonial da Africa, dividindo o continente entre as potencias europeias sem respeitar etnias ou culturas locais.","resposta":""},
  {"id":"4507","tipo":"multipla","disciplina":"Geografia","tema":"Economia Mundial","subtema":"Globalizacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A globalizacao economica e caracterizada, entre outros aspectos, por:","alternativa_a":"Liberalizacao dos mercados e fluxos de capital","alternativa_b":"Fortalecimento do proteccionismo","alternativa_c":"Reducao das trocas comerciais internacionais","alternativa_d":"Aumento das barreiras alfandegarias","alternativa_e":"Isolamento das economias nacionais","resposta_correta":"a","explicacao":"A globalizacao economica e marcada pela liberalizacao comercial, fluxos internacionais de capital, producao transnacional e integracao dos mercados mundiais.","resposta":""},
  {"id":"4508","tipo":"multipla","disciplina":"Geografia","tema":"Relevo","subtema":"Tipos de relevo","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"As chapadas e planaltos brasileiros sao formados predominantemente por:","alternativa_a":"Rochas sedimentares","alternativa_b":"Rochas igneas","alternativa_c":"Rochas metamorficas","alternativa_d":"Rochas vulcanicas","alternativa_e":"Rochas carbonaticas","resposta_correta":"a","explicacao":"As chapadas e planaltos sedimentares brasileiros (como a Chapada dos Guimaraes e a Chapada Diamantina) sao formados por camadas de rochas sedimentares.","resposta":""},
  {"id":"4509","tipo":"multipla","disciplina":"Geografia","tema":"Energia","subtema":"Fontes de energia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Brasil e um dos maiores produtores de energia hidroeletrica do mundo. A usina de Itaipu, localizada no Rio Parana, e uma parceria entre Brasil e:","alternativa_a":"Paraguai","alternativa_b":"Argentina","alternativa_c":"Uruguay","alternativa_d":"Bolivia","alternativa_e":"Peru","resposta_correta":"a","explicacao":"A Usina de Itaipu e um empreendimento binacional entre Brasil e Paraguai, construida no Rio Parana, sendo uma das maiores usinas hidroeletricas do mundo.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote44.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
