# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4710","tipo":"multipla","disciplina":"Matematica","tema":"Algebra","subtema":"Fatoracao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A fatoracao de x^2 - 9 e:","alternativa_a":"(x-3)(x+3)","alternativa_b":"(x-9)(x+1)","alternativa_c":"(x-3)^2","alternativa_d":"(x+3)^2","alternativa_e":"(x-1)(x+9)","resposta_correta":"a","explicacao":"x^2 - 9 = x^2 - 3^2 = (x-3)(x+3). Produto da soma pela diferenca (diferenca de quadrados).","resposta":""},
  {"id":"4711","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Angulos inscritos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O angulo inscrito numa circunferencia e a metade do angulo central que abrange o mesmo arco. Se o angulo central mede 80 graus, o angulo inscrito e:","alternativa_a":"40 graus","alternativa_b":"80 graus","alternativa_c":"160 graus","alternativa_d":"20 graus","alternativa_e":"60 graus","resposta_correta":"a","explicacao":"Angulo inscrito = (1/2) * angulo central = 80/2 = 40 graus.","resposta":""},
  {"id":"4712","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Grafico de funcao quadratica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A parabola f(x) = ax^2 + bx + c abre para cima quando:","alternativa_a":"a > 0","alternativa_b":"a < 0","alternativa_c":"b > 0","alternativa_d":"c > 0","alternativa_e":"Discriminante > 0","resposta_correta":"a","explicacao":"O sinal do coeficiente 'a' determina a concavidade da parabola: a > 0 abre para cima (concavidade positiva); a < 0 abre para baixo.","resposta":""},
  {"id":"4713","tipo":"multipla","disciplina":"Matematica","tema":"Progressao Aritmetica","subtema":"Interpolacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Entre os termos 2 e 14 de uma PA, foram inseridos 5 meios aritmeticos. A razao da PA e:","alternativa_a":"2","alternativa_b":"3","alternativa_c":"4","alternativa_d":"6","alternativa_e":"12","resposta_correta":"a","explicacao":"Com 5 meios entre 2 e 14, ha 7 termos totais. r = (14-2)/(7-1) = 12/6 = 2.","resposta":""},
  {"id":"4714","tipo":"multipla","disciplina":"Matematica","tema":"Inequacoes","subtema":"Inequacao do 2o grau","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A solucao de x^2 - 5x + 6 < 0 e:","alternativa_a":"2 < x < 3","alternativa_b":"x < 2 ou x > 3","alternativa_c":"x < 3 e x > 2","alternativa_d":"x = 2 ou x = 3","alternativa_e":"Todo real","resposta_correta":"a","explicacao":"As raizes sao x=2 e x=3. Como a > 0, a parabola abre para cima, logo a funcao e negativa (< 0) entre as raizes: 2 < x < 3.","resposta":""},
  {"id":"4715","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Espacial","subtema":"Piramide","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O volume de uma piramide de base quadrada com lado 6 cm e altura 4 cm e:","alternativa_a":"48 cm3","alternativa_b":"144 cm3","alternativa_c":"72 cm3","alternativa_d":"36 cm3","alternativa_e":"96 cm3","resposta_correta":"a","explicacao":"V = (1/3)*Ab*h = (1/3)*36*4 = 48 cm3.","resposta":""},
  {"id":"4716","tipo":"multipla","disciplina":"Matematica","tema":"Analise Combinatoria","subtema":"Anagramas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Quantos anagramas tem a palavra AMOR?","alternativa_a":"24","alternativa_b":"12","alternativa_c":"4","alternativa_d":"16","alternativa_e":"8","resposta_correta":"a","explicacao":"AMOR tem 4 letras distintas. Numero de anagramas = 4! = 24.","resposta":""},
  {"id":"4717","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Quartis","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"No conjunto ordenado {1, 3, 5, 7, 9, 11, 13}, a mediana (Q2) e:","alternativa_a":"7","alternativa_b":"5","alternativa_c":"9","alternativa_d":"6","alternativa_e":"8","resposta_correta":"a","explicacao":"O conjunto tem 7 elementos. A mediana e o 4o elemento: 7.","resposta":""},
  {"id":"4718","tipo":"multipla","disciplina":"Matematica","tema":"Numeros","subtema":"Multiplos e fatores","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Um numero e primo quando:","alternativa_a":"E divisivel apenas por 1 e por ele mesmo","alternativa_b":"E par","alternativa_c":"Termina em 1, 3, 7 ou 9","alternativa_d":"E impar","alternativa_e":"E multiplo de 3","resposta_correta":"a","explicacao":"Numero primo e aquele que tem exatamente dois divisores: 1 e ele mesmo. Ex.: 2, 3, 5, 7, 11, 13... O numero 2 e o unico primo par.","resposta":""},
  {"id":"4719","tipo":"multipla","disciplina":"Matematica","tema":"Financeira","subtema":"Amortizacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"No sistema de amortizacao SAC (Sistema de Amortizacao Constante), as parcelas sao:","alternativa_a":"Decrescentes","alternativa_b":"Constantes","alternativa_c":"Crescentes","alternativa_d":"Irregulares","alternativa_e":"Calculadas pelo sistema Price","resposta_correta":"a","explicacao":"No SAC, a amortizacao e constante e os juros diminuem a cada periodo (pois o saldo devedor cai), resultando em parcelas totais decrescentes.","resposta":""},
  {"id":"4720","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Dinamica rotacional","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O momento de inercia de um corpo rigido em rotacao desempenha papel analogo a qual grandeza na translacao?","alternativa_a":"Massa","alternativa_b":"Velocidade","alternativa_c":"Forca","alternativa_d":"Trabalho","alternativa_e":"Pressao","resposta_correta":"a","explicacao":"Analogia entre translacao e rotacao: Massa <-> Momento de inercia (I); Velocidade (v) <-> Velocidade angular (w); Forca (F) <-> Torque (T).","resposta":""},
  {"id":"4721","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Absorcao e emissao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O laser (Light Amplification by Stimulated Emission of Radiation) e baseado no principio de:","alternativa_a":"Emissao estimulada de fotons coerentes","alternativa_b":"Absorcao espontanea de luz","alternativa_c":"Reflexao total interna","alternativa_d":"Difracao de ondas de radio","alternativa_e":"Interferencia destrutiva","resposta_correta":"a","explicacao":"O laser funciona pela emissao estimulada: um foton incidente estimula um atomo excitado a emitir outro foton identico (mesma fase, frequencia e direcao), gerando luz coerente.","resposta":""},
  {"id":"4722","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Diodos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O diodo semicondutor permite a passagem de corrente:","alternativa_a":"Apenas em um sentido (polarizacao direta)","alternativa_b":"Nos dois sentidos igualmente","alternativa_c":"Apenas em alta tensao","alternativa_d":"Apenas em corrente alternada","alternativa_e":"Nao conduz eletricidade","resposta_correta":"a","explicacao":"O diodo e um componente eletronico que conduz corrente apenas em uma direcao (polarizacao direta). E usado em retificadores para converter CA em CC.","resposta":""},
  {"id":"4723","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Calor latente","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O calor latente e a energia trocada durante uma mudanca de estado a temperatura constante. O calor latente de vaporizacao da agua e:","alternativa_a":"540 cal/g","alternativa_b":"80 cal/g","alternativa_c":"100 cal/g","alternativa_d":"1 cal/g.oC","alternativa_e":"1000 cal/g","resposta_correta":"a","explicacao":"Calor latente de vaporizacao da agua: 540 cal/g (a 100 oC). Calor latente de fusao: 80 cal/g. Calor especifico da agua: 1 cal/g.oC.","resposta":""},
  {"id":"4724","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Ondas estacionarias","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma corda vibrante presa nas duas extremidades, o comprimento da corda deve ser multiplo de:","alternativa_a":"Metade do comprimento de onda","alternativa_b":"Um quarto do comprimento de onda","alternativa_c":"Um comprimento de onda inteiro","alternativa_d":"Dois comprimentos de onda","alternativa_e":"Tres quartos do comprimento de onda","resposta_correta":"a","explicacao":"Corda presa nas duas extremidades: L = n*(lambda/2), onde n=1,2,3... O comprimento e multiplo de meio comprimento de onda (lambda/2).","resposta":""},
  {"id":"4725","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Efeito Hall","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O efeito Hall e usado para medir:","alternativa_a":"Campo magnetico","alternativa_b":"Campo eletrico","alternativa_c":"Temperatura","alternativa_d":"Pressao","alternativa_e":"Resistencia em corrente alternada","resposta_correta":"a","explicacao":"O efeito Hall (Edwin Hall, 1879): quando corrente eletrica flui num condutor em campo magnetico, surge uma tensao transversal (tensao Hall), usada para medir campos magneticos.","resposta":""},
  {"id":"4726","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Pendulo simples","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O periodo de um pendulo simples depende de:","alternativa_a":"Comprimento do fio e aceleracao da gravidade","alternativa_b":"Massa do pendulo","alternativa_c":"Amplitude das oscilacoes","alternativa_d":"Material do fio","alternativa_e":"Temperatura do ambiente","resposta_correta":"a","explicacao":"Periodo do pendulo simples (para pequenas oscilacoes): T = 2pi*sqrt(L/g). Depende apenas do comprimento L e da gravidade g, nao da massa ou amplitude.","resposta":""},
  {"id":"4727","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Gas ideal","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A equacao de estado do gas ideal e PV = nRT. Nessa equacao, R e:","alternativa_a":"A constante universal dos gases","alternativa_b":"A resistencia do gas","alternativa_c":"A razao entre pressao e volume","alternativa_d":"O numero de Avogadro","alternativa_e":"A constante de Boltzmann","resposta_correta":"a","explicacao":"Na equacao de Clapeyron (PV = nRT), R e a constante universal dos gases: R ≈ 8,314 J/(mol.K). n e o numero de mols, T a temperatura em Kelvin.","resposta":""},
  {"id":"4728","tipo":"multipla","disciplina":"Fisica","tema":"Eletromagnetismo","subtema":"Regra da mao direita","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A regra da mao direita e usada para determinar a direcao do campo magnetico ao redor de:","alternativa_a":"Um fio retilineo percorrido por corrente","alternativa_b":"Um imã permanente","alternativa_c":"Um capacitor","alternativa_d":"Um resistor","alternativa_e":"Uma carga eletrica estacionaria","resposta_correta":"a","explicacao":"A regra da mao direita: ao segurar o fio com o polegar apontando no sentido da corrente, os demais dedos circulam em torno do fio indicando o sentido do campo magnetico.","resposta":""},
  {"id":"4729","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Hidrostatica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A pressao hidrostatica num fluido de densidade d a uma profundidade h e:","alternativa_a":"P = d*g*h","alternativa_b":"P = d*g/h","alternativa_c":"P = g*h","alternativa_d":"P = d*h","alternativa_e":"P = d/g*h","resposta_correta":"a","explicacao":"Pressao hidrostatica: P = d*g*h, onde d e a densidade do fluido, g e a aceleracao gravitacional e h e a profundidade.","resposta":""},
  {"id":"4730","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Acidos carboxilicos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os acidos carboxilicos contem o grupo funcional:","alternativa_a":"-COOH (carboxila)","alternativa_b":"-OH (hidroxila)","alternativa_c":"-CHO (aldeido)","alternativa_d":"-CO- (carbonila)","alternativa_e":"-NH2 (amino)","resposta_correta":"a","explicacao":"O grupo carboxila (-COOH) e o grupo funcional dos acidos carboxilicos. E formado por um carbonila (C=O) e um hidroxila (-OH) no mesmo carbono.","resposta":""},
  {"id":"4731","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Reacoes de sintese","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A reacao A + B -> AB e um exemplo de reacao de:","alternativa_a":"Sintese (ou adicao)","alternativa_b":"Analise (ou decomposicao)","alternativa_c":"Dupla troca","alternativa_d":"Simples troca","alternativa_e":"Combustao","resposta_correta":"a","explicacao":"Reacao de sintese: dois ou mais reagentes se combinam para formar um unico produto. E o tipo mais simples de reacao quimica.","resposta":""},
  {"id":"4732","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Ambiental","subtema":"Tratamento de agua","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Na estacao de tratamento de agua, o processo de coagulacao e floculacao tem como objetivo:","alternativa_a":"Aglomerar particulas em suspension","alternativa_b":"Eliminar bacterias","alternativa_c":"Remover metais pesados","alternativa_d":"Ajustar o pH","alternativa_e":"Adicionar fluor","resposta_correta":"a","explicacao":"Na coagulacao/floculacao, sulfato de aluminio e adicionado para aglomerar as particulas coloidais em suspensao em flocos maiores, que sedimentam mais facilmente.","resposta":""},
  {"id":"4733","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Polimerizacao por condensacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O PET (polietileno tereftalato), usado em garrafas plasticas, e formado por polimerizacao de:","alternativa_a":"Condensacao (perda de agua)","alternativa_b":"Adicao de olefinas","alternativa_c":"Radicais livres","alternativa_d":"Polimerização anionica","alternativa_e":"Reticulacao","resposta_correta":"a","explicacao":"O PET e um poliester formado por polimerizacao de condensacao entre acido tereftalico e etilenoglicol, com eliminacao de agua a cada ligacao ester formada.","resposta":""},
  {"id":"4734","tipo":"multipla","disciplina":"Quimica","tema":"Solucoes","subtema":"Propriedades coligativas","dificuldide":"Medio","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A adicao de sal (NaCl) a agua faz com que o ponto de congelamento:","alternativa_a":"Diminua (crioscopia)","alternativa_b":"Aumente","alternativa_c":"Permaneca inalterado","alternativa_d":"Varie so com temperatura","alternativa_e":"Dependa da pressao","resposta_correta":"a","explicacao":"Crioscopia (abaixamento crioscópico): a adicao de soluto nao volatil diminui o ponto de congelamento do solvente. Por isso usamos sal para derreter gelo em estradas.","resposta":""},
  {"id":"4735","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Oxidos anfoteros","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O oxido de aluminio (Al2O3) e um oxido anfotero porque:","alternativa_a":"Reage tanto com acidos quanto com bases","alternativa_b":"Reage apenas com acidos","alternativa_c":"Reage apenas com bases","alternativa_d":"Nao reage com outras substancias","alternativa_e":"Forma apenas sais neutros","resposta_correta":"a","explicacao":"Oxidos anfoteros (como Al2O3 e ZnO) reagem tanto com acidos (comportando-se como basicos) quanto com bases (comportando-se como acidicos).","resposta":""},
  {"id":"4736","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Terpenos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Os terpenos sao compostos organicos derivados do isopreno (C5H8). O limoneno, responsavel pelo aroma de citricos, e um:","alternativa_a":"Monoterpeno (C10)","alternativa_b":"Sesquiterpeno (C15)","alternativa_c":"Triterpeno (C30)","alternativa_d":"Tetraterpeno (C40)","alternativa_e":"Diterpeno (C20)","resposta_correta":"a","explicacao":"Monoterpenos sao formados por 2 unidades de isopreno (C10). O limoneno, com 10 carbonos, e um monoterpeno responsavel pelo aroma de laranjas e limaos.","resposta":""},
  {"id":"4737","tipo":"multipla","disciplina":"Quimica","tema":"Bioquimica","subtema":"Vitaminas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A carencia de vitamina C (acido ascorbico) causa a doenca chamada:","alternativa_a":"Escorbuto","alternativa_b":"Raquitismo","alternativa_c":"Pelagra","alternativa_d":"Beriberi","alternativa_e":"Cegueira noturna","resposta_correta":"a","explicacao":"Escorbuto e causado por deficiencia de vitamina C. Raquitismo = vitamina D. Pelagra = vitamina B3. Beriberi = vitamina B1. Cegueira noturna = vitamina A.","resposta":""},
  {"id":"4738","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Dureza da agua","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A dureza da agua e causada principalmente pela presenca de ions de:","alternativa_a":"Calcio e magnesio","alternativa_b":"Sodio e potassio","alternativa_c":"Ferro e manganês","alternativa_d":"Cloro e fluor","alternativa_e":"Sulfato e nitrato","resposta_correta":"a","explicacao":"A dureza da agua e causada por ions Ca^2+ e Mg^2+ (e em menor grau Fe^2+). Esses ions reagem com sabao, formando precipitados e reduzindo a espuma.","resposta":""},
  {"id":"4739","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Polissacarideos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O amido, polissacarideo de reserva das plantas, e formado por duas frações: amilose e:","alternativa_a":"Amilopectina","alternativa_b":"Glicogenio","alternativa_c":"Celulose","alternativa_d":"Pectina","alternativa_e":"Quitina","resposta_correta":"a","explicacao":"O amido e composto por amilose (cadeia linear de alfa-glicose) e amilopectina (cadeia ramificada). Ja o glicogenio e a forma de reserva em animais.","resposta":""},
  {"id":"4740","tipo":"multipla","disciplina":"Biologia","tema":"Evolucao","subtema":"Deriva genetica","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A deriva genetica tem maior efeito em:","alternativa_a":"Populacoes pequenas","alternativa_b":"Populacoes grandes","alternativa_c":"Populacoes com alta selecao natural","alternativa_d":"Populacoes de grandes animais","alternativa_e":"Populacoes com alta diversidade genetica","resposta_correta":"a","explicacao":"A deriva genetica e a mudanca aleatoria nas frequencias alelicas. Seu efeito e maior em populacoes pequenas, onde flutuacoes aleatorias podem fixar ou eliminar alelos.","resposta":""},
  {"id":"4741","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Coagulacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A vitamina K e essencial para a coagulacao sanguinea pois e necessaria para a sintese de:","alternativa_a":"Fatores de coagulacao (protrombina e outros)","alternativa_b":"Hemoglobina","alternativa_c":"Plaquetas","alternativa_d":"Albumina plasmatica","alternativa_e":"Leucocitos","resposta_correta":"a","explicacao":"A vitamina K e necessaria para a sintese hepatica de vários fatores de coagulacao, incluindo a protrombina (fator II), fator VII, IX e X. Sua deficiencia causa disturbios hemorrágicos.","resposta":""},
  {"id":"4742","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Cromossomos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O numero diploide de cromossomos na especie humana e:","alternativa_a":"46","alternativa_b":"23","alternativa_c":"48","alternativa_d":"44","alternativa_e":"92","resposta_correta":"a","explicacao":"Humanos tem 2n = 46 cromossomos (23 pares): 22 pares de autossomos e 1 par de cromossomos sexuais (XX nas mulheres, XY nos homens). Os gametas tem n = 23.","resposta":""},
  {"id":"4743","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Fluxo de energia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A eficiencia ecologica entre niveis troficos sucessivos e aproximadamente:","alternativa_a":"10%","alternativa_b":"50%","alternativa_c":"90%","alternativa_d":"1%","alternativa_e":"100%","resposta_correta":"a","explicacao":"A regra dos 10%: em media, apenas 10% da energia de um nivel trófico e transferida ao nivel seguinte. Os outros 90% sao perdidos como calor no metabolismo.","resposta":""},
  {"id":"4744","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Lisossomos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Os lisossomos sao organulos celulares responsaveis pela:","alternativa_a":"Digestao intracelular","alternativa_b":"Sintese de proteinas","alternativa_c":"Producao de energia","alternativa_d":"Divisao celular","alternativa_e":"Secrecao hormonal","resposta_correta":"a","explicacao":"Lisossomos contem enzimas hidrolíticas que digerem macromoleculas, organulos danificados (autofagia) e material ingerido por fagocitose (heterofagia).","resposta":""},
  {"id":"4745","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Vegetal","subtema":"Hormonio vegetal abscisico","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"O acido abscisico (ABA) nas plantas funciona principalmente como:","alternativa_a":"Hormonio de estresse (fecha estomatos e inibe crescimento)","alternativa_b":"Estimulador do crescimento em luz","alternativa_c":"Promotor de germinacao","alternativa_d":"Indutor de floracao","alternativa_e":"Hormonio de frutificacao","resposta_correta":"a","explicacao":"O ABA e o hormonio de estresse das plantas: em seca, fecha os estomatos para reduzir perda de agua; inibe o crescimento e promove a dormencia de sementes.","resposta":""},
  {"id":"4746","tipo":"multipla","disciplina":"Biologia","tema":"Zoologia","subtema":"Artropodes","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Os insetos sao artropodes com tres pares de patas e o corpo dividido em:","alternativa_a":"Cabeca, torax e abdomen","alternativa_b":"Cabeca e abdomen apenas","alternativa_c":"Cabeca, torax e telson","alternativa_d":"Pro-soma e opistossoma","alternativa_e":"Cefalotorax e abdomen","resposta_correta":"a","explicacao":"Insetos (classe Insecta) tem corpo dividido em 3 tagmas: cabeca (sensorial), torax (locomotor, com 3 pares de patas e geralmente asas) e abdomen (visceral).","resposta":""},
  {"id":"4747","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"JK e Brasilia","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A capital do Brasil foi transferida do Rio de Janeiro para Brasilia durante o governo de:","alternativa_a":"Juscelino Kubitschek","alternativa_b":"Joao Goulart","alternativa_c":"Castello Branco","alternativa_d":"Getulio Vargas","alternativa_e":"Ernesto Geisel","resposta_correta":"a","explicacao":"Brasilia foi inaugurada em 21 de abril de 1960, durante o governo JK (1956-1961), como parte do seu Plano de Metas ('50 anos em 5'). Foi projetada por Oscar Niemeyer e Lucio Costa.","resposta":""},
  {"id":"4748","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Totalitarismos","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O totalitarismo fascista italiano foi liderado por:","alternativa_a":"Benito Mussolini","alternativa_b":"Adolf Hitler","alternativa_c":"Francisco Franco","alternativa_d":"Antonio Salazar","alternativa_e":"Engelbert Dollfuss","resposta_correta":"a","explicacao":"Benito Mussolini fundou o fascismo italiano e governou como 'Il Duce' de 1922 a 1943. O termo 'fascismo' originou-se na Italia e influenciou outros regimes autoritarios.","resposta":""},
  {"id":"4749","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Multipolaridade","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Apos o fim da Guerra Fria (1991), o sistema internacional passou de bipolar para:","alternativa_a":"Unipolar (hegemonia americana) e depois multipolar","alternativa_b":"Bipolar novamente","alternativa_c":"Sem ordem definida","alternativa_d":"Multipolar imediatamente","alternativa_e":"Controlado pela ONU","resposta_correta":"a","explicacao":"Com o fim da URSS, os EUA se tornaram a unica superpotencia (unipolaridade), mas a ascensao da China, UE, Russia e outros poderes emergentes criou um sistema multipolar no seculo XXI.","resposta":""},
  {"id":"4750","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Plano Real","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Plano Real, que estabilizou a economia brasileira controlando a hiperinflacao, foi implementado em 1994 durante o governo de:","alternativa_a":"Itamar Franco (com Fernando Henrique como ministro)","alternativa_b":"Fernando Collor","alternativa_c":"Jose Sarney","alternativa_d":"Lula","alternativa_e":"Fernando Henrique Cardoso","resposta_correta":"a","explicacao":"O Plano Real foi lancado em julho de 1994 durante o governo Itamar Franco, com Fernando Henrique Cardoso como ministro da Fazenda. FHC depois venceu as eleicoes de 1994.","resposta":""},
  {"id":"4751","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Holocausto","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Holocausto durante a Segunda Guerra Mundial foi o exterminio sistematico de aproximadamente 6 milhoes de:","alternativa_a":"Judeus","alternativa_b":"Poloneses","alternativa_c":"Russos","alternativa_d":"Ciganos","alternativa_e":"Franceses","resposta_correta":"a","explicacao":"O Holocausto (Shoah) foi o genocidio de 6 milhoes de judeus pelo regime nazista. Tambem foram exterminados gitanos, pessoas com deficiencia, homossexuais e opositores politicos.","resposta":""},
  {"id":"4752","tipo":"multipla","disciplina":"Historia","tema":"Historia Antiga","subtema":"Mesopotamia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Codigo de Hamurabi, considerado um dos primeiros conjuntos de leis escritas da historia, foi desenvolvido na:","alternativa_a":"Mesopotamia (Babilonia)","alternativa_b":"Egipto Antigo","alternativa_c":"China Antiga","alternativa_d":"India vedica","alternativa_e":"Grecia Classica","resposta_correta":"a","explicacao":"O Codigo de Hamurabi (seculo XVIII a.C.) foi criado pelo rei babilonico Hamurabi na Mesopotamia. Contem 282 leis gravadas em pedra, baseadas no principio de taliao ('olho por olho').","resposta":""},
  {"id":"4753","tipo":"multipla","disciplina":"Geografia","tema":"Oceanografia","subtema":"Correntes oceanicas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Corrente do Golfo, corrente oceanica quente, influencia o clima de:","alternativa_a":"Europa Ocidental","alternativa_b":"America do Sul","alternativa_c":"Africa do Sul","alternativa_d":"Asia Oriental","alternativa_e":"Australia","resposta_correta":"a","explicacao":"A Corrente do Golfo leva aguas quentes do Golfo do Mexico para o Atlantico Norte, aquecendo o clima da Europa Ocidental (ex.: UK e Portugal sao mais quentes que latitudes similares no Canada).","resposta":""},
  {"id":"4754","tipo":"multipla","disciplina":"Geografia","tema":"Biogeografia","subtema":"Amazonia","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A floresta Amazonica e o maior bioma de floresta tropical do mundo. O Rio Amazonas, que a drena, desagua no:","alternativa_a":"Oceano Atlantico","alternativa_b":"Oceano Pacifico","alternativa_c":"Mar do Caribe","alternativa_d":"Rio Parana","alternativa_e":"Oceano Indico","resposta_correta":"a","explicacao":"O Rio Amazonas, com cerca de 6.400 km de extensao, e o maior rio do mundo em volume de agua e deságua no Oceano Atlântico, proximo a foz em Marajo (Para).","resposta":""},
  {"id":"4755","tipo":"multipla","disciplina":"Geografia","tema":"Populacao","subtema":"Migracao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A migracao campo-cidade no Brasil ocorreu intensamente entre os anos 1950-1980 devido principalmente a:","alternativa_a":"Industrializacao e busca de empregos urbanos","alternativa_b":"Guerras e conflitos rurais","alternativa_c":"Politicas de planejamento urbano","alternativa_d":"Reducao da producao agricola","alternativa_e":"Crescimento demografico elevado nas cidades","resposta_correta":"a","explicacao":"O êxodo rural brasileiro foi impulsionado pela industrializacao (especialmente no SE), mecanizacao do campo e busca de melhores condicoes de vida e emprego nas cidades.","resposta":""},
  {"id":"4756","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Periodo simples e composto","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O periodo composto e aquele que contem:","alternativa_a":"Duas ou mais oracoes","alternativa_b":"Uma unica oracao","alternativa_c":"Apenas sujeito e predicado","alternativa_d":"Verbos no infinitivo","alternativa_e":"Ausencia de sujeito","resposta_correta":"a","explicacao":"Periodo simples: uma oracao (um verbo). Periodo composto: duas ou mais oracoes, que podem ser coordenadas (independentes) ou subordinadas (dependentes).","resposta":""},
  {"id":"4757","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Pre-Modernismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Euclides da Cunha e autor de 'Os Sertoes' (1902), obra que narra a Guerra de Canudos. Essa obra e classificada no:","alternativa_a":"Pre-Modernismo","alternativa_b":"Realismo","alternativa_c":"Modernismo","alternativa_d":"Naturalismo","alternativa_e":"Parnasianismo","resposta_correta":"a","explicacao":"'Os Sertoes' de Euclides da Cunha e obra pre-modernista (1902), misturando ciencia, jornalismo e literatura. Retrata a Guerra de Canudos com perspectiva critica sobre o sertao e o sertanejo.","resposta":""},
  {"id":"4758","tipo":"multipla","disciplina":"Filosofia","tema":"Etica","subtema":"Virtude","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Para Aristoteles, a eudaimonia (florescimento humano ou felicidade plena) e alcanada pela:","alternativa_a":"Pratica habitual das virtudes","alternativa_b":"Acumulacao de riqueza","alternativa_c":"Contemplacao mistica","alternativa_d":"Prazer sensorial","alternativa_e":"Obediencia a lei divina","resposta_correta":"a","explicacao":"Eudaimonia (Aristoteles): o bem supremo e o florescimento humano, alcancado pelo exercicio habitual das virtudes segundo a razao, realizando o potencial humano na polis.","resposta":""},
  {"id":"4759","tipo":"multipla","disciplina":"Sociologia","tema":"Estratificacao","subtema":"Castas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sistema de castas, como existiu historicamente na India, e caracterizado por:","alternativa_a":"Estratificacao rigida e imobilidade social por nascimento","alternativa_b":"Alta mobilidade social por merito","alternativa_c":"Igualdade juridica entre os grupos","alternativa_d":"Estratificacao economica flexivel","alternativa_e":"Divisao baseada exclusivamente em riqueza","resposta_correta":"a","explicacao":"O sistema de castas e uma forma de estratificacao social fechada, em que a posicao social e determinada pelo nascimento e a mobilidade social ascendente e praticamente impossivel.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote49.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
