# -*- coding: utf-8 -*-
import csv

questions = [
  {"id":"4560","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao logaritmica","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O grafico da funcao f(x) = log(x) passa pelo ponto (1, 0) porque:","alternativa_a":"Log(1) = 0 para qualquer base","alternativa_b":"A funcao e crescente","alternativa_c":"O dominio inclui zero","alternativa_d":"A base e sempre 10","alternativa_e":"A funcao e bijetora","resposta_correta":"a","explicacao":"Log(1) = 0 em qualquer base b > 0 (b diferente de 1), pois b^0 = 1. Portanto, o ponto (1, 0) sempre pertence ao grafico de funcoes logaritmicas.","resposta":""},
  {"id":"4561","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Teorema de Pitagoras","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Em um triangulo retangulo com catetos 6 e 8, a hipotenusa e:","alternativa_a":"10","alternativa_b":"14","alternativa_c":"12","alternativa_d":"100","alternativa_e":"sqrt(28)","resposta_correta":"a","explicacao":"h^2 = 6^2 + 8^2 = 36 + 64 = 100. h = sqrt(100) = 10.","resposta":""},
  {"id":"4562","tipo":"multipla","disciplina":"Matematica","tema":"Probabilidade","subtema":"Distribuicao binomial","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em 4 lancamentos de uma moeda honesta, a probabilidade de obter exatamente 3 caras e:","alternativa_a":"1/4","alternativa_b":"1/8","alternativa_c":"3/8","alternativa_d":"1/16","alternativa_e":"3/16","resposta_correta":"a","explicacao":"P = C(4,3) * (1/2)^3 * (1/2)^1 = 4 * (1/8) * (1/2) = 4/16 = 1/4.","resposta":""},
  {"id":"4563","tipo":"multipla","disciplina":"Matematica","tema":"Numeros Complexos","subtema":"Operacoes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O resultado de (2+3i) + (1-i) e:","alternativa_a":"3 + 2i","alternativa_b":"3 + 4i","alternativa_c":"1 + 2i","alternativa_d":"3 - 2i","alternativa_e":"1 + 4i","resposta_correta":"a","explicacao":"(2+3i) + (1-i) = (2+1) + (3-1)i = 3 + 2i.","resposta":""},
  {"id":"4564","tipo":"multipla","disciplina":"Matematica","tema":"Sequencias","subtema":"PA infinita","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A soma de uma PG infinita com a1=4 e razao r=1/2 e:","alternativa_a":"8","alternativa_b":"4","alternativa_c":"6","alternativa_d":"16","alternativa_e":"2","resposta_correta":"a","explicacao":"Para PG infinita com |r| < 1: S = a1/(1-r) = 4/(1-1/2) = 4/(1/2) = 8.","resposta":""},
  {"id":"4565","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Analitica","subtema":"Equacao da reta","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A equacao da reta que passa pelos pontos A(0,2) e B(3,0) e:","alternativa_a":"y = -2x/3 + 2","alternativa_b":"y = 2x/3 + 2","alternativa_c":"y = -3x/2 + 2","alternativa_d":"y = x + 2","alternativa_e":"y = 2x + 2","resposta_correta":"a","explicacao":"Usando a forma interceptos: x/3 + y/2 = 1, multiplicando por 2: 2x/3 + y = 2, logo y = -2x/3 + 2.","resposta":""},
  {"id":"4566","tipo":"multipla","disciplina":"Matematica","tema":"Estatistica","subtema":"Moda e mediana","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"No conjunto {3, 5, 7, 7, 9}, a moda e:","alternativa_a":"7","alternativa_b":"5","alternativa_c":"9","alternativa_d":"6","alternativa_e":"3","resposta_correta":"a","explicacao":"A moda e o valor que aparece com maior frequencia. No conjunto {3,5,7,7,9}, o 7 aparece duas vezes, sendo a moda.","resposta":""},
  {"id":"4567","tipo":"multipla","disciplina":"Matematica","tema":"Funcoes","subtema":"Funcao injetora","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Uma funcao e injetora (ou injetiva) quando:","alternativa_a":"Elementos distintos do dominio tem imagens distintas","alternativa_b":"Todo elemento do contradominio tem preimagem","alternativa_c":"E injetora e sobrejetora","alternativa_d":"Dominio e contradominio sao iguais","alternativa_e":"Cada imagem tem mais de uma preimagem","resposta_correta":"a","explicacao":"Uma funcao e injetora se x1 diferente de x2 implica f(x1) diferente de f(x2), ou equivalentemente, f(x1) = f(x2) implica x1 = x2.","resposta":""},
  {"id":"4568","tipo":"multipla","disciplina":"Matematica","tema":"Calculo","subtema":"Integrais","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A integral de x^2 dx e:","alternativa_a":"x^3/3 + C","alternativa_b":"2x + C","alternativa_c":"x^3 + C","alternativa_d":"3x^3 + C","alternativa_e":"x^2/2 + C","resposta_correta":"a","explicacao":"Regra da potencia para integrais: integral de x^n dx = x^(n+1)/(n+1) + C. Portanto integral de x^2 dx = x^3/3 + C.","resposta":""},
  {"id":"4569","tipo":"multipla","disciplina":"Matematica","tema":"Geometria Plana","subtema":"Angulos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Dois angulos sao suplementares quando sua soma e:","alternativa_a":"180 graus","alternativa_b":"90 graus","alternativa_c":"360 graus","alternativa_d":"270 graus","alternativa_e":"45 graus","resposta_correta":"a","explicacao":"Angulos suplementares somam 180 graus. Angulos complementares somam 90 graus.","resposta":""},
  {"id":"4570","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Impulso","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O impulso de uma forca e igual a variacao de:","alternativa_a":"Quantidade de movimento","alternativa_b":"Energia cinetica","alternativa_c":"Energia potencial","alternativa_d":"Aceleracao","alternativa_e":"Trabalho","resposta_correta":"a","explicacao":"Teorema impulso-quantidade de movimento: I = F*Dt = DeltaP (variacao da quantidade de movimento). I = m*Deltav.","resposta":""},
  {"id":"4571","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Processos termodinamicos","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em um processo isotermico, a grandeza que permanece constante e a:","alternativa_a":"Temperatura","alternativa_b":"Pressao","alternativa_c":"Volume","alternativa_d":"Entropia","alternativa_e":"Energia interna","resposta_correta":"a","explicacao":"Processo isotermico: temperatura constante (DeltaT=0). Isocorrico: volume constante. Isobarico: pressao constante. Adiabatico: sem troca de calor.","resposta":""},
  {"id":"4572","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Efeito Joule","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O calor gerado em um resistor percorrido por uma corrente eletrica e descrito pelo:","alternativa_a":"Efeito Joule","alternativa_b":"Efeito fotoeletrico","alternativa_c":"Efeito Compton","alternativa_d":"Efeito Hall","alternativa_e":"Efeito piezoeletrico","resposta_correta":"a","explicacao":"O efeito Joule descreve a dissipacao de energia eletrica em calor em um resistor: Q = R*I^2*t = U*I*t = U^2/R*t.","resposta":""},
  {"id":"4573","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Polarizacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A polarizacao da luz e possivel porque ela e uma onda:","alternativa_a":"Transversal","alternativa_b":"Longitudinal","alternativa_c":"Mecanica","alternativa_d":"Sonora","alternativa_e":"Estacionaria","resposta_correta":"a","explicacao":"Apenas ondas transversais podem ser polarizadas. A luz e uma onda eletromagnetica transversal, com os campos eletrico e magnetico oscilando perpendicularmente a propagacao.","resposta":""},
  {"id":"4574","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Torque","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O torque (momento de forca) e definido como o produto da forca pelo:","alternativa_a":"Braco do momento (distancia perpendicular)","alternativa_b":"Modulo da velocidade angular","alternativa_c":"Momento de inercia","alternativa_d":"Angulo de aplicacao","alternativa_e":"Volume do objeto","resposta_correta":"a","explicacao":"Torque = Forca * braco (distancia perpendicular entre a linha de acao da forca e o eixo de rotacao): T = F * d.","resposta":""},
  {"id":"4575","tipo":"multipla","disciplina":"Fisica","tema":"Eletricidade","subtema":"Geradores","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Em um gerador eletrico, a forca eletromotriz (f.e.m.) indica:","alternativa_a":"A tensao maxima que o gerador pode fornecer","alternativa_b":"A corrente maxima do circuito","alternativa_c":"A resistencia interna do gerador","alternativa_d":"A potencia dissipada internamente","alternativa_e":"A frequencia da corrente","resposta_correta":"a","explicacao":"A f.e.m. (epsilon) e a tensao em circuito aberto, ou seja, a maxima diferenca de potencial que o gerador pode fornecer. U = epsilon - r*i.","resposta":""},
  {"id":"4576","tipo":"multipla","disciplina":"Fisica","tema":"Ondas","subtema":"Ressonancia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A ressonancia acustica ocorre quando a frequencia de excitacao e igual a:","alternativa_a":"Frequencia natural do sistema","alternativa_b":"Frequencia do som ambiente","alternativa_c":"Frequencia de Larmor","alternativa_d":"Frequencia de corte","alternativa_e":"Dobro da frequencia natural","resposta_correta":"a","explicacao":"A ressonancia ocorre quando a frequencia da forca excitadora coincide com a frequencia natural de oscilacao do sistema, causando grande aumento de amplitude.","resposta":""},
  {"id":"4577","tipo":"multipla","disciplina":"Fisica","tema":"Mecanica","subtema":"Plano inclinado","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Um objeto sobre um plano inclinado de angulo θ sem atrito experimenta uma forca paralela ao plano de valor:","alternativa_a":"mg*sen(θ)","alternativa_b":"mg*cos(θ)","alternativa_c":"mg*tg(θ)","alternativa_d":"mg","alternativa_e":"mg/(sen(θ))","resposta_correta":"a","explicacao":"A componente do peso paralela ao plano inclinado (que causa o escorregamento) e F = mg*sen(θ), enquanto a componente normal e N = mg*cos(θ).","resposta":""},
  {"id":"4578","tipo":"multipla","disciplina":"Fisica","tema":"Optica","subtema":"Espectro eletromagnetico","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Qual tipo de radiacao eletromagnetica tem maior frequencia?","alternativa_a":"Raios gama","alternativa_b":"Raios X","alternativa_c":"Ultravioleta","alternativa_d":"Luz visivel","alternativa_e":"Micro-ondas","resposta_correta":"a","explicacao":"No espectro eletromagnetico, em ordem crescente de frequencia: radio, micro-ondas, infravermelho, visivel, ultravioleta, raios X, raios gama. Raios gama tem a maior frequencia.","resposta":""},
  {"id":"4579","tipo":"multipla","disciplina":"Fisica","tema":"Termodinamica","subtema":"Entropia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A segunda lei da termodinamica afirma que, em processos espontaneos, a entropia do universo:","alternativa_a":"Sempre aumenta ou permanece constante","alternativa_b":"Sempre diminui","alternativa_c":"Permanece constante","alternativa_d":"Pode aumentar ou diminuir","alternativa_e":"Aumenta apenas se houver trabalho","resposta_correta":"a","explicacao":"A 2a lei da termodinamica (principio da entropia): a entropia total do universo (sistema + vizinhancas) nunca diminui em processos espontaneos.","resposta":""},
  {"id":"4580","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Reacoes de substituicao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A reacao de halogenacao de alcanos (substituicao de H por halogenio) ocorre na presenca de:","alternativa_a":"Luz ou calor","alternativa_b":"Acido como catalisador","alternativa_c":"Base como catalisador","alternativa_d":"Agua","alternativa_e":"Solvente polar","resposta_correta":"a","explicacao":"A halogenacao de alcanos e uma reacao radicalar que ocorre na presenca de luz (fotolitica) ou calor, gerando radicais halogeneos que substituem hidrogenios.","resposta":""},
  {"id":"4581","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Inorganica","subtema":"Nomenclatura de sais","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sulfato de calcio (CaSO4) e popularmente conhecido como:","alternativa_a":"Gesso","alternativa_b":"Cal","alternativa_c":"Soda caustica","alternativa_d":"Barrilha","alternativa_e":"Magnesia","resposta_correta":"a","explicacao":"O sulfato de calcio (CaSO4) e o principal componente do gesso. Quando semi-hidratado (CaSO4.1/2H2O) e chamado de gesso de Paris.","resposta":""},
  {"id":"4582","tipo":"multipla","disciplina":"Quimica","tema":"Bioquimica","subtema":"Carboidratos","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A glicose e um monossacarideo com formula molecular:","alternativa_a":"C6H12O6","alternativa_b":"C12H22O11","alternativa_c":"C6H6O6","alternativa_d":"C6H12","alternativa_e":"CH2O","resposta_correta":"a","explicacao":"A glicose tem formula molecular C6H12O6. A sacarose (acucar comum) tem formula C12H22O11 (dissacarideo).","resposta":""},
  {"id":"4583","tipo":"multipla","disciplina":"Quimica","tema":"Ligacoes Quimicas","subtema":"Ligacao metalica","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A propriedade dos metais de conduzir eletricidade e explicada pelo modelo da:","alternativa_a":"Nuvem de eletrons livres","alternativa_b":"Ligacao covalente apolar","alternativa_c":"Ligacao ionica","alternativa_d":"Forca de van der Waals","alternativa_e":"Ponte de hidrogenio","resposta_correta":"a","explicacao":"Na ligacao metalica, os eletrons da camada de valencia se desprendem e formam uma 'nuvem' de eletrons livres que explica a condutividade eletrica e termica dos metais.","resposta":""},
  {"id":"4584","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Analitica","subtema":"Titulacao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"Em uma titulacao acido-base, o ponto de equivalencia e atingido quando:","alternativa_a":"Os mols de acido igual aos mols de base","alternativa_b":"O pH atinge 7","alternativa_c":"A solucao muda de cor","alternativa_d":"A concentracao e 1 mol/L","alternativa_e":"A temperatura aumenta","resposta_correta":"a","explicacao":"O ponto de equivalencia ocorre quando o numero de mols do acido e exatamente igual ao numero de mols da base (considerando as valencias). O pH no ponto depende do tipo de acido/base.","resposta":""},
  {"id":"4585","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Nuclear","subtema":"Fissao e fusao","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"As usinas nucleares utilizam o processo de fissao nuclear, que consiste em:","alternativa_a":"Divisao de nucleos pesados liberando energia","alternativa_b":"Uniao de nucleos leves liberando energia","alternativa_c":"Emissao de eletrons pelo nucleo","alternativa_d":"Captura de neutrons sem liberar energia","alternativa_e":"Conversao de materia em luz","resposta_correta":"a","explicacao":"Fissao nuclear: nucleo pesado (como U-235) se divide ao ser bombardeado por neutrons, liberando energia, novos neutrons e produtos de fissao.","resposta":""},
  {"id":"4586","tipo":"multipla","disciplina":"Quimica","tema":"Quimica Organica","subtema":"Polimeros naturais","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A celulose, principal componente das paredes celulares vegetais, e um polissacarideo formado por unidades de:","alternativa_a":"Beta-glicose","alternativa_b":"Alpha-glicose","alternativa_c":"Frutose","alternativa_d":"Galactose","alternativa_e":"Ribose","resposta_correta":"a","explicacao":"A celulose e formada por unidades de beta-glicose unidas por ligacoes glicosidicas beta-1,4. O amido usa alfa-glicose. A diferenca estrutural torna a celulose indigesta para humanos.","resposta":""},
  {"id":"4587","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema cardiovascular","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O coração bombeia o sangue pelo corpo por meio de duas circulacoes: a pulmonar e a:","alternativa_a":"Sistemica","alternativa_b":"Coronariana","alternativa_c":"Linfatica","alternativa_d":"Hepatica","alternativa_e":"Renal","resposta_correta":"a","explicacao":"A circulacao sistemica (grande circulacao) leva sangue oxigenado do ventriculo esquerdo para todo o corpo e retorna sangue desoxigenado pelo atrio direito.","resposta":""},
  {"id":"4588","tipo":"multipla","disciplina":"Biologia","tema":"Genetica","subtema":"Biotecnologia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A tecnica de PCR (Reacao em Cadeia da Polimerase) e usada para:","alternativa_a":"Amplificar segmentos de DNA","alternativa_b":"Sequenciar proteinas","alternativa_c":"Clinar organismos inteiros","alternativa_d":"Sintetizar RNA mensageiro","alternativa_e":"Destruir bacterias resistentes","resposta_correta":"a","explicacao":"A PCR e uma tecnica que permite copiar (amplificar) rapidamente segmentos especificos de DNA milhoes de vezes. E usada em diagnostico, pesquisa forense e biotecnologia.","resposta":""},
  {"id":"4589","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Populacoes","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O crescimento populacional logistico ocorre quando a populacao se aproxima da:","alternativa_a":"Capacidade suporte do ambiente","alternativa_b":"Densidade zero","alternativa_c":"Taxa maxima de natalidade","alternativa_d":"Ausencia de predadores","alternativa_e":"Fase exponencial","resposta_correta":"a","explicacao":"No crescimento logistico (curva S), a populacao cresce exponencialmente no inicio e desacelera ao se aproximar da capacidade suporte (K), o maximo sustentavel pelo ambiente.","resposta":""},
  {"id":"4590","tipo":"multipla","disciplina":"Biologia","tema":"Fisiologia Humana","subtema":"Sistema excretor","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A unidade funcional do rim responsavel pela filtracao do sangue e formacao da urina e o:","alternativa_a":"Nefron","alternativa_b":"Alveolo","alternativa_c":"Lobulo hepatico","alternativa_d":"Vilosidade intestinal","alternativa_e":"Folículo","resposta_correta":"a","explicacao":"O nefron e a unidade funcional do rim, composto pelo corpusculo renal (glomérulo + capsula de Bowman) e tubulos (proximal, alca de Henle, distal).","resposta":""},
  {"id":"4591","tipo":"multipla","disciplina":"Biologia","tema":"Citologia","subtema":"Parede celular","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"A parede celular das plantas e formada principalmente por:","alternativa_a":"Celulose","alternativa_b":"Quitina","alternativa_c":"Peptidoglicano","alternativa_d":"Proteoglicanas","alternativa_e":"Colágeno","resposta_correta":"a","explicacao":"A parede celular das plantas e composta principalmente de celulose (polissacarideo), enquanto em fungos e quitina e em bacterias e peptidoglicano.","resposta":""},
  {"id":"4592","tipo":"multipla","disciplina":"Biologia","tema":"Botanica","subtema":"Crescimento das plantas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O hormonio vegetal responsavel pelo alongamento celular e a curvatura das plantas em direcao a luz e a:","alternativa_a":"Auxina","alternativa_b":"Giberelina","alternativa_c":"Citocenina","alternativa_d":"Etileno","alternativa_e":"Acido abscisico","resposta_correta":"a","explicacao":"A auxina (AIA - acido indolacetico) e o principal hormonio responsavel pelo fototropismo: a luz concentra auxina no lado oposto, causando alongamento assimetrico e curvatura.","resposta":""},
  {"id":"4593","tipo":"multipla","disciplina":"Biologia","tema":"Ecologia","subtema":"Poluicao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A biomagnificacao e o processo pelo qual substancias toxicas:","alternativa_a":"Se concentram progressivamente ao longo da cadeia trófica","alternativa_b":"Sao eliminadas pelo metabolismo dos seres vivos","alternativa_c":"Diminuem de concentracao no solo","alternativa_d":"Sao absorvidas apenas por plantas","alternativa_e":"Evaporam com o tempo","resposta_correta":"a","explicacao":"Na biomagnificacao, substancias como DDT e mercurio se acumulam progressivamente em cada nivel trófico, atingindo concentracoes perigosas nos predadores de topo.","resposta":""},
  {"id":"4594","tipo":"multipla","disciplina":"Historia","tema":"Historia Antiga","subtema":"Egipto","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"No Antigo Egipto, a escrita hieroglifica era usada principalmente em:","alternativa_a":"Monumentos e textos religiosos","alternativa_b":"Contratos comerciais","alternativa_c":"Correspondencias militares","alternativa_d":"Censos populacionais","alternativa_e":"Calculos matematicos","resposta_correta":"a","explicacao":"Os hieroglifos eram a escrita sacra do Egipto, usada em monumentos, templos, tumulos e textos religiosos. Para uso cotidiano usavam a escrita hieratica e depois a demotica.","resposta":""},
  {"id":"4595","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Movimento Operario","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O anarquismo teve grande influencia no movimento operario brasileiro nas primeiras decadas do seculo XX. Os imigrantes que mais contribuiram para a difusao dessas ideias foram os:","alternativa_a":"Italianos e espanhois","alternativa_b":"Alemaes e poloneses","alternativa_c":"Japoneses e chines","alternativa_d":"Ingleses e irlandeses","alternativa_e":"Portugueses e africanos","resposta_correta":"a","explicacao":"Os imigrantes italianos e espanhois foram os principais difusores do anarquismo no movimento operario brasileiro, especialmente em Sao Paulo, nas primeiras decadas do sec. XX.","resposta":""},
  {"id":"4596","tipo":"multipla","disciplina":"Historia","tema":"Historia Geral","subtema":"Colonizacao das Americas","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O sistema de encomienda colonial espanhol nas Americas consistia em:","alternativa_a":"Trabalho forcado de indigenas em troca de protecao e catequizacao","alternativa_b":"Distribuicao de terras para colonos sem trabalho indigena","alternativa_c":"Comercio livre entre colonias e metropole","alternativa_d":"Autorizacao de escravizacao de africanos","alternativa_e":"Sistema de peonagem voluntaria","resposta_correta":"a","explicacao":"O sistema de encomienda (sec. XVI-XVII) concedia ao colono espanhol o direito ao trabalho de um grupo de indigenas, em troca de os proteger e evangelizar. Foi amplamente abusado.","resposta":""},
  {"id":"4597","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Revolucao Russa","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Revolucao Russa de 1917 foi liderada pelos bolcheviques, cujo principal lider era:","alternativa_a":"Lenin","alternativa_b":"Trotsky","alternativa_c":"Stalin","alternativa_d":"Kerenski","alternativa_e":"Czar Nicolau II","resposta_correta":"a","explicacao":"Lenin liderou o Partido Bolchevique e a Revolucao de Outubro de 1917, que derrubou o Governo Provisorio e instalou o poder sovietico na Russia.","resposta":""},
  {"id":"4598","tipo":"multipla","disciplina":"Historia","tema":"Historia do Brasil","subtema":"Milagre Economico","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O 'Milagre Economico' brasileiro (1968-1973) foi marcado por altas taxas de crescimento do PIB. Esse crescimento ocorreu durante o governo de:","alternativa_a":"Medici","alternativa_b":"Costa e Silva","alternativa_c":"Geisel","alternativa_d":"Figueiredo","alternativa_e":"Castello Branco","resposta_correta":"a","explicacao":"O 'Milagre Economico' ocorreu principalmente no governo Medici (1969-1974), com crescimento medio do PIB de 11% ao ano, mas com concentracao de renda e repressao politica.","resposta":""},
  {"id":"4599","tipo":"multipla","disciplina":"Historia","tema":"Historia Contemporanea","subtema":"Descolonizacao africana","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A Negritude foi um movimento cultural e politico que surgiu entre intelectuais africanos e da diaspora. Seu principal expoente foi:","alternativa_a":"Aime Cesaire","alternativa_b":"Nelson Mandela","alternativa_c":"Kwame Nkrumah","alternativa_d":"Leopold Sedar Senghor","alternativa_e":"Franz Fanon","resposta_correta":"a","explicacao":"Aime Cesaire (Martinica) foi um dos fundadores do movimento da Negritude, ao lado de Leopold Senghor e Leon-Gontran Damas, valorizando a identidade e cultura africana.","resposta":""},
  {"id":"4600","tipo":"multipla","disciplina":"Geografia","tema":"Urbanizacao","subtema":"Favelas e habitacao","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"As favelas no Brasil surgiram como resultado principal de:","alternativa_a":"Urbanizacao acelerada e falta de habitacao para migrantes","alternativa_b":"Politicas habitacionais do governo federal","alternativa_c":"Heranca do periodo colonial","alternativa_d":"Expulsao de comunidades quilombolas","alternativa_e":"Imigração europeia sem recursos","resposta_correta":"a","explicacao":"As favelas surgiram e cresceram principalmente com o processo de urbanizacao acelerada (especialmente anos 1940-80), quando migrantes rurais nao tinham acesso a habitacao formal.","resposta":""},
  {"id":"4601","tipo":"multipla","disciplina":"Geografia","tema":"Economia","subtema":"Setor primario","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O setor primario da economia compreende as atividades de:","alternativa_a":"Extrativismo, agricultura e pecuaria","alternativa_b":"Industria de transformacao","alternativa_c":"Servicos e comercio","alternativa_d":"Tecnologia e inovacao","alternativa_e":"Financas e bancos","resposta_correta":"a","explicacao":"O setor primario abrange as atividades que extraem recursos diretamente da natureza: agricultura, pecuaria, pesca, silvicultura e mineracao.","resposta":""},
  {"id":"4602","tipo":"multipla","disciplina":"Geografia","tema":"Geopolitica","subtema":"Mercosul","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O Mercosul (Mercado Comum do Sul) e um bloco economico integrado por Brasil, Argentina, Uruguay, Paraguai e:","alternativa_a":"Venezuela (suspensa) e Bolivia (em adesao)","alternativa_b":"Chile e Peru","alternativa_c":"Colômbia e Ecuador","alternativa_d":"Mexico e Cuba","alternativa_e":"Bolivia e Ecuador","resposta_correta":"a","explicacao":"O Mercosul, criado em 1991, tem como membros plenos Brasil, Argentina, Uruguay, Paraguai e Venezuela (suspensa desde 2017). Bolivia esta em processo de adesao.","resposta":""},
  {"id":"4603","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Classes de palavras","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"As palavras que exprimem a acao, o estado ou o fenomeno referentes ao sujeito sao denominadas:","alternativa_a":"Verbos","alternativa_b":"Substantivos","alternativa_c":"Adjetivos","alternativa_d":"Adverbios","alternativa_e":"Preposicoes","resposta_correta":"a","explicacao":"Os verbos sao palavras que indicam acoes ('correr', 'estudar'), estados ('ser', 'estar') ou fenomenos naturais ('chover', 'ventar').","resposta":""},
  {"id":"4604","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Literatura","subtema":"Naturalismo","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"O Naturalismo, corrente literaria que via o ser humano determinado pelo meio e heranca biologica, tem como obra brasileira representativa:","alternativa_a":"O Cortico, de Alucisio Azevedo","alternativa_b":"Dom Casmurro, de Machado de Assis","alternativa_c":"Memorias Postumas, de Machado de Assis","alternativa_d":"O Guarani, de Jose de Alencar","alternativa_e":"Iracema, de Jose de Alencar","resposta_correta":"a","explicacao":"'O Cortico' (1890) de Alucisio Azevedo e a principal obra do Naturalismo brasileiro, descrevendo um cortico no Rio de Janeiro com abordagem determinista e cientificista.","resposta":""},
  {"id":"4605","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Gramatica","subtema":"Uso de maiusculas","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"Segundo a norma culta, deve-se usar letra maiuscula em:","alternativa_a":"Nomes proprios de pessoas, lugares e instituicoes","alternativa_b":"Inicio de toda frase apos virgula","alternativa_c":"Todo substantivo comum","alternativa_d":"Verbos no infinitivo","alternativa_e":"Toda palavra com mais de 5 letras","resposta_correta":"a","explicacao":"A letra maiuscula e usada obrigatoriamente em: inicio de periodo, nomes proprios (pessoas, cidades, paises, entidades, obras), titulos e siglas.","resposta":""},
  {"id":"4606","tipo":"multipla","disciplina":"Lingua Portuguesa","tema":"Interpretacao","subtema":"Generos textuais","dificuldade":"Facil","fonte":"Vestibular","ano":"2024","enunciado":"O texto que narra fatos reais ocorridos em sequencia cronologica, escrito na primeira pessoa, descrevendo vivencias do autor, e chamado de:","alternativa_a":"Autobiografia","alternativa_b":"Biografia","alternativa_c":"Cronica","alternativa_d":"Novela","alternativa_e":"Relatorio","resposta_correta":"a","explicacao":"A autobiografia e a narrativa de vida escrita pelo proprio protagonista (primeira pessoa). A biografia e escrita por terceiros sobre a vida de alguem.","resposta":""},
  {"id":"4607","tipo":"multipla","disciplina":"Filosofia","tema":"Metafisica","subtema":"Ontologia","dificuldade":"Dificil","fonte":"Vestibular","ano":"2024","enunciado":"A questao fundamental da ontologia e:","alternativa_a":"O que e o ser?","alternativa_b":"O que e o bem?","alternativa_c":"O que podemos conhecer?","alternativa_d":"Como devemos agir?","alternativa_e":"O que e belo?","resposta_correta":"a","explicacao":"A ontologia (do grego ontos = ser) e o ramo da metafisica que investiga a natureza do ser, a existencia e a realidade. Sua questao fundamental e 'O que e o ser?' (Aristoteles, Heidegger).","resposta":""},
  {"id":"4608","tipo":"multipla","disciplina":"Filosofia","tema":"Filosofia Politica","subtema":"Democracia","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"A democracia ateniense era direta, mas excluia a participacao de:","alternativa_a":"Mulheres, escravos e estrangeiros","alternativa_b":"Apenas os escravos","alternativa_c":"Apenas as mulheres","alternativa_d":"Apenas os estrangeiros","alternativa_e":"Os cidadaos mais pobres","resposta_correta":"a","explicacao":"A democracia direta de Atenas (sec. V a.C.) era restrita aos cidadaos: homens adultos atenienses livres. Mulheres, escravos (a maioria da populacao) e estrangeiros (metecos) eram excluidos.","resposta":""},
  {"id":"4609","tipo":"multipla","disciplina":"Sociologia","tema":"Educacao","subtema":"Reproducao social","dificuldade":"Medio","fonte":"Vestibular","ano":"2024","enunciado":"Pierre Bourdieu analisou como a escola reproduz as desigualdades sociais por meio da transmissao de:","alternativa_a":"Capital cultural","alternativa_b":"Capital economico","alternativa_c":"Capital fisico","alternativa_d":"Capital natural","alternativa_e":"Capital institucional","resposta_correta":"a","explicacao":"Para Bourdieu, a escola valoriza o capital cultural (habitus, linguagem, conhecimento) da classe dominante, reproduzindo as desigualdades sob a aparencia de igualdade de oportunidades.","resposta":""},
]

out = '/Users/dennysrian_/Desktop/aprova-ia/questoes_lote46.csv'
cols = ['id','tipo','disciplina','tema','subtema','dificuldade','fonte','ano','enunciado','alternativa_a','alternativa_b','alternativa_c','alternativa_d','alternativa_e','resposta_correta','explicacao','resposta']

with open(out,'w',newline='',encoding='utf-8') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_ALL)
    w.writerow(cols)
    for q in questions:
        w.writerow([q.get(c,'') for c in cols])

print(f'Total de questoes: {len(questions)}')
print(f'CSV gerado: {out}')
